### ISSUE TITLE
SMILES fails aromaticity

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1027]
c12c3c4c(cc(c3c3c(c5c(c2c(cc2c1cccc2)Br)c(cc1c5cccc1)Br)c1c(cc3Br)cccc1)Br)cccc4 does not convert to an aromatic system -- instead, double bonds go into the eight-membered ring.

c12c3=c4c5c(cc(c4=c4c(=c6c(=c3c(cc1cccc2)Br)c(cc1c6cccc1)Br)c1c(cc4Br)CCCC1)Br)cccc5

There should probably be a "tie-breaker" pass, when considering whether to put a double bond in one ring or another -- favor rings of size five and six.

Reported by: @ghutchis

**Comment by baoilleach** [comment]
Fixed by #1576: 

The following SMILES is now generated:
c12-c3c4c(cc(c3-c3c(-c5c(-c1c(cc1c2cccc1)Br)c(cc1c5cccc1)Br)c1c(cc3Br)cccc1)Br)cccc4

The corresponding kekule form is:
```
C12-C3=C4C(=CC(=C3-C3C(-C5C(-C1=C(C=C1C=2C=CC=C1)Br)=C(C=C1C=5C=CC=C1)Br)=C1C(=CC=3Br)C=CC=C1)Br)C=CC=C4
```
