### ISSUE TITLE
Memory leak in OBConversion::InstallStreamFilter()

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1029]
The function OBConversion::InstallStreamFilter() allocates memory in src/obconversion.cpp:722:
pLineEndBuf = new LErdbuf(pInStream->rdbuf());
pInStream->rdbuf(pLineEndBuf);
which is never freed. The comment to destructor of std::basic_ios reads: "it does not destroy the streambuf held by rdbuf()", so the application is responsible for destroying the buffer when pInStream is destroyed. 

valgrind report:
==29705== 2,280 bytes in 57 blocks are definitely lost in loss record 190 of 209
==29705==    at 0x48243C5: operator new(unsigned int) (vg_replace_malloc.c:214)
==29705==    by 0x48FF702: OpenBabel::OBConversion::InstallStreamFilter() (in /usr/lib/libopenbabel.so.3.0.3)
==29705==    by 0x48FFF7F: OpenBabel::OBConversion::Read(OpenBabel::OBBase*, std::istream*) (in /usr/lib/libopenbabel.so.3.0.3)
==29705==    by 0x4900644: OpenBabel::OBConversion::ReadString(OpenBabel::OBBase*, std::string) (in /usr/lib/libopenbabel.so.3.0.3)

OpenBabel library sources:
http://ftp.de.debian.org/debian/pool/main/o/openbabel/openbabel_2.2.3.orig.tar.gz

Reported by: dma_k

**Comment by serval2412** [comment]
The function InstallStreamFilter has been removed with da0215dacf10d534947e5dcbfc41236ed9dceb3b.
I suppose we can close this bugtracker now.
