### ISSUE TITLE
problem with reading/converting aromatic molecule

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1042]
I was testing Open Babel 2.3.0 for its ability to use it in a script to test for unique compounds when I encountered a problem concerning the processing of aromaticity when reading smiles input with some specific aromatic rings.

Step 1: convert this protonated molecule to canonical smiles:
$ echo "C1=CC=CC=C1N1[N-]C(=O)C=CC1(=O)" | babel -ismi -ocan
O=c1ccc(=O)n([n-]1)c1ccccc1

Step 2: read the canonical smiles and convert it to canonical smiles :
$ echo "O=c1ccc(=O)n([n-]1)c1ccccc1" | babel -ismi -ocan
O=C1CCC(=O)[N-]N1c1ccccc1	

One would expect that the result of step 2 would generate the same canonical smiles again, but as the example shows this is not happening. 

If I perform the same procedure but with neutral form the procedure is OK.
$ echo "C1=CC=CC=C1N1NC(=O)C=CC1(=O)" | babel -ismi -ocan
O=c1ccc(=O)n([nH]1)c1ccccc1	

$ echo "O=c1ccc(=O)n([nH]1)c1ccccc1" | babel -ismi -ocan
O=c1ccc(=O)n([nH]1)c1ccccc1	

Gert Thijs
gert.thijs@silicos.com

Reported by: @gertthijs

**Comment by baoilleach** [comment]
Confirmed as a bug with aromaticity detection.

**Comment by baoilleach** [comment]
Works fine now:
```
>obabel -:"C1=CC=CC=C1N1[N-]C(=O)C=CC1(=O)" -ocan
O=c1ccc(=O)n([n-]1)c1ccccc1
>obabel -:"O=c1ccc(=O)n([n-]1)c1ccccc1" -ocan
O=c1ccc(=O)n([n-]1)c1ccccc1
```
