### ISSUE TITLE
Debug output in OBAtom.HtoMethyl() should be removed?

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1056]
From Andrew Dalke:

OBAtom.HtoMethtyl() can dump code to stderr

 v3: < -0.28, 0, 0 > v4: < -0.28, 0, 0 >

This is quite clearly a bit of debugging code which
wasn't removed:

   cerr << "v3: " << v3 << " v4: " << v4 << endl;

Reported by: @baoilleach

**Comment by serval2412** [comment]
just to be sure, the goal is just to remove line 135 from bond.cpp
bond.cpp:135:    cerr << "v3: " << v3 << " v4: " << v4 << endl;
if yes, what about other lines containing cerr?

**Comment by ghutchis** [comment]
We should minimize dumping to std::cerr in production code. If needed, there's the error log, but this can just get removed.

Thanks!

**Comment by serval2412** [comment]
Thank you for your feedback, I submitted this patch:
https://github.com/openbabel/openbabel/pull/1825
