### ISSUE TITLE
SMILES does not match itself

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1065]
C1C(OC2=CC(=CC(=C2C1=O)O)O)C3=CC=C(C=C3)O does not match against itself with OBSmartsPattern. It matches however with Oc1ccc(cc1)C1CC(=O)c2c(O1)cc(cc2O)O which is the canonical form as reported by OB 2.3 SMI to CAN conversion.

In contrast, the new VF2 matcher with QueryFromSmiles seems to match it with itself.

Reported by: @ergo70

**Comment by baoilleach** [comment]
Here's a simpler example, benzene:
```
obabel -:C1=CC=CC=C1 -sC1=CC=CC=C1 -osmi
# no match
obabel -:C1=CC=CC=C1 -sc1ccccc1 -osmi
# match
obabel -:C1=CC=CC=C1 -s[#6]1=[#6][#6]=[#6][#6]=[#6]1 -osmi
# no match
```
I'll chat with others at work about whether this is working as intended.

**Comment by baoilleach** [comment]
Yes - this is working as intended. 'C' matches aliphatic carbon, so won't match benzene whether presented as Kekule or aromatic. Feel free to comment if not clear.
