### ISSUE TITLE
Hydrogen erroneously added when converting to InChI

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1078]
When doing some round tripping testing in OpenBabel 2.3.0 I came across the following cases where hydrogen was erroneously added to atoms with explicitly no hydrogen in the conversion from SMILES to InChI

Group 1/2 metals and In/Sn/Sb/Tl/Pb/Bi/Po/At.

e.g. [Li] -->InChI=1S/Li.H instead of InChI=1S/Li
[Bi] --> InChI=1S/Bi.3H instead of InChI=1S/Bi

Possibly relatedly [BiH4] gives InChI=1S/Bi.5H instead of InChI=1S/Bi.4H

Reported by: dan2097

**Comment by baoilleach** [comment]
All now fixed by #1576 @dan2097
