### ISSUE TITLE
Mistranslation of hydrogens

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1103]
Not sure if I'm just clueless or this is a genuine bug, however when converting from cdxml to pdb (for docking modelling basically) I always end up with extra hydrogens being added to my heterocycle.  It is cyclam (a tetraazamacrocycle, containing 4 N atoms as part of a ring, each of which bears 1H) and the C-NH-C that is drawn in ChemDraw always ends up as C-NH2-C after converting to pdb.

Any help would be appreciated.  Thanks.

Reported by: j-tyler

**Comment by baoilleach** [comment]
No test file provided.
