### ISSUE TITLE
wrong aromaticity?

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1132]
$obabel -:"CN1CCN(CC1)CC(=O)n1c2ccccc2c(=O)[nH]c2c1nccc2" -s"[#7]:[#6]:[#7]" -ocan 
CN1CCN(CC1)CC(=O)n1c2ccccc2c(=O)[nH]c2c1nccc2
1 molecule converted

this should not match according to daylight, the middle ring is not aromatic
http://www.daylight.com/daycgi/depict?434e3143434e28434331294343283d4f296e31633263636363633263283d4f295b6e485d633263316e63636332

Cheers,
Martin

Reported by: martinguetlein

**Comment by baoilleach** [comment]
Confirmed as a problem with aromaticity detection.

**Comment by baoilleach** [comment]
Fixed now. FYI @mguetlein
```
>obabel -:"CN1CCN(CC1)CC(=O)n1c2ccccc2c(=O)[nH]c2c1nccc2" -s"[#7]:[#6]:[#7]" -ocan
0 molecules converted
```
