### ISSUE TITLE
SMILES parser should fail with bad characters

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1138]
formats/smilesformat.cpp contains the two lines (starting at line 407)

    if (*_ptr<0 || isspace(*_ptr))
              continue;

This tells it to ignore any whitespace in the SMILES string (so the non-SMILES "C P" gets interpreted as "CP").

It also tells the parser to ignore any bytes with the high bit set.

The latter is a problem if the input comes from a UTF-8 encoded source, where the non-ASCII characters are encoded with bytes which set the high bit. It means that an input like "CöP" will be interpreted as "CP".

The fix should be:

    if (*_ptr<0 || isspace(*_ptr))
              return false;  // unsupported character

BTW, ideally "_ptr" should be a "signed char *". SGIs, for example, used an unsigned char as the default "char" type. I don't know if this is important these days.

Reported by: dalke

**Comment by serval2412** [comment]
Following 8a966e5c7b5472c7c0ce71a3d717e44887200ff9 (2017-12-13), the parsing process has been changed.
Could you give it a new try?

**Comment by baoilleach** [comment]
OP was @adalke, but I think I can answer for this one. When I did this work, I had forgotten this bug report, but in the course of rewriting I did accidentally fix it.

```
>>> pybel.readstring("smi", "C\vC").molwt
==============================
*** Open Babel Error  in OpenBabel::OBSmilesParser::ParseSimple
  SMILES string contains a character '♂' which is invalid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Tools\openbabel\baoilleach\scripts\python\pybel.py", line 209, in rea
dstring
    string, format))
OSError: Failed to convert 'C♂C' to format 'smi'
```
Thanks for the poke.
