### ISSUE TITLE
incorrect treatment of aromatic with explicit bond

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1140]
I was reviewing the Open Babel SMILES code and noticed that if atom1 and atom2 are joined, and atom1 and atom2 are aromatic, then the bond order is reset to _order=5. This is done in different ways in smilesformat.cpp

On line 1055:
            if (_order != 2) _order=5; //Potential aromatic bond -- but flag explicit double bonds
On line 1958:
            _order=5; //Potential aromatic bond

I haven't yet figured out if they are supposed to be the same or different, but I strongly suspect that it's supposed to be the same check.

It is possible, but rare, to have an explicit '-' bond marked to indicate that a bond between two aromatics is supposed to be a single/non-aromatic bond. For examples:

c12-c3c(cccc3)[IH]c1cccc2
Clc1cc-2c3c(cccc3n1)-c4c2cccc4
[Ni]123n4c5c6ccccc6c4nc-7[n+]2c(-c8ccccc78)nc9n1c(c1ccccc91)nc-1[n+]3c(-c2ccccc12)n5
O=c1nc-2cccccc2s1
c-12n(c3ccccc3n2)Cc4c1cc5ccccc5c4

These are not handled correctly in Open Babel. In RDKit:

    >>> from rdkit import Chem
    >>> mol = Chem.MolFromSmiles("c12-c3c(cccc3)[IH]c1cccc2")
    >>> Chem.MolToSmiles(mol)
    'c1ccc2c(c1)[IH]c1ccccc1-2'

See the "-2" at the end? That's the explicit single bond.

While Open Babel sees the explicit '-' as being an aromatic:

    % echo 'c12-c3c(cccc3)[IH]c1cccc2 blah' | babel -ismi -osmi
    c12c3c(cccc3)[IH]c1cccc2	blah
 
As an extreme example, here's a triple-bond joining two
aromatic rings in RDKit:

    >>> mol = Chem.MolFromSmiles("c1ccc[n-2]1#[n-2]1cccc1")
    >>> Chem.MolToSmiles(mol)
    'c1cc[n-2](#[n-2]2cccc2)c1'

Open Babel totally ignores the triple bond and says the
bond between the two aromatic rings is a single bond.

    % echo "c1ccccc1#c1ccccc1 blah" | babel -ismi -osmi
    c1ccccc1c1ccccc1	blah

BTW, I'm using the Open Babel build from today's version control.

Reported by: dalke

**Comment by baoilleach** [comment]
Fixed by #1576. See below -  single bond symbol respected and used where appropriate. Triple bond between aromatic atoms respected. (FYI @adalke)

```
>obabel -:"c12-c3c(cccc3)[IH]c1cccc2" -osmi
c12-c3c(cccc3)[IH]c1cccc2
> obabel -:"c1ccccc1#c1ccccc1" -osmi
==============================
*** Open Babel Warning  in OpenBabel::OBSmilesParser::ParseSmiles
  Failed to kekulize aromatic SMILES

[CH]1C=CC=C[C]1#[C]1[CH]C=CC=C1
```

**Comment by TermeHansen** [comment]
I have just compiled latest from master, and I still see the bug with Benzyne:

```
opt/openbabel/bin/obabel -ismi -:'c1ccccc#1' -oreport -h
FILENAME: 
FORMULA: C6H6
```
Open Babel 2.4.1 -- Jul 26 2017

**Comment by baoilleach** [comment]
I'll file a bug report for you. The bug reported above is fixed, as you can see.

**Comment by TermeHansen** [comment]
until the bug is opened I will fill in some more information I have found from the python interface, again with latest master from git.
using inchi ('InChI=1S/C6H4/c1-2-4-6-5-3-1/h1-4H'):
```
mol.GetFormula()
'C6H4'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-2-2',
 '1-1-3',
 '2-1-4',
 '3-2-5',
 '4-2-6',
 '5-2-6',
 '1-1-7',
 '2-1-8',
 '3-1-9',
 '4-1-10']
``` correct formula, benzene with 4 double bonds?!?

using smile ('C1=CC#CC=C1'):
```
mol.GetFormula()
'C6H4'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-2-2',
 '2-1-3',
 '3-3-4',
 '4-1-5',
 '5-2-6',
 '1-1-6',
 '1-1-7',
 '2-1-8',
 '5-1-9',
 '6-1-10']
``` correct formula, and correct structure

using smile ('c1ccccc#1'):
```
mol.GetFormula()
'C6H6'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-1-2',
 '2-2-3',
 '3-1-4',
 '4-2-5',
 '5-1-6',
 '1-3-6',
 '1-1-7',
 '2-1-8',
 '3-1-9',
 '4-1-10',
 '5-1-11',
 '6-1-12']
``` wrong formula, and correct aromatic structure, but Hydrogens on all carbons (brake of valence rule).
I hope this points in some direction.

**Comment by baoilleach** [comment]
Created issue #1605. Please add further comments there.
