### ISSUE TITLE
Canon failure for very simple case of two ions

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1166]
The attached SDF gives can of:
obabel 618085.sdf -ocan
[NH4+].[Cl-]

However., that SMILES string gives the opposite can:
obabel 618085.sdf -ocan | obabel -ismi -ocan
[Cl-].[NH4+]

Reported by: @baoilleach

**Comment by baoilleach** [comment]
Test file is:
[618085.sdf.txt](https://github.com/openbabel/openbabel/files/1049894/618085.sdf.txt)

**Comment by baoilleach** [comment]
Fixed by #1576. Both now give "[Cl-].[NH4+]".
