### ISSUE TITLE
SMILES parser loses aromaticity of fullerene

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1179]
The aromaticity of the attached SDF (C70 fullerene, see http://www.emolecules.com/cgi-bin/more?vid=30316111) is lost when it is read as a SMILES:

$ babel fullerene.sdf -o smi
c12c3c4c5c6c7c8c9c%10c%11c%12c%13c(c5c5c3c3c%14c1c1c%15c%14c%14c%16c3c5c%13c3c%16c5c%14c%13c%15c%14c%15c1c1c2c4c2c6c8c4c6c9c8c%10c9c%12c3c3c9c9c8c8c6c6c4c2c1c%15c6c1c%14c%13c(c53)c9c81)c7%11

 $ babel fullerene.sdf -o smi | babel -i smi -o can
C12C3C4C5C6C7C3C3C8C1C1C9C%10C2C2C4C4C5C5C%11C6C6C%12C7C3C3C7C8C1C1C8C9C9C%13C%10C2C2C4C4C5C5C%11C%10C6C6C%12C3C3C7C1C1C8C7C9C8C%13C2C4C2C8C4C7C7C1C3C6C7C%10C4C52

You can see that the problem occurs while parsing the SMILES by doing this:

$ babel fullerene.sdf -o smi | babel -i smi -o sdf

The resulting SDFs atom block seems to show two hydrogens on every carbon (which doesn't make sense) and the bond block is all single bonds.

Reported by: @cjames53

**Comment by baoilleach** [comment]
Fixed by #1576.
