### ISSUE TITLE
sdf to smi conversion - aromaticity of rings fails

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1201]
RE:  sdf to smi conversion - aromaticity of rings fails

After conversion the aromaticity of the ring system is not valid.
Does this go beyond what OpenBabel is intended to do,
or is this a bug?

This is an one example of a compound listed at DrugBank:  www.drugbank.ca
Compound ID:  DB02920
SMILES from DrugBank:
CC1=C(C=C)C2=CC3=[N-]4C(=CC5=C(CCC(O)=O)C(C)=C6N5[Zn++]44N2C1=CC1=[N-]4C(C(C)=C1C=C)=C6O)C(CCC(O)=O)=C3C

This was converted to the absolute SMILES at:
http://cdb.ics.uci.edu/cgibin/BabelWeb.py
ChemDB / Babel: Molecule Format Converter
SMILES:
Cc1c(c2=CC3=[N-]4C(=Cc5c(c(c6n5[Zn+2]47n2c1=CC8=[N-]7C(=C6O)C(=C8C=C)C)C)CCC(=O)O)C(=C3C)CCC(=O)O)C=C
This SMILES was converted to sdf and back to SMI with OpenBabel GUI.
Resulting SMILES:
Cc1c(c2=Cc3[n-]4c(=Cc5c(c(c6n5[Zn+2]54n2c1=Cc1[n-]5c(=C6O)c(c1C=C)C)C)CCC(=O)O)c(c3C)CCC(=O)O)C=C	

This SMILES gives and error instead of structure at:
ChemDB / Smi2Depict: Generate 2D Images from Molecule Files:
http://cdb.ics.uci.edu/cgibin/Smi2DepictWeb.py

The connections of the structure are valid but it apparently does not conform to aromaticity rules and so the ChemDB viewer will not display it.

John Gerlits
jg_erlit_s@hotmail.com
WindowsXP
OpenBabel version 2.3.1

Reported by: jgerlits

**Comment by baoilleach** [comment]
Seems to work fine with current version.
``` 
>obabel -:"Cc1c(c2=CC3=[N-]4C(=Cc5c(c(c6n5[Zn+2]47n2c1=CC8=[N-]7C(=C6O)C(=C8C=C)C)C)CCC(=O)O)C(=C3C)CCC(=O)O)C=C" -osdf | obabel -isdf -osmi
Cc1c(c2=CC3=[N-]4C(=Cc5c(c(c6n5[Zn+2]54n2c1=CC1=[N-]5C(=C6O)C(=C1C=C)C)C)CCC(=O)O)C(=C3C)CCC(=O)O)C=C
```
