### ISSUE TITLE
pH model term for azide removes a N

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1206]
```
obabel -:CN=[N+]=[N-] -osmi -p 7.4
C.[NH2+]=[N-]
```
...where is the missing nitrogen?

If one of the azide transformations is commented out all is well:
```
# TRANSFORM [ND2:1]=[ND2:2]=A >> [N]=[N+:2]=A                           1E+10
```
```
obabel -:CN=[N+]=[N-] -osmi -p 7.4
CN=[N+]=[N-]
1 molecule converted
```

I'm not sure what the intention of this term is, so it's hard to be sure what the right outcome is, but deleting the nitrogen is probably wrong!

Reported by: @baoilleach

Original Ticket: [openbabel/bugs/826](https://sourceforge.net/p/openbabel/bugs/826)

**Comment by baoilleach** [comment]
Works fine now. The SMARTS transform has been changed in the meanwhile.
