### ISSUE TITLE
S(C)(C)C not correctly interpreted by SMILES reader

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1207]
Reported by Daniel Lowe as part of PR#3157354
```
> obabel -:S(C)(C)C -osmi
[S](C)(C)C
```

Reported by: @baoilleach

Original Ticket: [openbabel/bugs/827](https://sourceforge.net/p/openbabel/bugs/827)

**Comment by baoilleach** [comment]
Fixed by #1576.
```
>obabel -:S(C)(C)C -osmi
S(C)(C)C
```
