### ISSUE TITLE
babel segfaults using --gen3D

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1216]
babel -ismi tmp.smi -osdf --gen3D segfaults using the attached file; --gen2D works though

Reported by: dhouston6

Original Ticket: [openbabel/bugs/836](https://sourceforge.net/p/openbabel/bugs/836)

**Comment by serval2412** [comment]
On pc Debian x86-64 with master sources updated today, I could reproduce this.
It seems the same as #1233 according to the bt.
parameterB is null too.

**Comment by timvdm** [comment]
Dupllicate of #1794
