### ISSUE TITLE
Python segfault when pybel & scipy.linalg imported

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1222]
The following short python script ends in a segfault.  I tested this on three different linux machines running ubuntu and archlinux

```
\#!/usr/bin/env python

import pybel
import scipy.linalg
```

There is no segfault if you reverse the order of the import.

Some package information:

Package: python-openbabel
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 3119
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: openbabel
Version: 2.3.0+dfsg-3ubuntu3
Provides: python2.7-openbabel
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libopenbabel4, libstdc++6 (>= 4.4.0), python2.7, python (>= 2.7.1-0ubuntu2), python (<< 2.8)
Original-Maintainer: Debichem Team <debichem-devel@lists.alioth.debian.org>
Homepage: http://openbabel.sourceforge.net

Package: python-scipy
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 24106
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 0.9.0+dfsg1-1ubuntu2
Provides: python2.7-scipy
Depends: python-numpy (>= 1:1.6.1), python-numpy-abi9, python2.7, python (>= 2.7.1-0ubuntu2), python (<< 2.8), libblas3gf | libblas.so.3gf | libatlas3gf-base, libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libgfortran3 (>= 4.6), liblapack3gf | liblapack.so.3gf | libatlas3gf-base, libstdc++6 (>= 4.1.1), libumfpack5.4.0 (>= 1:3.4.0)

Reported by: anthonybak

Original Ticket: [openbabel/bugs/842](https://sourceforge.net/p/openbabel/bugs/842)

**Comment by baoilleach** [comment]
Either fixed by #1775 or else it's a "works for me".
