### ISSUE TITLE
problem with hydrogens addition

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1223]
In 2.3.2 version of Openbabel (both invocation from python bindings and obabel binary) process enters in the infinite loop (no errors, process running & consuming CPU) with some molecules, like the attached one, if trying to add hydrogens to the molecule from which they were removed previously. In 2.3.1 version it worked correctly
Test scenario:
obabel 1.sdf -d -O 2.sdf # Done correctly
obabel 2.sdf -h -O 3.sdf # Never ends

Reported by: remezn

Original Ticket: [openbabel/bugs/843](https://sourceforge.net/p/openbabel/bugs/843)

**Comment by baoilleach** [comment]
Seems to work fine now.
