### ISSUE TITLE
Segfault when calculating FF energy or gen3D

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1233]
The following command produces a segmentation fault:

obabel -:"[2H]c1cc(c(cc1[2H])[2H])[2H]" -o sdf -O temp.sdf --gen3D

I have an sdf file with 3D coordinates for this molecule, and the segmentation fault also occurs when I try to compute the UFF energy.

Reported by: mtrsky

Original Ticket: [openbabel/bugs/853](https://sourceforge.net/p/openbabel/bugs/853)

**Comment by serval2412** [comment]
On pc Debian x86-64 with master sources updated today, I could reproduce this.
I attached the bt which shows this line:
765 openbabel/src/forcefields/forcefielduff.cpp
and parameterB = (OpenBabel::OBFFParameter *) 0x0
[bt.txt](https://github.com/openbabel/openbabel/files/1910366/bt.txt)

**Comment by serval2412** [comment]
It's not obvious to me to tell why GetParameterUFF returns NULL here or even if it could be expected so I can't do more here :-(

**Comment by timvdm** [comment]
Duplicate of #1794
