### ISSUE TITLE
Seg fault in gen3D

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1234]
Segmentation fault when calling:

obabel -:"[Br-][Al](C)(C)C" -o sdf -O temp.sdf --gen3D

Openbabel 2.3.2

Reported by: mtrsky

Original Ticket: [openbabel/bugs/854](https://sourceforge.net/p/openbabel/bugs/854)

**Comment by ghutchis** [comment]
This works with OB-2.4.0
