### ISSUE TITLE
inchi writer uninitialized variable

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1252]
valgrind(1) reports the use of an uninitialized variable in the InChI library with certain unusual metal/salt combinations.

echo "[Na+][Ge-2][Na+]" | valgrind obabel -i smi -o inchi
==18000== Memcheck, a memory error detector
==18000== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==18000== Using Valgrind-3.6.0.SVN-Debian and LibVEX; rerun with -h for copyright info
==18000== Command: obabel -i smi -o inchi
==18000== 
==18000== Conditional jump or move depends on uninitialised value(s)
==18000==    at 0x4C28757: strcpy (mc_replace_strmem.c:311)
==18000==    by 0x68555B5: MakeCRVString (string3.h:107)
==18000==    by 0x6820F75: str_AuxChargeRadVal (ichiprt3.c:2939)
==18000==    by 0x688F163: OutputINChI1 (ichiprt1.c:3128)
==18000==    by 0x68937B4: OutputINChI2 (ichiprt1.c:1110)
==18000==    by 0x684CF3D: SortAndPrintINChI (runichi.c:958)
==18000==    by 0x684DCAB: ProcessOneStructure (runichi.c:2933)
==18000==    by 0x68797ED: GetINCHI1 (inchi_dll.c:451)
==18000==    by 0x1213EE92: OpenBabel::InChIFormat::WriteMolecule(OpenBabel::OBBase*, OpenBabel::OBConversion*) (inchiformat.cpp:489)
==18000==    by 0x5343D07: OpenBabel::OBMoleculeFormat::WriteChemObjectImpl(OpenBabel::OBConversion*, OpenBabel::OBFormat*) (obmolecformat.cpp:182)
==18000==    by 0x52E6B95: OpenBabel::OBConversion::Convert() (obconversion.cpp:581)
==18000==    by 0x52E7347: OpenBabel::OBConversion::Convert(std::istream*, std::ostream*) (obconversion.cpp:450)
==18000== 

Reported by: @cjames53

Original Ticket: [openbabel/bugs/872](https://sourceforge.net/p/openbabel/bugs/872)

**Comment by serval2412** [comment]
With valgrind-3.13.0 and Openbabel master sources updated some days ago, I don't reproduce this.
Do you still reproduce this with recent Valgrind and Openbabel version?
