### ISSUE TITLE
kekulize.cpp crashes on modified molecule

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1253]
The short program below causes a segmentation violation.  If you un-comment the first pmol->EndModify(), the program doesn't crash.  The crash occurs on kekulize.cpp line 164, which is being called from the SMARTS matching because the particular SMARTS wants to know the number of bonds ("[v1]") to each atom.  The problem seems to be that the LSSR being used isn't valid because of the deleted atom.  Calling EndModify() before applying the SMARTS apparently resets something so that the segfault doesn't occur.

````````````~~~
#include <string>
#include <sstream>

#include <openbabel/babelconfig.h>
#include <openbabel/mol.h>
#include <openbabel/obconversion.h>

using namespace std;
using namespace OpenBabel;

int main(int argc, char **argv)  {

  OBMol *pmol = new OBMol;
  OBConversion conv(&cin, &cout);
  conv.SetInAndOutFormats("smi", "smi");
  conv.ReadString(pmol, "Cl.OC1CN2CCC1CC2");

  OBAtom *atom = pmol->GetAtom(1);      // Cl atom
  pmol->BeginModify();
  pmol->DeleteAtom(atom);

  OBSmartsPattern smarts;
  smarts.Init("[v1]");
  // pmol->EndModify();     // uncomment this and the segfault disappears
  smarts.Match(*pmol);

  pmol->EndModify();
  conv.Write(pmol);
}
```````````````~~



Reported by: @cjames53

Original Ticket: [openbabel/bugs/873](https://sourceforge.net/p/openbabel/bugs/873)

**Comment by baoilleach** [comment]
I'm going to close this for now. It doesn't tell us anything new that we don't know. I don't think now that the solution is documentation or better invalidation of perceived data. IMO, the solution is not to shuffle along the atoms when an atom is deleted. After that, it's the user's responsibility to reperceive ring data if they delete a ring atom.
