### ISSUE TITLE
aromaticity of cyclobutenedione

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1254]
If you have a cyclobutenedione drawn in the aromatic form, openbabel 2.3.2 will canonicalize it to cyclobutadione, hydrogenating the double bond in the ring.

echo 'CCOc1c(NCC)c(=O)c1=O'| obabel -ismi -ocan
CCNC1C(=O)C(=O)C1OCC

I don't know if cyclobutenedione is really aromatic or not, but if it is drawn as aromatic, then it can't have two sp3 carbons in the ring the way the canonicalization has it

Reported by: jeff-janes

Original Ticket: [openbabel/bugs/874](https://sourceforge.net/p/openbabel/bugs/874)

**Comment by baoilleach** [comment]
(FYI @jeffjanes) The smiles is correctly read with #1576 ("CCOC1=C(NCC)C(=O)C1=O"), but it is not perceived (on writing) as aromatic (but should be according to Daylight).

**Comment by baoilleach** [comment]
Actually, this is working correctly.
