### ISSUE TITLE
Round Trip SMILES changes double bonds to single bonds

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1278]
I am using openbabel 2.3.2, on a windows 7 32 bit machine.

I found this discrepancy from the command line, but also using the openbabel GUI

I started with the following SMILES, obtained from the nih cactus server:
[P]2(OC1=C(C(C)(C)C)C=C(C(C)(C)C)C=C1C3=C(O2)C(=CC(=C3)C(C)(C)C)C(C)(C)C)OCCN(CCO[P]5OC4=C(C(C)(C)C)C=C(C(C)(C)C)C=C4C6=C(O5)C(=CC(=C6)C(C)(C)C)C(C)(C)C)CCO[P]8OC7=C(C(C)(C)C)C=C(C(C)(C)C)C=C7C9=C(O8)C(=CC(=C9)C(C)(C)C)C(C)(C)C

if I translate this starting SMILES to SMILES, I get the following result:
p1(oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C)OCCN(CCOp1oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C)CCOp1oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C

and the following formula results from the original smiles, using the -oreport option:
FORMULA: C90H132NO9P3
MASS: 1464.9337
EXACT MASS: 1463.9114947

next, I take the **resulting** smiles, as listed above, copied and pasted, and use it as the input:
p1(oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C)OCCN(CCOp1oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C)CCOp1oc2c(C(C)(C)C)cc(C(C)(C)C)cc2c2c(o1)c(cc(c2)C(C)(C)C)C(C)(C)C

When i convert to -report, and view the graphics results, I see that all of the double bonds are converted to sigle bonds:
FORMULA: C90H168NO9P3
MASS: 1501.2195
EXACT MASS: 1500.1931959

I am sure that this is not the intended behavior, to electronically hydrogenate a molecule.  Please have a look at this when time allows.

Tim J

Reported by: tjanota

Original Ticket: [openbabel/bugs/898](https://sourceforge.net/p/openbabel/bugs/898)

**Comment by baoilleach** [comment]
Seems to be fixed.
