### ISSUE TITLE
obabel segfault from invalid command-line arg

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1282]
The simple command "obabel -i" causes a segfault.

The problem is several cases like this:

    for (arg = 1; arg < argc; ++arg)
      {
       ...
       case 'i':
         iext = argv[arg] + 2;
         if(!*iext)
           iext = argv[++arg];

Note that arg is incremented without checking to see whether it's past argc, so it's accessing past the end of the argv array.  By luck, it's getting a NULL pointer, but iext could point to anything.  There are a number of instances of this in the command-line parsing section.

Reported by: @cjames53

Original Ticket: [openbabel/bugs/902](https://sourceforge.net/p/openbabel/bugs/902)

**Comment by serval2412** [comment]
On master sources updated today, I could reproduce this, here's part of the bt:
`#1  0x000055555555eaec in main (argc=2, argv=0x7fffffffe8e8) at /home/julien/projects/openbabel/tools/obabel.cpp:115
115	                  if (strncasecmp(iext, "MIME", 4) == 0)
(gdb) p iext
$1 = 0x0`
