### ISSUE TITLE
Segmentation fault loading pubchem xml with .xml extension

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1289]
Loading a pubchem XML document with an XML extension will give a segfault.

I am using "Open Babel 2.3.2" from [this debian package](http://packages.debian.org/jessie/openbabel).

Steps to reproduce:
1. run `obprop CID_2519.xml`. It segfaults with a null pointer dereference.

The attached file `CID_2519.xml` comes from the [pubchem page for caffeine](https://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=2519&loc=ec_rcs#) by downloading the "2D XML: Save" option. If you rename the file to ".pc" as openbabel expects, then the file will be parsed correctly and there will be no segfault.

This issue is moderately inconvenient, because it means that avogadro cannot directly open the .xml files downloaded from pubchem.

Stack Trace:

    #  0 OpenBabel::XMLFormat::ReadMolecule(OpenBabel::OBBase*, OpenBabel::OBConversion*) at 0x7fffd09bbf3a in /usr/lib/openbabel/2.3.2/xmlformat.so
    #  1 OpenBabel::OBConversion::Read(OpenBabel::OBBase*, std::istream*) at 0x7ffff7727f6a in /usr/lib/libopenbabel.so.4.0.2
    #  2 None at 0x7ffff5cc3303 in /usr/lib/libavogadro.so.1.0.3
    #  3 None at 0x7ffff61f42ef in /usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.6
    #  4 start_thread at 0x7ffff48ebe0e in /lib/x86_64-linux-gnu/libpthread-2.17.so
    #  5 clone at 0x7ffff7b180fd in /lib/x86_64-linux-gnu/libc-2.17.so (BL)

Reported by: wirtha

Original Ticket: [openbabel/bugs/909](https://sourceforge.net/p/openbabel/bugs/909)

**Comment by serval2412** [comment]
Derek's fix is already in master (see e3f2d08c8c3e2398b2561a0428d642b4f6898fa8).
Can we close this one?

**Comment by serval2412** [comment]
Forgot to tell, I don't reproduce this with master sources, as expected (see my previous comment), here's the result:

> `julien@debian:~/projects/openbabel/build/bin$` ./obprop ../../bugs/
CID_2519.xml       mol1opt.log        mol1test_freq.log  patch-909.txt      
julien@debian:~/projects/openbabel/build/bin$ ./obprop ../../bugs/CID_2519.xml 
==============================
*** Open Babel Error  in XML Format
  Need to specify the input XML format more `precisely`
