### ISSUE TITLE
Spacegroup database has errors

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1292]
The space-groups.txt database has the following faults:

1. Comparing spacegroup 210 to International Tables for Crystallography, it is wrong at a glance, containing only translations by +-1/2, while it should also contain translations by 1/4 and 3/4.

+ Both settings of spacegroup 222 contain the same symmetry operations, which they shouldn't.

+ Hexagonal setting of spacegroup 160 has some of the symmetry operations negated.

+ Spacegroup B -2bc has two incorrect operations.

I fixed the latter two manually since they are small enough, and imported the first two from spglib. Patch follows.

    --- space-groups.orig	2012-10-03 21:08:56.000000000 +0200
    +++ space-groups.txt	2014-02-12 15:37:18.604296364 +0100
    @@ -397,9 +397,9 @@
     B -2bc
     B 1 1 n
     x,y,z
    -x,1/2+y,-z
    +x,1/2+y,1/2-z
     1/2+x,y,1/2+z
    -1/2+x,1/2+y,1/2-z
    +1/2+x,1/2+y,-z
     
     9
     I -2b
    @@ -5790,21 +5790,21 @@
     x,y,z
     -y,x-y,z
     y-x,-x,z
    -y,x,-z
    -x-y,-y,-z
    --x,y-x,-z
    +-y,-x,z
    +y-x,y,z
    +x,x-y,z
     2/3+x,1/3+y,1/3+z
     2/3-y,1/3+x-y,1/3+z
     2/3+y-x,1/3-x,1/3+z
    -2/3+y,1/3+x,1/3-z
    -2/3+x-y,1/3-y,1/3-z
    -2/3-x,1/3+y-x,1/3-z
    +2/3-y,1/3-x,1/3+z
    +2/3+y-x,1/3+y,1/3+z
    +2/3+x,1/3+x-y,1/3+z
     1/3+x,2/3+y,2/3+z
     1/3-y,2/3+x-y,2/3+z
     1/3+y-x,2/3-x,2/3+z
    -1/3+y,2/3+x,2/3-z
    -1/3+x-y,2/3-y,2/3-z
    -1/3-x,2/3+y-x,2/3-z
    +1/3-y,2/3-x,2/3+z
    +1/3+y-x,2/3+y,2/3+z
    +1/3+x,2/3+x-y,2/3+z
     
     160
     P 3* -2
    @@ -7277,102 +7277,102 @@
     210
     F 4d 2 3
     F 41 3 2
    -x,y,z
    --x,-y,z
    --x,y,-z
    -x,-y,-z
    -z,x,y
    -z,-x,-y
    --z,-x,y
    --z,x,-y
    -y,z,x
    --y,z,-x
    -y,-z,-x
    --y,-z,x
    -1/2+y,1/2+x,1/2+z
    -1/2-y,1/2-x,1/2+z
    -1/2+y,1/2-x,1/2-z
    -1/2-y,1/2+x,1/2-z
    -1/2+x,1/2+z,1/2+y
    -1/2-x,1/2+z,1/2-y
    -1/2-x,1/2-z,1/2+y
    -1/2+x,1/2-z,1/2-y
    -1/2+z,1/2+y,1/2+x
    -1/2+z,1/2-y,1/2-x
    -1/2-z,1/2+y,1/2-x
    -1/2-z,1/2-y,1/2+x
    -x,1/2+y,1/2+z
    --x,1/2-y,1/2+z
    --x,1/2+y,1/2-z
    -x,1/2-y,1/2-z
    -z,1/2+x,1/2+y
    -z,1/2-x,1/2-y
    --z,1/2-x,1/2+y
    --z,1/2+x,1/2-y
    -y,1/2+z,1/2+x
    --y,1/2+z,1/2-x
    -y,1/2-z,1/2-x
    --y,1/2-z,1/2+x
    -1/2+y,x,z
    -1/2-y,-x,z
    -1/2+y,-x,-z
    -1/2-y,x,-z
    -1/2+x,z,y
    -1/2-x,z,-y
    -1/2-x,-z,y
    -1/2+x,-z,-y
    -1/2+z,y,x
    -1/2+z,-y,-x
    -1/2-z,y,-x
    -1/2-z,-y,x
    -1/2+x,y,1/2+z
    -1/2-x,-y,1/2+z
    -1/2-x,y,1/2-z
    -1/2+x,-y,1/2-z
    -1/2+z,x,1/2+y
    -1/2+z,-x,1/2-y
    -1/2-z,-x,1/2+y
    -1/2-z,x,1/2-y
    -1/2+y,z,1/2+x
    -1/2-y,z,1/2-x
    -1/2+y,-z,1/2-x
    -1/2-y,-z,1/2+x
    -y,1/2+x,z
    --y,1/2-x,z
    -y,1/2-x,-z
    --y,1/2+x,-z
    -x,1/2+z,y
    --x,1/2+z,-y
    --x,1/2-z,y
    -x,1/2-z,-y
    -z,1/2+y,x
    -z,1/2-y,-x
    --z,1/2+y,-x
    --z,1/2-y,x
    -1/2+x,1/2+y,z
    -1/2-x,1/2-y,z
    -1/2-x,1/2+y,-z
    -1/2+x,1/2-y,-z
    -1/2+z,1/2+x,y
    -1/2+z,1/2-x,-y
    -1/2-z,1/2-x,y
    -1/2-z,1/2+x,-y
    -1/2+y,1/2+z,x
    -1/2-y,1/2+z,-x
    -1/2+y,1/2-z,-x
    -1/2-y,1/2-z,x
    -y,x,1/2+z
    --y,-x,1/2+z
    -y,-x,1/2-z
    --y,x,1/2-z
    -x,z,1/2+y
    --x,z,1/2-y
    --x,-z,1/2+y
    -x,-z,1/2-y
    -z,y,1/2+x
    -z,-y,1/2-x
    --z,y,1/2-x
    --z,-y,1/2+x
    +x,y,z 
    +x,1/2-y,1/2-z 
    +x,1/2+y,1/2+z 
    +x,-y,-z 
    +y,z,x 
    +y,1/2-z,1/2-x 
    +y,1/2+z,1/2+x 
    +y,-z,-x 
    +z,x,y 
    +z,1/2-x,1/2-y 
    +z,1/2+x,1/2+y 
    +z,-x,-y 
    +-x,-y,z 
    +-x,1/2+y,1/2-z 
    +-x,1/2-y,1/2+z 
    +-x,y,-z 
    +-y,-z,x 
    +-y,1/2+z,1/2-x 
    +-y,1/2-z,1/2+x 
    +-y,z,-x 
    +-z,-x,y 
    +-z,1/2+x,1/2-y 
    +-z,1/2-x,1/2+y 
    +-z,x,-y 
    +1/2+x,-y,1/2-z 
    +1/2+x,1/2+y,z 
    +1/2+x,1/2-y,-z 
    +1/2+x,y,1/2+z 
    +1/2+y,-z,1/2-x 
    +1/2+y,1/2+z,x 
    +1/2+y,1/2-z,-x 
    +1/2+y,z,1/2+x 
    +1/2+z,-x,1/2-y 
    +1/2+z,1/2+x,y 
    +1/2+z,1/2-x,-y 
    +1/2+z,x,1/2+y 
    +1/2-x,-y,1/2+z 
    +1/2-x,1/2+y,-z 
    +1/2-x,1/2-y,z 
    +1/2-x,y,1/2-z 
    +1/2-y,-z,1/2+x 
    +1/2-y,1/2+z,-x 
    +1/2-y,1/2-z,x 
    +1/2-y,z,1/2-x 
    +1/2-z,-x,1/2+y 
    +1/2-z,1/2+x,-y 
    +1/2-z,1/2-x,y 
    +1/2-z,x,1/2-y 
    +1/4+x,1/4+z,1/4-y 
    +1/4+x,1/4-z,1/4+y 
    +1/4+x,3/4+z,3/4-y 
    +1/4+x,3/4-z,3/4+y
    +1/4+y,1/4+x,1/4-z 
    +1/4+y,1/4-x,1/4+z 
    +1/4+y,3/4+x,3/4-z 
    +1/4+y,3/4-x,3/4+z 
    +1/4+z,1/4+y,1/4-x 
    +1/4+z,1/4-y,1/4+x 
    +1/4+z,3/4+y,3/4-x 
    +1/4+z,3/4-y,3/4+x 
    +1/4-x,1/4+z,1/4+y 
    +1/4-x,1/4-z,1/4-y 
    +1/4-x,3/4+z,3/4+y 
    +1/4-x,3/4-z,3/4-y 
    +1/4-y,1/4+x,1/4+z 
    +1/4-y,1/4-x,1/4-z 
    +1/4-y,3/4+x,3/4+z 
    +1/4-y,3/4-x,3/4-z 
    +1/4-z,1/4+y,1/4+x 
    +1/4-z,1/4-y,1/4-x 
    +1/4-z,3/4+y,3/4+x 
    +1/4-z,3/4-y,3/4-x 
    +3/4+x,1/4+z,3/4-y 
    +3/4+x,1/4-z,3/4+y 
    +3/4+x,3/4+z,1/4-y 
    +3/4+x,3/4-z,1/4+y 
    +3/4+y,1/4+x,3/4-z 
    +3/4+y,1/4-x,3/4+z 
    +3/4+y,3/4+x,1/4-z 
    +3/4+y,3/4-x,1/4+z 
    +3/4+z,1/4+y,3/4-x 
    +3/4+z,1/4-y,3/4+x 
    +3/4+z,3/4+y,1/4-x 
    +3/4+z,3/4-y,1/4+x 
    +3/4-x,1/4+z,3/4+y 
    +3/4-x,1/4-z,3/4-y 
    +3/4-x,3/4+z,1/4+y 
    +3/4-x,3/4-z,1/4-y 
    +3/4-y,1/4+x,3/4+z 
    +3/4-y,1/4-x,3/4-z 
    +3/4-y,3/4+x,1/4+z 
    +3/4-y,3/4-x,1/4-z 
    +3/4-z,1/4+y,3/4+x 
    +3/4-z,1/4-y,3/4-x 
    +3/4-z,3/4+y,1/4+x 
    +3/4-z,3/4-y,1/4-x 
     
     211
     I 4 2 3
    @@ -7949,54 +7949,54 @@
     222
     P 4 2 3 -1n
     P n -3 n
    -x,y,z
    -1/2-x,1/2-y,z
    -1/2-x,y,1/2-z
    -x,1/2-y,1/2-z
    -z,x,y
    -z,1/2-x,1/2-y
    -1/2-z,1/2-x,y
    -1/2-z,x,1/2-y
    -y,z,x
    -1/2-y,z,1/2-x
    -y,1/2-z,1/2-x
    -1/2-y,1/2-z,x
    -y,x,1/2-z
    -1/2-y,1/2-x,1/2-z
    -y,1/2-x,z
    -1/2-y,x,z
    -x,z,1/2-y
    -1/2-x,z,y
    -1/2-x,1/2-z,1/2-y
    -x,1/2-z,y
    -z,y,1/2-x
    -z,1/2-y,x
    -1/2-z,y,x
    -1/2-z,1/2-y,1/2-x
    --x,-y,-z
    -1/2+x,1/2+y,-z
    -1/2+x,-y,1/2+z
    --x,1/2+y,1/2+z
    --z,-x,-y
    --z,1/2+x,1/2+y
    -1/2+z,1/2+x,-y
    -1/2+z,-x,1/2+y
    --y,-z,-x
    -1/2+y,-z,1/2+x
    --y,1/2+z,1/2+x
    -1/2+y,1/2+z,-x
    --y,-x,1/2+z
    -1/2+y,1/2+x,1/2+z
    --y,1/2+x,-z
    -1/2+y,-x,-z
    --x,-z,1/2+y
    -1/2+x,-z,-y
    -1/2+x,1/2+z,1/2+y
    --x,1/2+z,-y
    --z,-y,1/2+x
    --z,1/2+y,-x
    -1/2+z,-y,-x
    -1/2+z,1/2+y,1/2+x
    +x,y,z 
    +-y,x,z 
    +-x,-y,z 
    +y,-x,z 
    +x,-y,-z 
    +-y,-x,-z 
    +-x,y,-z 
    +y,x,-z 
    +z,x,y 
    +z,-y,x 
    +z,-x,-y 
    +z,y,-x 
    +-z,x,-y 
    +-z,-y,-x 
    +-z,-x,y 
    +-z,y,x 
    +y,z,x 
    +x,z,-y 
    +-y,z,-x 
    +-x,z,y 
    +-y,-z,x 
    +-x,-z,-y 
    +y,-z,-x 
    +x,-z,y 
    +1/2-x,1/2-y,1/2-z 
    +1/2+y,1/2-x,1/2-z 
    +1/2+x,1/2+y,1/2-z 
    +1/2-y,1/2+x,1/2-z 
    +1/2-x,1/2+y,1/2+z 
    +1/2+y,1/2+x,1/2+z 
    +1/2+x,1/2-y,1/2+z 
    +1/2-y,1/2-x,1/2+z 
    +1/2-z,1/2-x,1/2-y 
    +1/2-z,1/2+y,1/2-x 
    +1/2-z,1/2+x,1/2+y 
    +1/2-z,1/2-y,1/2+x 
    +1/2+z,1/2-x,1/2+y 
    +1/2+z,1/2+y,1/2+x 
    +1/2+z,1/2+x,1/2-y 
    +1/2+z,1/2-y,1/2-x 
    +1/2-y,1/2-z,1/2-x 
    +1/2-x,1/2-z,1/2+y 
    +1/2+y,1/2-z,1/2+x 
    +1/2+x,1/2-z,1/2-y 
    +1/2+y,1/2+z,1/2-x 
    +1/2+x,1/2+z,1/2+y 
    +1/2-y,1/2+z,1/2+x 
    +1/2-x,1/2+z,1/2-y
     
     222
     -P 4a 2bc 3

Reported by: exzombie

Original Ticket: [openbabel/bugs/912](https://sourceforge.net/p/openbabel/bugs/912)

**Comment by wojdyr** [comment]
I looked at the four issues reported by exzombie here and I believe they all have been fixed in the meantime. This issue can be closed.

**Comment by baoilleach** [comment]
Pinging the original reporter, @exzombie.

**Comment by exzombie** [comment]
@wojdyr are you sure? This was never merged as-is and looking at commits, 7534c4626f1c72187472cada055b3176048040a5 *may* solve the issues I noticed with group 210, but for the rest, I can't tell with a quick glance. For example, 445afcb1428c80d98fce5f03fb9a8ae763a170ff touches group 222, but only changes the group's header.

From what I can remember, I noticed a problem while fixing `avogadro`, so I decided to systematically compare `openbabel` to `spglib`, yielding this bug report. Sadly, I don't have the test program after all these years, and ATM, I don't have the time to write it again. Perhaps later, although I hope someone beats me to it :)

**Comment by wojdyr** [comment]
@exzombie: going through your original points:

>    Comparing spacegroup 210 to International Tables for Crystallography, it is wrong at a glance, containing only translations by +-1/2, while it should also contain translations by 1/4 and 3/4.

now it contains translation by 1/4 and 3/4

>    Both settings of spacegroup 222 contain the same symmetry operations, which they shouldn't.

now they contain different operations and I just double checked -- they are correct (unless I erred when checking).

>    Hexagonal setting of spacegroup 160 has some of the symmetry operations negated.

all looks good to me
http://img.chem.ucl.ac.uk/sgp/large/160bz1.htm

>   Spacegroup B -2bc has two incorrect operations.

Now it is:
```
9
B -2bc
B n,B 1 1 n
x,y,z
x,1/2+y,1/2-z
1/2+x,y,1/2+z
1/2+x,1/2+y,-z
```
which is what you proposed in your patch.

In general, all operations match Hall symbols (apart from the one reported in #1641), but I didn't compare it with any external reference.

**Comment by afonari** [comment]
All space groups (540) present in spglib are present and have the same symm ops as in open babel. On top of that, open babel contains these Hall groups:
`['B 1', '-A 1', 'F 1', '-C 1', 'C 1', '-I 1', 'C -4 -2b', '-F 2y', '-F 4 2', 'I 1', '-I 4bd 2c 3', '-B 1', 'A 1', '-F 1', 'C 2c']`

**Comment by wojdyr** [comment]
But isn't the total number of entries in `space-groups.txt` 541? (not 540+15)

**Comment by afonari** [comment]
Ah, sorry you are correct. Spglib has 530 hall groups. 3 of those are not unique: `'C 2 2 -1bc', 'A 2 2 -1ac', 'B 2 2 -1bc'`.

Open babel contains 541 groups. 14 (not 15, as I wrote before) are not found in spglib:
`['B 1', '-A 1', 'F 1', '-C 1', 'C 1', '-I 1', 'C -4 -2b', '-F 2y', '-F 4 2', 'I 1', '-B 1', 'A 1', '-F 1', 'C 2c']`

527 + 14 == 541.

**Comment by exzombie** [comment]
@wojdyr: alright, thanks for checking.

**Comment by baoilleach** [comment]
Shouldn't we be working with spglib etc to develop a shared resource in this area?

**Comment by afonari** [comment]
What do you mean by a 'resource'?

**Comment by baoilleach** [comment]
That's the code. I think we can still work together on a list of space groups, e.g. under the Blue Obelisk umbrella.

**Comment by afonari** [comment]
I fear not to have similar situation as with webkit situation, where (in past) different browsers will use webkit. More engines is actually a good thing.

**Comment by baoilleach** [comment]
I must have misunderstood. I thought that the set of space groups is fixed
and known, and it is just a case of getting the information correct.

**Comment by afonari** [comment]
> I thought that the set of space groups is fixed and known, and it is just a case of getting the information correct.

As you can see from the discussion above, it is not necessarily the case ;)

**Comment by wojdyr** [comment]
@baoilleach: the set of space group is indeed fixed -- there are 230 3D space groups.
*The* reference for the names of the space groups is International Tables for Crystallography.
But while it is clear what are the names and operations of the standard settings for each space groups, and of popular alternative settings, it may not be so clear for some obscure settings.

To clarify: for many space groups you can have alternative settings with changed basis and/or shifted origin. Any two settings of the same space group can be transformed into each other by applying a 4x4 transformation matrix. The question is what settings are practical, useful and worth listing in a table. And what are their standard (H-M) names. (There is no problem with interpreting Hall names: they are unambiguous and they encode all the operations in the name).

ITfC has a few tables that list spacegroup settings (in Vol. A and B). These tables list different sets of settings, and they may differ between editions of ITfC. The table that is most commonly used in computer programs is in Vol. B. It is the same table that is used by SgInfo and cctbx/sgtbx (and spglib) and it's available here: http://cci.lbl.gov/sginfo/hall_symbols.html. It has 530 entries (3 are duplicate, as @afonari wrote above; different standard names correspond to the same sets of operations).

The only thing that differs is that Open Babel recognizes 14 (as @afonari calculated) extra settings. It's probably good, but there is no good reference for naming of these settings.
For example: "C -4 2 b" is listed on http://img.chem.ucl.ac.uk/sgp/MEDIUM/117cz1.htm, but not in ITfC. ITfC have a C-centered settings of the same spacegroup (117) named "C -4 2 g1". This name is listed in table 1.5.4.4 in Vol.A ch.1.5 (and without any further information), but not in the table with Hall symbols. So I'm not able to tell if "C -4 2 g1" from ITfC and "C -4 2 b" from Birkbeck collage website refer to the same settings.

Regarding shared resources: most of the programs I've seen use either the list of [530 settings][1] or the [syminfo.lib][2] file from CCP4 (or the older version named `symop.lib`).
I guess it's unavoidable that different programs recognize different sets of symbols, as there is no definite list.

[1]: http://cci.lbl.gov/sginfo/hall_symbols.html
[2]: http://fg.oisin.rc-harwell.ac.uk/scm/loggerhead/libccp4/trunk/view/head:/data/syminfo.lib

**Comment by baoilleach** [comment]
Thanks @wojdyr. Sounds like a great section for our forthcoming "crystallography with Open Babel" chapter in the docs.

**Comment by afonari** [comment]
Yep, thanks @wojdyr for taking the time summarizing stuff.
