### ISSUE TITLE
bond type 4 in SDF gives wrong Implicit-H count

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1300]
In an SDF, bond type "4" (aromatic) is not legal but is widely used. OpenBabel seems to parse it correctly (e.g. it will produce a correct SMILES or SDF), but atom->ImplicitHydrogenCount() returns the wrong value. See the attached C++ program. Here is the output of the program; note that impH is different in the two molecules even though both are benzene.

atom 1:  impH: 1, bond orders: 2 1
atom 2:  impH: 1, bond orders: 2 1
atom 3:  impH: 1, bond orders: 1 2
atom 4:  impH: 1, bond orders: 2 1
atom 5:  impH: 1, bond orders: 1 2
atom 6:  impH: 1, bond orders: 2 1

atom 1:  impH: 0, bond orders: 2 1
atom 2:  impH: 0, bond orders: 2 1
atom 3:  impH: 0, bond orders: 1 2
atom 4:  impH: 0, bond orders: 2 1
atom 5:  impH: 0, bond orders: 1 2
atom 6:  impH: 0, bond orders: 2 1

Reported by: @cjames53

Original Ticket: [openbabel/bugs/920](https://sourceforge.net/p/openbabel/bugs/920)

**Comment by baoilleach** [comment]
Here's the .cpp file from the original bug report:
<pre>

#include <openbabel/babelconfig.h>
#include <openbabel/mol.h>
#include <openbabel/obconversion.h>
#include <openbabel/plugin.h>

using namespace std;
using namespace OpenBabel;

const char *benzenes[] = {

  // Normal Kekule form
  "[NO NAME]\n"
  "  CHEMW2  04151411042D                              \n"
  "Created with ChemWriter - http://chemwriter.com\n"
  "  6  6  0  0  0  0            999 V2000\n"
  "  -15.8305   -2.0277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -11.5003   -4.5277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "   -7.1702   -2.0277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "   -7.1702    2.9723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -11.5003    5.4723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -15.8305    2.9723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  1  2  2  0  0  0  0\n"
  "  2  3  1  0  0  0  0\n"
  "  3  4  2  0  0  0  0\n"
  "  4  5  1  0  0  0  0\n"
  "  5  6  2  0  0  0  0\n"
  "  6  1  1  0  0  0  0\n"
  "M  END\n",

  // Nonstandard aromatic (bond type 4) form
  "[NO NAME]\n"
  "  CHEMW2  04151411042D                              \n"
  "Created with ChemWriter - http://chemwriter.com\n"
  "  6  6  0  0  0  0            999 V2000\n"
  "  -15.8305   -2.0277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -11.5003   -4.5277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "   -7.1702   -2.0277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "   -7.1702    2.9723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -11.5003    5.4723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  -15.8305    2.9723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
  "  1  2  4  0  0  0  0\n"
  "  2  3  4  0  0  0  0\n"
  "  3  4  4  0  0  0  0\n"
  "  4  5  4  0  0  0  0\n"
  "  5  6  4  0  0  0  0\n"
  "  6  1  4  0  0  0  0\n"
  "M  END\n",

  NULL
};

main(int argc, char **argv) {

  OBConversion conv;
  OBMol mol;
  const char **p;

  conv.SetInAndOutFormats("sdf", "sdf");

  for (p = benzenes; *p; p++) {
    cout << "\n";
    conv.ReadString(&mol, *p);
    FOR_ATOMS_OF_MOL(atom, &mol) {
      int idx = atom->GetIdx();
      cout << "atom " << idx << ": ";
      cout << " impH: " << atom->ImplicitHydrogenCount() << ", bond orders:";
      FOR_BONDS_OF_ATOM(b, &(*atom)) {
	int border = b->GetBO();
	cout << " " << border;
      }
      cout << "\n";
    }
  }
}

</pre>

**Comment by baoilleach** [comment]
Fixed by #1576 

<pre>
atom 1:  impH: 1, bond orders: 2 1
atom 2:  impH: 1, bond orders: 2 1
atom 3:  impH: 1, bond orders: 1 2
atom 4:  impH: 1, bond orders: 2 1
atom 5:  impH: 1, bond orders: 1 2
atom 6:  impH: 1, bond orders: 2 1

atom 1:  impH: 1, bond orders: 2 1
atom 2:  impH: 1, bond orders: 2 1
atom 3:  impH: 1, bond orders: 1 2
atom 4:  impH: 1, bond orders: 2 1
atom 5:  impH: 1, bond orders: 1 2
atom 6:  impH: 1, bond orders: 2 1
</pre>
