### ISSUE TITLE
Pybel modules can't be imported

### ISSUE THREAD

**Issue by yujietia** [openbabel/openbabel#131]
Cmake Config is like following:
![screen shot 2015-03-09 at 5 14 26 pm](https://cloud.githubusercontent.com/assets/10948687/6564526/ceb806b4-c67f-11e4-9833-a2e0e3b744ca.png)
![screen shot 2015-03-09 at 5 14 38 pm](https://cloud.githubusercontent.com/assets/10948687/6564527/ceb96ec8-c67f-11e4-813a-cfdbbf30bc30.png)

And the Cmake Log is like following:
Using included inchi library.
checking for module 'cairo'
  package 'cairo' not found
Could NOT find Cairo. PNG output will NOT be supported.
GUI will not be built
CMake Warning (dev) at test/CMakeLists.txt:174 (include):
  Syntax Warning in cmake code at

    /Users/YujieTian/Downloads/openbabel-2.3.1/cmake/modules/UsePythonTest.cmake:54:14

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at test/CMakeLists.txt:174 (include):
  Syntax Warning in cmake code at

    /Users/YujieTian/Downloads/openbabel-2.3.1/cmake/modules/UsePythonTest.cmake:54:31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at test/CMakeLists.txt:174 (include):
  Syntax Warning in cmake code at

    /Users/YujieTian/Downloads/openbabel-2.3.1/cmake/modules/UsePythonTest.cmake:57:25

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at test/CMakeLists.txt:174 (include):
  Syntax Warning in cmake code at

    /Users/YujieTian/Downloads/openbabel-2.3.1/cmake/modules/UsePythonTest.cmake:57:39

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testbabel.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testbabel.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:183 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testsym.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testsym.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:183 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testfastsearch.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testfastsearch.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:183 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testunique.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testunique.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:183 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testkekule.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} NOTFOUND)
      SET(ENV{LD_LIBRARY_PATH} NOTFOUND:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("NOTFOUND")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testkekule.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:183 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testbindings.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testbindings.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:209 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/test_pybel.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/test_pybel.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:209 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/modules/UsePythonTest.cmake:37 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
      SET(ENV{PYTHONPATH} ${pyenv})
      SET(ENV{LD_LIBRARY_PATH} ${pyenv}:\$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} ${ob_libdir})
      SET(ENV{BABEL_DATADIR} ${ob_datadir})
      MESSAGE(\"${pyenv}\")
      EXECUTE_PROCESS(
      	COMMAND ${PYTHON_EXECUTABLE} ${loc} ${wo_semicolumn}
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  the old evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testexample.py 
      	#WORKING_DIRECTORY 
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  but the new evaluation rules produce:

    '
      SET(ENV{PYTHONPATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib)
      SET(ENV{LD_LIBRARY_PATH} /Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib:$ENV{LD_LIBRARY_PATH})
      SET(ENV{BABEL_LIBDIR} /Users/YujieTian/Downloads/build/lib)
      SET(ENV{BABEL_DATADIR} /Users/YujieTian/Downloads/openbabel-2.3.1/data)
      MESSAGE("/Users/YujieTian/Downloads/build/scripts/pybuild:/Users/YujieTian/Downloads/build/lib")
      EXECUTE_PROCESS(
      	COMMAND /usr/bin/python /Users/YujieTian/Downloads/openbabel-2.3.1/test/testexample.py 
      	#WORKING_DIRECTORY @LIBRARY_OUTPUT_PATH@
      	RESULT_VARIABLE import_res
      	OUTPUT_VARIABLE import_output
      	ERROR_VARIABLE  import_output
      )
      
      # Pass the output back to ctest
      IF(import_output)
        MESSAGE('

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  test/CMakeLists.txt:209 (ADD_PYTHON_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

Python bindings will be compiled
Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   inchi
   openbabel

This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done

Need help! Thank you~

**Comment by baoilleach** [comment]
Try a more recent version of Open Babel.

- Noel

**Comment by yujietia** [comment]
The latest version is 2.3.1? I installed 2.3.1. 
Could you send me a link?

Yujie Tian

**Comment by yujietia** [comment]
I am using Mac osx 10.9.5. Do you offer a 2.3.2 open babel for mac?
Thanks a lot!

**Comment by ghutchis** [comment]
Sure, but you seem happy enough to compile from source and use GitHub. Why don't you use:
git clone https://github.com/openbabel/openbabel.git

**Comment by yujietia** [comment]
This git is of 2.3.0. Can it work?

**Comment by ghutchis** [comment]
Git is the most recent development code. You'll see that it calls itself 2.3.90 (i.e., pre-2.4.0)

You can see on GitHub (where you're posting) that the code is updated regularly.

**Comment by yujietia** [comment]
Ok, I will try. 
Thanks!

**Comment by yujietia** [comment]
Hi, thank you I have succeed installed the 2.3.9, but there is another problem that I can not use pybel in python after install that. Maybe cause the wrong cmake arrgs I made, or others. Any suggestion and guide for installing pybel?
Thanks~

**Comment by ghutchis** [comment]
I'm closing this. Please post to the mailing list and I'm sure we can help you.

**Comment by ghutchis** [comment]
I'm closing this. Please post to the mailing list and I'm sure we can help you.
