### ISSUE TITLE
Explicit hydrogen matching problem

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1315]
I have a structure like this O=c1cc[nH]c(=O)n1O in the database.
When I`m searching for O=c1ccnc(=O)n1O it fails to find it.

This problem doesn`t occur for Nc1nnc([nH]1)N or Nc1[nH]nc(n1)N.
When I`m searching for Nc1nnc(n1)N both can be found.

Also when generating SVG image O=c1cc[nH]c(=O)n1O gives right structure but O=c1ccnc(=O)n1O gives the saturated one (picture) 

Is this a bug or my misinterpretation?
 

Reported by: witekmo

Original Ticket: [openbabel/bugs/935](https://sourceforge.net/p/openbabel/bugs/935)

**Comment by baoilleach** [comment]
I think the comment by @chrismorl indicates this is a "won't fix".
