### ISSUE TITLE
Substructure matching problem

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1318]
I have a structure in the database: Cn1ccc(=O)n(c1=O)O
When I`m searching via fastsearch index for this smiles: O=c1cc[nH]c(=O)n1O which is apparent substructure, there are no results (structures attached)

Reported by: witekmo

Original Ticket: [openbabel/bugs/938](https://sourceforge.net/p/openbabel/bugs/938)

**Comment by baoilleach** [comment]
Might be fixed by #1576.

**Comment by baoilleach** [comment]
This isn't a bug, but the behaviour is not very clear from the docs. If specified as -s  "O=c1cc[nH]c(=O)n1O", then the [nH] is interpreted with the SMARTS meaning, i.e. must have exactly one hydrogen attached. If you drop the H, then you hit both.

On the other hand, if the molecule is stored in a file query.smi, and you use -s query.smi, then it behaves in the first place as intended.
