### ISSUE TITLE
SMILES perceptions of aromatic heterocycle converts to saturated

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1323]
Open babel correctly reads the sdf containing the kekule-drawing of attached molecule, and produces the aromatic SMILES.  But when fed that SMILES, it converts it to a saturated form.

obabel -isdf sulfurish.sdf -ocan
CCn1c(=S)sc2c1nc1c3ccccc3c(=O)[nH]n1c2=O

obabel -isdf sulfurish.sdf -ocan|obabel -ican - -ocan
CCN1C(=S)SC2C1NC1N(C2=O)NC(=O)C2C1CCCC2

This is both 2.3.2 and current git master.

Reported by: jeff-janes

Original Ticket: [openbabel/bugs/943](https://sourceforge.net/p/openbabel/bugs/943)

**Comment by baoilleach** [comment]
Fixed by #1576. (FYI @jeffjanes and @JamesJeffryes)

The first doesn't lose aromaticity.
``` 
>obabel -:"CCn1c(=S)sc2c1nc1c3ccccc3c(=O)[nH]n1c2=O" -ocan
CCn1c(=S)sc2c1nc1c3ccccc3c(=O)[nH]n1c2=O
```

The second cannot be kekulized (and that's what the error message says):
```` 
> obabel -:"n1c(c(cnc1C)Cn2c(c(sc2)CCO)C)N" -ocan
==============================
*** Open Babel Warning  in OpenBabel::OBSmilesParser::ParseSmiles
  Failed to kekulize aromatic SMILES

OCCC1=C(C)N([CH]S1)Cc1cnc(nc1N)C
````
