### ISSUE TITLE
Combined obMol objects causes segmentation fault

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1324]
Given two OBMol objects, we combine them together into a new molecule using the overloaded += operator as well as adding an individual bond (with addBond).

Eventually, when attempting to write to a string converting the OBMol object to SMI format with an OBConversion object, we receive the following stack trace due to a segmentation fault. We have verified the contents of the OBMol object prior to converting to SMI as valid, except we know that the coordinates of the new molecule are invalid (hence, we are attempting to scrub the coordinates by writing to a local buffer in SMI and subsequently reading the SMI format into an OBMol object).

Program received signal SIGSEGV, Segmentation fault.
OpenBabel::OBAtom::BeginBond (this=this@entry=0x0, i=...) at /root/openbabel-2.3.2/src/atom.cpp:1056
1056    /root/openbabel-2.3.2/src/atom.cpp: No such file or directory.
(gdb) where
0  OpenBabel::OBAtom::BeginBond (this=this@entry=0x0, i=...) at /root/openbabel-2.3.2/src/atom.cpp:1056
1  0x00007ffff7a1753b in OpenBabel::OBAtom::GetHvyValence (this=0x0) at /root/openbabel-2.3.2/src/atom.cpp:535
2  0x00007ffff7b5edec in OpenBabel::TetrahedralFrom3D (mol=mol@entry=0x7106f0, stereoUnits=...,
    addToMol=addToMol@entry=true) at /root/openbabel-2.3.2/src/stereo/perception.cpp:2107
3  0x00007ffff7b66a10 in OpenBabel::StereoFrom3D (mol=0x7106f0, force=<optimized out>)
    at /root/openbabel-2.3.2/src/stereo/perception.cpp:2073
4  0x00007ffff7b66dc9 in OpenBabel::PerceiveStereo (mol=<optimized out>, force=<optimized out>)
    at /root/openbabel-2.3.2/src/stereo/perception.cpp:73
5  0x00007ffff2f0cc4b in OpenBabel::MDLFormat::WriteMolecule (this=0x7ffff3117760, pOb=<optimized out>,
    pConv=0x7fffffffe300) at /root/openbabel-2.3.2/src/formats/mdlformat.cpp:743
6  0x00007ffff7ad6514 in OpenBabel::OBConversion::Write (this=0x7fffffffe300, pOb=0x7106f0, pos=<optimized out>)
    at /root/openbabel-2.3.2/src/obconversion.cpp:889
7  0x000000000041ef79 in OBWriter::ScrubAndExportSMI (this=0x7fffffffe8d0, molecules=...) at OBWriter.cpp:73
8  0x000000000041f33b in OBWriter::write (this=0x7fffffffe8d0, molecules=...) at OBWriter.cpp:121
9  0x00000000004160a2 in main (argc=3, argv=0x7fffffffec38) at Main.cpp:251

Reported by: wlafield

Original Ticket: [openbabel/bugs/944](https://sourceforge.net/p/openbabel/bugs/944)

**Comment by serval2412** [comment]
Steps to reproduce this still missing :-(

**Comment by baoilleach** [comment]
Let's close it. I'm not aware of any bug this might be.
