### ISSUE TITLE
Segfault when opening Q-Chem fragment file

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1331]
`QChemOutputFormat::ReadMolecule` cannot handle Q-Chem output files that contain fragments. I've included a sample output, though I could also create a simpler one.

Reported by: @berquist

Original Ticket: [openbabel/bugs/951](https://sourceforge.net/p/openbabel/bugs/951)

**Comment by serval2412** [comment]
Could someone provide the command line to reproduce this?

**Comment by berquist** [comment]
obabel -iqcout freq_noCT.cation.CO2.out -O freq_noCT.cation.CO2.xyz

**Comment by serval2412** [comment]
Thank you for your feedback, I could reproduce the segfault.
Here's the bt attached.
[bt.txt](https://github.com/openbabel/openbabel/files/1911057/bt.txt)

**Comment by serval2412** [comment]
The pb is in QChemOutputFormat::ReadMolecule from src/formats/qchemformat.cpp
The list of atoms is created from "Standard Nuclear Orientation" part
then used in different parts like "Mulliken Net Atomic Charges" one.
Here are the lines in the input file where these can be found:
Standard Nuclear Orientation (line 121)
nb atoms 19
Mulliken (line 493)
nb atoms 16

Standard Nuclear Orientation (line 320)
nb atoms 16
Mulliken (line 829)
nb atoms 3

Standard Nuclear Orientation (line 685)
nb atoms 3
Mulliken (line 996)
nb atoms 19

In the third case Openbabel crashes because there are more atoms in Mulliken part than the content of the list generated by the previous "Standard Nuclear Orientation" part.

**Comment by serval2412** [comment]
I added some traces to show nb of atoms retrieved in "Standard Nuclear Orientation" and nb of atoms expected when treating "Mulliken" line, here's the result:
[gdb_session.txt](https://github.com/openbabel/openbabel/files/1911988/gdb_session.txt)

First 10 lines of the file show the pb.

**Comment by berquist** [comment]
This example is complicated and frankly I wouldn't expect it to be fixed. It's a finite difference frequency calculation using fragments. In order, it echoes the supersystem geometry, does individual SCF calculations for each of the two fragments, does a supersystem SCF calculation, then does a finite difference calculation.

From what I understand based on your GDB output, the parsing would be fixed if the only the very first Standard Nuclear Orientation was ignored. Or, if the calculation was re-run without printing the individual fragment SCFs. The default setting in Q-Chem is to not print the individual fragment sections. Here is an example output that seems to parse fine.

[freq_noCT.cation.CO2_new.txt](https://github.com/openbabel/openbabel/files/1912974/freq_noCT.cation.CO2_new.txt)

**Comment by serval2412** [comment]
I gave a try with the last provided example, I got:

`*** Open Babel Warning  in PerceiveBondOrders`
`  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders`

`1 molecule converted`
Is it what you get?
For the first file, I think a patch just to prevent from Openbabel to segfault would be sufficient.

**Comment by berquist** [comment]
I didn't. I'm using v2.4.1 and not Git.

**Comment by serval2412** [comment]
About the crash, I submitted a patch to review here:
https://github.com/openbabel/openbabel/pull/1820
This one contains also some checking (see comment of the patch)

**Comment by serval2412** [comment]
Following the merge of #1820, may we close this one?

**Comment by berquist** [comment]
Looks good:
```
[eric@osmium]$ $apps/openbabel/git/bin/obabel -iqcout Desktop/freq_noCT.cation.CO2.out -oxyz
Error: a Standard Nuclear Orientation paragraph contains 3 whereas the following Mulliken paragraph contains 19 atoms
0 molecules converted
```
