### ISSUE TITLE
Openbabel 2.3.2 segfault with MOPAC2012 output files.

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1334]
Problem initially found when attempting to open output in Avogadro. Openbabel 2.3.2 gives a segmentation fault 11 when attempting to open any output file created by MOPAC2012. I had come across some an older [discussion](http://forums.openbabel.org/Open-Babel-version-2-3-2-wrong-format-conversion-td4656780.html) which suggested that changes to the MOPAC2012 output format broke the OB parser, however there was no mention of a segfault.

Simple input/output attached. Was briefly tested with OB GUI on windows, with same results.

OB version:

    Benjamins-MacBook-Pro:MOPAC test ben$ babel -V
    Open Babel 2.3.2 -- Jan 26 2015 -- 08:21:12

OB audit log:

    Benjamins-MacBook-Pro:MOPAC test ben$ babel ---errorlevel 4 -i mopout methane.out -o xyz    methane.xyz
    ==============================
    *** Open Babel Audit Log  in ReadChemObjectImpl
      OpenBabel::Read molecule MOPAC Output format
    ==============================
    *** Open Babel Audit Log  in Clear
      Ran OpenBabel::Clear Molecule
    ==============================
    *** Open Babel Audit Log  in Clear
      Ran OpenBabel::Clear Molecule
    ==============================
    *** Open Babel Audit Log  in Clear
      Ran OpenBabel::Clear Molecule
    ==============================
    *** Open Babel Debugging Message  in GetAtom
      Requested Atom Out of Range
    Segmentation fault: 11

Reported by: stei7766

Original Ticket: [openbabel/bugs/954](https://sourceforge.net/p/openbabel/bugs/954)

**Comment by serval2412** [comment]
with master sources updated today, no segfault here:
julien@debian:~/projects/openbabel/build/bin$ ./babel ---errorlevel 4 -i mopout ~/projects/openbabel/bugs/methane.out -o xyz    ~/projects/openbabel/bugs/methane.xyz
==============================
*** Open Babel Audit Log  in Clear
  Ran OpenBabel::Clear Molecule
==============================
*** Open Babel Audit Log  in Clear
  Ran OpenBabel::Clear Molecule
==============================
*** Open Babel Audit Log  in Clear
  Ran OpenBabel::Clear Molecule
==============================
*** Open Babel Audit Log  in Clear
  Ran OpenBabel::Clear Molecule
==============================
*** Open Babel Audit Log  in Clear
  Ran OpenBabel::Clear Molecule
==============================
*** Open Babel Audit Log  in ConnectTheDots
  Ran OpenBabel::ConnectTheDots
==============================
*** Open Babel Audit Log  in PerceiveBondOrders
  Ran OpenBabel::PerceiveBondOrders
==============================
*** Open Babel Audit Log  in FindSSSR
  Ran OpenBabel::FindSSSR
==============================
*** Open Babel Debugging Message  in EndModify
  _mod is negative - EndModify() called too many times
1 molecule converted
8 audit log messages 1 debugging messages

**Comment by serval2412** [comment]
ok I'll use "preview" next time and attach txt file for my local output
