### ISSUE TITLE
InChI for senkirkine segfaults on Arch

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1337]
Hi, 

OpenBabel seems to have an issue with Senkirkine.
http://www.chemspider.com/Chemical-Structure.10254880.html

The following will segfault, InChI comes from ChemSpider:

echo "InChI=1S/C19H27NO6/c1-5-13-10-12(2)19(3,24)18(23)25-11-14-6-8-20(4)9-7-15(16(14)21)26-17(13)22/h5-6,12,15,24H,7-11H2,1-4H3/b13-5-,14-6-/t12-,15-,19-/m1/s1" | obabel -i inchi - -xK -o inchi

The corresponding does not SEGV, but does not result in any conversion:

echo "C/C=C\1/C[C@H]([C@@](C(=O)OC/C/2=C/CN(CC[C@H](C2=O)OC1=O)C)(C)O)C" | obabel -i inchi - -xK -o inchi

Only the SDF/MOL get me an inchikey:

https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/6433332/record/SDF/?response_type=save&record_type=2d

and also 

http://www.chemspider.com/FilesHandler.ashx?type=str&striph=yes&id=10254880

obabel -i sdf data.sdf -xK -o inchi HPDHKHMHQGCNPE-PYWIAZMFSA-N

It seems that also most depiction services choke on the InChI:

https://apps.ideaconsult.net/ambit2/depict?search=InChI%3D1S%2FC19H27NO6%2Fc1-5-13-10-12%282%2919%283%2C24%2918%2823%2925-11-14-6-8-20%284%299-7-15%2816%2814%2921%2926-17%2813%2922%2Fh5-6%2C12%2C15%2C24H%2C7-11H2%2C1-4H3%2Fb13-5%2B%2C14-6-%2Ft12-%2C15%3F%2C19-%2Fm1%2Fs1&smarts=

While the corresponding SMILES from ChemSpider seems to work in 
several toolkits, including OpenBabel:

https://apps.ideaconsult.net/ambit2/depict?search=C%2FC%3DC\1%2FC[C%40H]%28[C%40%40]%28C%28%3DO%29OC%2FC%2F2%3DC%2FCN%28CC[C%40H]%28C2%3DO%29OC1%3DO%29C%29%28C%29O%29C&smarts=

I tried Open Babel 2.3.2 and today's Open Babel 2.3.90 -- Mar  4 2015 (a65a93bed157d66f8fd6b68e1d5e96ba77ffa744)

Anything else where I can help debug this ?

Yours,
Steffen

Reported by: sneumann

Original Ticket: [openbabel/bugs/957](https://sourceforge.net/p/openbabel/bugs/957)

**Comment by ghutchis** [comment]
I've closed this because as far as I can tell, this works on all platforms - Mac, Windows, Debian/Ubuntu, RedHat. 

I can't vouch for Arch, but IMHO that would be an Arch bug, not an Open Babel one.
