### ISSUE TITLE
Problems with gen3d and InChI

### ISSUE THREAD

**Issue by fredrikw** [openbabel/openbabel#134]
Following a thread from the mailing list (http://sourceforge.net/p/openbabel/mailman/message/33638880/) there seems to be a problem with gen3d for some InChI strings.
In short, using the InChI from https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1096885 with gen3d will produce a very strange structure where the sugar moiety has been completely mangled with e.g. hydrogens with multiple bonds (see attached image)
![untitled_document-1](https://cloud.githubusercontent.com/assets/86855/6824103/26da3102-d2ef-11e4-99d3-75a88fc82c79.png)

However, when going through canonical smiles, the problem doesn't occur. Compare the results from the following commands and you'll see that the generated structures are different even at connection level. The first is directly InChI -> can with gen3d, for the second command, I first convert InChI -> can and then in a separate call to obabel I generate 3D coordinates.
```shell
> obabel -iinchi -:"InChI=1S/C34H36F3NO13/c1-4-5-9-21(40)49-13-20(39)33(47)11-16-24(19(12-33)51-22-10-17(27(41)14(2)50-22)38-32(46)34(35,36)37)31(45)26-25(29(16)43)28(42)15-7-6-8-18(48-3)23(15)30(26)44/h6-8,14,17,19,22,27,41,43,45,47H,4-5,9-13H2,1-3H3,(H,38,46)/t14-,17-,19-,22-,27+,33-/m0/s1" -ocan --gen3d
COc1cccc2c1C(=O)c1c(C2=O)c(O)c2c(c1O)[C@H]13[H]C4([H][C@H]56O[C@H]7(O1)[H]C5[H][C@H]6([C@H]([H]4)(C7)N=C(C(F)(F)F)O)O)CCCC(=O)OCC(=O)[C@](C2)(C3)O	
1 molecule converted

> obabel -iinchi -:"InChI=1S/C34H36F3NO13/c1-4-5-9-21(40)49-13-20(39)33(47)11-16-24(19(12-33)51-22-10-17(27(41)14(2)50-22)38-32(46)34(35,36)37)31(45)26-25(29(16)43)28(42)15-7-6-8-18(48-3)23(15)30(26)44/h6-8,14,17,19,22,27,41,43,45,47H,4-5,9-13H2,1-3H3,(H,38,46)/t14-,17-,19-,22-,27+,33-/m0/s1" -ocan | obabel -ismi -ocan --gen3d
1 molecule converted
CCCCC(=O)OCC(=O)[C@@]1(O)C[C@H](O[C@@H]2O[C@@H](C)[C@H]([C@H](C2)N=C(C(F)(F)F)O)O)c2c(C1)c(O)c1c(c2O)C(=O)c2c(C1=O)cccc2OC	
1 molecule converted
```

**Comment by baoilleach** [comment]
Here's a simpler test case presumably stemming from the same problem:
>obabel -:O[C@@H](C)N -oinchi | obabel -iinchi -osmi -h
C1[C@H](N)(O)[H]1

**Comment by baoilleach** [comment]
It's an interaction with OBVirtualBond somehow. I'm not yet quite on top of how this works, but reading the InChI leaves some OBVirtualBond data attached to the molecule, which I'm guessing either should not have been there in the first place, or should have been removed. Anyway, this data is 'triggered' when NewAtom is called later with the reported 'surprising' results.

**Comment by baoilleach** [comment]
Aha! 
1. The InChI format Is adding each bond twice, once from A->B and once from B->A.
2. This wouldn't have been a particular problem except that the logic in AddBond was not adding up. It was adding virtual bonds in this case instead of just returning false immediately.

I've left point 1 alone as it's not a particular problem, and solved the logic in 2.
