### ISSUE TITLE
Memory Leak in Python Swig inteface (OBRotor object)

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1340]
Hi,

I found a bug when trying to use OBRotor objects in Python openbabel library.
Everytime I call a method of this objects I get a warning

swig/python detected a memory leak of type 'std::vector< OpenBabel::OBRotor *,std::allocator< OpenBabel::OBRotor * > >::iterator *', no destructor found.

My code is something like this:
	rbonds = openbabel.OBRotorList()
	rbonds.Setup(mol)

	rotor = rbonds.BeginRotor(rbonds.BeginRotors())
	for i in range(rbonds.Size()):
		print rotor.Size()
		rotor = rbonds.NextRotor(rbonds.BeginRotors())

[]'s

Reported by: hmcezar

Original Ticket: [openbabel/bugs/961](https://sourceforge.net/p/openbabel/bugs/961)

**Comment by serval2412** [comment]
On pc Debian x86-64 with master sources updated some days ago , I could reproduce this.
I just had to remove Setup line since "mol" is undeclared.

**Comment by serval2412** [comment]
dup of #190

**Comment by baoilleach** [comment]
The iterators need special handling in the swig interface. The C++ methods cannot be used directly.

**Comment by tverho** [comment]
I can reproduce the bug and I can't see a workaround. I wonder why this bug was closed?

**Comment by baoilleach** [comment]
The C++ methods cannot be used directly. OBMolTorsionIter and the other iterators are provided for Python users.

**Comment by tverho** [comment]
But don't you need OBRotorIterator to create rotamers with OBRotorList and OBRotamerList? I don't see how you could use the python iterators there.
