### ISSUE TITLE
Opem Babel misses hydrogen from InChI or from MDL MOL file

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1343]
Hi,
I have a MDL MOL file of "sodium cyanoborohydride", and want its molecular mass. So, I try _Open Babel 2.3.2_ on _Windows_. Yet, the formula in molreport's output is missing one hydrogen, and the molecular weight is missing one Dalton.

If I replace the MDL MOL input file by the InChI string I get the same problem.
If I replace the molreport out by any SMILES output, I get the same problem.
If I use _Open Babel 2.3.1_ on _Linux_, I get the same problem.

Example:
    `Echo "InChI=1S/CH3BN.Na/c2-1-3;/h2H3;/q-1;+1" | obabel -i inchi -o can`
should output
    `[BH3-]C#N.[Na+]`
but outputs
    `[BH2-]C#N.[Na+]`

Thanks

Reported by: luismsanchez

Original Ticket: [openbabel/bugs/964](https://sourceforge.net/p/openbabel/bugs/964)

**Comment by baoilleach** [comment]
Fixed by #1576.
```
>obabel -:"InChI=1S/CH3BN.Na/c2-1-3;/h2H3;/q-1;+1" -iinchi -ocan
[BH3-]C#N.[Na+]
```
