### ISSUE TITLE
Bad symbols in elements database! 

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1345]
There are errors in the elements Symbols of the last two lines of the file `/usr/share/openbabel/2.3.2/element.txt` is says `Uuh` and `Uuh` whereas it should be `Uus` and `Uuo`.

Reported by: correaa

Original Ticket: [openbabel/bugs/966](https://sourceforge.net/p/openbabel/bugs/966)

**Comment by serval2412** [comment]
It should be closed since src/elementtable.h shows:
`ELEMTABLE(117, Ts, 0.00, 1.60, 1.60, 2.00,  6,        294, 0.00,       0,          0, 0.99, 0.00, 0.07, Tennessine),
ELEMTABLE(118, Og, 0.00, 1.60, 1.60, 2.00,  6,        294, 0.00,       0,          0, 0.99, 0.00, 0.06, Oganesson)`
