### ISSUE TITLE
pybel 2.3.2 crash when universal SMILES write follows inchified SMILES write

### ISSUE THREAD

**Issue by mattbernst** [openbabel/openbabel#135]
```
import pybel

mA = pybel.readstring("smi", "C(=O)([O-])C(=O)O")

print (mA.write("smi", opt={"I" : True}))
print (mA.write("smi", opt={"U" : True}))
```

I expected this code to print the inchified SMILES form of the molecule followed by the universal SMILES form. In fact it works when the order of the write operations is reversed. But this ordering leads to abnormal program termination:

matt@mbe-laptop:~$ python pybel-bug.py 
C(=O)(C(=O)O)[O-]	

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted

**Comment by ghutchis** [comment]
That's certainly weird. If you use the latest Git master, does the bug also occur? Thanks.

**Comment by mattbernst** [comment]
Yes, as of commit a345105b28173eb7da14ecd1e5beebe94140c6d7 this bug also occurs with the git master. I confirmed the crash under strace to make sure it was loading the latest built-from-source shared libraries rather than the version packaged by Ubuntu.

I built this software under Ubuntu 14.04 64 bit. I will also note my build procedure here since the INSTALL instructions are a bit out of date:

```
sudo apt-get install swig

mkdir -p /opt/science/openbabel/src
cd /opt/science/openbabel/src
wget http://bitbucket.org/eigen/eigen/get/3.2.4.tar.bz2
tar xjvf 3.2.4.tar.bz2
git clone https://github.com/openbabel/openbabel.git
cd openbabel
mkdir build
cd build

cmake .. -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DCMAKE_INSTALL_PREFIX=/opt/science/openbabel -DEIGEN3_INCLUDE_DIR=/opt/science/openbabel/src/eigen-eigen-10219c95fe65
make -j 4
make test
make install
```

**Comment by baoilleach** [comment]
Got it. It's the short-circuiting of the InChI generation that's causing the problem. Looks like the solution is to avoid this short-circuit if any options are specified to the writer. Will check in some code as soon as possible.
