### ISSUE TITLE
Mac binary installs for scripting binding

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1503]
As the title indicates, the Mac install should include optional packages for installing the scripting bindings.

Reported by: @ghutchis

Original Ticket: "openbabel/feature-requests/134":https://sourceforge.net/p/openbabel/feature-requests/134

**Comment by ghutchis** [comment]
I'm closing this. The best (simple) option on Mac is to install Anaconda, then `conda install -c conda-forge openbabel`
