### ISSUE TITLE
Turbomole IR spectra

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1515]
Attached are two files that contain vibrational data from turbomole. AFAIK:
* Both are generated during the analysis
* Either can be used to get the information
* The files are both separate from the "main" output tmol file (I'm assuming this, because reading fails when changing the extension to tmol)

Files can be found here:
http://drunks.servebeer.com/david/misc/control
http://drunks.servebeer.com/david/misc/aoforce.out

Reported by: @dlonie

Original Ticket: [openbabel/feature-requests/146](https://sourceforge.net/p/openbabel/feature-requests/146)

**Comment by allisonvacanti** [comment]
Those example files are looooong gone. @ghutchis Feel free to close this.

**Comment by ghutchis** [comment]
No worries - hope you're doing well!
