### ISSUE TITLE
need for ring connections with more than 2 digits

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1529]
Good day.  I noticed that one cannot make ring connections with numbers of more than 2 digits in a SMILES string.

i.e. valid structures for diphenylmethane are c1ccccc1Cc2ccccc2 and c%84ccccc%84Cc%85ccccc%85 but c%1000ccccc%1000Cc%1001ccccc%1001 is not.  The connections just do not happen as intended.

Is there a reason why we are limited to 2 digit ring connections?  Is there a way to have this changed?  Is there a way to do something like this within the existing framework in a clever manner?

Thanks. 

Steve

Reported by: sgarturo

Original Ticket: [openbabel/feature-requests/160](https://sourceforge.net/p/openbabel/feature-requests/160)

**Comment by baoilleach** [comment]
Pinging @sgarturo. See #1677 discussion.

**Comment by ghutchis** [comment]
This has been merged, so I'm closing the issue.
