### ISSUE TITLE
Periodic boundary conditions

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1536]
It would be great if OB could deal with structures and bond perception over periodic boundaries. This has already been implemented by G. Garberoglio in http://software-lisc.fbk.eu/obgmx/ but it would be great to get his patches merged into the standard version.

Reported by: tdaff

Original Ticket: [openbabel/feature-requests/168](https://sourceforge.net/p/openbabel/feature-requests/168)

**Comment by bbucior** [comment]
Are there any updates on this topic, other than the occasional feature request on the mailing list?  I am in the process of implementing PBC (work-in-progress) but could also try to get in contact with the obgmx author to compare our work.
