### ISSUE TITLE
Notice: I've started to remove legacy codes to make libopenbabel C++14 compatible

### ISSUE THREAD

**Issue by saki7** [openbabel/openbabel#154]
I'd like to announce openbabel committers that i've started a fork project which aims to make openbabel C++14 friendly.

Here's my fork: https://github.com/chlorix/skyscraper

Here's the initial diff:
https://github.com/chlorix/skyscraper/commit/442a761d1aa580c33f2918e208c9ad59dc22febf?w=0
(Do not click the direct commit URL since it's too large. This link excludes whitespace related diffs. )

Until now, I have:
- Killed evil `using namespace std` in `*.cpp` files.
  - Luckily, there was none of them in header files, but......
  - This was causing some cpp files to reference C library functions instead of C++ `std::*` functions.
- Added much much more `const`ness to the codebase. :tada:
- Replaced `NULL` with `nullptr`.

Some of my next goals are:
- Complete `-Wall` support.
- Replace all iterator related stuff with Range.
- Replace obsolete string manipulations with Boost stuff.

---

### So what am I thinking?

- I am certainly going to break backward compatibilities.
- I'd like to hear some opinions from the current openbabel maintainers.
- I'd be happy to receive any kind of advices to keep openbabel fresh and updated.

**Comment by baoilleach** [comment]
Why don't you email the mailing list before you do too much on this....

**Comment by saki7** [comment]
The only reason I forked it before discussing is becase I thought it would be easier to understand by looking into the diffs than reading tons of sentences in email :)

If you wish to have more conversation with me on the mailing list, that's fine, too. Please CC me on the mailing list.

**Comment by saki7** [comment]
Let's see... I'm gonna post this issue to the mailing list and see how other contributors think.

**Comment by dkoes** [comment]
Eh.  Most changes seem to be syntactic sugar (e.g., NULL->nullptr).  What are the changes that bring actual value to the users/developers and can they be implemented without breaking compatibility?

Personally, I'm in favor of bringing in boost as a dependency, although I understand the arguments against it (perhaps just the header-only libraries?).

Dropping language bindings is a horrible idea.

**Comment by baoilleach** [comment]
Let's have this discussion on the dev list rather than in two places...
