### ISSUE TITLE
Attribute error: readstring in the module pybel.py 

### ISSUE THREAD

**Issue by pearlphilip** [openbabel/openbabel#1543]
I believe this to be a bug with openbabel/openbabel/scripts/python/pybel.py in line 172 for function readstring 

## Expected Behavior
Example:
```
input = "C1=CC=CS1"
mymol = readstring("smi", input)
len(mymol.atoms)

5

```
## Actual Behavior
I get this error 
  ```
pip install pybel
...
import pybel

mol = pybel.readstring("smi", smiles)
AttributeError: 'module' object has no attribute 'readstring'
```

**Comment by baoilleach** [comment]
What operating system and version is this? Can you search your computer for other files with the name pybel.py?

**Comment by mcs07** [comment]
`pip install pybel` is not correct. That's an [unrelated package](https://pypi.python.org/pypi/PyBEL). Instead, do `pip install openbabel`

**Comment by baoilleach** [comment]
Ah - of course - the penny drops. Thanks Matt.
