### ISSUE TITLE
how to add a new format type

### ISSUE THREAD

**Issue by mj-harvey** [openbabel/openbabel#155]
Hi,

I'd like to add a new format type - could anyone give me - or point me to - instructions for doing this please? I'm at sea with Cmake.

MJH

**Comment by Reinis** [comment]
On Mon, Apr 27, 2015 at 10:20:36AM -0700, M J Harvey wrote:
> Hi,
> 
> I'd like to add a new format type - could anyone give me - or
> point me to - instructions for doing this please? I'm at sea
> with Cmake.
> 

You can look in Git history for previous examples, e.g. [1]. From
that you could see that you need to add the name of your plugin
to src/formats/CMakeLists.txt and src/formats/formats.cmake, but
all other changes are in C++ files.

There is an old wiki article on the general topic [2].


Reinis

[1] https://github.com/openbabel/openbabel/pull/113/files
[2] http://openbabel.org/wiki/HowTo:Add_A_New_File_Format

**Comment by mj-harvey** [comment]
Perfect, thank you!

**Comment by baoilleach** [comment]
It's in the docs :
http://open-babel.readthedocs.org/en/latest/WritePlugins/AddFileFormat.html
