### ISSUE TITLE
No python SWIG binding for std::vector of OBAtom *

### ISSUE THREAD

**Issue by djh901** [openbabel/openbabel#1551]
Would it be as easy as adding a line to this part of openbabel-python.i?

```
VECTORTEMPLATE_WRAP(Int, int)
VECTORTEMPLATE_WRAP(UnsignedInt, unsigned int)
VVTEMPLATE_WRAP(Int, int)
VECTORTEMPLATE_WRAP(Double, double)
VECTORTEMPLATE_WRAP(ULong, unsigned long)
VECTORTEMPLATE_WRAP(String, std::string)
VECTORTEMPLATE_WRAP(Vector3, OpenBabel::vector3)
VVTEMPLATE_WRAP(Vector3, OpenBabel::vector3)
VECTORTEMPLATE_WRAP(OBMol, OpenBabel::OBMol)
VECTORTEMPLATE_WRAP(OBBond, OpenBabel::OBBond)
VECTORTEMPLATE_WRAP(OBResidue, OpenBabel::OBResidue)
VECTORTEMPLATE_WRAP(OBRing, OpenBabel::OBRing)
VECTORTEMPLATE_WRAP(pOBRing, OpenBabel::OBRing*)
VECTORTEMPLATE_WRAP(pOBGenericData, OpenBabel::OBGenericData*)
VECTORTEMPLATE_WRAP(pOBInternalCoord, OpenBabel::OBInternalCoord*)
```

**Comment by ghutchis** [comment]
Yes, that's right.

**Comment by baoilleach** [comment]
What function are you calling?

**Comment by djh901** [comment]
FindChildren. It seems to be overloaded with one version supporting an integer vector and the other supporting a vector of atom pointers. I wanted to use the latter version, but found there was no way to create a vector of Atoms. I did some digging to figure out why and found the above code that curiously omits OBAtom and OBAtom * from std::vector template bindings.

**Comment by baoilleach** [comment]
Every addition to std::vector in the bindings creates a lot of boilerplate
code and so I've avoided needlessly adding methods where a duplicate
exists. From what you say, this is also the case here. From a user
perspective, the other method should be excluded from the bindings
explicitly to avoid confusion.

**Comment by djh901** [comment]
Should I add an %ignore line to the interface files, then?

**Comment by baoilleach** [comment]
That'd be great. Is it okay to close this bug report so...?
