### ISSUE TITLE
SMILES parsing failure for a simple case

### ISSUE THREAD

**Issue by nkstnkst** [openbabel/openbabel#1570]
I'm using openbabel 2.4.1. For the SMILES "O[BrH+].C=C.[Br-]", obabel doesn't seem to be able to convert it to the right molecule. It misses all implicit hydrogens. Here are two examples where obabel fails. 

% obabel mymol.smi -oxyz
6

O          0.00000        0.00000        0.00000
Br         0.00000        0.00000        0.00000
H          0.00000        0.00000        0.00000
C          0.00000        0.00000        0.00000
C          0.00000        0.00000        0.00000
Br         0.00000        0.00000        0.00000

% obabel mymol.smi -osdf
 OpenBabel05171709412D

  6  3  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 Br  0  3  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 Br  0  5  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  4  5  2  0  0  0  0
M  CHG  2   2   1   6  -1
M  END
$$$$

-Xianghai Sheng

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by baoilleach** [comment]
This is not a bug. This is working as intended. Only explicit hydrogens are written in XYZ and SDF formats. The -h option converts all implicit hydrogens to explicit hydrogens.
