### ISSUE TITLE
Does the lastest version of openbabel remove MACCS fingerprint?

### ISSUE THREAD

**Issue by zealseeker** [openbabel/openbabel#1573]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: win10
conda list:
openbabel                 2.4.1                    py27_2    openbabel
## Expected Behavior

calculate the maccs fingerprint via compounds.calcfp('maccs')

## Actual Behavior

Install openbabel via 
`conda install -c openbabel openbabel`
Then
```python
import pybel
pybel.fps
# ['ecfp0', 'ecfp10', 'ecfp2', 'ecfp4', 'ecfp6', 'ecfp8', 'fp2', 'fp3', 'fp4']
```

**Comment by mwojcikowski** [comment]
Can you check if it's also absent in obabel binary: `obabel -L fingerprints`

**Comment by zealseeker** [comment]
C:\Users\yanya>obabel
No input file or format spec or possibly a misplaced option.
Most options must come after the input files. (-i -o -O -m can be anywhwere.)

Open Babel 2.4.1 -- Mar 29 2017 -- 10:52:57
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.

C:\Users\yanya>obabel -L fingerprints
ECFP0    Extended-Connectivity Fingerprints (ECFPs)
ECFP10    Extended-Connectivity Fingerprints (ECFPs)
ECFP2    Extended-Connectivity Fingerprints (ECFPs)
ECFP4    Extended-Connectivity Fingerprints (ECFPs)
ECFP6    Extended-Connectivity Fingerprints (ECFPs)
ECFP8    Extended-Connectivity Fingerprints (ECFPs)
FP2    Indexes linear fragments up to 7 atoms.
FP3    SMARTS patterns specified in the file patterns.txt
FP4    SMARTS patterns specified in the file SMARTS_InteLigand.txt

**Comment by mwojcikowski** [comment]
I have reproduced the problem on my Winodws machine. Openbabel can not locate the "share" directory. To fix it set `BABEL_DATADIR` in your session:

>  set "BABEL_DATADIR=C:\Users\username\Miniconda3\share\openbabel"

Note, that `Miniconda3` dir may differ on your setup.

**Comment by zealseeker** [comment]
It works!
I think it will be better if the environment vairable can be automatically set when installing by anaconda.
