### ISSUE TITLE
Wedge depiction in cyclopropyl

### ISSUE THREAD

**Issue by fredrikw** [openbabel/openbabel#1581]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Trunk as of 2017-05-31
Operating system and version: Mac OSX 10.12.5 (but also Ubuntu 16.04)

## Expected Behavior
When depicting a molecule with a cyclopropyl with stereochemistry on the cyclic carbons, the wedges are best shown "extracyclicly".

## Actual Behavior
The wedge bonds end up in the cycle, see added image.
![test](https://cloud.githubusercontent.com/assets/86855/26625417/4bd49f68-45f4-11e7-9dbc-4bab996add05.png)

## Steps to Reproduce
obabel -ismi -:"C[C@H]1[C@]([C@]1([H])C(O)=O)([H])CC" -O test.png

**Comment by baoilleach** [comment]
Certainly.

**Comment by fredrikw** [comment]
I just submitted a PR to fix this (https://github.com/openbabel/openbabel/pull/1582)
