### ISSUE TITLE
OBMol has several bad memory leaks

### ISSUE THREAD

**Issue by arkose** [openbabel/openbabel#1583]
- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 2.4.1
Operating system and version: OSX 10.12

## Expected Behavior
Running the following program should not produce memory leaks.

`#ifdef WIN32`
`#define USING_OBDLL`
`#endif`
`#ifndef _MSC_VER`
`#include <unistd.h>`
`#endif`
`#include <openbabel/base.h>`
`#include <openbabel/babelconfig.h>`
`#include <openbabel/obconversion.h>`
`#include <openbabel/mol.h>`
`#include <openbabel/obutil.h>`
`int main(int argc, char **argv)`
`{ `
`    OpenBabel::OBMol mol;`
`    return 0;`
`} `

## Actual Behavior

`==16640== LEAK SUMMARY:`
`==16640==    definitely lost: 85424 bytes in 1998 blocks`

Full information attached here:
[leaks.txt](https://github.com/openbabel/openbabel/files/1042456/leaks.txt)

## Steps to Reproduce

Using valgrind, heapusage or a similar tool, run and analyze the above program.

A fix would be greatly appreciated.

**Comment by baoilleach** [comment]
If you create a second OBMol how much extra memory is leaked?

**Comment by arkose** [comment]
Interesting; if I write

`OBMol molA;`
`OBMol molB;`

no additional memory is leaked:

`==22754==    definitely lost: 85424 bytes in 1998 blocks`

However if I write

`OBMol molA;`
`OBMol molB = molA;`

I get that there is more memory leaked:

`==23673==    definitely lost: 89768 bytes in 2004 blocks`

So there does seem to be a memory leak that can increase when assignment is performed. This seems to occur with each assignment call; if I write

`OBMol molA;`
`OBMol molB = molA;`
`molB = molA;`

I get additional leaked memory:

`==24594==    definitely lost: 90008 bytes in 2008 blocks`

**Comment by davethecipo** [comment]
Just FYI, I can't reproduce this on linux.

**Comment by baoilleach** [comment]
Hmmmm. Was that clang on the Mac?

**Comment by baoilleach** [comment]
@davethecipo if you like a challenge try compiling against libc++ on Linux and checking whether you can find the leaks.

**Comment by arkose** [comment]
@baoilleach Yes, this was using clang on a mac.
