### ISSUE TITLE
segfault when accessing Atom attributes through pybel

### ISSUE THREAD

**Issue by joshkamm** [openbabel/openbabel#1602]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 (installed through anaconda)
Operating system and version: Mac OS 10.12.5 (Sierra)
Python version: 3.6.1

## Expected Behavior

I expect pybel library calls to either return or throw a catchable exception.

## Steps to Reproduce and Actual Behavior

I have a python function that reads in a bunch of xyz files into pybel Molecule objects. Later on I iterate over all of the Molecule objects and read variables from some of the pybel Atom objects within each Molecule (to generate features for machine learning). While trying to access the Atom objects and variables within them a segmentation fault occurs that kills the python interpreter (it terminates with exit code 139). I can also kill the python interpreter with a segfault while my code is paused in the debugger (which I access through Eclipse / PyDev) by navigating into and trying to inspect pybel Atoms' variables. The segfault does not always occur when accessing the first Atom and does not consistently happen on the same Atom when running the exact same code multiple times in succession but it does usually happen within the first 5-10 Atoms.

## Notes

Sorry I understand this is probably difficult to debug because of its inconsistency and lack of a small reproducible example but I've already spent a lot of time trying to understand what was going on so hopefully I can give enough information to still be helpful.

My current workaround which appears to be working is to have a wrapper python atom class around the pybel atom class with variables to keep a copy of all the data that I use from the pybel atom. I initialize those variables in my wrapper's constructor right after the pybel Atom and OBAtom are constructed before their data becomes corrupted.

My speculation would be that somewhere in the (pybel Atom -> swig OBAtom wrapper -> C++ OBAtom -> variable) chain memory is being deallocated even though I still have a reference to the pybel Atom.

This is because using the debugger I was able to determine that I can access an Atom's variable (e.g. "valence") right after I initialize it without a failure and then receive a segmentation fault when trying to access the same variable at the same memory location later in the program.

P.S. I'm new so I didn't want to change the wiki without communicating with anyone else but maybe the instructions on bug reporting at http://openbabel.org/wiki/Help should point directly to GitHub instead of pointing to SourceForge which then points to here

**Comment by ghutchis** [comment]
You absolutely, positively need to give us some example code. Even if the segfault isn't a consistent problem, what you write does not tell me anything about what you're trying to do in the code.

**Comment by joshkamm** [comment]
Alright well I can provide the code I'm hoping to actually use if that would be helpful but there are multiple files containing the hundreds of lines of code involved in reproducing the original bug. After some messing around I figured out how to get incorrect and what I think is related behavior by doing the same thing over and over again instead of a bunch of different things. Here's the example code:

**Code**
```python
import pybel as pb
sampleXyzString = '2\n\nH 0 0 0\nH 1 0 0\n'
print('Correct: ', pb.readstring('xyz', sampleXyzString).atoms[0].valence)
atoms = [pb.readstring('xyz', sampleXyzString).atoms[0] for i in range(50)]
for atom in atoms:
    print(atom.valence, end=' ')
```
**Sample output (differs each time run):**
Correct:  1
0 452 4294967084 4294967203 0 0 3826109482 3826109482 3826109482 0 0 0 0 0 0 0 0 0 0 0 4294967203 0 4294967203 0 0 68013098 68013098 1 172 172 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5299 1 1 1 1 1

**Comment by ghutchis** [comment]
Seriously, I'm not sure why anyone would want to do that. Why would you want to re-parse the same string repeatedly?

But what you're doing later is just bad code. You're parsing a molecule that Python probably treats as a temporary. Then you grab an atom reference. That's still probably a temporary. Then you put that into a list.

Then *after* putting all those atom references in a list, you interrogate them? I'm not surprised it leads to weird behavior. Python (and the SWIG interface) can't determine whether the temporary can be free, so it probably frees some of them. Now you're asking for valence on some undefined C++ pointer.

What exactly are you trying to do? Then we can probably come up with a safe way to do that.

**Comment by baoilleach** [comment]
You need to keep a reference to the molecule if you are accessing its
atoms. Otherwise the atom is destroyed when the molecule goes out of scope.

**Comment by joshkamm** [comment]
What I'm trying to do is read in an arbitrary number of xyz files (thousands) each representing the reactants of a reaction. Then I have atom indices of the atoms that are involved in each reaction and I'm trying to generate a vector representation of each of those atoms using things like atomic #, # of connections, hybridization, and similar information of atoms it's bonded to. Then I aggregate the vector representations of the atoms involved in each reaction into a vector representation of each reaction as a whole. Then I use those reaction vector representations as data in a machine learning pipeline.

Thanks @baoilleach, I tried keeping a reference to each reactants Molecule in my Reaction class (which I had been planning on doing anyway but hadn't remembered and hadn't needed to use yet) and that seems to keep all of the Atom instances valid at least in my initial tests involving what hadn't worked previously.

Destroying all atoms owned by a Molecule in the Molecule's destructor seems like reasonable design but is that documented anywhere? If not should it be added somewhere (by me or someone else)?

**Comment by baoilleach** [comment]
I've been thinkking about your last comment for a while. This a difference between Python and C++. In Python, nothing is destroyed so long as you kept a reference. In C++, everything is typically destroyed once the container is destroyed (this is the typical design decision or else memory leaks will be common). So I think this behaviour is not unexpected once you accept that the Python bindings are simply wrappers around a C++ library.
