### ISSUE TITLE
Benzyne read incorrectly

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1605]
As reported by @TermeHansen...

I have just compiled latest from master, and I still see the bug with Benzyne:

```
opt/openbabel/bin/obabel -ismi -:'c1ccccc#1' -oreport -h
FILENAME: 
FORMULA: C6H6
```
should be C6H4

Open Babel 2.4.1 -- Jul 26 2017

I will fill in some more information I have found from the python interface, again with latest master from git.
using inchi ('InChI=1S/C6H4/c1-2-4-6-5-3-1/h1-4H'):
```
mol.GetFormula()
'C6H4'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-2-2',
 '1-1-3',
 '2-1-4',
 '3-2-5',
 '4-2-6',
 '5-2-6',
 '1-1-7',
 '2-1-8',
 '3-1-9',
 '4-1-10']
```
correct formula, benzene with 4 double bonds?!?

using smile ('C1=CC#CC=C1'):
```
mol.GetFormula()
'C6H4'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-2-2',
 '2-1-3',
 '3-3-4',
 '4-1-5',
 '5-2-6',
 '1-1-6',
 '1-1-7',
 '2-1-8',
 '5-1-9',
 '6-1-10']
```
correct formula, and correct structure

using smile ('c1ccccc#1'):
```
mol.GetFormula()
'C6H6'

['{}-{}-{}'.format(b.GetBeginAtomIdx(),b.GetBondOrder(),b.GetEndAtomIdx()) for b in ob.OBMolBondIter(mol)]
['1-1-2',
 '2-2-3',
 '3-1-4',
 '4-2-5',
 '5-1-6',
 '1-3-6',
 '1-1-7',
 '2-1-8',
 '3-1-9',
 '4-1-10',
 '5-1-11',
 '6-1-12']
```
wrong formula, and correct aromatic structure, but Hydrogens on all carbons (brake of valence rule).
I hope this points in some direction.

**Comment by baoilleach** [comment]
Fixed by #1606. Thanks for reporting. It's a one-line change (see commit above) so you can easily apply it at your end while you wait for this to be merged.

**Comment by baoilleach** [comment]
FYI, the InChI normalises different resonance forms. See https://en.wikipedia.org/wiki/Aryne for a picture of the cumulene resonance form of benzyne.

**Comment by TermeHansen** [comment]
The issue seems to be fixed now, thank you! I have however found another inconsistency between smiles and inchi, where this time I find that smile chooses the wrong resonance form:
[https://en.wikipedia.org/wiki/Benzo(c)cinnoline](Benzo(c)cinnoline)
aromatic smiles
```
getAtomsBonds('c1ccc2c(c1)nnc1ccccc12')
Out[10]: 
[{'C': 12, 'H': 8, 'N': 2},
 defaultdict(int,
             {'C-1-C': 8, 'C-1-H': 8, 'C-2-C': 5, 'C-2-N': 2, 'N-1-N': 1}),
 {'molwt': 180.20531999999986, 'spin': 1},
 'C12H8N2']
```
inchi
```
getAtomsBonds('InChI=1S/C12H8N2/c1-3-7-11-9(5-1)10-6-2-4-8-12(10)14-13-11/h1-8H',term='inchi')
Out[11]: 
[{'C': 12, 'H': 8, 'N': 2},
 defaultdict(int,
             {'C-1-C': 7, 'C-1-H': 8, 'C-1-N': 2, 'C-2-C': 6, 'N-2-N': 1}),
 {'molwt': 180.20531999999992, 'spin': 1},
 'C12H8N2']
```

**Comment by baoilleach** [comment]
It's a nice example, but that's not a bug - it's working as intended. The first resonance form found wins. If you want, you could file a feature request to favour benzene rings on kekulization and provide this example.

Note that if you want to force a particular resonance form, you can include a single or double bond symbol explicitly (-xk for Kekule output), e.g. 
```
>obabel -:"c1ccc-2c(c1)nnc1ccccc-21" -osmi -xk
C1C=CC2=C(C=1)N=NC1C=CC=CC2=1
```
