### ISSUE TITLE
pybel python 3 compatibility

### ISSUE THREAD

**Issue by matk86** [openbabel/openbabel#1615]
* error: `TypeError: a bytes-like object is required, not 'str'`
* in line https://github.com/openbabel/openbabel/blob/master/scripts/python/pybel.py#L528
* solution: before that line set `filename = filename.decode()`

**Comment by cowsandmilk** [comment]
solution is more complex than that, you are describing an error that only occurs if the user passes in a bytes-like object as the filename. If, as I would expect to be typical, the user passes in a str, your solution would result in "AttributeError: 'str' object has no attribute 'decode"

**Comment by matk86** [comment]
well, you could do a hasattr check then...

**Comment by matk86** [comment]
`filename = filename.decode() if hasattr(filename, "decode") else filename`

**Comment by baoilleach** [comment]
Looking at the docs for os.path, it seems that both str and byte filenames should be handled as much as possible. A possible solution is to think about path-like objects (https://docs.python.org/3/glossary.html#term-path-like-object).

**Comment by mwojcikowski** [comment]
I assume that it will also break for Py2 and filename of unicode type. Maybe an input validation `isinstance(filname, str)` is sufficient? If not throw `ValueError` and let the user bother.

The other solution would be more complex and would require casting from bytes to str in Py3 and from unicode to bytes in Py2 with addition of `six` preferably.

**Comment by afonari** [comment]
In what case filename is not a string? Just for my education.

**Comment by baoilleach** [comment]
See top of https://docs.python.org/3/library/os.path.html.

**Comment by afonari** [comment]
Holy sh*t! Thanks, @baoilleach.
