### ISSUE TITLE
cannot pip install openbabel and install by myself

### ISSUE THREAD

**Issue by paulgholin** [openbabel/openbabel#1620]
Hi Dr. Noel,
I use the latest version of Mac (10.12.6) and python 3.6. I tried the following two methods to install openbabel-2.4.1: 
1. pip install openbabel  
2. python setup.py install
Both shows the following errors:
Error: SWIG failed. Is Open Babel installed?
You may need to manually specify the location of Open Babel include and library directories. For example:
      python setup.py build_ext -I/usr/local/include/openbabel-2.0 -L/usr/local/lib
      python setup.py install

I have done: brew install swig, but the errors still exist.
Could you please let me know how to solve this? 

Thank you.
Paul

The detailed errors from pip install openbabel is:
Paulin@Paulins-MBP:~$ pip install openbabel
Collecting openbabel
  Using cached openbabel-2.4.1.tar.gz
Building wheels for collected packages: openbabel
  Running setup.py bdist_wheel for openbabel ... error
  Complete output from command /Users/Paulin/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-build-v0rof5j4/openbabel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/tmpwh85q9mepip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Open Babel location automatically determined by pkg-config:
  - include_dirs: ['/Users/Paulin/miniconda3/include/python3.6m', '/usr/local/include/openbabel-2.0']
  - library_dirs: ['/Users/Paulin/miniconda3/lib', '/usr/local/lib']
  building '_openbabel' extension
  swigging openbabel-python.i to openbabel-python_wrap.cpp
  swig -python -c++ -small -O -templatereduce -naturalvar -I/Users/Paulin/miniconda3/include/python3.6m -I/usr/local/include/openbabel-2.0 -o openbabel-python_wrap.cpp openbabel-python.i
  openbabel-python.i:225: Error: Unable to find 'openbabel/babelconfig.h'
  openbabel-python.i:227: Error: Unable to find 'openbabel/data.h'
  openbabel-python.i:228: Error: Unable to find 'openbabel/rand.h'
  openbabel-python.i:229: Error: Unable to find 'openbabel/obutil.h'
  openbabel-python.i:230: Error: Unable to find 'openbabel/math/vector3.h'
  openbabel-python.i:232: Error: Unable to find 'openbabel/math/matrix3x3.h'
  openbabel-python.i:233: Error: Unable to find 'openbabel/math/transform3d.h'
  openbabel-python.i:234: Error: Unable to find 'openbabel/math/spacegroup.h'
  openbabel-python.i:238: Error: Unable to find 'openbabel/base.h'
  openbabel-python.i:240: Error: Unable to find 'openbabel/generic.h'
  openbabel-python.i:241: Error: Unable to find 'openbabel/griddata.h'
  openbabel-python.i:243: Error: Unable to find 'openbabel/chains.h'
  openbabel-python.i:244: Error: Unable to find 'openbabel/typer.h'
  openbabel-python.i:252: Error: Unable to find 'openbabel/plugin.h'
  openbabel-python.i:257: Error: Unable to find 'openbabel/oberror.h'
  openbabel-python.i:258: Error: Unable to find 'openbabel/format.h'
  openbabel-python.i:259: Error: Unable to find 'openbabel/obconversion.h'
  openbabel-python.i:260: Error: Unable to find 'openbabel/residue.h'
  openbabel-python.i:261: Error: Unable to find 'openbabel/internalcoord.h'
  openbabel-python.i:262: Error: Unable to find 'openbabel/atom.h'
  openbabel-python.i:263: Error: Unable to find 'openbabel/bond.h'
  openbabel-python.i:264: Error: Unable to find 'openbabel/reaction.h'
  openbabel-python.i:282: Error: Unable to find 'openbabel/mol.h'
  openbabel-python.i:289: Error: Unable to find 'openbabel/ring.h'
  openbabel-python.i:290: Error: Unable to find 'openbabel/parsmart.h'
  openbabel-python.i:291: Error: Unable to find 'openbabel/alias.h'
  openbabel-python.i:292: Error: Unable to find 'openbabel/atomclass.h'
  openbabel-python.i:294: Error: Unable to find 'openbabel/fingerprint.h'
  openbabel-python.i:296: Error: Unable to find 'openbabel/descriptor.h'
  openbabel-python.i:301: Error: Unable to find 'openbabel/forcefield.h'
  openbabel-python.i:303: Error: Unable to find 'openbabel/builder.h'
  openbabel-python.i:304: Error: Unable to find 'openbabel/op.h'
  openbabel-python.i:306: Error: Unable to find 'openbabel/chargemodel.h'
  openbabel-python.i:309: Error: Unable to find 'openbabel/phmodel.h'
  openbabel-python.i:310: Error: Unable to find 'openbabel/graphsym.h'
  openbabel-python.i:311: Error: Unable to find 'openbabel/isomorphism.h'
  openbabel-python.i:312: Error: Unable to find 'openbabel/query.h'
  openbabel-python.i:313: Error: Unable to find 'openbabel/canon.h'
  openbabel-python.i:315: Error: Unable to find 'openbabel/stereo/stereo.h'
  openbabel-python.i:318: Error: Unable to find 'openbabel/bitvec.h'
  openbabel-python.i:321: Error: Unable to find 'openbabel/rotor.h'
  openbabel-python.i:323: Error: Unable to find 'openbabel/rotamer.h'
  openbabel-python.i:324: Error: Unable to find 'openbabel/spectrophore.h'
  openbabel-python.i:374: Error: Unable to find 'openbabel/obiter.h'
  stereo.i:1: Error: Unable to find 'openbabel/stereo/tetranonplanar.h'
  stereo.i:2: Error: Unable to find 'openbabel/stereo/tetraplanar.h'
  stereo.i:3: Error: Unable to find 'openbabel/stereo/tetrahedral.h'
  stereo.i:4: Error: Unable to find 'openbabel/stereo/cistrans.h'
  stereo.i:5: Error: Unable to find 'openbabel/stereo/squareplanar.h'
  stereo.i:6: Error: Unable to find 'openbabel/stereo/bindings.h'
  
  Error: SWIG failed. Is Open Babel installed?
  You may need to manually specify the location of Open Babel include and library directories. For example:
    python setup.py build_ext -I/usr/local/include/openbabel-2.0 -L/usr/local/lib
    python setup.py install
  
  ----------------------------------------
  Failed building wheel for openbabel
  Running setup.py clean for openbabel
Failed to build openbabel
Installing collected packages: openbabel
  Running setup.py install for openbabel ... error
    Complete output from command /Users/Paulin/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-build-v0rof5j4/openbabel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-2iizw9um-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    Open Babel location automatically determined by pkg-config:
    - include_dirs: ['/Users/Paulin/miniconda3/include/python3.6m', '/usr/local/include/openbabel-2.0']
    - library_dirs: ['/Users/Paulin/miniconda3/lib', '/usr/local/lib']
    building '_openbabel' extension
    swigging openbabel-python.i to openbabel-python_wrap.cpp
    swig -python -c++ -small -O -templatereduce -naturalvar -I/Users/Paulin/miniconda3/include/python3.6m -I/usr/local/include/openbabel-2.0 -o openbabel-python_wrap.cpp openbabel-python.i
    openbabel-python.i:225: Error: Unable to find 'openbabel/babelconfig.h'
    openbabel-python.i:227: Error: Unable to find 'openbabel/data.h'
    openbabel-python.i:228: Error: Unable to find 'openbabel/rand.h'
    openbabel-python.i:229: Error: Unable to find 'openbabel/obutil.h'
    openbabel-python.i:230: Error: Unable to find 'openbabel/math/vector3.h'
    openbabel-python.i:232: Error: Unable to find 'openbabel/math/matrix3x3.h'
    openbabel-python.i:233: Error: Unable to find 'openbabel/math/transform3d.h'
    openbabel-python.i:234: Error: Unable to find 'openbabel/math/spacegroup.h'
    openbabel-python.i:238: Error: Unable to find 'openbabel/base.h'
    openbabel-python.i:240: Error: Unable to find 'openbabel/generic.h'
    openbabel-python.i:241: Error: Unable to find 'openbabel/griddata.h'
    openbabel-python.i:243: Error: Unable to find 'openbabel/chains.h'
    openbabel-python.i:244: Error: Unable to find 'openbabel/typer.h'
    openbabel-python.i:252: Error: Unable to find 'openbabel/plugin.h'
    openbabel-python.i:257: Error: Unable to find 'openbabel/oberror.h'
    openbabel-python.i:258: Error: Unable to find 'openbabel/format.h'
    openbabel-python.i:259: Error: Unable to find 'openbabel/obconversion.h'
    openbabel-python.i:260: Error: Unable to find 'openbabel/residue.h'
    openbabel-python.i:261: Error: Unable to find 'openbabel/internalcoord.h'
    openbabel-python.i:262: Error: Unable to find 'openbabel/atom.h'
    openbabel-python.i:263: Error: Unable to find 'openbabel/bond.h'
    openbabel-python.i:264: Error: Unable to find 'openbabel/reaction.h'
    openbabel-python.i:282: Error: Unable to find 'openbabel/mol.h'
    openbabel-python.i:289: Error: Unable to find 'openbabel/ring.h'
    openbabel-python.i:290: Error: Unable to find 'openbabel/parsmart.h'
    openbabel-python.i:291: Error: Unable to find 'openbabel/alias.h'
    openbabel-python.i:292: Error: Unable to find 'openbabel/atomclass.h'
    openbabel-python.i:294: Error: Unable to find 'openbabel/fingerprint.h'
    openbabel-python.i:296: Error: Unable to find 'openbabel/descriptor.h'
    openbabel-python.i:301: Error: Unable to find 'openbabel/forcefield.h'
    openbabel-python.i:303: Error: Unable to find 'openbabel/builder.h'
    openbabel-python.i:304: Error: Unable to find 'openbabel/op.h'
    openbabel-python.i:306: Error: Unable to find 'openbabel/chargemodel.h'
    openbabel-python.i:309: Error: Unable to find 'openbabel/phmodel.h'
    openbabel-python.i:310: Error: Unable to find 'openbabel/graphsym.h'
    openbabel-python.i:311: Error: Unable to find 'openbabel/isomorphism.h'
    openbabel-python.i:312: Error: Unable to find 'openbabel/query.h'
    openbabel-python.i:313: Error: Unable to find 'openbabel/canon.h'
    openbabel-python.i:315: Error: Unable to find 'openbabel/stereo/stereo.h'
    openbabel-python.i:318: Error: Unable to find 'openbabel/bitvec.h'
    openbabel-python.i:321: Error: Unable to find 'openbabel/rotor.h'
    openbabel-python.i:323: Error: Unable to find 'openbabel/rotamer.h'
    openbabel-python.i:324: Error: Unable to find 'openbabel/spectrophore.h'
    openbabel-python.i:374: Error: Unable to find 'openbabel/obiter.h'
    stereo.i:1: Error: Unable to find 'openbabel/stereo/tetranonplanar.h'
    stereo.i:2: Error: Unable to find 'openbabel/stereo/tetraplanar.h'
    stereo.i:3: Error: Unable to find 'openbabel/stereo/tetrahedral.h'
    stereo.i:4: Error: Unable to find 'openbabel/stereo/cistrans.h'
    stereo.i:5: Error: Unable to find 'openbabel/stereo/squareplanar.h'
    stereo.i:6: Error: Unable to find 'openbabel/stereo/bindings.h'
    
    Error: SWIG failed. Is Open Babel installed?
    You may need to manually specify the location of Open Babel include and library directories. For example:
      python setup.py build_ext -I/usr/local/include/openbabel-2.0 -L/usr/local/lib
      python setup.py install
    
    ----------------------------------------
Command "/Users/Paulin/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-build-v0rof5j4/openbabel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-2iizw9um-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/6l/bwvmq2t17sl44hn70n2przcr0000gn/T/pip-build-v0rof5j4/openbabel/

**Comment by fredrikw** [comment]
Hi,

Have you installed OpenBabel? Can you run it from the command line?

Kind regards,
Fredrik

Med vänliga hälsningar,
Fredrik

**Comment by mcs07** [comment]
Seeing as you are using anaconda python, maybe try installing openbabel via conda:

    conda install -c openbabel openbabel 

This is the full openbabel installation, and it includes the python bindings.

**Comment by paulgholin** [comment]
@fredrikw , I was able to obabel -V and obabel -Hsdf but cannot import openbabel (https://openbabel.org/docs/dev/UseTheLibrary/PythonInstall.html)

@mcs07 , your method works and I can use in python now. 

Thank you for your help!

**Comment by bian1d** [comment]
> Seeing as you are using anaconda python, maybe try installing openbabel via conda:
> 
> ```
> conda install -c openbabel openbabel 
> ```
> 
> This is the full openbabel installation, and it includes the python bindings.

fucking helpful bro, you are my hero
