### ISSUE TITLE
math parsing issue during compile

### ISSUE THREAD

**Issue by Justinzobel** [openbabel/openbabel#1624]
## Environment Information
Open Babel version: 2.4.0/1
Operating system and version: Linux (Solus 3)

## Expected Behavior
Compile

## Issue
cmake '-DCMAKE_CFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fexceptions -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT' '-DCMAKE_CXX_FLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -fno-omit-frame-pointer -fexceptions -D_FORTIFY_SOURCE=2 -fstack-protector --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT' '-DCMAKE_LD_FLAGS=-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000' -DCMAKE_LIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr .
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-gcc
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-g++
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-solus-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using included inchi library.
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.4") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found wxWidgets: -L/usr/lib64;-pthread;-Wl,--copy-dt-needed-entries;-Wl,-O1;-Wl,-z,relro;-Wl,-z,now;;-L/usr/lib64;;-lwx_baseu-2.8;-lwx_gtk2u_core-2.8;-lwx_gtk2u_adv-2.8 (found version "2.8.12") 
-- Looking for conio.h
-- Looking for conio.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for rpc/xdr.h
-- Looking for rpc/xdr.h - found
-- Looking for regex.h
-- Looking for regex.h - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for rint
-- Looking for rint - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for sranddev
-- Looking for sranddev - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of clock_t
-- Check size of clock_t - done
CMake Error at cmake/modules/MacroEnsureVersion.cmake:76 (MATH):
  math cannot parse the expression: "x86_646*10000 + x86_644*100 + x86_640":
  syntax error, unexpected exp_NUMBER, expecting $end (8)
Call Stack (most recent call first):
  cmake/modules/MacroEnsureVersion.cmake:95 (NORMALIZE_VERSION)
  CMakeLists.txt:248 (macro_ensure_version)

CMake Error at cmake/modules/MacroEnsureVersion.cmake:76 (MATH):
  math cannot parse the expression: "x86_646*10000 + x86_644*100 + x86_640":
  syntax error, unexpected exp_NUMBER, expecting $end (8)
Call Stack (most recent call first):
  cmake/modules/MacroEnsureVersion.cmake:95 (NORMALIZE_VERSION)
  CMakeLists.txt:249 (macro_ensure_version)

CMake Error at cmake/modules/MacroEnsureVersion.cmake:76 (MATH):
  math cannot parse the expression: "x86_646*10000 + x86_644*100 + x86_640":
  syntax error, unexpected exp_NUMBER, expecting $end (8)
Call Stack (most recent call first):
  cmake/modules/MacroEnsureVersion.cmake:95 (NORMALIZE_VERSION)
  CMakeLists.txt:250 (macro_ensure_version)

-- Performing Test SCANDIR_NEEDS_CONST
-- Performing Test SCANDIR_NEEDS_CONST - Failed
-- Performing Test HAVE_GCC_VISIBILITY
-- Performing Test HAVE_GCC_VISIBILITY - Success
-- Checking available shared pointer...
-- Performing Test HAVE_STD_SHARED_PTR
-- Performing Test HAVE_STD_SHARED_PTR - Success
-- Performing Test HAVE_STD_TR1_SHARED_PTR
-- Performing Test HAVE_STD_TR1_SHARED_PTR - Failed
-- Performing Test HAVE_STD_TR1_SHARED_PTR_IN_TR1_HEADER
-- Performing Test HAVE_STD_TR1_SHARED_PTR_IN_TR1_HEADER - Success
-- Use std::shared_ptr in memory
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'cairo'
--   Found cairo, version 1.14.10
-- Found Cairo: /usr/lib/libcairo.so  
-- Cairo found. PNG output will be supported.
-- Looking for getopt
-- Looking for getopt - found
-- Attempting to build the GUI
--    wxWidgets found => GUI will be built
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Configuring incomplete, errors occurred!

**Comment by cowsandmilk** [comment]
I think the best approach to this would be to move to using CMAKE_CXX_COMPILER_VERSION , but that was added in CMake 2.8.10 . The current CMakeLists.txt says that we should remain compatible with 2.4.8 .

Can we increase the minimum CMake version? I'll note RHEL 6 ships with 2.8.12.2 ; RHEL 5 basically hit end of life on March 31 of this year, so I'm considering that dead.

So, if we update the minimum CMake version, we should be able to eliminate the regex parsing of gcc --version.

**Comment by Justinzobel** [comment]
Happy to test a patch if needed.

**Comment by ghutchis** [comment]
@cowsandmilk - I'm fine to bump to 2.8.10. That seems like a safe level for a bit.

**Comment by baoilleach** [comment]
Can this method be included without the version bump, e.g. by including one file from a layer release?

**Comment by baoilleach** [comment]
To answer my own question. Looks like not.

**Comment by ghutchis** [comment]
@baoilleach - I mean, CMake version 2.8.10 is from 31 Oct 2012, so I'd think a ~5-year old release is okay..
https://cmake.org/Wiki/CMake_Released_Versions

**Comment by cowsandmilk** [comment]
@Justinzobel can you confirm the merged #1630 solves your issue?

**Comment by Justinzobel** [comment]
Indeed it does @cowsandmilk, thank you!

**Comment by Justinzobel** [comment]
Will a new release be made ie 2.4.1.1 or 2.4.2 soon?

**Comment by baoilleach** [comment]
I think the answer is now officially "no". The next release I believe will be 2.5.0. There is no timeline at the moment.
