### ISSUE TITLE
New Elements codes is not case-insensitive

### ISSUE THREAD

**Issue by cowsandmilk** [openbabel/openbabel#1628]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: git master
Operating system and version: RHEL 6

## Expected Behavior
PDB file with element CL in columns 77-78 should produce a chlorine atom

## Actual Behavior
PDB file with element CL in columns 77-78 gives a dummy atom

## Steps to Reproduce
(1) curl http://ligand-expo.rcsb.org/reports/0/00T/00T_ideal.pdb | obabel -ipdb -omol2
(2)  see line with Du atom that should be chlorine

I would try to fix it myself, but I believe Noel has some script that produces the switch statements from a csv file

**Comment by cowsandmilk** [comment]
@baoilleach your elements code

**Comment by baoilleach** [comment]
This is certainly a bug (we need more testcases) but while it is true that the original code did handle "CL" and "Chlorine" among other synonyms, I decided during the rewrite that the GetAtomicNum should just contain the atomic symbol 'Cl'. This function should do one job and do it well.

In other words, I'd prefer not to change a core function for the sake of a particular format, and instead just lower-case the 2nd letter before lookup.

**Comment by cowsandmilk** [comment]
Alright, I'll fix the pdb format and add a test.

**Comment by cowsandmilk** [comment]
fixed by #1631
