### ISSUE TITLE
OBMolAtomBFSIter works incorrectly in Python3 

### ISSUE THREAD

**Issue by oititov** [openbabel/openbabel#1636]
There is a bug in the current version with OBMolAtomBFSIter in Python bindings. 
The Python3 code like 

    for atom, depth in OBMolAtomBFSIter(mol, 1):

results in an error

    Traceback (most recent call last):
      File "./test.py", line 17, in <module>
        for atom, depth in OBMolAtomBFSIter(mol, 1):
    TypeError: 'OBAtom' object is not iterable

This behavior can be checked with a script from https://baoilleach.blogspot.ru/2008/07/calculate-circular-fingerprints-with.html 

The problem may be fixed by addition of  `__next__ = next` in the code of the `class OBIterWithDepth(OBIter)` in `scripts/openbabel-python.i` lines 410 - 421

https://github.com/openbabel/openbabel/blob/6bfa4234df4e6744fec858b9e562d419848e6985/scripts/openbabel-python.i#L422

**Comment by baoilleach** [comment]
Good point.

**Comment by oititov** [comment]
Added a pull request with the fix. #1637

**Comment by ghutchis** [comment]
Resolved via merge. Thanks!

**Comment by mwojcikowski** [comment]
There is no stable version with this issue resolved. Just the git master, or the first future release (as of 16.05.2018).

Just add following to your code after pybel import and you're good to go:
```python
import pybel
ob = pybel.ob
ob.OBIterWithDepth.__next__ = ob.OBIterWithDepth.next
```

**Comment by nate-russell** [comment]
@mwojcikowski Thank you
