### ISSUE TITLE
wrong spacegroup entry for Hall symbol "C -4 -2b"

### ISSUE THREAD

**Issue by wojdyr** [openbabel/openbabel#1641]
I wrote a little [script][1] to check consistency of the Hall symbols and spacegroup operators in `space-groups.txt`.
One entry is inconsistent:

    117
    C -4 -2b
    C -4 2 b

This Hall symbol is not in the International Tables, but if I enter it into
https://cci.lbl.gov/cctbx/explore_symmetry.html
I get:
> Space group number: 113

so something is wrong.

This entry was added in PR #256, so perhaps something was wrong in COD?
@afonari ?

[1]: https://github.com/project-gemmi/gemmi/blob/master/tools/ob_spacegroups.py

**Comment by afonari** [comment]
Hi Marcin,

This space group does exist: http://img.chem.ucl.ac.uk/sgp/large/117cz1.htm

I will try to match symm ops of it from the OpenBabel definition with one of the space groups from spglib. Note that, it is also missing from Hall names: http://pmsl.planet.sci.kobe-u.ac.jp/~seto/?page_id=37&lang=en

Will update soon.

**Comment by wojdyr** [comment]
Hi Sasha,
could it be that the website in Birkbeck is wrong?
Perhaps adding base centering to spacegroup 117 transforms it into spacegroup 111.
That's what I get from sgtbx when I put the list of operations:
```
Space group number: 111
Conventional Hermann-Mauguin symbol: P -4 2 m
Universal    Hermann-Mauguin symbol: P -4 2 m (a+b,-a+b,c)
Hall symbol:  P -4 2 (1/2*x+1/2*y,-1/2*x+1/2*y,z)
Change-of-basis matrix: x-y,x+y,z
               Inverse: 1/2*x+1/2*y,-1/2*x+1/2*y,z
```

**Comment by afonari** [comment]
I cannot find its set of symm. ops in the spglib. I remember there was CIF files with that space group (I don't have access to CCDC to check). Also another website mentions it: https://bruceravel.github.io/demeter/documents/Artemis/atoms/space.html as being 117.

**Comment by wojdyr** [comment]
So I was wrong and the website in Birkbeck/UCL is right.
Jeremy Karl Cockcroft, the author of the diagrams on that website kindly replied to my email and explained it to me.
I'll make a PR proposing a Hall symbol that generates this spacegroup.
