### ISSUE TITLE
Residue coordinates are not copied using AddResidue function (?)

### ISSUE THREAD

**Issue by jeeberhardt** [openbabel/openbabel#1646]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 (python 2.7.13)
Operating system and version: Ubuntu 16.04 LTS

## Expected Behavior
The goal is to create a new molecule ```new_mol``` (OBMol) by selecting some residues (OBResidu), based on arbitrary criteria, from an other molecule ```mol``` (OBMol).

## Actual Behavior
The number and the name (for example) of residues in the new molecule ```new_mol``` are correct, but there is no coordinates for atoms.

... or maybe, this is not the right way to doing that?
Thanks!

## Steps to Reproduce
```
# Installation: conda install openbabel

import openbabel as ob

obconv = ob.OBConversion()
obconv.SetInFormat("pdb")

# Read Molecule
mol = ob.OBMol()
obconv.ReadFile(mol, "1lbd.pdb")

# Create new molecule
new_mol = ob.OBMol()

# Add new residu to new_mol
for residue in ob.OBResidueIter(mol):
    # If criteria is filled, add residu to new_mol
    new_mol.AddResidue(residue)
    print residue.GetNumAtoms()

print "New Molecule"
    
for residue in ob.OBResidueIter(new_mol):        
    print residue.GetNumAtoms()
    print residue.GetName()
```

**Comment by baoilleach** [comment]
That's not a bug. Residues are just overlays on certain atoms of an OBMol, providing additional information. It sounds like you either way to delete all but one residue from the existing OBMol, or else clone the existing OBMol and then delete them.

**Comment by Luckick** [comment]
I faced the same problem.
And I solved it by adding atom by atom, bond by bond, removing atom by atom.

`  ligand = openbabel.OBMol()
    ligand_atoms_ids = []

    for atom in residue.atoms:
        ligand_atoms_ids.append(atom.idx)  
    for idx in ligand_atoms_ids:
        ligand.AddAtom(complex.OBMol.GetAtom(idx))
        for idx2 in ligand_atoms_ids:
            bond = complex.OBMol.GetAtom(idx).GetBond(complex.OBMol.GetAtom(idx2))
            if bond is not None:
                ligand.AddBond(bond)

    ligand_atoms_ids.reverse()
    for idx in ligand_atoms_ids:
        complex.OBMol.DeleteAtom(complex.OBMol.GetAtom(idx))`
