### ISSUE TITLE
Unable to even convert files after snap installation

### ISSUE THREAD

**Issue by SimonEnsemble** [openbabel/openbabel#1647]
- [x ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: openbabel  2.4.0    baoilleach  Installed via snap.
Operating system and version: Ubuntu 16.04

## Expected Behavior
Have a cif file CoBDP.cif that Avogadro reads just fine. Goal is to convert to .cssr. Or .pdb. I get tons of different errors.

## Actual Behavior
`openbabel.obabel -icif CoBDP.cif -ocssr` 
gives
```Open Babel Error  in OpenAndSetFormat
  Cannot open CoBDP.cif
```
and
```
openbabel.obabel CoBDP.cif -O CoBDP.pdb
```
gives:
```
Open Babel Error  in FullConvert
  Cannot write to CoBDP.pdb
```
When I run with sudo, I get the same thing so it is not a file permissions thing.

I also tried the same commands with attempts to convert .cssr files to .pdb.
I also tried `openbabel.babel` and got the same thing.

## Steps to Reproduce
Here is the .cif file: https://www.dropbox.com/s/uyzdmuwuzy0mg5x/CoBDP.cif?dl=0

**Comment by baoilleach** [comment]
Doh! Snaps run in a sandboxed environment, and don't have permissions unless the creator grants them. I'll have to redo the snap. In the meanwhile you can still pipe stuff through obabel and pipe the output to a file, e.g.
cat tmpfile.cif | openbabel.obabel -icif -opdb > tmpfile.pdb
(I've confirmed this works with your test file)

When I've done it, I'll update this issue.

**Comment by baoilleach** [comment]
Try again now and let me know if it works. It's version 2.4.1 now.

**Comment by SimonEnsemble** [comment]
Excellent, file permissions are working now. Thank you. The snap makes it so easy to install, I love it.
