### ISSUE TITLE
file INSTALL cannot find libopenbabel.so.5.0.0 

### ISSUE THREAD

**Issue by Hassenky** [openbabel/openbabel#1649]
I tried to install openbabel 2.4.1 in my user folder; however, there is always error as follows.

> CMake Error at src/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/home/user10/sources/openbabel-git/lib/libopenbabel.so.5.0.0".
Call Stack (most recent call first):
  cmake_install.cmake:75 (include)

> make: [install] Error 1

Can someone tell me how to avoid this error?

Thank you.

**Comment by lorybaby** [comment]
I have the same problem. How to solve it ?
