### ISSUE TITLE
Fingerprint folding not quite right

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1654]
From a comment in #1653 by @johnmay.

Also looks like the ``Fold()`` function is doing the wrong thing elsewhere too. For example if I generate MACCS keys...
```
0000000000021000014416cf1be5b083ad2fef7f1f	204
0004200000000021418004afa160b00910a1e46a1b	205
8004040000100200000816cf8d69b847856dfefb19	206
000000002000002141d034e82b61b08b01230d2d1f	207
00000000204000840194b1091b73b3e781eb2fff1f	208
```
and then fold them to say 256 bits... one would expect the output to be padded with trailing zeros
```
000000000000300001d204de90699425843952fe1f0000000000000000000000	173
801480800d580b84e5fc9ded3773d16fd6efeb7f1f0000000000000000000000	174
000000040000000000000006800c2e84290404d6080000000000000000000000	175
0000000000000000810002401b510165546fc3ff1f0000000000000000000000	176
000000002000002001d0169e9b61b16340e3cdfb1f0000000000000000000000	177
0000000000400084015085871013a7e58deff7df1f0000000000000000000000	178
```
good... but now 512...
```
000004000001002001c4301e9b61bd43cce17deb1f00000000000000000000007373000000000000510000000000000000000000000000000900000006000000	17
0000000000000001038002461a81a18149a1c5391f00000000000000000000007373000000000000510000000000000024000000000000002400000000000000	18
0000000000002000800230510000016604dcbafa1f00000000000000000000007373000000000000b10000000000000090460828177f00000000000000000000	19
0000000000000000004434c80960b1e38963afff1f00000000000000000000007373000000000000210000000000000090be6d000000000098be6d0000000000	20
000000002000102181d41ecf133192635c6feafd1f00000000000000000000007373000000000000f10100000000000058f86d000000000008fc6e0000000000	21
0000800008108364600cb1703f59ecafdbbb7fff1f0000000000000000000000737300000000000021000000000000000f000000000000009cbe6d0000000000	22
000000002000380011d00caa9361b6095c2154ae1f000000000000000000000073730000000000007100000000000000204e6d0000000000a0686e0000000000	23
```
I think this is just a missing ``memset(0)`` but thought I should point it out.

**Comment by ghutchis** [comment]
Yeah, that has all the telltale signs of un-initialized memory.

**Comment by ghutchis** [comment]
I was looking at the fold code.. I think the problem is that you're folding to *larger* bit sizes, not *smaller* which was the intent of folding. That's clearly undefined behavior.

Patch coming..

**Comment by johnmay** [comment]
Yep, the use of 'folding' to a larger a size is for example with MACCS116 doesn't fit nicely in 32 or 64 bit words which one would typically use for popcount.

**Comment by mwojcikowski** [comment]
Isn't folding a one way function as hash is? You may loose some data during
folding and there is no way to recover that.

----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl

2017-10-09 14:12 GMT+02:00 John Mayfield <notifications@github.com>:

**Comment by ghutchis** [comment]
Technically speaking, the code doesn’t put any restriction on the “folding” size. The method was written with “folding down” but as John showed, you can put in 512 bits for MACCS fingerprints and it will attempt to “fold up.” (That is, it will pad the bit vector.)

**Comment by baoilleach** [comment]
Ultimately the API might need a refresh. There are a few sore points like
this. But first...other stuff :-)
