### ISSUE TITLE
NaNs in builder.cpp

### ISSUE THREAD

**Issue by elmar-k** [openbabel/openbabel#1662]
Dear OpenBabel team,

converting this SMILES string...

FCl(=O)=O

..to a 3D structure yields atoms with NaN coordinates in builder.cpp.

This is a trivial patch to get rid of the NaNs, but doesn't yield a correct molecule:

>replace
        bond1 = bond1.normalize();
        bond2 = bond2.normalize();
        v1 = bond1 + bond2;
        v1 = v1.normalize();

        if (atom->GetHyb() == 2)
>with
        bond1 = bond1.normalize();
        bond2 = bond2.normalize();
        v1 = bond1 + bond2;
        if (v1==VZero) v1.randomUnitVector();
        v1 = v1.normalize();

        if (atom->GetHyb() <= 2)

>replace
        if (atom->GetHyb() == 1)
          newbond = bond1; // i.e., in the exact opposite direction
>with
        if (atom->GetHyb() <= 1)
          newbond = bond1; // i.e., in the exact opposite direction

- [X ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

**Comment by baoilleach** [comment]
Acknowledged. There have been a serious of reports about the builder.
