### ISSUE TITLE
'OBAtom' object has no attribute 'IsHydrogen'

### ISSUE THREAD

**Issue by filipsPL** [openbabel/openbabel#1664]
I'm using [the script](https://gist.github.com/baoilleach/974477) for calculating RMSD between experimentally determined ligand pose and docking results. The script worked some time ago (like 6 month ago, don't remember the OpenBabel version).

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.4.90 -- Oct 12 2017 -- 16:01:29 compiled from sources
Operating system and version: Ubuntu 16.04.3 LTS

## Expected Behavior

- calculation of RMSD table

## Actual Behavior
```python
./rmsd.py
Read crystal pose
Traceback (most recent call last):
  File "./rmsd.py", line 26, in <module>
    if not atom.OBAtom.IsHydrogen():
AttributeError: 'OBAtom' object has no attribute 'IsHydrogen'
```

## Steps to Reproduce

- extract the [rmsd.zip](https://github.com/openbabel/openbabel/files/1379621/rmsd.zip) and run `./rmsd.py`

**Comment by baoilleach** [comment]
Not a bug. IsHydrogen() is no longer in the API. Call GetAtomicNum() and compare against 1.
