### ISSUE TITLE
Is there a Ubuntu ppa to install the latest version from binaries?

### ISSUE THREAD

**Issue by UnixJunkie** [openbabel/openbabel#1668]
Hello,
I don't like to install from sources (because then some things that work with
a system-wide-install via packages stop working).
Are there up to date Ubuntu/Debian packages somewhere?
Alternatively, can those be reconstructed from sources easily (I could create a PPA then)?
Thanks,
F.

**Comment by mwojcikowski** [comment]
Hi,

There is no up-to-date PPA as far as I know (I've built one, but it's
terribly out of date). There is up to date package in Debian experimental
branch, which you could install or base on it to build your own devel
packages: https://packages.debian.org/experimental/python-openbabel

You can set up experimental tree with lower priority (
https://wiki.debian.org/DebianExperimental) and install it with "apt
install -t experimental python-openbabel".

----
Pozdrawiam,  |  Best regards,
Maciek Wójcikowski
maciek@wojcikowski.pl

2017-10-20 8:10 GMT+02:00 Francois BERENGER <notifications@github.com>:

**Comment by mbanck** [comment]
The reason those are in experimental is that we did not manage to finish the 2.4.1 transition before the Debian freeze and since then, I've been too busy otherwise to keep up with (among others) OpenBabel packages for Debian.

**Comment by baoilleach** [comment]
We do however have snap packages for the release (2.4.1) and dev (2.4.90, on the edge channel). I've been trying to get in touch with the Ubuntu maintainer (@laserjock) to put automatic builds in place, but I haven't heard back so far.

**Comment by mbanck** [comment]
@baoilleach I haven't heard from @laserjock with regards to chemistry packages in Ubuntu for a long while, however @ginggs is active in Ubuntu with respect to that (but not sure about snap packages).

**Comment by baoilleach** [comment]
Thanks. I just see Jordan's name at https://launchpad.net/openbabel (but there's also https://bugs.launchpad.net/ubuntu/+source/openbabel ?!?), and since it's already registered I can't create it myself.

Can you help @ginggs? Or do I just create another launchpad project, openbabel-snap or so?

Also, what do we need to do to get OB2.4.1 ready for 18.04LTS? Does this need to appear in Debian first?

**Comment by ginggs** [comment]
@UnixJunkie On an Ubuntu machine, you can fetch the sources for the Debian experimental package by doing:
`dget http://deb.debian.org/debian/pool/main/o/openbabel/openbabel_2.4.1-1.dsc`
You can then build locally, and create a PPA if desired.

@baoilleach https://launchpad.net/openbabel appears to be a project in Launchpad's Bazaar VCS, I have no idea if it is possible to transfer ownership.  You could trying asking a question 'for Launchpad itself' at https://answers.launchpad.net/launchpad

I'm not sure if having an openbabel project on Launchpad has any advantages over simply publishing a PPA from your own Launchpad account.  You could base it on the version from Debian experimental, as above.

https://launchpad.net/ubuntu/+source/openbabel is the source package for the versions available from the Ubuntu repositories.

If a new version is uploaded to Debian unstable within the next 5 months or so, it will automatically be pulled into the 18.04 LTS development version.  Once there, it can be backported to 16.04 LTS (or 17.10, etc.) by following the request for backports process: https://wiki.ubuntu.com/UbuntuBackports

**Comment by laserjock** [comment]
@baoilleach I have made @ginggs the owner of https://launchpad.net/openbabel . I created that stuff back in the day when there was a push to get at least stub Launchpad projects for all upstreams.

**Comment by baoilleach** [comment]
Thanks @laserjock. I'll file a new issue here related to the snap support, and ping @ginggs to work out the details.
