### ISSUE TITLE
Set up an automated build for snaps based off master

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1679]
I would like to set up an automated system to generate 'dev' snaps. There is a place for these on the 'edge' channel.

The documentation at https://docs.snapcraft.io/build-snaps/ci-integration describes how to do this, either via Travis or Launchpad. I'm not keen to rope Travis into this as the configuration is a bit involved, and according to the Travis docs, the credentials only last a year at a time.

Via Launchpad, it says to set up an openbabel project. One exists, and it's currently owned by @ginggs. So, the question is, would you (@ginggs) be willing to run through the steps required? Obviously I'd be happy to do it instead, but I guess I'd need to be made an admin or something of the openbabel Launchpad project - is this possible?

Note that I haven't already checked in a snapcraft.yaml, but I guess I'd need to do that. (It doesn't say this anywhere in the docs.)

**Comment by ginggs** [comment]
@baoilleach I know nothing about snaps, so I can't really help there.  As you know, @laserjock made me the owner in #1668, I'd be glad to hand it over to you.
I assume this you? https://launchpad.net/~baoilleach

**Comment by baoilleach** [comment]
That sounds fine to me. And yes, that is me.

**Comment by baoilleach** [comment]
This is working now. I decided not to fully automate it, but rather every so often I merge 'master' into the snap branch (https://github.com/baoilleach/openbabel/tree/snaps). This is automatically built by LaunchPad (see https://code.launchpad.net/~baoilleach/+snap/openbabel) and pushed to the snap store. When the user updates their distro, it will be updated along with everything else.
