### ISSUE TITLE
Smiles canonical is not idempotent in some cases

### ISSUE THREAD

**Issue by rexdwyer** [openbabel/openbabel#1680]
- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Windows 10

## Expected Behavior
I expect the operation of converting to canonical smiles to be idempotent, i.e., I expect to get back my input if the output is already the output of the process.

## Actual Behavior
canonica(canonical(x)) != canonical(x) for some x, as documented in the attached Python program.
Fortunately it affects only 3 of ~5900 molecules I'm dealing with, so OpenBabel is an enormous help for my project.
[idempotence.txt](https://github.com/openbabel/openbabel/files/1425359/idempotence.txt)

## Steps to Reproduce
Python file attached.

**Comment by baoilleach** [comment]
Absolutely it should. I'll check the dev version when I'm back at my computer next week, as this includes some fixes to kekulization and aromaticity that may affect these molecules.

**Comment by baoilleach** [comment]
It seems to be working fine with the dev version (phew!). I placed the strings below in a file:
```
NC1=C(C[N]2=CSC(CCO)=C2C)C=NC(C)=N1
C[SH](CC1OC(N2C=NC3=C2N=CN=C3N)C(C1O)O)CCC(C(O)=O)N
OC(CCC(C1=[N]2[Fe]34(O)[N]5=C6C=C(C(C)=C7CCC(O)=O)N3C7=C1)=C(C)C2=CC(N84)=C(C)C(C=C)=C8C=C5C(C)=C6C=C)=O
```
I converted to can to give:
```
OCCC1=C(C)[N](=CS1)Cc1cnc(nc1N)C	
CS(CC1OC(C(C1O)O)n1cnc2c1ncnc2N)CCC(C(=O)O)N	
C=CC1=C(C)C2=Cc3n4[Fe]56([N]2=C1C=c1c(C)c(c(=CC2=[N]6C(=Cc4c(c3C=C)C)C(=C2CCC(=O)O)C)n51)CCC(=O)O)O		
```
I converted it again to can, and when I diffed the files, no difference was reported.
