### ISSUE TITLE
Hydrogen printing over the top of carbon bond in LSD

### ISSUE THREAD

**Issue by phosphre** [openbabel/openbabel#1681]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.4.1 -- Oct 20 2017 -- 06:42:45
Operating system and version:  Darwin box.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

## Expected Behavior

Explicit hydrogens on LSD molecule display correctly.

## Actual Behavior

Take the LSD .sdf file from pubchem renamed to .txt for github:
[VAYOSLLFUXYJDT-RDTXWAMCSA-N.txt](https://github.com/openbabel/openbabel/files/1426112/VAYOSLLFUXYJDT-RDTXWAMCSA-N.txt)

Run this:

obabel VAYOSLLFUXYJDT-RDTXWAMCSA-N.sdf -O VAYOSLLFUXYJDT-RDTXWAMCSA-N.png -d  -xp 1025 -xu -xU -xb none -xB black -xd -xm -xt

Look at the resulting image:

![vayosllfuxyjdt-rdtxwamcsa-n](https://user-images.githubusercontent.com/20246402/32156975-71cc705e-bd38-11e7-9c1a-f70d2f4ab901.png)

SDF appear to have better molecule arrangement characteristics than SMILES but using SMILES does not produce this as it doesn't print this hydrogen.  Maybe it's not explicit then I guess.  My cheminformatics is new.

**Comment by baoilleach** [comment]
What exactly is the problem with the image?

**Comment by phosphre** [comment]
https://github.com/openbabel/openbabel/issues/1681 <https://github.com/openbabel/openbabel/issues/1681>

mq.
http://phosph.re <http://phosph.re/>

!!!
Alert! This email is quiescing as soon as possible.  Please update your records.

MY NEW EMAIL: email@ej73.com <mailto:email@ej73.com>
PLEASE DELETE: q@phosph.re <mailto:q@phosph.re> 

from all address books and previously sent addresses.
!!!

**Comment by phosphre** [comment]
Hi baoilleach
There is a hydrogen on the right side which is overwriting a c-c bond.

**Comment by baoilleach** [comment]
I don't think so. There are no explicit hydrogens in that molecule - you deleted them with "-d". I think you are looking at a wedge bond, indicating the stereo at the tetrahedral carbon below the N-CH3.

**Comment by phosphre** [comment]
Please compare the above structure with the [pubchem 2D structure](https://pubchem.ncbi.nlm.nih.gov/compound/5761#section=2D-Structure), showing, in green, a H which 'protrudes towards the camera'.  The same H is depicted  as 'protruding' above the ring with the NCH3 group in [the wikipedia entry](https://en.wikipedia.org/wiki/Lysergic_acid_diethylamide#/media/File:LSD-2D-skeletal-formula-and-3D-models.png).

The Pubchem 3D shows the hydrogen in more detail.

My point is that obabel's depiction of this molecule with the flags I used provides an image structure where this H 'protrudes' below the molecule, but in line with a C-C bond in the ring it is a member of, so you have both lines running in the same direction, one on top of the other, and although this may structurally possible, for the purposes of depicting the structure, it is less clear than the two references included above.

Now this may be because I'm using obabel incorrectly, and if so, totally cool.  But although I'm new to the notion of implicit and explicit hydrogens in the context of cheminformatics and 2D structure depictions, the flags I have used have hidden all the implicit hydrogens, but not the case H in point which appears to be nonetheless plotted, but in a way which is confusing, and irrespective, I was urged to log this as a bug by Geoff, so assumed it was therefore a bug.

Therefore, I'm hoping that either
1. Someone with authority admits this is a bug
2. Someone suitably knowledgeable informs me I'm using the wrong flags (and hopefully graciously corrects me) and obabel produces the same structure but with this H sticking out on its own or
3. Someone suitably knowledgeable informs me that this is a feature of obabel, and irrespective of the flags, I will not be able to plot this H in such a way that it 'sticks out' without being plotted over another bond in which case, I can close this issue and use a different tool for those structures I have to plot where I find this anomaly.

**Comment by baoilleach** [comment]
So I wrote some of the stereo code in Open Babel and also some of the handling of implicit hydrogens. I guess you don't mean to wind me up, but I'm going to step away from the keyboard and leave this to @ghutchis.

**Comment by jeffjanes** [comment]
On Fri, Nov 3, 2017 at 7:04 AM, phosphre <notifications@github.com> wrote:

> Please compare the above structure with the pubchem 2D structure
> <https://pubchem.ncbi.nlm.nih.gov/compound/5761#section=2D-Structure>,
> showing, in green, a H which 'protrudes towards the camera'. The same H is
> depicted as 'protruding' above the ring with the NCH3 group in the
> wikipedia entry
> <https://en.wikipedia.org/wiki/Lysergic_acid_diethylamide#/media/File:LSD-2D-skeletal-formula-and-3D-models.png>
> .
>

Having a hydrogen protrude above the screen conveys exactly the same
information as having any one of the three carbons indicated to protrude
below the screen.  And that is what you are seeing, one of the carbons was
chosen to be  depicted protruding below the screen.  Openbabel's depiction
of below-the-plane bonds includes a solid line with the hashed wedged
superimposed over the solid line, instead of just showing the hashed wedge
like most software does.  You seem to be confusing that superimposition to
be two different bonds (and further thinking one of them is to a hydrogen,
despite the lack of 'H'). It is not, it is one bond with two graphical
elements.

Personally I find the superimposition of hashed wedge with a solid line
through it to be unattractive, especially when the solid line is so thick
as in your image.  Maybe there is some option you can give it to turn off
that solid line running through the hashed wedge.  That would make it more
attractive to me and less confusing for you.

> The Pubchem 3D shows the hydrogen in more detail.
>

Well, you didn't tell Pubchem to delete the hydrogens, like you did
openbabel.

Cheers,

Jeff

**Comment by phosphre** [comment]
Thanks Jeff, that explains it perfectly.

Thanks,

Mark Lewis
email@ej73.com
