### ISSUE TITLE
Website links to subversion.tigris.org instead of Git

### ISSUE THREAD

**Issue by frankschmitt** [openbabel/openbabel#1682]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: n/a
Operating system and version: n/a

## Expected Behavior
The link on http://openbabel.org/wiki/Git should point to git-scm.com

## Actual Behavior
The link points to subversion.tigris.org

## Steps to Reproduce
n/a

**Comment by baoilleach** [comment]
Fixed. Thanks. We keep thinking about moving the website to Github Pages, which is why there are multiple small niggles. But we should keep things up to date in the meanwhile....
