### ISSUE TITLE
error: openbabel/babelconfig.h: No such file or directory

### ISSUE THREAD

**Issue by laestis** [openbabel/openbabel#1683]
Hi,

I have bee using openbabel as a library for a while. I wanted to update my version of openbabel and thus download and compile openbabel-2.4.1. Problem is when I want to compile my code, I get the following error
: /home/bomble/Project/openbabel-2.4.1/include/openbabel/mol.h:25: error: openbabel/babelconfig.h: No such file or directory
and indeed I can't find babelconfig.h in the include dir but babelconfig.h is asked in almost all other include.
Where can I find it?

Thanks

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by ghutchis** [comment]
This is not a bug. You're asking for support and asked on the mailing list (which is the right thing to do).
