### ISSUE TITLE
string comparison does not work with numeric sd titles

### ISSUE THREAD

**Issue by cowsandmilk** [openbabel/openbabel#1684]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: git master
Operating system and version: Ubuntu 17.10

## Expected Behavior
According to [the documentation](http://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html#string-descriptors), `obabel test/files/filterset.sdf -osmi --filter "title<'129'"` should return 2 molecules, 123 and 126

## Actual Behavior
No molecules are returned

## Steps to Reproduce
    $ obabel test/files/filterset.sdf -osmi --filter "title<'129'"
    0 molecules converted

**Comment by baoilleach** [comment]
Hmmm...it works for me on Windows. Here's what I did. I took a SMILES file:
```
C       18
CC      123
CCC     124
CCCC    125
```
I converted it to an SDF file. Then:
```
C:\Tools\openbabel\baoilleach\2017build\bin\Release>obabel test.sdf -osmi --filter "title<'129'"
CC      123
CCC     124
CCCC    125

C:\Tools\openbabel\baoilleach\2017build\bin\Release>obabel test.sdf -osmi --filter "title<129"
C       18
CC      123
CCC     124
CCCC    125
```
Can you doublecheck just to be sure, to be sure?

**Comment by merkys** [comment]
I confirm the bug:
```
andrius@tasmanijos-velnias ~ $ obabel ~/src/openbabel-2.4.1/test/files/filterset.sdf -osmi --filter "title<'129'"
0 molecules converted
andrius@tasmanijos-velnias ~ $ obabel --version
No input file or format spec or possibly a misplaced option.
Most options must come after the input files. (-i -o -O -m can be anywhwere.)

Open Babel 2.4.1 -- Oct 24 2017 -- 16:08:06
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.
```

**Comment by baoilleach** [comment]
Are either of you interested in having a go at this?
