### ISSUE TITLE
An hydrogen missing when tautomerisation is conducted

### ISSUE THREAD

**Issue by laestis** [openbabel/openbabel#1692]
Hello,

I am using open babel as a library for my code.
I use the tautomer feature by calling the routine EnumerateTautomers. Most of the case it works fine, but I am having error when I input anyline derivative (for example C[NH2+]c1ccccc1). One H gets removed giving a smiles misinterpreted later on (C[NH+]C1=CC=CC=C1). By looking a bit in the code I noticed it's occurre in EndMol subroutine. 
Could you help on this one? Is there an option or subtlety I missed?
Thanks

- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by baoilleach** [comment]
This is fixed in the development version.

Current release:
obtautomer test.smi gives "C[NH+]c1ccccc1"

Dev version:
obtautomer test.smi gives "C[NH2+]c1ccccc1"
