### ISSUE TITLE
Register Option Param and PointCloud

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#170]
<pre>
>obabel -:O[C@@H](C)N -oinchi
==============================
*** Open Babel Error  in OpenBabel::OBConversion::RegisterOptionParam
  The number of parameters needed by option "r" in Point cloud on VDW surface di
ffers from an earlier registration.
==============================
*** Open Babel Error  in OpenBabel::OBConversion::RegisterOptionParam
  The number of parameters needed by option "x" in Point cloud on VDW surface di
ffers from an earlier registration.
==============================
*** Open Babel Error  in OpenBabel::OBConversion::RegisterOptionParam
  The number of parameters needed by option "p" in Chemical Markup Language diff
ers from an earlier registration.
InChI=1S/C2H7NO/c1-2(3)4/h2,4H,3H2,1H3/t2-/m0/s1
1 molecule converted
</pre>

**Comment by Reinis** [comment]
I see the same issue with other formats too:
```
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "p" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "c" in VDW surface in binary STL format suitable for 3D printing differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "p" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "x" in Point cloud on VDW surface differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "s" in ChemKin format differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "s" in Macromolecular Crystallographic Info differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "s" in FASTA format differs from an earlier registration.
==============================
*** Open Babel Error  in RegisterOptionParam
  The number of parameters needed by option "r" in SMILES format differs from an earlier registration.
```

**Comment by mj-harvey** [comment]
Certainly in the pointcloud and stl classes I only register those options once, each with one parameter. 
Are options registered into a single global set, rather than residing within the scope of their format?
If so, then these warnings arise from some other format registering the same letter option first, but with a differing # of parameters.

**Comment by baoilleach** [comment]
That's exactly it. But what you don't realise is that there is no need to
register options. If you just remove those lines everything will still work.

**Comment by mj-harvey** [comment]
So all calls to  OBConversion::RegisterOptionParam( .. ) are redundant?
Will it always DTRT based on what it finds onthe command line, irrespective
of what's been registered?

Matt

On 6 May 2015 at 21:29, baoilleach <notifications@github.com> wrote:

> That's exactly it. But what you don't realise is that there is no need to
> register options. If you just remove those lines everything will still
> work.
>
> On 6 May 2015 at 18:08, M J Harvey <notifications@github.com> wrote:
>
> > Certainly in the pointcloud and stl classes I only register those options
> > once, each with one parameter.
> > Are options registered into a single global set, rather than residing
> > within the scope of their format?
> > If so, then these warnings arise from some other format registering the
> > same letter option first, but with a differing # of parameters.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openbabel/openbabel/issues/170#issuecomment-99539688
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openbabel/openbabel/issues/170#issuecomment-99580928>.
>



-- 
M J Harvey
CTO
Acellera Ltd.
London, Barcelona.
www.acellera.com | m.j.harvey@acellera.com
Follow us on: twitter <http://www.twitter.com/acellera>, linkedin
<http://www.linkedin.com/company/acellera>, youtube
<http://youtube.com/acelleracom>.
Skypename: acellera

**Comment by baoilleach** [comment]
You'd have to look back at the list at Chris's comments on the matter, but I believe that everything should work fine. I've never called Register for any option I've added.

**Comment by swamidass** [comment]
So is there plans to fix this soon?

**Comment by filipsPL** [comment]
The same here... asking for a fix.

**Comment by ghutchis** [comment]
Sorry, I had a host of things to finish before I could tackle this today.

**Comment by swamidass** [comment]
Thanks Geoff,

Much appreciated.

S Joshua Swamidass
http://swami.wustl.edu/
