### ISSUE TITLE
typo in smilesformat.cpp

### ISSUE THREAD

**Issue by balducci** [openbabel/openbabel#1701]
hello

just tried to build latest master (5a9457ab01b473d1057ecd1dca107f4d49844c75) and getting this compile error:

    /home/balducci/tmp/install-us-d/openbabel-4950.d/openbabel-4958/src/formats/smilesformat.cpp:2869:14: error: cannot convert 'bool' to 'const char*' in return
           return false;

Things get fixed for me with:

diff -c src/formats/smilesformat.cpp.FIX_SMILESFORMAT_CPP src/formats/smilesformat.cpp
*** src/formats/smilesformat.cpp.FIX_SMILESFORMAT_CPP	Fri Nov 24 15:51:44 2017
--- src/formats/smilesformat.cpp	Fri Nov 24 15:51:44 2017
***************
*** 2866,2872 ****
    {
      // If no chiral neighbors were passed in, we're done
      if (chiral_neighbors.size() < 4)
!       return false;
      
      OBAtom *atom = node->GetAtom();
  
--- 2866,2872 ----
    {
      // If no chiral neighbors were passed in, we're done
      if (chiral_neighbors.size() < 4)
!       return (const char*)false;
      
      OBAtom *atom = node->GetAtom();

thanks

ciao
-gabriele

**Comment by baoilleach** [comment]
My bad. I'll fix. What compiler and version, out of interest?

**Comment by balducci** [comment]
> What compiler and version, out of interest?

yeah, I could have given that information

I'm on linux and building with gcc:

Linux 4.14.0 #1 SMP Mon Nov 13 19:53:13 CET 2017 x86_64 GNU/Linux

gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


thanks for your work

ciao
gabriele
