### ISSUE TITLE
OpenBabel GUI freezes when trying to convert SMILES to mol2 format

### ISSUE THREAD

**Issue by lrieswijk** [openbabel/openbabel#1709]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1.
Operating system and version: Windows 10

## Expected Behavior
 conversion of SMILES (approximately 500 rows) to mol2 output (including hydrogen bonds with polar atoms and 3D coordinates)

## Actual Behavior
 The program freezes and takes up all memory of my pc

**Comment by ghutchis** [comment]
Can you post the file?

**Comment by lrieswijk** [comment]
I'm not able to upload a SMI file. Attached is the .txt version
[All_smiles_together.txt](https://github.com/openbabel/openbabel/files/1507380/All_smiles_together.txt)

**Comment by lrieswijk** [comment]
Can you see if something is wrong with the file/format?

**Comment by ghutchis** [comment]
Nothing's wrong with the file. Some of the molecules take a while to process because of stereochemical complexity.

**Comment by nj633** [comment]
Dear Sir/Mam,I have installed openbabel 3.0. I have tried multiple times to convert multiple smiles into pdbqt (with 3D co-ordinates), everytime open babel crashed.Please suggest how to do this?
Thanks & Regards-- 
Nishant Joshi
