### ISSUE TITLE
STL format warnings

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#172]
C:\openbabel\src\formats\stlformat.cpp(123): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(222): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(223): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(224): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(230): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(231): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(232): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(238): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(239): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(240): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]
C:\openbabel\src\formats\stlformat.cpp(287): warning C4244: 'argument' : conversion from 'const double' to 'float', possible loss of data [C:\openbabel\build\src\formats\formats_misc.vcxproj]

(As a rule of thumb, just use doubles everywhere)

**Comment by mj-harvey** [comment]
https://github.com/openbabel/openbabel/pull/179

**Comment by baoilleach** [comment]
Could you send a pull request that just has a patch for this issue? #179 has many different commits for different issues.

**Comment by ghutchis** [comment]
I fixed this manually. Closing.
