### ISSUE TITLE
obabel cannot read input format

### ISSUE THREAD

**Issue by samdani1593** [openbabel/openbabel#1722]
## Environment Information
Open Babel version: 2.4.1 
Operating system and version: Ubuntu 16.04.2 LTS

## Actual Behavior

I had installed openbabel-2.4.1 and installation went perfectly well without any errors. while I tried the obabel for conversion the following error arises. I tried with other file formats too. Still the same error arises. kindly help me to solve this issue.

obabel -ipdb dap.pdb -omol2 asd.mol2
obabel: cannot read input format!
Open Babel 2.4.1 -- Dec  8 2017 -- 18:23:52
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.

**Comment by mwojcikowski** [comment]
Can you send the files?

**Comment by ghutchis** [comment]
This works for me. You seem to indicate that no input format works. Have you tried the Ubuntu packages?

**Comment by s-ansa** [comment]
I have the same problem. 
Open Babel version: Open Babel 2.4.1 -- Nov 12 2018 -- 12:24:14 
Operating system: Ubuntu 19.10
My input file is an xyz with ethanol, however I cannot attach it here.

**Comment by fredrikw** [comment]
How did you install OpenBabel? Do you also have the problem with multiple formats? (run `obabel -L formats` to see which formats you have installed)

If the problem is with multiple formats missing, it is most likely a problem with the environment variable [BABEL_LIBDIR](https://open-babel.readthedocs.io/en/latest/Installation/install.html#environment-variables)

**Comment by othmanalbahri1** [comment]
I am facing a similar issue with `xyz` format. The OpenBabel GUI doesn't include `xyz` in the ----INPUT FORMAT---- list. 

I simply downloaded and installed the latest release `OpenBabel-3.1.1-x64.exe`. 

I'm not sure how to troubleshoot this. Any ideas?
