### ISSUE TITLE
Differences in atom coordinates loading CIF using version 2.3.2 and 2.4.1

### ISSUE THREAD

**Issue by johan-westin-work** [openbabel/openbabel#1726]
- [? ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 and 2.3.2
Operating system and version:
$ uname -a
Linux semlxl10142d803-vm01 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Found differences in atom coordinates when loading CIF using version 2.3.2 and 2.4.1, see below.

- Are the 2.4.1-coordinates closer to the “truth” or is it just a matter of taste?
- Is there a scientific explanation of the differences?
- Is there a way, using OpenBabel 2.4.1, to achieve the “2.3.2”-coordinates?

Please find attached CIF-files, PNG-depictions and Python script. 

Run script:
$ python load_cif.py test01.cif

Best regards,
Johan Westin

$ python -V && obabel -V && python load_cif.py test01.cif                $ python -V && obabel -V && python load_cif.py test01.cif
Python 2.7.14                                                            Python 3.6.3
Open Babel 2.3.2 -- Dec  8 2017 -- 10:34:11                              Open Babel 2.4.1 -- Dec 12 2017 -- 09:09:08
[                                                                        [
{"idx": 1, "type": S2, "coord": (6.84400, 0.27097, 11.70525)},           {"idx": 1, "type": S2, "coord": (0.00000, 0.27097, 11.70525)},
{"idx": 2, "type": F, "coord": (5.77346, 2.22243, 4.77258)},             {"idx": 2, "type": F, "coord": (5.77346, 2.22243, 4.77258)},
{"idx": 3, "type": F, "coord": (6.84400, 3.69147, 3.62745)},             {"idx": 3, "type": F, "coord": (0.00000, 3.69147, 3.62745)},
{"idx": 4, "type": O2, "coord": (6.84400, 5.13963, 5.73536)},            {"idx": 4, "type": O2, "coord": (0.00000, 5.13963, 5.73536)},
{"idx": 5, "type": Car, "coord": (6.84400, 1.89682, 13.66857)},          {"idx": 5, "type": Car, "coord": (0.00000, 1.89682, 13.66857)},
{"idx": 6, "type": Car, "coord": (6.84400, 2.45654, 9.97756)},           {"idx": 6, "type": Car, "coord": (0.00000, 2.45654, 9.97756)},
{"idx": 7, "type": Car, "coord": (6.84400, 4.28894, 8.41099)},           {"idx": 7, "type": Car, "coord": (0.00000, 4.28894, 8.41099)},
{"idx": 8, "type": Car, "coord": (6.84400, 1.55877, 8.89654)},           {"idx": 8, "type": Car, "coord": (0.00000, 1.55877, 8.89654)},
{"idx": 9, "type": Car, "coord": (6.84400, 3.38718, 7.33677)},           {"idx": 9, "type": Car, "coord": (0.00000, 3.38718, 7.33677)},
{"idx": 10, "type": Car, "coord": (6.84400, 2.02831, 7.59183)},          {"idx": 10, "type": Car, "coord": (0.00000, 2.02831, 7.59183)},
{"idx": 11, "type": Car, "coord": (6.84400, 2.70819, 12.51483)},         {"idx": 11, "type": Car, "coord": (0.00000, 2.70819, 12.51483)},
{"idx": 12, "type": C3, "coord": (6.84400, 3.01847, 4.77646)},           {"idx": 12, "type": C3, "coord": (0.00000, 3.01847, 4.77646)},
{"idx": 13, "type": Car, "coord": (6.84400, 1.95457, 11.35277)},         {"idx": 13, "type": Car, "coord": (0.00000, 1.95457, 11.35277)},
{"idx": 14, "type": Car, "coord": (6.84400, 0.55750, 13.41490)},         {"idx": 14, "type": Car, "coord": (0.00000, 0.55750, 13.41490)},
{"idx": 15, "type": C2, "coord": (6.84400, 3.96911, 5.98099)},           {"idx": 15, "type": C2, "coord": (0.00000, 3.96911, 5.98099)},
{"idx": 16, "type": Car, "coord": (6.84400, 3.82940, 9.70960)},          {"idx": 16, "type": Car, "coord": (0.00000, 3.82940, 9.70960)},
{"idx": 17, "type": H, "coord": (6.84400, 2.25664, 14.55003)},           {"idx": 17, "type": H, "coord": (0.00000, 2.25664, 0.67303)},
{"idx": 18, "type": H, "coord": (6.84400, 5.22625, 8.24155)},            {"idx": 18, "type": H, "coord": (0.00000, 5.22625, 8.24155)},
{"idx": 19, "type": H, "coord": (6.84400, 0.62413, 9.06307)},            {"idx": 19, "type": H, "coord": (0.00000, 0.62413, 9.06307)},
{"idx": 20, "type": H, "coord": (6.84400, 1.41040, 6.86911)},            {"idx": 20, "type": H, "coord": (0.00000, 1.41040, 6.86911)},
{"idx": 21, "type": H, "coord": (6.84400, 3.65815, 12.52954)},           {"idx": 21, "type": H, "coord": (0.00000, 3.65815, 12.52954)},
{"idx": 22, "type": H, "coord": (6.84400, 4.44886, 10.43134)},           {"idx": 22, "type": H, "coord": (0.00000, 4.44886, 10.43134)},
]                                                                        ]
 
 
$ python -V && obabel -V && python load_cif.py HOFQAV.cif                $ python -V && obabel -V && python load_cif.py HOFQAV.cif
Python 2.7.14                                                            Python 3.6.3
Open Babel 2.3.2 -- Dec  8 2017 -- 10:34:11                              Open Babel 2.4.1 -- Dec 12 2017 -- 09:09:08
[                                                                        [
{"idx": 1, "type": So2, "coord": (2.84962, 2.15640, 6.24948)},           {"idx": 1, "type": S3, "coord": (2.84962, 2.15640, 6.24948)},
{"idx": 2, "type": O2, "coord": (4.07068, 3.16218, 6.45106)},            {"idx": 2, "type": O2, "coord": (4.07068, 3.16218, 6.45106)},
{"idx": 3, "type": O2, "coord": (3.35939, 0.85335, 6.01263)},            {"idx": 3, "type": O3, "coord": (3.35939, 0.85335, 6.01263)},
{"idx": 4, "type": O2, "coord": (2.03139, 2.41258, 7.38135)},            {"idx": 4, "type": O3, "coord": (2.03139, 2.41258, 7.38135)},
{"idx": 5, "type": C2, "coord": (5.30523, 2.96283, 5.75099)},            {"idx": 5, "type": C2, "coord": (5.30523, 2.96283, 5.75099)},
{"idx": 6, "type": C2, "coord": (6.33726, 2.60377, 6.50049)},            {"idx": 6, "type": C2, "coord": (6.33726, 2.60377, 6.50049)},
{"idx": 7, "type": Car, "coord": (7.74817, 2.52858, 6.08362)},           {"idx": 7, "type": Car, "coord": (7.74817, 2.52858, 6.08362)},
{"idx": 8, "type": Car, "coord": (8.53898, 1.46655, 6.49295)},           {"idx": 8, "type": Car, "coord": (8.53898, 1.46655, 6.49295)},
{"idx": 9, "type": Car, "coord": (9.87638, 1.41292, 6.16247)},           {"idx": 9, "type": Car, "coord": (9.87638, 1.41293, 6.16247)},
{"idx": 10, "type": Car, "coord": (10.45089, 2.42366, 5.44131)},         {"idx": 10, "type": Car, "coord": (10.45089, 2.42366, 5.44131)},
{"idx": 11, "type": Car, "coord": (9.69368, 3.48452, 5.03399)},          {"idx": 11, "type": Car, "coord": (9.69368, 3.48452, 5.03398)},
{"idx": 12, "type": Car, "coord": (8.34838, 3.54047, 5.35183)},          {"idx": 12, "type": Car, "coord": (8.34838, 3.54047, 5.35183)},
{"idx": 13, "type": Car, "coord": (5.25242, 3.21231, 4.30220)},          {"idx": 13, "type": Car, "coord": (5.25242, 3.21231, 4.30219)},
{"idx": 14, "type": Car, "coord": (5.71361, 2.25054, 3.42380)},          {"idx": 14, "type": Car, "coord": (5.71361, 2.25054, 3.42380)},
{"idx": 15, "type": Car, "coord": (5.60586, 2.44639, 2.06324)},          {"idx": 15, "type": Car, "coord": (5.60586, 2.44639, 2.06324)},
{"idx": 16, "type": Car, "coord": (5.03446, 3.59060, 1.56306)},          {"idx": 16, "type": Car, "coord": (5.03446, 3.59060, 1.56306)},
{"idx": 17, "type": Car, "coord": (4.58615, 4.55645, 2.42267)},          {"idx": 17, "type": Car, "coord": (4.58615, 4.55645, 2.42267)},
{"idx": 18, "type": Car, "coord": (4.68407, 4.38042, 3.79047)},          {"idx": 18, "type": Car, "coord": (4.68407, 4.38042, 3.79046)},
{"idx": 19, "type": Car, "coord": (2.05232, 2.74716, 4.80699)},          {"idx": 19, "type": Car, "coord": (2.05232, 2.74716, 4.80699)},
{"idx": 20, "type": Car, "coord": (2.17012, 2.06343, 3.61968)},          {"idx": 20, "type": Car, "coord": (2.17012, 2.06343, 3.61968)},
{"idx": 21, "type": Car, "coord": (1.62506, 2.59969, 2.46794)},          {"idx": 21, "type": Car, "coord": (1.62506, 2.59969, 2.46794)},
{"idx": 22, "type": Car, "coord": (0.95495, 3.81385, 2.48889)},          {"idx": 22, "type": Car, "coord": (0.95495, 3.81385, 2.48889)},
{"idx": 23, "type": Car, "coord": (0.81816, 4.46610, 3.70577)},          {"idx": 23, "type": Car, "coord": (0.81816, 4.46610, 3.70577)},
{"idx": 24, "type": Car, "coord": (1.35796, 3.95549, 4.85997)},          {"idx": 24, "type": Car, "coord": (1.35796, 3.95549, 4.85997)},
{"idx": 25, "type": C3, "coord": (0.41894, 4.43638, 1.22981)},           {"idx": 25, "type": C3, "coord": (0.41894, 4.43638, 1.22981)},
{"idx": 26, "type": H, "coord": (6.15082, 2.37469, 7.38258)},            {"idx": 26, "type": H, "coord": (6.15082, 2.37469, 7.38258)},
{"idx": 27, "type": H, "coord": (8.16199, 0.78107, 6.99605)},            {"idx": 27, "type": H, "coord": (8.16199, 0.78107, 6.99605)},
{"idx": 28, "type": H, "coord": (10.38983, 0.68664, 6.43089)},           {"idx": 28, "type": H, "coord": (10.38983, 0.68664, 6.43089)},
{"idx": 29, "type": H, "coord": (11.35603, 2.38810, 5.22817)},           {"idx": 29, "type": H, "coord": (11.35603, 2.38810, 5.22817)},
{"idx": 30, "type": H, "coord": (10.08281, 4.17058, 4.54135)},           {"idx": 30, "type": H, "coord": (10.08281, 4.17058, 4.54135)},
{"idx": 31, "type": H, "coord": (7.83966, 4.26675, 5.07110)},            {"idx": 31, "type": H, "coord": (7.83966, 4.26675, 5.07110)},
{"idx": 32, "type": H, "coord": (6.09819, 1.46947, 3.75135)},            {"idx": 32, "type": H, "coord": (6.09819, 1.46947, 3.75135)},
{"idx": 33, "type": H, "coord": (5.92293, 1.79647, 1.47836)},            {"idx": 33, "type": H, "coord": (5.92293, 1.79647, 1.47836)},
{"idx": 34, "type": H, "coord": (4.95356, 3.70893, 0.64370)},            {"idx": 34, "type": H, "coord": (4.95356, 3.70893, 0.64370)},
{"idx": 35, "type": H, "coord": (4.21273, 5.33811, 2.08357)},            {"idx": 35, "type": H, "coord": (4.21273, 5.33811, 2.08357)},
{"idx": 36, "type": H, "coord": (4.37257, 5.03850, 4.36888)},            {"idx": 36, "type": H, "coord": (4.37257, 5.03850, 4.36887)},
{"idx": 37, "type": H, "coord": (2.61389, 1.24622, 3.59119)},            {"idx": 37, "type": H, "coord": (2.61389, 1.24622, 3.59119)},
{"idx": 38, "type": H, "coord": (1.70963, 2.13804, 1.66470)},            {"idx": 38, "type": H, "coord": (1.70963, 2.13804, 1.66470)},
{"idx": 39, "type": H, "coord": (0.34964, 5.26816, 3.74057)},            {"idx": 39, "type": H, "coord": (0.34964, 5.26816, 3.74057)},
{"idx": 40, "type": H, "coord": (1.26201, 4.40898, 5.66552)},            {"idx": 40, "type": H, "coord": (1.26201, 4.40898, 5.66552)},
{"idx": 41, "type": H, "coord": (1.02320, 4.26093, 0.50357)},            {"idx": 41, "type": H, "coord": (1.02320, 4.26093, 0.50357)},
{"idx": 42, "type": H, "coord": (0.33355, 5.38474, 1.35209)},            {"idx": 42, "type": H, "coord": (0.33355, 5.38474, 1.35209)},
{"idx": 43, "type": H, "coord": (-0.44123, 4.06099, 1.02870)},           {"idx": 43, "type": H, "coord": (19.35877, 4.06099, 1.02870)},
]                                                                        ]

[attachements.zip](https://github.com/openbabel/openbabel/files/1554903/attachements.zip)

**Comment by afonari** [comment]
From test01.cif:
```
_cell_length_a                   6.844(6)
_cell_length_b                   22.211(19)
_cell_length_c                   13.877(10)
```
```
S(1) S 1.0000 0.0122 0.8435 0.024 Uani 1.00 2 d R
F(1) F 0.84358(12) 0.10006(4) 0.34392(5) 0.0431(2) Uani 1.00 1 d .
F(2) F 1.0000 0.1662 0.2614 0.042 Uani 1.00 2 d R
...
```

X fractional coordinate for S1 and F2 is 1.0 in OpenBabel 2.3.2, X cartesian coordinate is: 6.844 (which is a-axis length). In OpenBabel 2.4.1 X cartesian coordinate is 0 (shifted by a length). Both structures seems to be the same (if disregard the shift). I think pictures are different because they don't take into account periodic boundary conditions (PBCs).

**Comment by johan-westin-work** [comment]
OK, how can I shift X-coordinate back to 6.844 (in this case) without changing the symmerty? Thanks, Johan W

**Comment by afonari** [comment]
> how can I shift X-coordinate back to 6.844 (in this case) without changing the symmerty?

I'm not familiar with python API, but approximate steps would be (maybe someone else can suggest a better way):
```
if atom.x_frac_coord == 1.0:
    atom.x_coord = unit_cell.a_length
```
Do you generate images using OpenBabel?

**Comment by johan-westin-work** [comment]
Hi, no extract coordinates and use Gaussian on these down the workflow. Gaussian can not handle the shifted coordinates (from ob 2.4.1). It can not handle cases where shifted from "slighly negativt"  value to "almost 1" value. The molecule is sort of "ripped apart. I will keep digging... Thanks, Johan W

**Comment by johan-westin-work** [comment]
Hi again,

Found the following in src/formats/mmcifformat.cpp: 
         .....
         .....
         pmol->SetData(pCell);
         if (use_fract)
           {
           for (OBAtomIterator atom_x = pmol->BeginAtoms(), atom_y = pmol->EndAtoms(); atom_x != atom_y; ++ atom_x)
             {
             OBAtom * atom = (* atom_x);
             atom->SetVector(pCell->FractionalToCartesian(
                             pCell->WrapFractionalCoordinate(atom->GetVector())));
             }
           }
         }
         .....
         .....

where the WrapFractionalCoordinate call is was causing the issue for me.

Is it possible to avoid the wrapping if using the _atom_site_Cartn_? labels in the CIF instead?

Wonder,
Johan Westin

**Comment by ghutchis** [comment]
I can confirm that it's the wrapping call. I'm going to revert that behavior by adding a flag to wrap if requested - but the default will be to use the unwrapped coordinates.

Do you want a copy of the patch? It'll go into development (3.0) but not 2.4.x.

**Comment by johan-westin-work** [comment]
Hi,

This is the perfect solution! Yes, please send the patch.

Is there a planned date for release of 3.0?

Thanks a lot!

Regards,
Johan Westin
