### ISSUE TITLE
CML output error if atom class data exists AND more than 26 atoms have the same class

### ISSUE THREAD

**Issue by BernardUPSud** [openbabel/openbabel#1731]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.4.1 -- Jan  2 2017 -- 15:21:43
Operating system and version: Linux styx 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

## Expected Behavior

First of all, thanks for the great software!

I use smile code to define AtomClass value for each atom and want to write it in CML output. For exemple `[N:730]`, should give the following output for the atom field:

`<atom id="aa730" elementType="N"/>`

The atom id is created including a string (aa) and the atom class value (730). The string value is incremented (ab, ac, ...) if other atoms with the same atom class exist in the molecule.

## Actual Behavior

Everything is fine if and only if the number of atoms with the same class is smaller than 27. For large molecules, obabel fails and a seg fault is produced.

When using obabel 2.4.1 with the command
`obabel -ismi mpdtmc3.smi -ocml`, a segmentation fault occurs with the original version whereas a unique atom id is given for each atom with the correction proposed.

[mpdtmc3.smi.zip](https://github.com/openbabel/openbabel/files/1584141/mpdtmc3.smi.zip)
[cmlformat.cpp.zip](https://github.com/openbabel/openbabel/files/1584138/cmlformat.cpp.zip)

**Comment by baoilleach** [comment]
I was just looking at this code this week, and I can imagine the problem. Can I ask what do you use this CML for? What I've been thinking about is whether it would be better to write out the atomclass information in some other way if this is allowed by the CML spec.

**Comment by BernardUPSud** [comment]
Hi,

I am doing molecular simulations with empirical force fields (e.g. OPLSAA or other). In order to do a molecular simulation, I must assign a force field type to each atom in a molecule. Recently, I decided to use the AtomClass number as a force field type. I found that CML is the only output format that use the AtomClass number but I would like to output this information directly in tinker xyz file (instead of MM2 force field).

My work flow for a molecular simulation is then: create a SMILE code for molecules including AtomClass number (or equivalently force field type), use obabel to output a tinker xyz file (with coordinates and connectivity informations) and a cml file (with force field information) from which as script creates input files for my molecular dynamics code…

This is just a second-choice route! Ideally, I would like obabel to do atom typing (associate force field to atoms from element names and connectivity using rules) just like aten does using NETA langage.

I will be happy to help or test!
Bernard


> Le 23 déc. 2017 à 22:16, baoilleach <notifications@github.com> a écrit :
> 
> I was just looking at this code this week, and I can imagine the problem. Can I ask what do you use this CML for? What I've been thinking about is whether it would be better to write out the atomclass information in some other way if this is allowed by the CML spec.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Bernard Rousseau
Directeur de Recherche CNRS
Laboratoire de Chimie Physique - UMR 8000
Université Paris Sud, Orsay

T: +331 6915 3030

**Comment by ghutchis** [comment]
I'd be happy to work with you on modifying Tinker XYZ to allow arbitrary atom classes - that wouldn't be hard.

But Open Babel does have atom typing for a wide range of force fields - using SMARTS. If you'd like to work on code (e.g., using an OBOp) that applies SMARTS patterns and assigns atom types, that wouldn’t' be too hard either.

So I think:
* Let's fix the CML bug (medium priority)
* Please add an issue to create custom force field atom types for Tinker (high priority = easy)
* Please create an issue and let's talk about a way to use SMARTS patterns to apply arbitrary atom types (e.g., data/UFF.prm)

**Comment by BernardUPSud** [comment]
> But Open Babel does have atom typing for a wide range of force fields - using SMARTS. If you'd like to work on code (e.g., using an OBOp) that applies SMARTS patterns and assigns atom types, that wouldn’t' be too hard either.

I imagined that obabel used something like this to assign atome types with existing force fields, but I didn't go into details. I have to look at SMARTS patterns!
 
> So I think:
> 
>     Let's fix the CML bug (medium priority)

This will be great. I will be able to use the official version again.

>     Please add an issue to create custom force field atom types for Tinker (high priority = easy)

OK.

>     Please create an issue and let's talk about a way to use SMARTS patterns to apply arbitrary atom types (e.g., data/UFF.prm)

This sounds more ambitious :) but could be of great help to me! I'm going to create an issue.

Thanks,
Bernard

**Comment by baoilleach** [comment]
Just to add my 2c to the discussion on atom typing. My recommendation would be to avoid SMARTS and do the atom typing in code. It will be faster, but I think also clearer and less prone to errors. You can find examples of both approaches in the Open Babel codebase.

**Comment by BernardUPSud** [comment]
Obviously, if the atom typing is done in the code, a new code has to be written for each forcefield... my intention was to provide a way for users (with no knowledge in cpp :) ) to do typing from some rules provided in a input file.

I understand from your message that atoms can be selected and given a "type" using SMARTS. I have to understand how this can be done because this is precisely what I need!

I you can show me an example from Open Babel codebase, it will help.
Thank you,
Bernard

**Comment by baoilleach** [comment]
Ah right. Regarding SMARTS, perhaps a good place to start is to try implementing a group-contribution descriptor as described at http://open-babel.readthedocs.io/en/latest/WritePlugins/AddNewDescriptor.html. Use ";debug" for more info. Atom-typing would be implemented in a similar way.

**Comment by baoilleach** [comment]
Fixed by #1746
