### ISSUE TITLE
Variable set but not used in OBForceField::DistanceGeometry()

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1735]
I've been working on eliminating warnings from "-W -Wall" (for "make openbabel") with the aim of adding this to Travis. Here's one I don't immediately see the correct solution for (does it indicate a bug, for example?), but @ghutchis might:
```
/home/noel/Tools/openbabel-git/src/forcefield.cpp: In member function 'void OpenBabel::OBForceField::DistanceGeometry()':
/home/noel/Tools/openbabel-git/src/forcefield.cpp:1962:26: error: variable 'l_bc' set but not used [-Werror=unused-but-set-variable]
             double l_ab, l_bc, l_ac; // lower limits
```

**Comment by ghutchis** [comment]
D'oh! That was a bad mistake. When I have a chance, I'll see if I can sneak in a triangle-smoothing unit test. Both that code, and `distgeom.cpp` had weird copy/paste errors there.
