### ISSUE TITLE
OBMol.Separate permutes atoms

### ISSUE THREAD

**Issue by dudektria** [openbabel/openbabel#1763]
The following Python code

    from cinfony import pybel
    mol = pybel.readfile("xyz", "examples/water_dimer.xyz").next()
    print(mol.write("xyz"))

    for m in mol.OBMol.Separate():
        print(pybel.Molecule(m).write("xyz"))

gives me

    6
    examples/water_dimer.xyz
    O          0.12908       -0.26336        0.64798
    H          0.89795        0.28805        0.85518
    H          0.10833       -0.20468       -0.33302
    O          0.31020        0.07569       -2.07524
    H          0.64083       -0.57862       -2.71449
    H         -0.26065        0.64232       -2.62218

    3

    O          0.12908       -0.26336        0.64798
    H          0.89795        0.28805        0.85518
    H          0.10833       -0.20468       -0.33302

    3

    O          0.31020        0.07569       -2.07524
    H         -0.26065        0.64232       -2.62218
    H          0.64083       -0.57862       -2.71449

Is this the expected behaviour? Observe that **atoms 5 and 6 get swapped** in the second fragment.
If it is not a bug, is there a way to keep the atomic ordering with OBMol.Separate?

## Environment Information
Open Babel version: 2.3.2
Operating system and version: Ubuntu 17.10

**Comment by baoilleach** [comment]
I would not expect it to permute atoms. Or at least, it feels like more work to permute atoms than it would be to just keep them in the original order.

**Comment by dudektria** [comment]
I compiled version 2.4.1 yesterday and can confirm that the code above runs exactly the same, also swapping atoms.

**Comment by baoilleach** [comment]
Looking at the implementation, I can see what the problem is. It's adding the atoms to the new molecules in depth-first-search order (which is how it's finding the fragments). It's not a bug, but I think it'd be better if it did as the user might expect. I'll follow this up...

**Comment by baoilleach** [comment]
I've changed the behavior to preserve atom order. It's just a couple of lines change in mol.cpp which you can make yourself based on the pull request link above, or else check out the latest development code from the git repo. Your test case is included as a unit test.
