### ISSUE TITLE
Unable to use CML file format

### ISSUE THREAD

**Issue by bazitur** [openbabel/openbabel#1764]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: `Open Babel 2.4.1 -- Jan 23 2018`
Operating system and version: `Linux-4.13.0-26-generic-x86_64-with-Ubuntu-16.04-xenial`

#### `$ obabel -L cml`
 ```
XML format. This implementation uses libxml2.
 Write options for CML: -x[flags] (e.g. -x1ac)
 1  output CML1 (rather than CML2)
 a  output array format for atoms and bonds
 h  use hydrogenCount for all hydrogens
 m  output metadata
 x  omit XML and namespace declarations
 N<prefix> add namespace prefix to elements
```
#### `$ obabel -icml cyclohexane.cml -osmiles`
 ```
C1CCCCC1
```
####  `$ obabel -L cml `
 ```
cml is not a recognized plugin type. Those with instances of sub-types loaded are:
charges
descriptors
fingerprints
forcefields
formats
loaders
ops
```
#### `$ obabel -icml cyclohexane.cml -osmiles`
```
obabel: cannot read input format!
Open Babel 2.4.1 -- Jan 23 2018 -- 20:20:02
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.
```

**Comment by bazitur** [comment]
And other formats work fine, e.g `obabel -ismiles caffeine.smiles -oxyz`

**Comment by baoilleach** [comment]
Did you compile openbabel yourself? If so, could you provide the output of
cmake?

**Comment by bazitur** [comment]
Yes, I did, so here are the logs: https://gist.github.com/bazitur/7bebdb03456beec290f77db682b6d28a

**Comment by baoilleach** [comment]
Those files don't provide the information I'm looking for. Could you
provide the output that appears on the screen when you run cmake? For
example, in a clean build directory, something like "cmake  ../openbabelsrc
|& tee cmake.out".

**Comment by bazitur** [comment]
Ah, found it: ```
CMake Warning at CMakeLists.txt:168 (message):
libxml2 not found - disabling CML support!
```
Closing issue then. Sorry for taking your time.
