### ISSUE TITLE
Keeping Debian and RPMs up to date

### ISSUE THREAD

**Issue by tdudgeon** [openbabel/openbabel#1766]
The Debian and RPM packages for openbabel (and the python bindings) that are available mostly relate to version 2.3.2, dating from 2012.

What's the possibility of keeping these up to date with the releases?

**Comment by merkys** [comment]
Openbabel v2.4.1 [is already in Debian experimental release](https://packages.qa.debian.org/o/openbabel.html), thus AFAIK, it should appear in the nearest Debian and Ubuntu releases. As per Debian policy, non-security updates are not backported in the stable releases.

I have no experience with RPM packaging and inclusion of RPM packages by their package managers.

**Comment by ghutchis** [comment]
Our general policy has been that distributions seem to find people willing to package. (Over the years, this is certainly true.) If you think there isn't a maintainer of the RPM, I suggest posting on openbabel-discuss mailing list. 

While I'm willing to help packaging in whatever ways we can, I'm marking this closed.

**Comment by tdudgeon** [comment]
Thanks. I got the 2.4.1 version working with Debian which was my main priority.
As a hint to anyone wanting to do this you need to do this:

```
echo 'deb http://deb.debian.org/debian experimental main' >> /etc/apt/sources.list
apt-get install -y -t experimental openbabel python-openbabel
```

Would be useful to keep the RPMs udpated as well.
Anyway, keep up the good work, and hope these packages can keep up with the times!

**Comment by merkys** [comment]
@tdudgeon let us (me; I have contributed a little in the packaging) know should you encounter any unusual behavior of the 2.4.1 Debian package. The proper way to report package bugs is via Debian Bug Tracking System.
