### ISSUE TITLE
Segfault upon reading GAMESS outputs of DFTB3 calculations

### ISSUE THREAD

**Issue by sjojungfrun** [openbabel/openbabel#1768]
I am getting a segfault (core dumped) when reading with openbabel a GAMESS (single core, SMP paralellised) output of a DFTB3 geometry optimisation (file dftb3-2.out attached). For a single point calculation with the same binary, this failure is not found (file dftb3-2-sp.out attached). Besides, when using another GAMESS binary (earlier program version than previous binary, single core IntelMPI pararellised), openbabel does not have problems to read a geometry optimisation with the DFTB3 method (file dftb3-2_oldGamess.out attached). 

This feature is unique of the DFTB3 method. When trying the DFTB one, reading goes smoothly

[attachments.zip](https://github.com/openbabel/openbabel/files/1681190/attachments.zip)

**Comment by serval2412** [comment]
here's the bt:
0x00007ffff7322c44 in OpenBabel::OBAtom::SetPartialCharge (this=0x0, pcharge=0) at /home/julien/projects/openbabel/include/openbabel/atom.h:154
154	      void SetPartialCharge(double pcharge){ _pcharge = pcharge; }
(gdb) bt
#0  0x00007ffff7322c44 in OpenBabel::OBAtom::SetPartialCharge (this=0x0, pcharge=0) at /home/julien/projects/openbabel/include/openbabel/atom.h:154
#1  0x00007fffe4880413 in OpenBabel::GAMESSOutputFormat::ReadMolecule (this=0x7fffe4ab2f30 <OpenBabel::theGAMESSOutputFormat>, pOb=0x55555579f1d0, pConv=0x7fffffffe530)
    at /home/julien/projects/openbabel/src/formats/gamessformat.cpp:478
#2  0x00007ffff75785af in OpenBabel::OBMoleculeFormat::ReadChemObjectImpl (pConv=0x7fffffffe530, pFormat=0x7fffe4ab2f30 <OpenBabel::theGAMESSOutputFormat>)
    at /home/julien/projects/openbabel/src/obmolecformat.cpp:98

The pb is the fact that, on the contrary of the file dftb3-2-sp.out where we got:
TOTAL MULLIKEN
some headings
values...
blank line

in dftb3-2.out, the second occurence with "TOTAL MULLIKEN" contains:
TOTAL MULLIKEN
some headings
values...
DDI: 263640 bytes...

**Comment by serval2412** [comment]
I don't know if the patch will be accepted since it may need an associated test case.
As a workaround, waiting for a fix, I think that just adding a blank line before "DDI:" line.

**Comment by serval2412** [comment]
Shouldn't the status change since the fix patch has been merged?

**Comment by ghutchis** [comment]
In theory, it should have closed automatically since the patch mentioned a fix... Thanks for the reminder. :-)
