### ISSUE TITLE
Isotopic mass not correctly read from Mol files

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1769]
In slide 4 of https://www.slideshare.net/NextMoveSoftware/building-on-sand-standard-inchis-on-nonstandard-molfiles, @johnmay shows that Open Babel is not reading the "atomic mass delta" in Mol files correctly. This value is one way of specifying the isotopic mass. 

The correct way to read this is whatever BioVIA draw is doing. Presumably @johnmay has already fixed this in CDK (?) and we can steal, I mean study and learn from, his approach.

**Comment by johnmay** [comment]
Actually not fixed in CDK either, but this will prompt be to do it. However most toolkits were off only for rarer elements, OB was off every over one (e.g. Li, B, ..) due to double -> integer truncation. I did find it in the code but forget now where it is.

**Comment by baoilleach** [comment]
Do you have the test file available?

**Comment by johnmay** [comment]
Got it on a google spreadsheet, will share at work

**Comment by baoilleach** [comment]
Attaching the details for MDL Bench 2 here for future reference.

[MDL Bench 2.tsv.txt](https://github.com/openbabel/openbabel/files/1734629/MDL.Bench.2.tsv.txt)
