### ISSUE TITLE
Doesn't find wxWidgets

### ISSUE THREAD

**Issue by themaddoctor** [openbabel/openbabel#1780]
CMake is not finding wxWidgets.
Linux 64-bit
OpenBabel source 2.4.1
wxwidgets-gtk3-unicode 3.1.0 and development are installed

mkdir build
cd build
PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB_INSTALL_DIR=lib64 \
    -DOPENBABEL_USE_SYSTEM_INCHI=ON

-- Found INCHI: /usr/lib64/libinchi.so
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.7")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
-- Looking for conio.h
-- Looking for conio.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for rpc/xdr.h
-- Looking for rpc/xdr.h - found
-- Looking for regex.h
-- Looking for regex.h - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for rint
-- Looking for rint - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for sranddev
-- Looking for sranddev - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of clock_t
-- Check size of clock_t - done
-- Performing Test SCANDIR_NEEDS_CONST
-- Performing Test SCANDIR_NEEDS_CONST - Failed
-- Performing Test HAVE_GCC_VISIBILITY
-- Performing Test HAVE_GCC_VISIBILITY - Success
-- Checking available shared pointer...
-- Performing Test HAVE_STD_SHARED_PTR
-- Performing Test HAVE_STD_SHARED_PTR - Success
-- Performing Test HAVE_STD_TR1_SHARED_PTR
-- Performing Test HAVE_STD_TR1_SHARED_PTR - Failed
-- Performing Test HAVE_STD_TR1_SHARED_PTR_IN_TR1_HEADER
-- Performing Test HAVE_STD_TR1_SHARED_PTR_IN_TR1_HEADER - Success
-- Use std::shared_ptr in memory
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Checking for module 'cairo'
--   Found cairo, version 1.14.10
-- Found Cairo: /usr/lib64/libcairo.so
-- Cairo found. PNG output will be supported.
-- Looking for getopt
-- Looking for getopt - found
-- Attempting to build the GUI
--    wxWidgets not found => GUI will not be built
-- Found PythonInterp: /usr/bin/python (found version "3.6.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/building/science/openbabel-2.4.1/build

If it's relevant, there is no "FindWxWidgets.cmake" in the modules directory:

> ls openbabel-2.4.1/cmake/modules/
FindCairo.cmake   FindEigen3.cmake  MacroEnsureVersion.cmake
FindEigen2.cmake  FindInchi.cmake   UsePythonTest.cmake

**Comment by baoilleach** [comment]
Which distro and version? My guess is that you're missing the dev or devel package.

**Comment by themaddoctor** [comment]
distro = built from source
All dev packages are present, I assure you. I was able to manually rewrite the CMakeLists.txt and the generated flags.cmake and link.txt to force it to build obgui.

**Comment by themaddoctor** [comment]
Now that it's built, I have a new problem. The build directory's name is hard-coded into the library, so it cannot find the modules after they are installed.

**Comment by themaddoctor** [comment]
I don't know if that is why obgui segfaults whenever I hit the "convert" button, but I am rebuilding now.

**Comment by themaddoctor** [comment]
WTF?!? the build directory is still hard-coded into the library.

**Comment by baoilleach** [comment]
Going back to the original question, then you need to pass params to FindWxWidgets. This is provided by Cmake  so I would look there for the various params supported. I'm marking the original bug as fixed. Feel free to file additional or mail the list.

**Comment by themaddoctor** [comment]
The problem is that FindWxWidgets is COMPLETELY MISSING from the source tarball.
NOT FIXED. But whatever, you do what you want.

**Comment by ghutchis** [comment]
FindWxWidgets is not part of Open Babel - it's part of CMake:

Open Babel source:
https://github.com/openbabel/openbabel/tree/master/cmake/modules

CMake source:
https://github.com/Kitware/CMake/blob/master/Modules/FindwxWindows.cmake

**Comment by themaddoctor** [comment]
In that case, the problems seems to be that it is not being used by
the openbabel build.


On 2/17/18, Geoff Hutchison <notifications@github.com> wrote:
> FindWxWidgets is not part of Open Babel - it's part of CMake:
>
> Open Babel source:
> https://github.com/openbabel/openbabel/tree/master/cmake/modules
>
> CMake source:
> https://github.com/Kitware/CMake/blob/master/Modules/FindwxWindows.cmake
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openbabel/openbabel/issues/1780#issuecomment-366447276


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
