### ISSUE TITLE
FindWxWidgets is missing from the release tarball

### ISSUE THREAD

**Issue by themaddoctor** [openbabel/openbabel#1782]
2.4.1
As a result, WxWidgets is NEVER found. You closed my bug, so per your suggestion, I am filing another one.

tar -vtlf /sources/openbabel-2.4.1.tar.gz |grep -i find
-rw-r--r-- ghutchis/staff     486 2011-07-25 23:19 openbabel-2.4.1/scripts/python/examples/findcoverage.bat
-rw-r--r-- ghutchis/staff    1438 2014-07-25 14:36 openbabel-2.4.1/cmake/modules/FindCairo.cmake
-rw-r--r-- ghutchis/staff    2866 2011-07-25 23:18 openbabel-2.4.1/cmake/modules/FindEigen2.cmake
-rw-r--r-- ghutchis/staff    2995 2011-07-25 23:18 openbabel-2.4.1/cmake/modules/FindEigen3.cmake
-rw-r--r-- ghutchis/staff     823 2013-10-30 15:30 openbabel-2.4.1/cmake/modules/FindInchi.cmake

**Comment by baoilleach** [comment]
It's part of cmake not openbabel. Try the locate command.

**Comment by ghutchis** [comment]
As I indicated in the other bug, this is *not* part of Open Babel and never has been. It's part of CMake:
https://github.com/Kitware/CMake/blob/master/Modules/FindwxWindows.cmake
