### ISSUE TITLE
Conversion smi -> fpt is not working using Perl bindings

### ISSUE THREAD

**Issue by merkys** [openbabel/openbabel#1783]
I believe this to be a bug with Open Babel.

## Environment Information
Open Babel version: 2.4.1, built from source; same confirmed with 2.3.2.
Operating system and version: Ubuntu-16.04

## Expected Behavior
I expected to convert SMILES string to fingerprint (fpt format) via Perl bindings following [OpenBabel's documentation](https://openbabel.org/docs/dev/UseTheLibrary/Perl.html). I prefer all-Perl solution despite the fact that command line copes well with this task:
```Bash
echo c1ccccc1 | obabel -ismi -ofpt
```
Output (I expected to get the same using Perl bindings):
```
>   6 bits set 
00000000 00000000 00000000 00000200 00000000 00000000 
00000000 00000000 00000000 00000840 00000000 00008000 
00000000 00000000 00000000 00000000 00000000 00000000 
00000000 00000000 00000000 08000000 00000000 00000000 
00000000 00000000 00000000 00000000 00000000 00020000 
00000000 00000000 
1 molecule converted

```

## Actual Behavior and Minimal Reproducible Example
My Perl script:
```Perl
use strict;
use warnings;
use Chemistry::OpenBabel;
my $obmol = new Chemistry::OpenBabel::OBMol;
my $conversion = new Chemistry::OpenBabel::OBConversion; $conversion->SetInAndOutFormats("smi", "fpt");
$conversion->ReadString($obmol, "c1ccccc1");
print "[" . $conversion->WriteString($obmol) . "]\n";
```
Output:
```
[>
]
```

**Comment by baoilleach** [comment]
Does smi to smi conversion work?

**Comment by merkys** [comment]
Yes it does, as well as:
* smi -> sdf
* smi -> can
* smi -> cif.

smi -> fpt seems to be a special failing case.

**Comment by baoilleach** [comment]
Ah. I just checked the docs. Try adding the h output option.

**Comment by merkys** [comment]
Great, ``h`` option solves the problem! Many thanks!

**Comment by baoilleach** [comment]
Great. When I read the docs for fpt, it described special behavior when it knows that there is only a single molecule. That's fine for "obabel", but WriteString() doesn't know what's happening and so it sticks to the default behavior.
