### ISSUE TITLE
Wrong isotope generated from InChI string

### ISSUE THREAD

**Issue by hunter-moseley** [openbabel/openbabel#1785]
- [x ] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Fedora 27 Linux

## Expected Behavior

% obabel -iinchi Sn120.inchi -omol -OSn120.mol
given file SN120.inchi:
---------
InChI=1S/Sn/i1+1
---------
should produce the file Sn120.mol:
---------

 OpenBabel03041813502D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 Sn  0  0  0  0  0 15  0  0  0  0  0  0
M  ISO  1   1 120
M  END
---------
This is based on the InChI Trust FAQs: https://www.inchi-trust.org/technical-faq/#9.2
"The isotopic shift indicated in the isotopic layer is an integer giving atomic mass relative to the rounded average atomic mass of the element."
For Sn, round(118.710) = 119

## Actual Behavior

However, the command actually generates the following Sn120.mol file:
-------------

 OpenBabel03041813502D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 Sn  0  0  0  0  0 15  0  0  0  0  0  0
M  ISO  1   1 121
M  END
-------------

In comparison, the InChI Trust software does generate the correct output.

## Steps to Reproduce
See above.

**Comment by baoilleach** [comment]
Thanks for reporting. Will sort asap.
