### ISSUE TITLE
OBResidue::GetNum() unsigned and negative residue numbers

### ISSUE THREAD

**Issue by ntropia2** [openbabel/openbabel#1786]
When using GetNum() with residues with negative residue numbers, the output is wrong.

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: (git)
Operating system and version: (all)

## Expected Behavior
Return the correct residue number (negative)

## Actual Behavior
The unsigned version of a negative number is returned (-1 -> 4294967295).
Using signed integers would solve the problem.

## Steps to Reproduce
#!/usr/bin/env python
import openbabel as ob

res = ("ATOM      1  N   MET A  -1     -14.828  18.011  17.067  1.00 23.45           N\n"
"ATOM      2  CA  MET A  -1     -14.103  16.799  16.701  1.00 20.23           C\n"
"ATOM      3  C   MET A  -1     -12.600  17.037  16.703  1.00 19.11           C\n"
"ATOM      4  O   MET A  -1     -11.816  16.089  16.744  1.00 19.81           O\n" 
"ATOM      5  CB  MET A  -1     -14.558  16.295  15.329  1.00 20.29           C\n" 
"ATOM      6  CG  MET A  -1     -15.990  15.795  15.315  1.00 23.10           C\n" 
"ATOM      7  SD  MET A  -1     -16.273  14.605  16.642  1.00 26.64           S\n" 
"ATOM      8  CE  MET A  -1     -15.012  13.399  16.255  1.00 26.91           C\n")

obConversion =  ob.OBConversion()
obConversion.SetInFormat("pdb")
mol = ob.OBMol()
obConversion.ReadString(mol, res)
res = mol.GetResidue(0)
print res.GetNumString()
print res.GetNum()

**Comment by baoilleach** [comment]
What's the range of values that might occur? Any negative number or just -1?

**Comment by ghutchis** [comment]
Yeah, I feel like this has been changed a few times - aren't there cases where this can be a string too?

**Comment by ntropia2** [comment]
According to the PDB specification ([1], page 187), the residue sequence number is defined from column 23 to 26, and can only be an integer, not a string. 
This means that values there should only range from -999 to 9999.

[1] ftp://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_Letter.pdf

**Comment by baoilleach** [comment]
I see no problem moving to (signed) int unless we can find an example of a string being used here. It's an API change, but we're in the process of making several at the moment, so now's the time and it sounds like it's necessary. We should make sure to add a test case to make it clear that this is the desired behaviour.

By the way, in your Python, you might prefer to use the triple quote (""") for multi-line strings.

**Comment by ntropia2** [comment]
I've been looking at this issue for a while, and I didn't find any cases with strings. 
If people follows the standards of the format, it should be safe to go for a signed int.... but, it's the PDB, after all, so I wouldn't be surprised if somebody would feel the urge to put unicode characters in there.

**Comment by baoilleach** [comment]
Apparently the "resnum" may be something like "1B" (according to the API docs), so we need to keep the string as the underlying datatype.

I note that the current API is poorly designed: SetNum() takes a string; but GetNum() returns an integer. API Design 101 is to use the same type for getter/setter. GetNum() is a convenience function that just calls atoi on the string value - this is the sort of thing that we should just leave to the user.

Anyway, I'll make the "signed int" change now.

**Comment by baoilleach** [comment]
Fixed by #1786.
