### ISSUE TITLE
Document updation and explanation of --gen3d

### ISSUE THREAD

**Issue by laeeq80** [openbabel/openbabel#1788]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request
- [x] Document Updation

## Environment Information
Open Babel version: latest
Operating system and version: All relevant

Dear Geoff,

From Sourceforge mailing list, I was able to find that gen3d speed can be changed with options. e.g. fastest, fast, med, slow, slowest. I was not able to find this in the docs, hopefully I havn't missed it. I also think there should be little explanation e.g. what is the default option on --gen3d from the earlier five discussed options and what we lose in quality when we use fastest or fast.

Best Regards,
Laeeq

**Comment by baoilleach** [comment]
You can see the updated version at https://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html#specify-speed
