### ISSUE TITLE
Support for Schrodinger MAE files

### ISSUE THREAD

**Issue by ghutchis** [openbabel/openbabel#1803]
- [ ] I believe this to be a bug with Open Babel
- [X] This is a feature request

Schrodinger has helpfully made an open source parser for MAE files available:
https://github.com/schrodinger/maeparser

It would be great to support MAE parsing at baseline using the MAE code.

**Comment by ghutchis** [comment]
Paging @torcolvin - is there a format specification somewhere (e.g., for writing)? Is this even a good idea?

**Comment by mbeachy** [comment]
We don't have documentation of the keys anywhere, which is the important part of being able to use the files to create an actually usable data structure. (IOW schrodinger/maeparser deals with the syntax but not the semantics.)

I think this is a good idea, but it is probably on us to first document or perhaps even implement.
