### ISSUE TITLE
Pybel import crashes Anaconda Python3.6 Ubuntu

### ISSUE THREAD

**Issue by gjbartlett** [openbabel/openbabel#1805]
- [X ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.5.0 (2017-XX-XX) (cloned from github.com)
Operating system and version: Ubuntu 16.04.4 LTS
Running Anaconda python 3.6

## Actual Behavior

compiled using:

cmake .. -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON 

make & sudo make install all run ok.

make test all tests run fine.

Output from python below:

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openbabel
>>> import pybel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/pybel.py", line 43, in <module>
    descs = _getpluginnames("descriptors")
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/pybel.py", line 41, in _getpluginnames
    return [x.split()[0] for x in plugins]
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/pybel.py", line 41, in <listcomp>
    return [x.split()[0] for x in plugins]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

**Comment by baoilleach** [comment]
Hi there. This might take a little digging as I'm not really familiar with how ones builds for anaconda. Is that a special cmake that anaconda provides? The reason I'm confused is that I don't think the regular system cmake would find the anaconda python without some prompting.

**Comment by gjbartlett** [comment]
Hi - it was compiled using the regular cmake installed in /usr/bin, version 3.5.1

What confuses me is that openbabel imports just fine, it is pybel that has problems.

Thanks :-)

**Comment by gjbartlett** [comment]
I've got it to work - I did the following (prompted by this thread: http://forums.openbabel.org/Openbabel-and-Anaconda-td4658042.html)

`conda install cmake lxml swig`

`cmake .. -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DCMAKE_INSTALL_PREFIX=~/anaconda3 -DPYTHON_INCLUDE_DIR=~/anaconda3/include/python3.6m/ -DCMAKE_LIBRARY_PATH=~/anaconda3/lib -DSWIG_DIR=~/anaconda3/share/swig/3.0.12/ -DSWIG_EXECUTABLE=~/anaconda3/bin/swig -DPYTHON_LIBRARY=~/anaconda3/lib/libpython3.6m.so`

`make && make install`

and all was well.

**Comment by baoilleach** [comment]
Good to hear. And that's useful to know for my own reference.

It's also nice to finally 'meet' my co-author on https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1634735/.  :-)
