### ISSUE TITLE
CMake Error at FindRapidJSON.cmake

### ISSUE THREAD

**Issue by merkys** [openbabel/openbabel#1812]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: commit 7617c7c237ec8e55f73fc597ccd2af21454f76ef
Operating system and version: Ubuntu-16.04

## Expected Behavior
I have installed RapidJSON from APT repository (``apt-get install rapidjson-dev``) and have expected cmake to build the Open Babel using the already installed RapidJSON.

## Actual Behavior
CMake threw a CMake error and downloaded RapidJSON to external/:
```
andrius@tasmanijos-velnias build $ cmake ..
...
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Error at cmake/modules/FindRapidJSON.cmake:43 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:469 (find_package)

-- Found RapidJSON: /usr/include (Required is at least version "1.1.0") 
-- Downloaded RapidJSON to /home/andrius/src/openbabel/external/rapidjson-1.1.0.
-- JSON formats will be supported. Using RapidJSON 1.1.0 at /home/andrius/src/openbabel/external/rapidjson-1.1.0/include
-- Checking for module 'cairo'
...
```

## Steps to Reproduce
```
sudo apt-get install rapidjson-dev
cd ~/src/openbabel
mkdir build
cd build
cmake ..
```

**Comment by merkys** [comment]
My bad: ``apt-get install rapidjson-dev`` installs RapidJSON v0.12, which does not even contain ``RAPIDJSON_(MAJOR|MINOR|PATCH)_VERSION``. Sorry for the noise.

**Comment by mcs07** [comment]
I should probably fix that to give a more useful error message for an incompatible version of RapidJSON.

**Comment by merkys** [comment]
@mcs07 it would be nice indeed. The script could just emit a warning if no ``RAPIDJSON_(MAJOR|MINOR|PATCH)_VERSION`` is found.
