### ISSUE TITLE
Stereo on tetrahedral nitrogen is not preserved

### ISSUE THREAD

**Issue by baoilleach** [openbabel/openbabel#1830]
I'm pretty sure this is a regression, and am surprised that it's not covered by the tests. Anyhoo, stereo on a nitrogen due to a LP is not accepted when reading from SMILES. (Note this is nothing to do with stereo perception, just the mechanics of reading a SMILES string.)

```
>obabel -ismi -:[N@@](Br)(F)I -osmi
==============================
*** Open Babel Warning  in OpenBabel::OBSmilesParser::ParseSmiles
  Ignoring stereochemistry. Not enough connections to this atom.
N(Br)(F)I
```

**Comment by ghutchis** [comment]
It's probably worth doing a `git blame` to find out when / how this warning was introduced:
https://github.com/openbabel/openbabel/blame/6c576995969b048186232970ef1b630400544b31/src/formats/smilesformat.cpp#L614

BTW looks like @baoilleach is the culprit. 😉

**Comment by baoilleach** [comment]
I assumed so. :-/ Just disappointed that it wasn't covered by the test
suite.

**Comment by baoilleach** [comment]
Actually, I don't think this was a regression in the end. But it was good to add support in any case. There's probably a few more elements too, but it'll be easy to add them now.
