### ISSUE TITLE
Make use of hardware bit counting

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#184]
I have a branch "mpopcnt" which adds the -mpopcnt flag to the compilation.  This uses hardware support for the "__builtin_popcount" operations.  

This makes searches in fast-search indexes 3 to 6 times faster.

I know little about cmake, and I did this through random mutagenesis.  Does anyone know what would be the correct way to integrate this into the build script?

**Comment by baoilleach** [comment]
Many types of awesome! I thought this was already happening but apparently not.

I'll have a look as soon as possible if no-one else gets there first.

**Comment by baoilleach** [comment]
I think the correct approach would be to add a Check script that tries to compile and run a one-line cpp file containing __builtin_popcount with -mpopcnt. This fails with "illegal instruction" on systems that don't support it. Hopefully all of this is possible in practice.

**Comment by jeffjanes** [comment]
Do we have to worry about cross-compilation where the target platform might not support it even though the compiling one does?  Or is that not supported in the first place?

**Comment by ghutchis** [comment]
I believe Cmake handles those cases - that is, the various compiler checks would be for the cross-compiler.

**Comment by cowsandmilk** [comment]
(i) checking if the compiler has support for a flag using CMake:
check_c_compiler_flag(-mpopcnt HAS_POPCOUNT)

(ii) I think the check Noel is referring to, and @jeffjanes for cross-compilation, is processor support. I agree with @jeffjanes that there is an issue where the library could be compiled on a computer with processor support, then run on a computer without it. The most common example is packaging for operating systems. Shipping rpms that require the popcnt instruction would be less than ideal.

I also know of several pharma companies that use a module system such that openbabel is run from the same binaries/dynamic libraries on disparate hardware from new to 6+ years old.

So, I think there should be some CMake variable set by the user at compilation time for turning it on or off. I don't have strong opinions on defaulting to on or off.

**Comment by jeffjanes** [comment]
Perhaps we could compile both versions of Tanimoto, and then at run time when it opens a fs file, make a dummy __builtin_popcount call and trap the illegal instruction signal (if it is trappable) and change a function pointer to use the other version.  Of course trying to do that in a portable way would also be problematic.  Another the issue is that the "emulated" __builtin_popcount you get when lacking the -mpopcnt flag is probably better than the fallback which openbabel uses.  So we would need to improve that fall-back method as well, or some systems would end up worse off.  

Unless we put the two Tanimoto functions in different compilation modules, and compiled one with -mpopcnt and one without that, but with identical source code.  This is rapidly getting over my head.

Does anyone know of other examples of packaged software that has dealt with this issue?  I haven't been able to find any.

**Comment by baoilleach** [comment]
@cowsandmilk  That is a nice counter example. It's clear that this will cause some bug reports, but there's no way around it apart from flagging it up in the docs, and perhaps also at the end of the configuration (I think Avogadro does a great job of summarising the configuration after running cmake).

@jeffjanes: I don't think that's possible. I think we should just optimise for the architecture at build time, with an option to override it (which we flag up in the configuration summary somehow).

**Comment by baoilleach** [comment]
You can find cmake files that check for popcount in /proc/cpuinfo. I don't really like that approach.

**Comment by baoilleach** [comment]
Roger suggests instead -march=native which applies all of the relevant machine-specific optimisations (e.g. SSE4.2 might help Eigen) and so there would be no need to test for popcount. Using the -S option (show assembly) on a test program would allow us to see whether this works. Obviously, we would still need the possibility to turn off this functionality for people cross-compiling.

**Comment by baoilleach** [comment]
-march=native seems to work like Roger says. The only catch is that VirtualBox doesn't pass through the proper CPU information (regarding SSE4.2 and popcount), so you don't get the benefit there. Strangely, if you forced -mpopcnt, the code would actually run fine. Anyhoo, this is a corner case.

**Comment by baoilleach** [comment]
I've written some code. Just need to test it on Linux, and then I'll submit a pull request...

**Comment by baoilleach** [comment]
Fixed by #186
