### ISSUE TITLE
64 bit python bindings

### ISSUE THREAD

**Issue by odioidentisti2** [openbabel/openbabel#1841]
OpenBabel version 2.4 supports 64 bit, but I think that the last openbabel-python bindings version (openbabel-python-1.8.py33.exe) is for OpenBabel 2.3 (32 bit only).
Is there any way to develop a python program using OpenBabel 64 bit without having to compile it?

**Comment by baoilleach** [comment]
32-bit and 64-bit bindings are available from https://pypi.org/project/openbabel/#files. Where did you find the link to the 1.8 version?

**Comment by odioidentisti2** [comment]
Oh, thank you!
All my bookmarks are on sourceforge, I found the link here: https://sourceforge.net/projects/openbabel/files/openbabel-python/
As you can see from the weekly download, people are still downloading from there. And the fact that there's the link to the latest openbabel version 2.4, it doesn't give you the idea of an old repository.
