### ISSUE TITLE
Has bug #873 being solved?

### ISSUE THREAD

**Issue by odioidentisti2** [openbabel/openbabel#1842]
I cannot find news about bug #873 which was raising a segfault when deleting atoms. This was in version 2.3.2. Has the issue been solved? Since which version?

**Comment by baoilleach** [comment]
The page you link says it was solved already in 2.2.2.

**Comment by odioidentisti2** [comment]
Sorry, that bug number was on Sourceforge: https://sourceforge.net/p/openbabel/bugs/873/ . I saw that  bug tracking is closed there, i think it has moved here keeping the same number (I didn't actually link the page, i just wrote the number).
I was experiencing the issue on Ubuntu and OB 2.3.2.
