### ISSUE TITLE
segmentation fault when converting smi to sdf using --gen2D

### ISSUE THREAD

**Issue by paulboardman** [openbabel/openbabel#1851]
## Environment Information
Open Babel version: 2.4.1
Operating system and version: OS X El Capitan (10.11.6) and CentOs v3.10.0

Below are some example SMILES entries from a public database that cause segmentation faults when converted to SDF.  These all have a common core ring structure that may be causing issues.  None of the other 5M+ structures evaluated caused segmentation faults.

O=C(C1=CN=CS1)N1C2CCC1CN(CC1CC3CCC1O3)C2
O=C(CC1CC1)N1C2CCC1CC(NC(=O)C13CCC(CC1)CC3)C2
O=C([C@@H]1C[C@H]1C1CCC1)N1C2CCC1CN(C(=O)C13CCN(CC1)C3)C2
O=C(CCN1C=CN=C1)N1C2CCC1CN(CC1CC3CCC1C3)C2

example command: `babel input.smi --gen2D output.sdf`

**Comment by serval2412** [comment]
With master sources updated today, I reproduced the crash.
Here's the bt:
[bt.txt](https://github.com/openbabel/openbabel/files/2081924/bt.txt)

**Comment by serval2412** [comment]
With this patch, I got a segfault at another location, see new bt:
[bt1.txt](https://github.com/openbabel/openbabel/files/2082051/bt1.txt)

**Comment by merkys** [comment]
Thanks @fredrikw, opened #2417 for this.
