### ISSUE TITLE
Memory leak in OBSmartsPattern

### ISSUE THREAD

**Issue by n-yoshikawa** [openbabel/openbabel#1869]
When `OBSmartsPattern::Init()` is called more than once in one object, a memory leak occurs.

## Environment Information
Open Babel version: Current master (`699a54e`)
Operating system and version: Ubuntu 16.04

## Steps to Reproduce
1. Save the following code `leak.cpp`.
```cpp
#include <openbabel/parsmart.h>

int main() {
  OpenBabel::OBSmartsPattern sp;
  sp.Init("CC");
  sp.Init("CO");
}
```
2. Compile `leak.cpp` with sanitize flags
```
g++ -g -fsanitize=address -fno-omit-frame-pointer -Wall -I /usr/local/include/openbabel-2.0/ -L /usr/local/lib/openbabel/2.4.90/ leak.cpp -o leak -lopenbabel
```
3. Execute the compiled program. The output in my environment was:
```
$ ./leak 

=================================================================
==11385==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7f57a6778532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f57a63ba27d in OpenBabel::OBSmartsPattern::ParseSMARTSPattern() (/usr/local/lib/libopenbabel.so.5+0x17427d)

Indirect leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f57a67786b2 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x996b2)
    #1 0x7f57a63b8fa1 in OpenBabel::CreateAtom(OpenBabel::Pattern*, OpenBabel::_AtomExpr*, int, int) (/usr/local/lib/libopenbabel.so.5+0x172fa1)

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7f57a6778532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f57a63b7743 in OpenBabel::OBSmartsPattern::ParseSimpleAtomPrimitive() (/usr/local/lib/libopeParseSMARTSPartnbabel.so.5+0x171743)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f57a6778532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f57a63b9965 in OpenBabel::OBSmartsPattern::SMARTSParser(OpenBabel::Pattern*, OpenBabel::ParseState*, int, int) (/usr/local/lib/libopenbabel.so.5+0x173965)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f57a67786b2 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x996b2)
    #1 0x7f57a63b6f21 in OpenBabel::CreateBond(OpenBabel::Pattern*, OpenBabel::_BondExpr*, int, int) (/usr/local/lib/libopenbabel.so.5+0x170f21)

Indirect leak of 8 byte(s) in 2 object(s) allocated from:
    #0 0x7f57a6778532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f57a62b828c in std::vector<int, std::allocator<int> >::_M_insert_aux(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, int const&) (/usr/local/lib/libopenbabel.so.5+0x7228c)

SUMMARY: AddressSanitizer: 256 byte(s) leaked in 8 allocation(s).
```

**Comment by serval2412** [comment]
With openbabel sources updated today, I've got this
ASAN:DEADLYSIGNAL
'=================================================================
==8994==ERROR: AddressSanitizer: SEGV on unknown address 0x55a2cecbd435 (pc 0x7fb250916094 bp 0x7fff308992b0 sp 0x7fff30898a28 T0)
==8994==The signal is caused by a WRITE memory access.
    #0 0x7fb250916093  (/lib/x86_64-linux-gnu/libc.so.6+0xa1093)
    #1 0x7fb25188054d  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x7754d)
    #2 0x7fb2512e6503 in std::char_traits<char>::copy(char*, char const*, unsigned long) /usr/include/c++/7/bits/char_traits.h:350
    #3 0x7fb2512f014b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) /usr/include/c++/7/bits/basic_string.h:340
    #4 0x7fb251320497 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) /usr/include/c++/7/bits/basic_string.tcc:440
    #5 0x7fb25131fe5e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*) /usr/include/c++/7/bits/basic_string.h:1420
    #6 0x7fb25131f7aa in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) /usr/include/c++/7/bits/basic_string.h:694
    #7 0x7fb2514f0a6f in OpenBabel::OBSmartsPattern::Init(char const*) /home/julien/projects/openbabel/src/parsmart.cpp:1722
    #8 0x55a2cecbd2f5 in main /home/julien/projects/openbabel/testjul/leak.cpp:5
    #9 0x7fb250897b16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)
    #10 0x55a2cecbd169 in _start (/home/julien/projects/openbabel/testjul/leak+0x1169)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0xa1093) 
==8994==ABORTING
`
