### ISSUE TITLE
Implicit valence for s-block elements

### ISSUE THREAD

**Issue by avcopan** [openbabel/openbabel#1874]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

In pybel, I am finding that the implicit valences of s-block elements are always zero.  According to the documentation, the implicit valence of an atom within a molecule is "The maximum number of connections expected for this molecule".  Given that, I would have expected that the alkali metals would have an implicit valence of 1 and alkaline earth metals would have an implicit valence of 2.
## Environment Information
Open Babel version: 2.4.1
Operating system and version: macOS High Sierra

## Expected Behavior
```
>>> import pybel
>>> mol = pybel.readstring('smi', '[F]')
>>> mol.atoms[0].implicitvalence
1
>>> mol = pybel.readstring('smi', '[O]')
>>> mol.atoms[0].implicitvalence
2
>>> mol = pybel.readstring('smi', '[N]')
>>> mol.atoms[0].implicitvalence
3
>>> mol = pybel.readstring('smi', '[C]')
>>> mol.atoms[0].implicitvalence
4
>>> mol = pybel.readstring('smi', '[B]')
>>> mol.atoms[0].implicitvalence
3
>>> mol = pybel.readstring('smi', '[Be]')
>>> mol.atoms[0].implicitvalence
2
>>> mol = pybel.readstring('smi', '[Li]')
>>> mol.atoms[0].implicitvalence
1
```

## Actual Behavior
```
>>> import pybel
>>> mol = pybel.readstring('smi', '[F]')
>>> mol.atoms[0].implicitvalence
1
>>> mol = pybel.readstring('smi', '[O]')
>>> mol.atoms[0].implicitvalence
2
>>> mol = pybel.readstring('smi', '[N]')
>>> mol.atoms[0].implicitvalence
3
>>> mol = pybel.readstring('smi', '[C]')
>>> mol.atoms[0].implicitvalence
4
>>> mol = pybel.readstring('smi', '[B]')
>>> mol.atoms[0].implicitvalence
3
>>> mol = pybel.readstring('smi', '[Be]')
>>> mol.atoms[0].implicitvalence
0
>>> mol = pybel.readstring('smi', '[Li]')
>>> mol.atoms[0].implicitvalence
0
```

**Comment by baoilleach** [comment]
Let me first answer the question you are trying to answer. With the current master (not 2.4.1):
```
import pybel
ob = pybel.ob
for element in [ob.Fluorine, ob.Oxygen, ob.Nitrogen, ob.Carbon, ob.Boron, ob.Beryllium, ob.Lithium]:
    print(ob.GetTypicalValence(element, 0, 0))
```
Output is:
```
>py test.py
1
2
3
4
3
2
1
```
Note that guessing the valence in this manner is imprecise - you can't always get it right when you start moving down the periodic table. If you are writing cheminformatics code relying on these values, you will run into problems at some point.

Regarding the GetImplicitValence function, let's just say that it's likely to be removed or somehow fixed/changed in the near future, as the way Open Babel handles implicit hydrogens has changed, and the name of the functions doesn't correspond to what they actually do.

I'm going to mark this bug as closed, but feel free to continue the conversation if anything is unclear.
