### ISSUE TITLE
AttributeError: module 'openbabel' has no attribute 'OBConformerSearch'

### ISSUE THREAD

**Issue by dudektria** [openbabel/openbabel#1876]
Hi,

I believe the standard Ubuntu package of OpenBabel is not [compiled](http://open-babel.readthedocs.io/en/latest/Installation/install.html#compiling-open-babel) with [Eigen](http://eigen.tuxfamily.org/) (`libeigen2-dev` in Ubuntu). This would make `OBConformerSearch` not available. Is this expected?

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Ubuntu 18.04.1 LTS (Kernel 4.15.0-29-generic x86_64)

## Steps to Reproduce

I get the following when trying to use `OBConformerSearch` from `pybel.ob`.

    % ipython
    Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
    Type 'copyright', 'credits' or 'license' for more information
    IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
    
    In [1]: import pybel
    
    In [2]: cs = pybel.ob.OBConformerSearch()
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-2-abbf488f9f28> in <module>()
    ----> 1 cs = pybel.ob.OBConformerSearch()
    
    AttributeError: module 'openbabel' has no attribute 'OBConformerSearch'
    
    In [3]: 

The same happens with Python 2.7.15rc1 and IPython 5.7.0.
I'm using `openbabel-2.4.1` as installed using `pip`.

Compiling OpenBabel with Eigen and using the resulting bindings results in no error.

**Comment by baoilleach** [comment]
That's a pity, but we have no control over any what any Linux distribution does, or does not, do when they compile Open Babel. I would encourage you to file a bug with Ubuntu.

(I'm marking as closed but feel free to reopen if necessary.)

**Comment by dudektria** [comment]
Thanks for the suggestion, I filed a question at [lauchpad](https://answers.launchpad.net/ubuntu/+source/openbabel/+question/671261) about that.
