### ISSUE TITLE
Black and white renderings using pybel 

### ISSUE THREAD

**Issue by psychemedia** [openbabel/openbabel#1879]
Is there a way of disabling the use of colour when rendering molecules so that I can produce black and white outputs?

e.g. the following both produce coloured outputs when previewed in a Jupyter notebook:

```python
import pybel
mol = pybel.readstring( "smi","O" )
mol
```

and

```python
from IPython.display import display, SVG
display(SVG(mol.write("svg")))
```

Where should I be looking for docs about display parameters and different output / output style information?

**Comment by fredrikw** [comment]
Hi,

The SVG format has an -xu option so the following should work:

import pybel
from IPython.display import display, SVG
mol = pybel.readstring( "smi","O" )
conv = pybel.ob.OBConversion()
conv.SetOutFormat("svg")
conv.SetOptions('u', conv.OUTOPTIONS)
display(SVG(conv.WriteString(mol.OBMol)))

Kind regards,
Fredrik

**Comment by psychemedia** [comment]
Works fine, thanks...

e.g. something like:

```python
import pybel
from IPython.display import display, SVG

def smilesSVG(smi, addH=False, bw=False):
   ''' Render molecule structure from SMILES string as SVG. '''

    mol = pybel.readstring( "smi",smi )
    if addH: mol.addh()
    conv = pybel.ob.OBConversion()
    conv.SetOutFormat("svg")
    #Optonally, set black and white output
    #The openbabel SVG export formatter has an -xu option which we can pass
    if bw:
        conv.SetOptions('u', conv.OUTOPTIONS)
    display(SVG(conv.WriteString(mol.OBMol)))
```

I note lots more possible [options for SVG_2D_depiction](https://openbabel.org/docs/dev/FileFormats/SVG_2D_depiction.html). Would it make sense to have a generalisation of the above function that accepts a generic list of command line options and sets them on `.WriteString()`?

**Comment by baoilleach** [comment]
Fyi, mol.write also has an opt param to specify write options.
