### ISSUE TITLE
2D depict generates weird result for fragmented SMILES

### ISSUE THREAD

**Issue by sxhexe** [openbabel/openbabel#1889]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: both master/2.4.90 and 2.4.1
Operating system and version: Ubuntu on windows

## Expected Behavior

![image](https://user-images.githubusercontent.com/29393696/45576948-6e19ef80-b82e-11e8-9793-dc80f6fb3406.png)

## Actual Behavior

![1](https://user-images.githubusercontent.com/29393696/45577003-bcc78980-b82e-11e8-81b7-7ebd71e8b3ad.png)

## Steps to Reproduce

$ obabel test.smi -Otest.png

test.smi:
[H+].CC[O-].CC[O-]

I uploaded more examples here. I was trying to find a general rule about when the bug would show up but couldn't find one. It seems super random. 
[pics.zip](https://github.com/openbabel/openbabel/files/2385189/pics.zip)

**Comment by marcabrus** [comment]
I've experienxed the same issue, but with every kind of molecule, but only in 2.4.9

**Comment by sxhexe** [comment]
> I've experienxed the same issue, but with every kind of molecule, but only in 2.4.9

Have you tried other versions? Is there a version that this behaves correctly?
