### ISSUE TITLE
Help with Install Please!

### ISSUE THREAD

**Issue by christiesandall** [openbabel/openbabel#1897]
Hi there,

I am very new to all of this, and am looking for help with the install.  I followed the instructions on the page below:

http://openbabel.org/wiki/Install_(source_code)

specifically the section on Installing globally with root access.  I also installed a GNU compiler according to these instructions: https://wiki.helsinki.fi/display/HUGG/GNU+compiler+install+on+Mac+OS+X and cmake prior to running these commands.

I used the following commands:

tar zxvf openbabel-2.4.1.tar.gz
mv openbabel-2.4.1 ob-src
mkdir ob-build
cd ob-build
cmake ../ob-src 2>&1 | tee cmake.out
sudo make install

Everything seemed to install, but I am looking to run the optimize plugin in pymol, and I got an error there: "Optimize plug-in needs openbabel to be installed in your system, please follow the instructions at
http://openbabel.org/wiki/Get_Open_Babel”.  I realized I still did not have it completely installed, so I tried the following command:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
which “ran” with no errors.  I now have several files and folders in the following directory:
/usr/local/lib
They are:
pkgconfig (FOLDER)

libinchi.dylib

libinchi.0.4.1.dylib

libinchi.0.dylib

openbabel (FOLDER)

libopenbabel.dylib

libopenbabel.5.0.0.dylib

libopenbabel.5.dylib

cmake (FOLDER)

I believe open babel is still not completely installed because I did not compile the language bindings at the time of install.  I now have installed python (2.7.10), but am looking for how I can finish this install.  As I said above, I’m looking to use the optimize plugin in pymol.  I’m working on a Mac (running MacOS Mojave version 10.14).  Would very much appreciate any help.  Thanks very much!

**Comment by sunoru** [comment]
See http://openbabel.org/docs/current/Installation/install.html#compile-bindings and try to recompile with python binding?

**Comment by ghutchis** [comment]
I would say that for most people, installing Anaconda and then `conda install -c conda-forge openbabel` is the best solution to get `obabel`, python and associated bindings.
