### ISSUE TITLE
Corrupted PNG images

### ISSUE THREAD

**Issue by andersx** [openbabel/openbabel#1900]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
**Open Babel version:** `Open Babel 2.4.90 -- Oct 15 2018 -- 13:24:25`
This is the latest master from GitHub cloned and compiled, passes all tests.
**Operating system and version:** Ubuntu 18.04

    $ uname -a
    Linux nuke 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior

Dear Open Babel,  I am having troubles with the most recent version from Github. I am trying to convert smiles to 2d PNG files with the command:

    obabel -:c1ccccc1 -o test.png

With my old version of Open Babel, `Open Babel 2.4.1 -- Feb  2 2017 -- 11:49:37`
I get a correctly looking png file:

Inline-style: 
![alt text2](https://i.imgur.com/WpUcWKE.png "Old Open Babel")

## Actual Behavior

With the most recent Open Babel, I get a corrupted image with the exact same input line
![alt tex12](https://i.imgur.com/OM9yIqx.png "New Open Babel")

## Steps to Reproduce

Running the following command

    obabel -:c1ccccc1 -o test.png

**Comment by andersx** [comment]
I am not sure if this closed issue is related, but the PNG file in the bug report looks like it has a similar error.
https://github.com/openbabel/openbabel/issues/1889

**Comment by fredrikw** [comment]
This regression was caused by #1852
Running `obabel -:c1ccccc1 -omol` before the commit that mergers that PR gives:
```

 OpenBabel10161813072D

  6  6  0  0  0  0  0  0  0  0999 V2000
   -0.8660   -0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7321   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7321    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8660    1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0000    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  6  2  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
M  END
```
while after the commit it gives:
```

 OpenBabel10161813102D

  6  6  0  0  0  0  0  0  0  0999 V2000
   -0.9710    0.3495    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9710   -0.6309    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8201   -1.1212    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6692   -0.6309    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6692    0.3495    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  6  2  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
M  END
```

The problem seems to be that the final atom doesn't get it's coordinates updated.

I don't know the full history for the changes made there, does @serval2412 have any input?

**Comment by serval2412** [comment]
Sorry, I can't help here. Don't hesitate to revert the other patch since I'm not an expert at all.
