### ISSUE TITLE
Bug in OBMol::CopyConformer 

### ISSUE THREAD

**Issue by tconvard** [openbabel/openbabel#1907]
- [ X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:Open Babel 2.4.1 -- Apr  4 2018 -- 09:45:46
Operating system and version:ubuntu 16.04 LTS

## Expected Behavior

The current API documentation gives the following details for the function of interest :

void CopyConformer  (  double *  c,int  nconf  )   

Copy the conformer nconf into the array c
Warning: Does no checking to see if c is large enough 

## Actual Behavior

in fact I saw that the opposite was done, the content of the array c is copied into the nconf

the code is
void OBMol::CopyConformer(double *c,int idx)
  {
    //    obAssert(!_vconf.empty() && (unsigned)idx < _vconf.size());
    memcpy((char*)_vconf[idx],(char*)c,sizeof(double)*3*NumAtoms());
  }

**Comment by baoilleach** [comment]
Thanks for reporting. I guess no-one has ever used this function.
