### ISSUE TITLE
GetGenericValueDef bad behavior Ubuntu 18.04

### ISSUE THREAD

**Issue by orex** [openbabel/openbabel#1913]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: any
Operating system and version: Ubuntu 18.04

## Expected Behavior

I would like to get 1.0 when I'm calling the function
`dynamic_cast<OBPairFloatingPoint *>((OBGenericData*)NULL)->GetGenericValueDef(1.0)`
but I get segmentation fail in Ubuntu 18.04 (master branch compiled with standard g++ compiler from Ubuntu repository. See https://stackoverflow.com/questions/2474018/when-does-invoking-a-member-function-on-a-null-instance-result-in-undefined-behav

Simple test case (fails in Ubuntu 18.04 `g++ -O3 main.cpp; ./a.out`)
```
// Example program
#include <iostream>
#include <string>

class A {
public:    
float f;
inline float foo(const float & def) {
  if( this == NULL) {
    return def;
  }
  else return f; 
}
};

int main()
{
  A * d = NULL;  
  std::cout << d->foo(1.0) << std::endl;
}
```

I think, that it is much better to have the function like this
```
static ValueT GetValue(OBGenericData * obd)
{ 
  OBPairTemplate<ValueT> * pd = dynamic_cast<OBPairTemplate<ValueT> *>(obd);
  assert( pd != NULL);
  return pd->GetGenericValue();
}
static ValueT GetValue(OBGenericData * obd, const ValueT &def_val)
{ 
  OBPairTemplate<ValueT> * pd = dynamic_cast<OBPairTemplate<ValueT> *>(obd);
  return (pd == NULL) ? def_val : pd->GetGenericValue();
}
```
Using the static function gives much nicer call.
`float f = OBPairFloatingPoint::GetValue(a.getData("something"), 1.0);`
instead of
`float f = dynamic_cast<OBPairFloatingPoint *>(a->GetData("something"))->GetGenericValueDef(1.0);`

**Comment by baoilleach** [comment]
For some time, I have intended to remove GetGenericValueDef() from the Open Babel API. This is a convenience function that should never have been added as the user can simply handle this at their end with a function in their own code.

**Comment by orex** [comment]
Your are right! A user can handle the functionality by himself, that's what I did in my own code to fix the bug. From another side, I think that convenience is important part of any libraries API. Users used to have such functionality: dictionaries in python, boost property tree etc. all of them have get(<default>) methods in API. I hope, that the solution I've proposed can be safe and convenient solution for users of your package (feedback is very welcome).

**Comment by baoilleach** [comment]
API functions that enable users to do more cheminformatics are the core of what OB is all about. The generic data  classes and functions are present to enable formats to return data to the user. They are not intended as for general-purpose data storage; that's what the STL is for, or third-party libraries such as boost.
