### ISSUE TITLE
Eigen3 not found and Eigen3_DIR is ignored

### ISSUE THREAD

**Issue by yesint** [openbabel/openbabel#1918]
- [x ] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: latest git
Operating system and version: linux

## Expected Behavior
OpenBabel should search for Eigen using Eigen3_DIR variable, which is used in most of other software to locate Eigen.

## Actual Behavior
The value of Eigen3_DIR variable is ignored and Eigen3 is never found if it is installed into non-standard location.

## Steps to Reproduce
In my system Eigen3 is installed in ~/programs/Eigen/. Here is the output of cmake for OpenBabel:
```

$ cmake ../openbabel -DCMAKE_INSTALL_PREFIX=~/programs/openbabel -DWITH_JSON=OFF -DEigen3_DIR=~/programs/Eigen/

...
...
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
-- Could NOT find Eigen2 (missing: EIGEN2_INCLUDE_DIR EIGEN2_VERSION_OK) (Required is at least version "2.0.0")
...
...
CMake Warning:
  Manually-specified variables were not used by the project:

    Eigen3_DIR
```

**Comment by baoilleach** [comment]
This isn't a bug - the correct variable names are documented. You need to specify the location with EIGEN3_INCLUDE_DIR.
