### ISSUE TITLE
OBIsomorphismMapper finds incorrect isomorphisms

### ISSUE THREAD

**Issue by n-yoshikawa** [openbabel/openbabel#1929]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 and current latest (`cfd7846`)
Operating system and version: Ubuntu 18.04

## Expected Behavior
The atomic numbers of corresponding atoms mapped by OBIsomorphismMapper match.
## Actual Behavior
They do not match.

## Steps to Reproduce
1. Run this code. (`molA.sdf` and `molB.sdf` are [in this gist](https://gist.github.com/n-yoshikawa/15e05728df7b4eb778a22ef69c46e74f). They have different structure, but they represent the same molecule i.e. they have identical InChI.)

```python
import pybel
ob = pybel.ob

molA = pybel.readfile("sdf", "molA.sdf").next()
molB = pybel.readfile("sdf", "molB.sdf").next()

print(molA.write("inchi"))
print(molB.write("inchi"))

# https://baoilleach.blogspot.com/2010/11/automorphisms-isomorphisms-symmetry.html
query = ob.CompileMoleculeQuery(molA.OBMol)
mapper = ob.OBIsomorphismMapper.GetInstance(query)
isomorph = ob.vpairUIntUInt()
mapper.MapFirst(molB.OBMol, isomorph)

# Get mapping of atom index
idxMap = dict(isomorph)

for atomA in ob.OBMolAtomIter(molA.OBMol):
    idxA = atomA.GetIdx()
    # OBMol is 1-indexed while the mapper is 0-indexed
    idxB = idxMap[idxA - 1] + 1
    atomB = molB.OBMol.GetAtom(idxB)
    print(atomA.GetAtomicNum(), atomB.GetAtomicNum())
```
2. The result is:
```
InChI=1S/C20H19NO2/c1-13-19(14(2)23-21-13)16-9-8-15-10-11-20(22,18(15)12-16)17-6-4-3-5-7-17/h3-9,12,22H,10-11H2,1-2H3/t20-/m1/s1

InChI=1S/C20H19NO2/c1-13-19(14(2)23-21-13)16-9-8-15-10-11-20(22,18(15)12-16)17-6-4-3-5-7-17/h3-9,12,22H,10-11H2,1-2H3/t20-/m1/s1

(6, 6)
(6, 6)
(8, 7)
(7, 8)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(8, 8)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(6, 6)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
```

All atomic numbers should be the same in all lines, but they are different in the 3rd and 4th line.

The 3D images of two molecules are as follows:
![mola](https://user-images.githubusercontent.com/29328746/53170315-31df8c00-3623-11e9-8f9e-848d41277525.png)
![molb](https://user-images.githubusercontent.com/29328746/53170325-36a44000-3623-11e9-8e83-e36e7e44d2d5.png)
N (Atomic number 7, shown in blue) and O (Atomic number 8, shown in red) in a ring cause this problem.

I think this behavior is a bug, but if this is the expected behavior or my misunderstanding, please tell me.

**Comment by ghutchis** [comment]
Oh, I wonder if it's an issue of breaking the tie when it goes around that ring - one case goes C->C(CH3)->O and the other goes C->C(CH3)->N

**Comment by n-yoshikawa** [comment]
Thank you for your comment. I thought two molecular graphs are isomorphic only when all corresponding atoms are the same, so they are not tie (either of two is not isomorphic).

After some googling, I found out that [molecular graphs](https://en.wikipedia.org/wiki/Molecular_graph) are classified as a labeled graph and there are two definitions for [isomorphism of labeled graphs](https://en.wikipedia.org/wiki/Graph_isomorphism#Isomorphism_of_labeled_graphs). I assumed the first definition (both edge-preserving and label-preserving) is used, but it seems to be the second definition (only edge-preserving) is adopted in the current implementation. Maybe we should update documentation to avoid future misunderstanding.

**Comment by baoilleach** [comment]
No - it's a bug, and looks pretty serious. The isomorphism should be of the labeled graph. Here's a simpler example:

```
import pybel
ob = pybel.ob

smi = "Cc1onc(C)c1"
mol = pybel.readstring("smi", smi)

query = ob.CompileMoleculeQuery(mol.OBMol)
mapper = ob.OBIsomorphismMapper.GetInstance(query)
isomorph = ob.vpairUIntUInt()
mapper.MapFirst(mol.OBMol, isomorph)
data = [isomorph[i] for i in range(len(isomorph))]
print(data)
```

**Comment by baoilleach** [comment]
I'll keep looking into it. In the meanwhile, a workaround is to canonically reorder (or just label) the atoms in both molecules, and then use FindAutomorphisms on one of them to compute all of the possible mappings. This appears to work correctly, at least for this molecule.

**Comment by n-yoshikawa** [comment]
I guess the main cause of this behavior is that [bond match is evaluated by OBQueryBond::Matches()](https://github.com/openbabel/openbabel/blob/cfd78460ef6476afebcb1f0b08323901f0202841/src/isomorphism.cpp#L139) and [it checks if both bonds are aromatic and compares the bond orders otherwise](http://openbabel.org/dev-api/classOpenBabel_1_1OBQueryBond.shtml#aeae2e5cc4cded6921003fb5f3d7962d8) i.e. atom types do not affect bond match.

**Comment by baoilleach** [comment]
@johnmay has taken a look and come to a similar conclusion. It's missing the atom test, probably as the first line of matchCandidate. More problematic is that the built-in test is fairly simplistic and is not strictly speaking testing isomorphism exactly. Still, it'll be better than the current. I'll make the change and test it against @johnmay's VF2.

**Comment by johnmay** [comment]
Done, I initially wrote an automorphism but that seemed fine so replicated exactly Noel's case and confirmed if failed without the change to ``ismorphism.cpp``.

**Comment by baoilleach** [comment]
Maybe we should coordinate better. :-)

**Comment by johnmay** [comment]
Ah well
