### ISSUE TITLE
SVG "ball-and-stick" depiction

### ISSUE THREAD

**Issue by ghutchis** [openbabel/openbabel#193]
The current SVG code performs a 2D layout of a structure to produce a chemical diagram.

For some compounds, a better representation would be a ball-and-stick projection of the 3D coordinates, e.g.:
http://plindenbaum.blogspot.com/2009/06/fun-with-svg-ncbipubchemxslt-svg.html

![](http://40.media.tumblr.com/NngfN9gsDobdle0pIyy8oIw3o1_400.png)

**Comment by ghutchis** [comment]
There is a bounty for adding this feature:
https://www.bountysource.com/issues/22362687-svg-ball-and-stick-depiction

**Comment by jnavila** [comment]
Hi,

You are a developer of the project. What is the purpose of this bounty?

**Comment by ghutchis** [comment]
I don't have time (or the expertise) to code this in a reasonable period of time. I would like the feature for a related project and I'm willing to offer the bounty. If you have the expertise, feel free to grab the bounty. :-)

**Comment by ghutchis** [comment]
I'm willing to give pointers as well. I think my coding is better spent on the chemistry-oriented features rather than trying to figure out SVG..

**Comment by jnavila** [comment]
OK. I have half a day to spend on this, and I just wanted to be sure that it would be of some use. Might be fun too...

**Comment by ghutchis** [comment]
Some useful cases might be in:
src/xyzformat.cpp:WriteMolecule()
src/povrayformat.cpp

etab.GetRGB(int atomicnum)

If you have some time, I think it would be a great feature. I'm hoping to use it at http://pqr.pitt.edu/ for search results (i.e., rather than 20 interactive JavaScripts panels).

**Comment by jnavila** [comment]
Do you think of any method to get a good idea of the radius of the circles depending on the atomic number ? Is there a "standard" on ball and stick representation ?

**Comment by ghutchis** [comment]
# the most useful "bonding radius"
etab.GetCovalentRad(atomicnum);

# the "full" van der Waals radius
etab.GetVdwRad(atomicnum);

I think the "standard" would be the covalent radius, although some people scale the VdW radius down. I'd  set that as a parameter and try a few scaling factors to see what looks the best.

**Comment by ghutchis** [comment]
One other nice trick would be to find the best fit plane of the molecule given the XYZ coordinates and then project them via a "camera" perspective, e.g using Eigen:

        Eigen::Hyperplane<double, 3> planeCoeffs;
        Eigen::fitHyperplane(numAtoms(), atomPositions, &planeCoeffs);
        delete[] atomPositions;
        d->normalVector = planeCoeffs.normal();
