### ISSUE TITLE
Appveyor Build fail for Windows

### ISSUE THREAD

**Issue by njzjz** [openbabel/openbabel#1930]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

I submitted OpenBabel to conda-forge (conda-forge/staged-recipes#7754). The build passed on Linux, but Appveyor build failed on Windows. [Here is the whole log.](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22373261)

## Environment Information
Open Babel version: 2.4.1
Operating system and version: win-64, py27, compiler=vs2008, see the log for details

## Expected Behavior
The build passes.

## Actual Behavior
Too many errors. See [the log](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22373261) for details.

## Steps to Reproduce
[The conda recipe is here](https://github.com/conda-forge/staged-recipes/pull/7754/files).

**Comment by cowsandmilk** [comment]
It appears the root error is:

```
1>c:\bld\openbabel_1550159794694\_h_env\library\include\eigen3\eigen\src/Core/arch/SSE/PacketMath.h(811) : fatal error C1001: An internal error has occurred in the compiler.
8701>(compiler file 'msc1.cpp', line 1411)
8711> To work around this problem, try simplifying or changing the program near the locations listed above.
8721>Please choose the Technical Support command on the Visual C++ 
8731> Help menu, or open the Technical Support help file for more information
8741>Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\x86_amd64\cl.exe.  You will be prompted to send an error report to Microsoft later.
```

I'm not sure much can be done when the error message is that the compiler cannot handle the file.

The best advice is probably to just have it target python 3.5-3.7 and drop python 2.7 support, which will cause condo-forge to use Visual Studio 14.0 (2017) instead of Visual Studio 9.0 (2008 aka over a decade old).

**Comment by baoilleach** [comment]
Or try EIGEN2 instead. I think both are supported, but the CMAKE
environment variable is differeny.

**Comment by baoilleach** [comment]
According to the Eigen page, you need Eigen 3.1 for MSVC 2008. Newer versions dropped support,

**Comment by njzjz** [comment]
There is no version 3.1 in the conda-forge channel, so I just skip it.

**Comment by njzjz** [comment]
The issue has been fixed. The last issue for conda-forge to resolve is #1932.
