### ISSUE TITLE
segmentation fault after compile

### ISSUE THREAD

**Issue by SamKChang** [openbabel/openbabel#194]
I cloned the master branch to Ubuntu 12.04/32bit and 14.04/64bit. Both of them gives segmentation fault when I specified input format. It works fine with "obabel -V", it prints the version and compile time. I tried the patch from Matt at https://gist.github.com/mcs07/7264376 but did not work either. I could not fine the reason for this because there are too many changes from the source on Ubuntu repository: openbabel-2.3.2+dfsg.

**Comment by cowsandmilk** [comment]
Can you provide an example command that segfaults?

**Comment by baoilleach** [comment]
FWIW, I use the master branch on Ubuntu 14.04 64-bit all the time.

**Comment by SamKChang** [comment]
OMG... I embarrassed myself! segfaults is because I did not use "make install". Without root access, "make install" gives an error at the final step to link to /usr/local/bin. But the binary at openbabel/build/bin works fine.
