### ISSUE TITLE
elements.h is missing from the latest release

### ISSUE THREAD

**Issue by mboisson** [openbabel/openbabel#1941]
- [ X ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: irrelevant

## Expected Behavior
elements.h is missing from the latest release. Are you guys due for a new release ?

**Comment by baoilleach** [comment]
Not a bug. elements.h is new since 2.4.1.

**Comment by mboisson** [comment]
What is the ETA for a new release that would include it ?
