### ISSUE TITLE
DLFCN problem: Fix bug# 368 script not working

### ISSUE THREAD

**Issue by lalehan** [openbabel/openbabel#1947]
Hello, I downloaded the script which is the[ Fix bug# 368](https://github.com/openbabel/openbabel/commit/92f4646d5cbf8d3291c66f9bff7ae61b6d535763) and replaced it with the old CMakeLists.txt, however the same problem persists:
ModuleNotFoundError: No module named 'DLFCN'

Could you please help?

**Comment by baoilleach** [comment]
Can you check out the latest code from Github (https://github.com/openbabel/openbabel/archive/master.zip), and try that. If that doesn't work, reopen this bug and let us know. In the meanwhile, I'm going to mark this as closed.

**Comment by lalehan** [comment]
Thank you for the code. I replaced it and it didn't work either. I'm afraid for the command I execute, system doesn't search in the folder where CMakeLists.txt exists, hence the persistence of the problem. To make it more clear, here is the output:
```
File "/home/lale/anaconda3/lib/python3.7/site-packages/openbabel.py", line 6, in <module>
    import DLFCN as dl
ModuleNotFoundError: No module named 'DLFCN'

```
To overcome the problem arising from this Python library bindings, should I install again (using the code you provided) all over or go change the py script?

**Comment by baoilleach** [comment]
Ok - let's take if from the top. Can you describe exactly the steps you are doing after downloading the zip file linked above?

**Comment by lalehan** [comment]
Alright, hope my story won't be long.
After downloading the zip, I only unzipped it, found the CMakeLists.txt file, and replaced it with the one that was in the openbabel-2.3.1 directory (which I built yesterday). Then I ran the program (Autodock-covalent) which uses pybel & openbabel. The output you see is right after I ran this program.

Originally, I installed the openbabel-2.3.1, installed the python bindings, ran setup.py in the openbabel-2.3.1/python directory and also installed Eigen2 and copied its directory to /usr/include. Everything seemed fine until I bumped into this DLFCN problem. That's when I saw the new CMakeLists.txt on the Github page and only replaced it with the one that is already in openbabel-2.3.1 directory. At this stage, I did not install anything new. I ran the program again, and the same error happened. When I reported this, you provided the openbabel-master package and again didn't install anything, just replaced the CmakeLists.txt file in that package with the one in the openbabel-2.3.1 folder.

Maybe I should install the openbabel with the new package you provided all over again?

Thanks!

**Comment by ghutchis** [comment]
Yes, absolutely. The Open Babel 2.3.1 is ancient. You're not going to be able to mix and match CMakeLists and expect they'll just work - changes to the build system happen as part of development.

**Comment by lalehan** [comment]
Thank you! That's what I thought, but the lazy side of me was looking for an easier trick :) 
Anyway, do directions to install [here](http://openbabel.org/docs/dev/Installation/install.html) exactly apply to the new package as well?

**Comment by trinhsk** [comment]
hi i am getting this error message when doing a docker image build. What is the resolution? It seems you have to patch the code where it tries to import DLFCN to import os as dl instead. How do I do apply that patch?
