### ISSUE TITLE
obrotate matches all dihedrals with SMARTS but only sets angle of last one

### ISSUE THREAD

**Issue by khuston** [openbabel/openbabel#196]
The obrotate program, given a SMARTS string and an input structure, will match all the dihedrals, but will only rotate the last one in a molecule. It looks like the functionality to rotate all matching dihedrals was almost added, but instead there's just a commented-out call to SetTorsion in the for loop over all matches:

```
// if (changeAll)
//  mol.SetTorsion(a1, a2, a3, a4, angle * DEG_TO_RAD); 
```

It seems the only thing missing is the acquisition of bool changeAll from the command line arguments, and adding the condition that changeAll == False to the warning that "Only last one [dihedral] will be rotated." Then the user should be able to change all torsions matching a SMILES pattern and not just the last instance in a molecule.

**Comment by serval2412** [comment]
I submitted a patch to review here:
https://github.com/openbabel/openbabel/pull/1835

**Comment by serval2412** [comment]
Just for information, the patch has been pushed  today.
So I suppose we can close this tracker.
