### ISSUE TITLE
flood of errors (eg OBMolRingIter is not a member of OpenBabel) with current master

### ISSUE THREAD

**Issue by balducci** [openbabel/openbabel#1962]
hello

building from git on linux with gcc:

     ----8<----
     install:651> uname -sr
     Linux 5.0.7
     install:652> gcc --version
     gcc (GCC) 8.3.0
     Copyright (C) 2018 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     ---->8----

With current master (6aff822f8d37074eebcd1901628623ea1b97f6ae) I get a
flood of errors like this:

     ----8<----
     scripts/ruby/openbabel-ruby.cpp:49397 error: 'OBMolRingIter' is not a member of 'OpenBabel'
     ---->8----

(build log is too big (~9.8MB) to attach)

My previous build (c28c7dc86db1f415c0a60abeb94497d49161ff8d) was
absolutely fine, as always.

Is there any problem or am I missing something?

thanks a lot
ciao
-g

**Comment by baoilleach** [comment]
I'll sort it out asap.

**Comment by balducci** [comment]
> I'll sort it out asap.

thanks for the quick reply

We can arrange to send you the build log, if that can be of any help

just let me know, in case

ciao
gabriele

**Comment by baoilleach** [comment]
It's ok. I know what it is. I need to add some headers into the bindings after my recent work merged yesterday.

**Comment by baoilleach** [comment]
Could you let me know if this is fixed?

**Comment by balducci** [comment]
> Could you let me know if this is fixed?

yes, of course

it will be within today

thanks a lot
ciao
-g

**Comment by balducci** [comment]
> Could you let me know if this is fixed?

just built and installed master and everything is fine

thanks a lot
ciao
-g
