### ISSUE TITLE
protobuf clash with tensorflow

### ISSUE THREAD

**Issue by adityanandy** [openbabel/openbabel#1983]
- [ x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Ubuntu 19.04

## Expected Behavior

Importing openbabel and tensorflow (version 1.13.0) in the same script causes import issues, due to the protobuf library. Tensorflow (1.13.0) depends on protobuf library 3.7.1. Obabel looks for 3.6.1, and does not work with 3.7.1. Thus, to simultaneously use obabel and tensorflow, the tensorflow version must be downgraded to 1.12.0.

## Actual Behavior

Conda installed openbabel and tensorflow (on ubuntu). Just used a python script where I tried "import openbabel" and "import tensorflow as tf," in various orders (i.e. openbabel first, then tf, tf first, then openbabel, etc.). The issue of the protobuf library comes up when the import is done in certain orders. Downgrading tf to 1.12.0 solves the issue, but just wanted to note this here in case upgrading dependency of the protobuf library to 3.7.1 is an easy fix.

**Comment by ghutchis** [comment]
I don't know which package you installed, but Open Babel does not depend on protobuf.

Which conda package did you install?

**Comment by baoilleach** [comment]
Could be the dl flags issue.

**Comment by adityanandy** [comment]
Hi there,
I Installed openbabel via conda with:
conda install -c openbabel openbabel 

In a conda environment (conda 2, python 2.7), where only tensorflow (1.13.0, installed with conda install tensorflow) and openbabel (2.4.1) are installed, import order begins to matter. If I import openbabel, and then tensorflow, I get this error. If I import tensorflow, then openbabel, then the error goes away.

Let me know if more information is needed... thanks for your help and for such a great tool!
![Screenshot from 2019-05-09 20-18-18](https://user-images.githubusercontent.com/7635801/57494561-db840000-7297-11e9-86b4-a796d4bc1739.png)

**Comment by baoilleach** [comment]
This should be fixed in the current development version but in the meanwhile, this workaround should help. Before importing openbabel, get the value of dlopenflags and then reset it afterwards:
```
flags = sys.getdlopenflags()
import openbabel
sys.setdlopenflags(flags)
```
