### ISSUE TITLE
Missed ctime header in fpsformat.cpp

### ISSUE THREAD

**Issue by orex** [openbabel/openbabel#1990]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: master
Operating system and version: MinGW windows crosscompiling 

## Actual Behavior

 openbabel/src/formats/fpsformat.cpp: Missed header
`#include <ctime>`

**Comment by ghutchis** [comment]
thanks for the bug report - I'm at a conference right now. if you can make a quick pull request, I'd be happy to merge ASAP.

**Comment by ghutchis** [comment]
Thanks for the fix.
