### ISSUE TITLE
ob.OBConversion().ReadString behaves inconsistenly

### ISSUE THREAD

**Issue by MarcoGorelli** [openbabel/openbabel#1994]
- [X ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.3.1
Operating system and version: Ubuntu 18.04.1

## Expected Behavior

Reading an `.xyz` file should not affect the behaviour of `ReadString`.

## Actual Behavior

```
import openbabel as ob


xyz_string = (
    "3\n\nO -0.0343604951 0.9775395708 0.0076015923\n"
    "H 0.0647664923 0.0205721989 0.0015346341\n"
    "H 0.8717903737 1.3007924048 0.0006931336"
)
```
Then, if I run this
```
mol = ob.OBMol()
ob.OBConversion().ReadString(mol, xyz_string)
```
it returns `False`.

If I run this
```
with open("temp.xyz", "w") as f:
    f.write(xyz_string)

mol = ob.OBMol()
ob.OBConversion().ReadFile(mol, "temp.xyz")
```
it returns True.

But what really puzzles me is that if I run
```
ob_conversion = ob.OBConversion()

with open("temp.xyz", "w") as f:
    f.write(xyz_string)

mol = ob.OBMol()
ob_conversion.ReadFile(mol, "temp.xyz")
ob_conversion.ReadString(mol, xyz_string)
```
then this returns `True` now!

**Comment by baoilleach** [comment]
You need to set the input format. ReadFile is doing this for you.

**Comment by MarcoGorelli** [comment]
Got it, thanks!
