### ISSUE TITLE
python2.7 import openbabel problem

### ISSUE THREAD

**Issue by orzrunningsnail** [openbabel/openbabel#2006]
Hi! When I ues openbabel 2.4.1 and python2.7(32) in my win10. I install the python API followed the 
org. But, when I import openbabel, it notes: ImportError: DLL load failed:...。I have tried other versions e.g. 2.3.1. But there is a same problem, when  I import openbabel. I search the season on the internet, but no result. So, I ask for you help!
 
![image](https://user-images.githubusercontent.com/35757143/61582233-af6be180-ab5a-11e9-920c-fe36c78836bc.png)
![image](https://user-images.githubusercontent.com/35757143/61582247-d4f8eb00-ab5a-11e9-9475-f3a04027d037.png)

![image](https://user-images.githubusercontent.com/35757143/61582250-e4783400-ab5a-11e9-88d3-0159f20b56bf.png)

**Comment by ghutchis** [comment]
I'd highly recommend installing python through Anaconda, in which case you can install Open Babel through `conda install -c conda-forge openbabel`
