### ISSUE TITLE
gamess output translation to sdf or smi fails with segfault

### ISSUE THREAD

**Issue by bennion1** [openbabel/openbabel#2020]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by bennion1** [comment]
[bennion1@czvnc2 ATBJOBS]$ /usr/gapps/bbs/TOSS-3/bin/obabel -igamess 317358/1/qm.out -osdf -O test
Segmentation fault (core dumped)
Setting errorlevel doesn’t seem to produce any extra data.
[qm.txt](https://github.com/openbabel/openbabel/files/3561172/qm.txt)

**Comment by bennion1** [comment]
Was told to leave a gamess output file here.  gamess input files are not parseable either.

**Comment by ghutchis** [comment]
I don't know what version this was, but it works with v3.1.
