### ISSUE TITLE
load fingerprint via OBDotNet

### ISSUE THREAD

**Issue by drjahu** [openbabel/openbabel#2023]
Dear all,
I seek support for an issue where I try to programmaticaly load an fingerprint which is generated in the OpenBabel GUI and saved to a text file.

The fingerprint looks like that:
```
>   1535 bits set 
f78f653f f788fbd1 f788fbd1 f788fbd1 f483f4e7 ef8b7e2f 
e9e5be3f e9e5be3f e9e5be3f e2d45009 dfe49bdf dfe49bdf 
d9934563 d6e3f7a2 d6e0861f d6e0861f c7a9894e c691f1d5 
c5a51b2f c38b3152 c38b3152 c18d73f0 ba1039b8 ba1039b8 
b6c804e7 b1ce8ba1 acaf0910 a795d505 9e35e385 9933b3d4 
9630d053 8ded7546 7a817362 76258d45 72c49066 6ff1d590 
6cdf4289 6cdf4289 6cdf4289 6cdf4289 6cdf4289 6cdf4289 
6cdf4289 6cdf4289 6ab48711 69a2560a 69a2560a 69a2560a 
69a2560a 5faf488d 5faf488d 5faf488d 572f25d6 565a47ac 
530075b3 4e8b69b6 4a7b5d42 4a7b5d42 4a7b5d42 4a7b5d42 
468e2b3d 45b91d6a 45b91d6a 45b91d6a 45b91d6a 44a4d88c 
439d6fa4 4236ab98 41f91858 3e57602f 3cd9ba8b 3cd9ba8b 
3cd9ba8b 3cd9ba8b 3cd9ba8b 3b1ca892 3b1ca892 385eeb12 
372c3bca 3579bb6d 3579bb6d 2cf5676b 21451a2d 20afc63a 
20afc63a 1f92b832 1d8532eb 1c66c562 1170108b 1170108b 
1170108b 1170108b 1170108b 1170108b 1170108b 015cf378 
```
I try to read this fingerprint from the textfile using OBDotNet Version=0.5.0.0 in C#.
I have read the posting from [Andrew Dalke](http://www.dalkescientific.com/writings/diary/archive/2008/06/27/generating_fingerprints_with_openbabel.html)
and I lerned that I need to pay attention to BigEndian and LowEndian conversions. Essentially, I read each block as a hexadecimal formatted Unsigned integer, do a BigEndian to LowEndian conversion and add the result to a list of `unsigned Integers`. After that loop I reverse the `list<uint>` to generate the `OpenBabel.VectorUInt`. However, while some positions of the generated fingerprint are correct, many positions (without any pattern I can recognize) do not match to a `OpenBabel.VectorUInt` which is directly generated from the identical structure using the OpenBabel.Net library.

What am I doing wrong? Can somebody share some code on how to shuffle the bytes?

Thank you very much in advance!
Jan

- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: windows 10

**Comment by baoilleach** [comment]
If you start with a simple molecule, e.g. methane, or ethane, or water, you will only set a small number of bits. These should help you to work it out.

Note that for most applications the exact order of bits is not important (e.g. calculating Tanimoto similarities), so long as you don't mix bit vectors with different orders.

**Comment by drjahu** [comment]
Thanks for comment! Actually part of problems are described [different ECFP2 values for the same molecule](https://github.com/openbabel/openbabel/issues/1557#issue-218369553) here. Thats the actual reason why I could not recreate a fingerprint.
I also tested different BigEndian to LowEndian conversions.

For whom it may interest, I came to to this code:

`private void LoadFingerprint()
        {
            Func<uint, uint> Big2Little = (uint x) =>
            {
                byte[] bytes = BitConverter.GetBytes(x);
                Array.Reverse(bytes, 0, bytes.Length);
                return BitConverter.ToUInt32(bytes, 0);
            };
            Func<uint, uint> Big2Little2 = (uint x) =>
            {
                byte[] bytes = BitConverter.GetBytes(x);
                return (uint)((bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3]);
            };
            Func<uint, uint> Big2Little3 = (uint x) =>
            {
                return (x & 0x000000FF) << 24 |
                       (x & 0x0000FF00) << 8 |
                       (x & 0x00FF0000) >> 8 |
                       (x & 0xFF000000) >> 24;
            };

            bool isLittleEndian = BitConverter.IsLittleEndian;
            const string formatter = "{0,10}\t{1,10}\t{2,10}\t{3,10}\t{4,10}\t{5,10}"; ;
            Debug.WriteLine(formatter, "i", "file", "cmp", "B2L cmp", "parsed", "B2L parsed");
            Debug.WriteLine(formatter, Enumerable.Range(1, 6).Select(x => "--------").ToArray());

            //Debug.WriteLine("{0:X8}", big2litte1);

            string KeggSmiles = "[C@H]1(n2c3c(nc2)c(ncn3)N)[C@@H]([C@@H]([C@H](O1)COP(=O)(OP(=O)(OC[C@H]1O[C@H]([C@@H]([C@@H]1O)O)N1C=C(CC=C1)C(=O)N)O)O)O)OP(=O)(O)O";
            string KeggECFP2 = @"f5137cdc f5137cdc f08b4928 e9e5be3f e9e5be3f e9e5be3f 
e99821a1 dfe49bdf dfe49bdf d6e0861f d6e0861f cef9a4bc 
cb69fe08 c885380c c6d3b3eb c38b3152 c38b3152 c36fb784 
be842c9d bdb9a034 bd1c43c3 ac8924de ab904d16 aa139040 
a795d505 9ce64676 96ad281d 7ef444f9 7ef444f9 7ef444f9 
7ef444f9 7be0ee02 79e96c34 782c4b73 6cdf4289 6cdf4289 
6cdf4289 6cdf4289 6cdf4289 6cdf4289 6cdf4289 6cdf4289 
69a2560a 69a2560a 69a2560a 69a2560a 636f8f6a 5faf488d 
5faf488d 5faf488d 5d2209c6 5a9bc9d5 5888721b 5645f44d 
54125a1f 53362b63 5299f401 4e8b69b6 4c4118f4 4b1ef6fb 
4a7b5d42 4a7b5d42 4a7b5d42 4a7b5d42 4863a65a 45b91d6a 
45b91d6a 45b91d6a 45b91d6a 43c18a3a 413d3b6c 3df636cd 
3df636cd 3df636cd 3df636cd 3cd9ba8b 3cd9ba8b 3cd9ba8b 
3cd9ba8b 3cd9ba8b 3b1ca892 3b1ca892 3a336052 275de761 
1c66c562 18eb4a1e 1170108b 1170108b 1170108b 1170108b 
1170108b 1170108b 1170108b 09639408 094b2d63 026490f7".Replace(Environment.NewLine, string.Empty);

            string EthanolSmiles = "CCO";
            string EthanolFP2 = @"00000000 00000000 00000000 00000000 00000000 00000000 
00000000 00000000 00000000 00000000 00000000 40000000 
00000000 00000000 00000000 00080008 00000000 00000000 
00000000 00000000 00000000 00000000 00000000 00000000 
00000000 00000000 00000000 00000000 00000000 00000000 
00000000 00000000".Replace(Environment.NewLine, string.Empty);

            VectorUInt res = new VectorUInt();

            var blocks = KeggECFP2.Split(' ').ToList();
            blocks.Reverse();
            foreach (string block in blocks)
            {
                uint uintValue = uint.Parse(block, System.Globalization.NumberStyles.HexNumber);
                //byte[] bb = BitConverter.GetBytes(uintValue);
                //Debug.WriteLine(formatter, uintValue, BitConverter.ToString(bb));

                //parsed.Add(Big2Little3(uintValue));
                res.Add(uintValue);
            }

            using (OBConversion conv = new OBConversion())
            using (OBMol mol = new OBMol())
            using (OBFingerprint fp = OBFingerprint.FindFingerprint("ECFP2"))
            using (VectorUInt vec = new VectorUInt())
            {
                conv.SetInFormat("smi");
                mol.Clear();
                conv.ReadString(mol, KeggSmiles);
                fp.GetFingerprint(mol, vec);

                System.Collections.Generic.List<uint> cmpFP = new System.Collections.Generic.List<uint>(vec);
                //cmpFP.Reverse();

                for (int i = 0; i < cmpFP.Count; i++)
                {
                    Debug.WriteLine(formatter,
                        i,
                        blocks[i].ToUpper(),
                        BitConverter.ToString(BitConverter.GetBytes(cmpFP[i])).Replace("-", string.Empty),
                        BitConverter.ToString(BitConverter.GetBytes(Big2Little3(cmpFP[i]))).Replace("-", string.Empty),
                        BitConverter.ToString(BitConverter.GetBytes(res[i])).Replace("-", string.Empty),
                        BitConverter.ToString(BitConverter.GetBytes(Big2Little3(res[i]))).Replace("-",string.Empty));
                }

                byte[] bytes = Converter.ToByteArray(vec);

                for (int i = 0; i < vec.Count; i++)
                {
                    Debug.Assert(vec[i] == res[i]);
                }
            }
        }`

**Comment by ghutchis** [comment]
This seems like it's resolved?
