### ISSUE TITLE
make test fails, and can't use pybel.

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#2046]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

[cloud_init_openbabel.txt](https://github.com/openbabel/openbabel/files/3648942/cloud_init_openbabel.txt)

## Environment Information
Open Babel version: 2.4.1 and HEAD
Operating system and version:  Ubuntu 18.04

## Expected Behavior
make test to pass, pybel to work.

## Actual Behavior
pybindtest_bindings fails make test.  Trying to import Pybel fails with:

> PYTHONPATH=/usr/local/lib/python2.7/dist-packages/openbabel/ python test.py
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     import pybel
>   File "/usr/local/lib/python2.7/dist-packages/openbabel/pybel.py", line 51, in <module>
>     from . import openbabel as ob
> ValueError: Attempted relative import in non-package
> 

I wanted to verify that #1557 was fixed in HEAD, figure out what commit fixed it, and see if it the same issue as one I ran into in a different context (obabel command line), and maybe learn a little pybel at the same time.  But I can't get pybel to run at all, and there is a possibly related regression test failure.  

## Steps to Reproduce

I've seen similar reports before, but they don't seem to go anywhere often due to reproducibility issues or problems with finding multiple libraries from different versions.  To try to get around that I've attached a file that can be sent as "user data" to a AWS instance, this should make it very reproducible to anyone that uses AWS.  I used Ubuntu 18.04 ami-05c1fa8df71875112 (64-bit x86), and m4.large or m4.xlarge size.  If you aren't an AWS user, I hope it is easy enough to parse this file out into the steps.

In the past I had issues with getting the environment right for "make test" to find the right .so files.  By doing "make install" before "make test", I think it should get around that, and the final test I do should only use the installed files anyway.

**Comment by ghutchis** [comment]
I have no idea about your 2.4.1 report, but HEAD has new syntax for 3.0 - and I believe requires Python 3.x.

```
from openbabel import openbabel as ob
from openbabel import pybel
```

**Comment by ghutchis** [comment]
You can see from Travis that "make test" works just fine, e.g.
https://travis-ci.org/openbabel/openbabel/builds/587511901
