### ISSUE TITLE
Perceiving bonds fails for water

### ISSUE THREAD

**Issue by psavery** [openbabel/openbabel#2050]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: openbabel-2.4.1 (installed via pip)
Operating system and version: Ubuntu 18.04

## Expected Behavior
Water bonding to be perceived

## Actual Behavior
No bonds are perceived for water

## Steps to Reproduce
Hi All! 

I seem to have ran into an issue with Open Babel where water bonds are not being perceived. More details are posted [here](https://github.com/OpenChemistry/mongochemserver/issues/145) along with an example. Do you have any ideas as to what the problem might be?

Thanks,
Patrick

**Comment by ghutchis** [comment]
This is not a bug. You've supplied a Molfile with no bonds, so valence is set accordingly.

If you want bonds to be perceived, you might want something like XYZ format.

**Comment by psavery** [comment]
Hmm, okay. I'll give that a try. The reason I thought it was a bug was because bond perception (of a molfile with no bonds) seemed to be working for almost every other molecule I tried (including things like ethanol).

**Comment by psavery** [comment]
I think using xyz is going to work much better for us. Thank you for the help, Geoff! Closing.
