### ISSUE TITLE
Bug in fingerprinting FP2

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#206]
If I fingerprint these two representations of the same molecule, I get different fingerprints:

C12CCN(CC1)C2
C1CN2CC1CC2

Looking at the ouptut of:

obabel dist2.smi -ocan -ofpt -xs

I see that the first representation gives a bit set for:
0 6 1 7 1 6 1 6 1 6 1 6 1 6

while the second one does not.

I don't know which direction the error is.  Should that path be included from both, or not included in either?

**Comment by johnmay** [comment]
I think (not tested),

https://github.com/openbabel/openbabel/blob/master/src/fingerprints/finger2.cpp#L176

is the problem as this makes the hashing asymetric (trailing bond order)? The rotation to find the max ring hash (in DoRings()) is then different depending on which way round you traverse the path.

John

**Comment by jeffjanes** [comment]
On Mon, Aug 3, 2015 at 8:02 AM, John May <notifications@github.com> wrote:

> I think (not tested),
>
>
> https://github.com/openbabel/openbabel/blob/master/src/fingerprints/finger2.cpp#L176
>
> is the problem as this makes the hashing asymetric (trailing bond order)?
> The rotation to find the max ring hash (in DoRings()) is then different
> depending on which way round you traverse the path.
>

In the case here, the missing (or extra) fingerprint bit is not part of a
ring-fingerprint (there is a ring, but the closure of the ring is not part
of the fingerprint path.  The 7th atom closes back to the 2nd one, not back
to the 1st one), so I don't think that that alone can be the answer.  Also,
if the rotation algorithm was broken, I think that would lead much less
subtle problems than this one seems to be.

Cheers,

Jeff
