### ISSUE TITLE
3D structure generation failing on linked ring structures.

### ISSUE THREAD

**Issue by jcminerlanl** [openbabel/openbabel#2061]
- [ ] I believe this to be a bug with Open Babel - molecules with several linked six-member and five-member rings cannot be converted to .smi files that are able to be read back into 3D forms.

## Environment Information
Open Babel version: Open Babel 2.4.1 -- Oct 12 2016 -- 00:36:21
Operating system and version:  macOS Sierra 10.12.6
Darwin Kernel Version 16.7.0

## Expected Behavior
(Starting from a 3D structure of a molecule - a chemically-acceptable geometry)

`babel -ipdb digitoxin2.pdb -osmi digitoxin2.smi`
Output:
C[C@@H]1[C@H]([C@H](C[C@@H](O1)O[C@@H]1[C@H](O[C@H](C[C@@H]1O)O[C@@H]1[C@H](O[C@H](C[C@@H]1O)O[C@H]1CC[C@]2([C@@H](C1)CC[C@@H]1[C@@H]2CC[C@]2([C@@]1(CC[C@@H]2C1=CC(=O)OC1)O)C)C)C)C)O)O
(This was fine)

`babel  -ismi digitoxin2.smi --gen3d --h -opdb digitoxin2-2.pdb`

(From the last command I expect to see a 3D configuration generated).

## Actual Behavior
Error:
==============================
*** Open Babel Warning  in CorrectStereoAtoms
  Could not correct 3 stereocenter(s) in this molecule (digitoxin2.pdb)
  with Atom Ids as follows: 40 41 52
Warning: Stereochemistry is wrong, using the distance geometry method instead

The original molecule (attached) does not have incorrect stereochemistry, so somewhere in open babel the code either cannot make the correct SMILES format, or cannot convert the SMILES format into the correct 3D structure.

## Steps to Reproduce
`babel -ipdb digitoxin2.pdb -osmi digitoxin2.smi` (CORRECT)
`babel  -ismi digitoxin2.smi --gen3d --h -opdb digitoxin2-2.pdb` (WRONG)

(Attaching digitoxin2.pdb as a .txt file to allow attachment) Do `mv digitoxin2.txt digitoxin2.pdb` before the above commands.

[digitoxin2.txt](https://github.com/openbabel/openbabel/files/3726767/digitoxin2.txt)

**Comment by ghutchis** [comment]
This works in OB-3.0 with my testing.
