### ISSUE TITLE
Using OBConformerScore leads to segfault after ConformerSearch.Search()

### ISSUE THREAD

**Issue by thesketh** [openbabel/openbabel#2066]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 or 3.0.0
Operating system and version: macOS High Sierra, CentOS 7

## Expected Behavior
Conformer scoring methods to work properly

## Actual Behavior
Segmentation fault after conformer search

## Steps to Reproduce

The following is self contained and should demonstrate the error:

```python
try:
    from openbabel import openbabel as ob
except ImportError:
    import openbabel as ob
import os

AF = """COMPND    AF
AUTHOR    Generated procedurally.
ATOM      1  N   ALA     1A   -3.763     0.633   1.306  1.00  0.00           N1+
ATOM      2  HT1 ALA     1A   -4.732     0.958   1.534  1.00  0.00           H
ATOM      3  HT2 ALA     1A   -3.119     1.452   1.157  1.00  0.00           H
ATOM      4  HT3 ALA     1A   -3.350     0.072   2.077  1.00  0.00           H
ATOM      5  CA  ALA     1A   -3.725    -0.167   0.100  1.00  0.00           C
ATOM      6  HA  ALA     1A   -4.393    -1.054   0.211  1.00  0.00           H
ATOM      7  CB  ALA     1A   -4.153     0.670  -1.107  1.00  0.00           C
ATOM      8  HB1 ALA     1A   -4.395     1.687  -0.745  1.00  0.00           H
ATOM      9  HB2 ALA     1A   -3.357     0.776  -1.855  1.00  0.00           H
ATOM     10  HB3 ALA     1A   -5.005     0.168  -1.568  1.00  0.00           H
ATOM     11  C   ALA     1A   -2.323    -0.554  -0.141  1.00  0.00           C
ATOM     12  O   ALA     1A   -2.084    -1.258  -1.152  1.00  0.00           O
ATOM     13  N   PHE     2A   -1.288    -0.152   0.725  1.00  0.00           N
ATOM     14  HN  PHE     2A   -1.426     0.431   1.576  1.00  0.00           H
ATOM     15  CA  PHE     2A    0.093    -0.557   0.450  1.00  0.00           C
ATOM     16  HA  PHE     2A    0.095    -1.184  -0.502  1.00  0.00           H
ATOM     17  CB  PHE     2A    0.921     0.626   0.133  1.00  0.00           C
ATOM     18  HB1 PHE     2A    0.918     1.414   0.915  1.00  0.00           H
ATOM     19  HB2 PHE     2A    0.463     1.117  -0.764  1.00  0.00           H
ATOM     20  CG  PHE     2A    2.332     0.332  -0.168  1.00  0.00           C
ATOM     21  CD1 PHE     2A    2.658    -0.081  -1.471  1.00  0.00           C
ATOM     22  HD1 PHE     2A    1.839    -0.184  -2.190  1.00  0.00           H
ATOM     23  CE1 PHE     2A    3.962    -0.333  -1.783  1.00  0.00           C
ATOM     24  HE1 PHE     2A    4.237    -0.655  -2.788  1.00  0.00           H
ATOM     25  CZ  PHE     2A    5.000    -0.207  -0.886  1.00  0.00           C
ATOM     26  HZ  PHE     2A    6.027    -0.408  -1.140  1.00  0.00           H
ATOM     27  CE2 PHE     2A    4.706     0.194   0.385  1.00  0.00           C
ATOM     28  HE2 PHE     2A    5.431     0.326   1.165  1.00  0.00           H
ATOM     29  CD2 PHE     2A    3.375     0.458   0.724  1.00  0.00           C
ATOM     30  HD2 PHE     2A    3.137     0.798   1.731  1.00  0.00           H
ATOM     31  C   PHE     2A    0.522    -1.454   1.509  1.00  0.00           C
ATOM     32  OT1 PHE     2A   -0.019    -2.622   1.495  1.00  0.00           O
ATOM     33  OT2 PHE     2A    1.416    -1.244   2.524  1.00  0.00           O1-
MASTER        0    0    0    0    0    0    0    0   33    0    0    0
END
"""

with open('AF.pdb', 'w') as pdb_file:
    pdb_file.write(AF)

mol = ob.OBMol()
reader = ob.OBConversion()
reader.SetInAndOutFormats('pdb', 'pdb')
reader.ReadFile(mol, 'AF.pdb')
os.remove('AF.pdb')

n_conformers = 10
n_children = 5
mutability = 5
convergence = 10
conformer_search = ob.OBConformerSearch()
conformer_search.Setup(mol, n_conformers, n_children,
                       mutability, convergence)

# Without the following two lines, this works.
conformer_score = ob.OBRMSDConformerScore()
conformer_search.SetScore(conformer_score)

conformer_search.Search()
# SEGFAULT here
conformer_search.GetConformers(mol)
```

OBRMSDConformerScore was just an example - this also occurs with OBEnergyConformerScore and OBMinimizingEnergyConformerScore.

I'm fairly new to using the Python wrappers to OpenBabel, so there's a good chance I'm doing something wrong when setting up the score!

**Comment by ghutchis** [comment]
I don't know why there's a segfault - obviously that shouldn't happen. If you use these from the command-line do they work?

**Comment by baoilleach** [comment]
Hey Travis, no need to write to a file first. Just use ```mol = pybel.readstring("pdb", AF).OBMol```. 

With the code as presented, you need to check the return value of ReadFile. It may have failed for example, and still be an empty molecule. Unfortunately, not all functions behave themselves when given an empty molecule. Can you check this, and see if it's okay?

**Comment by thesketh** [comment]
> I don't know why there's a segfault - obviously that shouldn't happen. If you use these from the command-line do they work?

Seems to work okay from the command line (2.4.1) using the following command:

```
obabel AF.pdb -O conformers.sdf --conformer --nconf 10 --children 5 --mutability 5 --convergence 10 --score minenergy --writeconformers
```

This works using both the minenergy and energy scores. There might be something wrong with the way I've set up the search in the Python script.

Curiously the segfault only happens _after_ the search. The scoring function seems to work fine during the search (for instance, OBMinimizingEnergyConformerScore takes longer than OBEnergyConformerScore).

> Hey Travis. Just to note that there is no need to write to a file first. Just use `mol = pybel.readstring("pdb", AF).OBMol`.
> 
> With the code as presented, you need to check the return value of ReadFile. It may have failed for example, and still be an empty molecule. Unfortunately, not all functions behave themselves when given an empty molecule. Can you check this, and see if it's okay?

Hi Noel,

Thanks for the tip! I haven't spent much time with the Pybel module because I couldn't see an easy way to run a conformational search on a Pybel mol, and reading the molecules in from PDB is analogous to what I'm doing in my own code.

I'm already performing a check with my systems of interest (verifying the number of atoms in the OBMol)  - I just left it out in this example for clarity.
