### ISSUE TITLE
Python bindings don't build in the 3.0 release tarball due to incorrect path

### ISSUE THREAD

**Issue by merkys** [openbabel/openbabel#2081]
Just wanted to make sure that this is intentional: scripts/CMakeLists.txt looks for SWIG-generated Python bindings under `scripts/python/openbabel-python.cpp`, but when their generation is requested with `RUN_SWIG=ON`, Python bindings are generated at `scripts/python/openbabel/openbabel-python.cpp` (and this file is shipped in release tarballs). Is the difference here intentional?

**Comment by baoilleach** [comment]
If I understand you correctly, you are saying that building the Python bindings from the release doesn't work. Is that correct?

**Comment by merkys** [comment]
> If I understand you correctly, you are saying that building the Python bindings from the release doesn't work. Is that correct?

Yes, unless `RUN_SWIG=ON` is used. I assume `openbabel-python.cpp` is shipped in the release source in order to skip SWIG execution, but as the paths are different, `cmake` ignores the shipped `openbabel-python.cpp`.

**Comment by baoilleach** [comment]
If you have time to prepare a PR to fix this, that'd be great. It should build for release users who don't have SWIG.
