### ISSUE TITLE
Open Babel 3.0.0 on NetBSD

### ISSUE THREAD

**Issue by voidpin** [openbabel/openbabel#2092]
Open Babel version: 3.0.0
Operating system and version: NetBSD-8.1_STABLE using pkgsrc-HEAD

I've just successfully built openbabel-3.0.0 on NetBSD thanks to the help of Kamil, a NetBSD dev.
Four patches were required to build it successfully and it would be great to upstream these to you.

Thank you for this. The chemistry world needs you!

Best Regards,
pin

**Comment by baoilleach** [comment]
Great to hear, but where can we find the patches?

**Comment by voidpin** [comment]
I've just hosted them on my github repo, https://github.com/voidpin/netbsd-openbabel-patches
Let me know once you have fetch them and I'll remove the repo.
