### ISSUE TITLE
OBDistanceGeometry is unavailable to users

### ISSUE THREAD

**Issue by n-yoshikawa** [openbabel/openbabel#2098]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Current master (`6d774e8`)
Operating system and version: Ubuntu 18.04

## Expected Behavior

We can use `OpenBabel::OBDistanceGeometry` if Eigen is installed properly.

## Actual Behavior

We can't use it.

## Steps to Reproduce

When we try to compile
```cpp
#include <openbabel/distgeom.h>

int main(){
  OpenBabel::OBDistanceGeometry dg;
}
```
by 
```
g++ -I /usr/local/include/openbabel3/ -L /usr/local/lib/openbabel/3.0.0/ test.cpp -lopenbabel
```
we get an error: `error: ‘OBDistanceGeometry’ is not a member of ‘OpenBabel’`.

There are two problems:
- `HAVE_EIGEN` is not defined when this code is compiled, so most of `openbabel/distgeom.h` is ignored.
- `LBFGS.h` is not installed properly when we run `make install`

If we define `HAVE_EIGEN` manually and specify the local pass of `LBFGS.h`, this code can be compiled, but I don't think it is an expected behavior.
 
I'm not sure how to fix these problems. Do you have any suggestions?

**Comment by e-kwsm** [comment]
How about including Eigen as [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html)?

But [Eigen is scheduled to migrate from Bitbucket to GitLab on 4 Dec](http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th).

**Comment by ghutchis** [comment]
This isn't a bug. You need:
`#include <openbabel/babelconfig.h>`

This sets appropriate HAVE_* macros.

As far as LBFGS.h - that's clearly a bug - you need to make sure it's an installable header.

**Comment by n-yoshikawa** [comment]
I added `#include <openbabel/babelconfig.h>`, but it did not solve the problem.
I checked [config.h.cmake](https://github.com/openbabel/openbabel/blob/master/src/config.h.cmake), but it does not seem to define `HAVE_EIGEN`.
I couldn't figure out how to fix this.

As for `LBFGS.h`, I made a pull request.
