### ISSUE TITLE
pip install openbabel vs openbabel-python and dependencies/requirements

### ISSUE THREAD

**Issue by devowit** [openbabel/openbabel#2103]
- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: all
Operating system and version: all

## Expected Behavior

when i do pip install openbabel and then run pip freeze, I expect to see openbabel in the list of installed packages. this would then enable me to save pip freeze > requirements.txt and get the name openbabel in the requirements.txt file.

in the same way, with a package that depends on the openbabel python bindings, I could write in setup.py install_requires openbabel and have pip install openbabel when installing the package in question. when installing a package and openbabel is already installed, I'd expect the stup.py process to recognize that openbabel is already installed.

## Actual Behavior

instead of saving as openbabel, the package saves as openbabel-python. over and over this breaks things for me when checking if openbabel is installed and if not installing openbabel. either i check for openbabel, in which case it attempts to install regardless of whether openbabel is already installed or not, or i check for openbabel-python, and it successfully identifies it when installed, but fails to install when missing because no such package exists in pypi

## Steps to Fix

Please please please change the name of the openbabel python package to either consistently be openbabel or consistently be openbabel-python.

**Comment by mcs07** [comment]
I don't see this issue with the current version (3.0.0). Looks like it may have specifically been an issue with the Windows wheels on PyPI for v2.4.1 (and earlier?)

**Comment by mcs07** [comment]
See also #1843

**Comment by baoilleach** [comment]
This was fixed in the Windows bindings before the 3.0 release.
