### ISSUE TITLE
fatal error: 'tr1/memory' file not found, during make

### ISSUE THREAD

**Issue by aloshbau** [openbabel/openbabel#2104]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: openbabel-2.3.1
Operating system and version: MacOS Mojave 10.14.5

## Expected Behavior
Compilation

## Actual Behavior

aloshbaugh at LYMAC079 in ~/Documents/openbabel-build
 ○ make
Scanning dependencies of target openbabel
[  0% ] Building CXX object src/CMakeFiles/openbabel.dir/alias.o
In file included from /Users/aloshbaugh/Documents/openbabel-2.3.1/src/alias.cpp:17:
In file included from /Users/aloshbaugh/Documents/openbabel-2.3.1/include/openbabel/alias.h:19:
/Users/aloshbaugh/Documents/openbabel-2.3.1/include/openbabel/shared_ptr.h:25:14: fatal error: 'tr1/memory' file not found
    #include <tr1/memory>
             ^~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/openbabel.dir/alias.o] Error 1
make[1]: *** [src/CMakeFiles/openbabel.dir/all] Error 2
make: *** [all] Error 2

**Comment by ghutchis** [comment]
This is an absolutely ancient version (2011-ish). Use OB-3.0.0. I can verify it works on all modern Macs.

**Comment by ghutchis** [comment]
https://github.com/openbabel/openbabel/releases

**Comment by ghutchis** [comment]
Fair enough. I was not aware that openbabel.org/docs/ hasn't been updated. That certainly is a bug, even though the whole website is about to be obliterated.
- but the wiki points to OB-2.4.1 (which doesn't have the bug).
- SF.net has the 2.4.1 release under the 'download' link
- This Github page has the 3.0 release prominently indicated as the latest release both under 'releases' and on the README.

So yes, it's a doc bug, but there are multiple sources pointing to much newer releases. (Homebrew for example had 2.4.1 and now has 3.0.0)

**Comment by aloshbau** [comment]
It's great that some of the documentation is correct but it shouldn't be a crapshoot depending on which doc page you end up on. If the whole website is about to be deleted that should resolve the problem. Thank you!
