### ISSUE TITLE
Applying Cartesian transformations to generated coordinates.

### ISSUE THREAD

**Issue by Arpan-term** [openbabel/openbabel#2106]
- [ ] I believe this to be a bug with Open Babel
- [x] This is a feature request

## Environment Information
Open Babel version: OpenBabelGUI
Operating system and version: Windows 10

## Expected Behavior
I want to convert SMILES format into xyz(3D) coordiantes of the molecule (a) and (b) attached below. I've produced the xyz coordiantes of 'a' using 'C1=C(O)C(O)=CC2=C1C=C(C(O)=O)N2' as the SMILES input. But couldn't produce the xyz for 'b'.
![untitled](https://user-images.githubusercontent.com/58414762/70790568-5cb9ed00-1dbb-11ea-9ef1-3c74c3605dd6.png)

## Actual Behavior
whatever SMILES representations I use for 'b' (), it essentially gives the xyz of the 'a' or 180 degree rotated structure about X axis of 'a' only. I tried 'N1C(C(O)=O)=CC2=C1C=C(O)C(O)=C2' , 'C1=C(O)C(O)=CC(NC(C(O)=O)=C2)=C12', 'C1=C(O)C(O)=CC(C=C(C(O)=O)N2)=C12' and others for producing 'b'. But nothing is working.

## Steps to Reproduce
xyz for orientation 'a' is 
[orientation_(a).txt](https://github.com/openbabel/openbabel/files/3960230/orientation_.a.txt)
which is absolutely fine.
And xyz generated for orientation 'b' using 'N1C(C(O)=O)=CC2=C1C=C(O)C(O)=C2' is 
[orientation_(b).txt](https://github.com/openbabel/openbabel/files/3960245/orientation_.b.txt)
which nothing but a 180 degree rotated structure about X axis of 'a' , but i need a 180 degree rotated structure about Y axis of 'a'.

**Comment by ghutchis** [comment]
Changing the order of the SMILES will not necessarily change the orientation of the molecule in the XYZ frame of reference.

If you want to rotate 'a' around the Y axis, I suggest taking the coordinates of 'a' and multiplying the X coordinate by -1.0.

(There are programs, particularly a wide variety of Python scripts to apply such transforms.)

**Comment by Arpan-term** [comment]
> Changing the order of the SMILES will not necessarily change the orientation of the molecule in the XYZ frame of reference.
> 
> If you want to rotate 'a' around the Y axis, I suggest taking the coordinates of 'a' and multiplying the X coordinate by -1.0.
> Yes, my goal is definitely this one. But unfortunately, i don't want to play with Cartesian coordinates, rather I'm trying to find if there is any way to rotate the molecule around Y axis using the SMILES notation only.
Thank you.
> (There are programs, particularly a wide variety of Python scripts to apply such transforms.)

**Comment by ghutchis** [comment]
No, this would be very complicated to do. Even the atom-by-atom builder does not guarantee a frame of reference - but most of the coordinate generation is done by fragments.

If this is your feature request, I'm going to close this. By far the easiest solution is to build the geometry then rotate.

**Comment by Arpan-term** [comment]
Thank you.
