### ISSUE TITLE
pybel : AttributeError: 'module' object has no attribute 'readstring'

### ISSUE THREAD

**Issue by cullsin** [openbabel/openbabel#2118]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version: windows 10 / 7 

## Expected Behavior
pybel should have readString() method.

## Actual Behavior

C:\Windows\system32>python
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybel
>>> pybel.readstring()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'readstring'
>>>

## Steps to Reproduce
Install openbabel in windows

**Comment by mcs07** [comment]
Change `import pybel` to `from openbabel import pybel`.

**Comment by baoilleach** [comment]
Maybe you have installed PyBEL (https://github.com/pybel/pybel), which is why the import works, but that is nothing to do with Open Babel.
