### ISSUE TITLE
Zero occupancy in cif file treated as 1.0.

### ISSUE THREAD

**Issue by orex** [openbabel/openbabel#2125]
Dear OpenBabel developers.
Many thanks for your program, and sorry for avoiding the template.

The problem appears in commit bf2204231bfc2bf1a97bf193fa56c3d72ff0c97b and now in master.
The issue is that the CIF file occupancy values can be treated incorrectly.

```
commit bf2204231bfc2bf1a97bf193fa56c3d72ff0c97b
Author: Alexandr Fonari <alexandr.fonari@gmail.com>
Date:   Mon Mar 19 11:39:33 2018 -0400

    Update mmcifformat.cpp

diff --git a/src/formats/mmcifformat.cpp b/src/formats/mmcifformat.cpp
--- a/src/formats/mmcifformat.cpp
+++ b/src/formats/mmcifformat.cpp
@@ -777,1 +777,3 @@
-               occup->SetValue(token.as_number());
+               double occup = token.as_number();
+               if (occup <= 0.0 || occup > 1.0){
+                  occup = 1.0;


```
The occupancy become 1.0 if it is 0.0. This affect supercell program. https://github.com/orex/supercell/issues/28
I would like to get a comment from @afonari about the reason of such behaviour. If there are no "strong"  reasons for this, I propose to change the code to
```
occup = std::max(0.0, std::min(1.0, occup));
```

Sincerely yours,
Kirill.

**Comment by afonari** [comment]
There is no strong reason for this. I think your change is good.

**Comment by afonari** [comment]
@orex are you going to create a pull request?

**Comment by orex** [comment]
Hello. I would like to create a pull request, but I'm extremely busy this week. I don't' want to create it w/o testing.

**Comment by afonari** [comment]
Thanks, sounds goods, no rush.
