### ISSUE TITLE
DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by cullsin** [openbabel/openbabel#2129]
## Environment Information
Open Babel version: 3.0
Operating system and version: win 32. python 2.7

## Expected Behavior
I suppose to import openbabel.

## Actual Behavior
![image](https://user-images.githubusercontent.com/5137598/74587536-c0f66880-5019-11ea-8585-7ff44fab13b3.png)

## Steps to Reproduce
Install Openbabel 3.0.0
pip install openbabel. ( python version 2.7 )
import openbabel

Thanks,
Raja K

**Comment by baoilleach** [comment]
Which version of Open Babel 3.0.0 exactly did you install? The 32-bit or 64-bit? If you used the default installation directory, it will be "Program Files" for 64-bit and "Program Files (x86)" for 32-bit.

Is the Open Babel 3.0 installation folder on the PATH? From Python you can check this with "import sys; print(sys.path)". If not, add it to the front of your Windows environment variable (google "how to change path"), and restart VS Code.

**Comment by cullsin** [comment]
Thanks. I will check it out and get back to you tomorrow. Can you please give me a URL to download 32-bit open babel? I got to download only one version from the website if I am not wrong.

**Comment by baoilleach** [comment]
https://github.com/openbabel/openbabel/releases/tag/openbabel-3-0-0
The 32-bit version is named OpenBabel-3.00-x86.exe.

**Comment by baoilleach** [comment]
Closing. Reopen if still a problem.
