### ISSUE TITLE
Problem with static compilation

### ISSUE THREAD

**Issue by rquiroga7** [openbabel/openbabel#2134]
Hi everybody. I apologize in advance if my question is dumb, and thank anyone that could help me out. I'm quite new to C++ and cmake.

I have written a new plugin format, PDBT, which at the moment is nothing more than a copy of pdbqt format, but which will change once I can get it to work.

When compiling normally everything works, I am able to use the new file format.

However, I need an executable that can be distributed for use on different machines.

When compiling using -DBUILD_SHARED=OFF -DBUILD_MIXED=ON, I can compile libopenbabel.a which I can then use to compile a static obabel binary. This executable works, but the new plugin (PDBT) is absent from obabel -L formats list, and fails when I try to use it doing "obabel -isdf test/pdb_ligands_sdf/966c_rs2.sdf -opdbt".

Does anyone have any idea why the plugin is not working on the mixed compiled executable?

Here is my fork with the PDBT format (simply copied the pdbqt file in formats folder and modified formats.cmake to add pdbt format):

https://github.com/rquiroga7/openbabel.git

I am attaching my CMakeLists file which I use to compile the obabel executable:
[CMakeLists.txt](https://github.com/openbabel/openbabel/files/4268993/CMakeLists.txt)

**Comment by ghutchis** [comment]
This is not a bug. Please post to the openbabel-devel mailing list.
