### ISSUE TITLE
copy_file is problematic in scripts/python/setup.py

### ISSUE THREAD

**Issue by hongyi-zhao** [openbabel/openbabel#2139]
Hi,

The copy_file function used in https://github.com/openbabel/openbabel/blob/master/scripts/python/setup.py, is as follows:

```
    self.copy_file(os.path.join('..', 'stereo.i'), pkg_dir, link=link)
    self.copy_file(os.path.join('..', 'openbabel-python.i'), pkg_dir, link=link)
```

I'm confusing on the above codes, in detail:
The copy_file function is a built-in function instead of customized one, so needn't the self.  So it should be import as following for using it:

```
    from distutils.file_util import copy_file
    [...]
    copy_file(os.path.join('..', 'stereo.i'), pkg_dir, link=link)
    copy_file(os.path.join('..', 'openbabel-python.i'), pkg_dir, link=link)
 ```

But I tried with the above revision, and it still failed to copy the corresponding files while running the setup.py.  See here for detail: https://github.com/openbabel/openbabel/issues/2137#issuecomment-597689294

Any hints for this issue?

Regards

**Comment by baoilleach** [comment]
This isn't a bug, nor is it problematic. It seems like a question about how disutils works. Feel free to reopen if you disagree.

**Comment by hongyi-zhao** [comment]
I agree with you,  If I compile it with cmake by changing the `-DCMAKE_INSTALL_PREFIX`, the python binding will be installed into the customized location correctly.

Regards.
