### ISSUE TITLE
Segmentation fault when convert smi to mol2 using openbabel-3.0.0 with --gen3D

### ISSUE THREAD

**Issue by jrhaulung** [openbabel/openbabel#2141]
system ubuntu-16.04 LTS
openbabel 3.0.0 compile from source (zip file)
conversion of smile string of a ZINC15 biogenic compound  to 3D mol2 
encounters a reproducible segmentation fault error

obabel -:'CC(=O)OC[C@]12C[C@H]
(OC(=O)CC(C)C)C(C)=C[C@@H]1O[C@H]1[C@H](OC(C)=O)[C@H](OC(C)=O)[C@@]2(C)[C@@]12CO2' -omol2 --gen3D
==============================
*** Open Babel Warning  in CorrectStereoAtoms
  Could not correct 2 stereocenter(s) in this molecule ()
  with Atom Ids as follows: 5 33
Warning: Stereochemistry is wrong, using the distance geometry method instead
Segmentation fault (core dumped)

gdb obabel core result shows 

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `obabel -ismi Z15-biogenic307814-sort85597276.smi --gen3D -omol2 -O Z15-biogenic'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3778b694d5 in OpenBabel::OBRotamerList::SetCurrentCoordinates(OpenBabel::OBMol&, std::vector<int, std::allocator<int> >) () from /usr/local/lib/libopenbabel.so.6

help will be highly appreciated, Thanks

sincerely,
Jrhau

**Comment by ghutchis** [comment]
I'm closing this - the SMILES as posted is invalid and it's been over a month since I asked for clarification. Version 3.1 or `master` should fix this.
