### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by JohnScott623** [openbabel/openbabel#2148]
Hello,

OpenBabel 3.0 had a couple issues that seems to make it difficult to use in projects with CMake, but it looks like they've been fixed in Git ~~long~~ some time ago. The [projects](https://github.com/openbabel/openbabel/projects/3) and [milestones](https://github.com/openbabel/openbabel/milestones) look empty, and I was wondering if there were plans to make a new release?

I'm not familiar with OpenBabel, but this prohibits [KDE's Kalzium](https://bugs.kde.org/show_bug.cgi?id=416856) from upgrading in the time being.

**Comment by JohnScott623** [comment]
@baoilleach I believe the necessary fixes are [8f24fa64](https://github.com/openbabel/openbabel/commit/8f24fa64606376e38180a455e7a60c71a23b2d71), which was committed the day after 3.0's release but didn't make it into a 3.0.1, and #2086

**Comment by ghutchis** [comment]
We'll certainly make a 3.0.1 soon. Outside the packaging issue, there were a variety of crashes that have been fixed.
