### ISSUE TITLE
install python bindings 3.0.0 on ubuntu 18.04

### ISSUE THREAD

**Issue by odioidentisti2** [openbabel/openbabel#2151]
(OpenBabel 3.0.0 will be available on Ubuntu repositories from the next version: 20.04)

On Ubuntu 18.04 I've installed openbabel_3.0.0 via snap, but python bindings don't come along.
So I was thinking to compile them, but on the doc looks like if I can compile the bindings only as an option while compiling openbabel itself (I cannot compile the bindings for my actual snap version of openbabel, I should compile everything together). Is that correct?

Another option would be to force an early upgrade to Ubuntu 20.04.

Is this the present situation, or am I missing something?

**Comment by baoilleach** [comment]
You're right.

But compiling Open Babel should be straightforward. If not, come back here
and we can help. Or better, email the mailing openbabel-discuss@lists.sf.net
.

snaps seems to be only for desktop applications. If I could provide a
Python binding snap, I would.

**Comment by odioidentisti2** [comment]
ok, no problem.
just one question: in case of multiple python installations (I have 2.7 and
3.6 on my machine) can i get the bindings for both versions? How? Which
python version is used by default?
I guess python-dev is required for Python2 and python3-dev for Python3...

I inform you that in the doc at
https://open-babel.readthedocs.io/en/latest/Installation/install.html , in
the "Requirements" paragraph, the "source code" link is still pointing to
the old 2.4 version in the sourceforge repository

Il giorno mer 1 apr 2020 alle ore 19:40 baoilleach <notifications@github.com>
ha scritto:

**Comment by ghutchis** [comment]
I would highly suggest migrating to Python3 ASAP. While you can currently install OB bindings for 2.7, they will not be tested or supported going forward.

**Comment by odioidentisti2** [comment]
Sorry but I don't get it.
I have python3, I will develop for python3 and the first goal of my
question is to be sure that I'll get the bindings for python3. That's why I
asked for which python are the bindings installed by default. (you know, if
I type "python" at the console I still get python2, I must type "python3"
to get python3)

Still, i don't want to leave my python2 "unbound". Actually, I should keep
python2 bound to openbabel2 and python3 to openbabel 3.

So I clarify my question: if I compile openbabel 3 with python bindings, to
which python will it be bound to, if I have both 2 and 3?

Do you think I can keep both versions of openbabel: the version 2 from the
Ubuntu repositories bound to python2, and the version 3 compiled by me and
bound to python3, without messing around?

Thank you

**Comment by odioidentisti2** [comment]
So, I thought that maybe I was being too much cautious, and obviously the
bindings of openbabel3 would have been installed for Python3...

Well, I was actually right to be cautious, cmake gave me this:
-- Found PythonInterp: /usr/bin/python (found version "2.7.17")

So I'm back to my question: how do I install the python bindings for
python3?

I've got also a couple of warnings, I'll ask in the mailing list
openbabel-discuss@lists.sf.net


Il giorno gio 2 apr 2020 alle ore 04:34 Thomas <odioidentisti@gmail.com> ha
scritto:

**Comment by odioidentisti2** [comment]
I've managed to build openbabel with bindings to python 3 on a local install. Everything went smooth. 

This is my cmake command:
cmake ../openbabel-3.0.0 -DCMAKE_INSTALL_PREFIX=~/WORKSPACE/OpenBabel/openbabel-3.0.0_INSTALL -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON

Still, after setting the PYTHONPATH:
export PYTHONPATH=~/WORKSPACE/OpenBabel/openbabel-3.0.0_INSTALL

 I get error:
>>> from openbabel import openbabel 
ModuleNotFoundError: No module named 'openbabel'

I don't know if it can be useful, but if I add the "lib" sub-directory to the PYTHONPATH i get this:
export PYTHONPATH=~/WORKSPACE/OpenBabel/openbabel-3.0.0_INSTALL/lib 

>>> from openbabel import openbabel
ImportError: cannot import name 'openbabel'
>>> import openbabel
>>> dir(openbabel)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

Pretty tired now, I give up for today.
Thank you for your help

**Comment by odioidentisti2** [comment]
ok, I was using the wrong path. ther ight path in my installation is

 PYTHONPATH=~/WORKSPACE/OpenBabel/openbabel-3.0.0_INSTALL/lib/python3.6/site-packages
