### ISSUE TITLE
SMART query fails incosistently

### ISSUE THREAD

**Issue by aanastasiou** [openbabel/openbabel#2156]
I am faced with a set of strange SMART query failures across different molecules and I wonder if I am encountering something like [this](https://github.com/openbabel/openbabel/issues/1034) or it is a new bug entirely (?).

Specifically, I am trying to match just the atoms of the backbone with: `[NH0,NH1,NH2,NR5]~[C,CR5]-[CX3](=O)`. (That is a Nitrogen at the start of a chain (NH2), a Nitrogen somewhere along the chain (NH0, NH1), a Nitrogen on the ring of a PROline aminoacid, followed by a carbon (or carbon of a PROline aminoacid, followed by the final carbon of the main chain atoms).

I have two molecules that I am trying this query on, a simple one (1GCN) and a more complex one (6QWY).

This query matches ALL residues on 1GCN but skips residues 63,72,83,84 (**zero based index used here**) . The residues that are there are CYS, ARG, LEU, SER. So, it is not even the same residue it skips.

When I am quering the atoms of the residues that are skipped (and I would expect that the query would have picked up), they are not any different than others that have produced a positive match. Their **types** are still "Nam, C3, C2, O2".

Am I missing something here or could this be some sort of a bug?

** Environment Information:**

Open Babel version: 2.3.2
Operating system and version: Linux (Ubuntu 18.04)

**Comment by baoilleach** [comment]
Just to note that [C,CR5] simplifies to C and that OB 2.3.2 is quite old so I'd definitely try a newer version.

That said, I'd guess that the problem is with the structures, or OB's perception thereof, not with the SMARTS matcher. OB matches the all-atom structure whereas the PDB file is often missing bonds and bond orders, so these must be inferred. If you convert the structure to a MOL file and look at the bonds and bond orders, there must be something messed up.

**Comment by aanastasiou** [comment]
@baoilleach Thank you very much, this is helpful at this point.

I agree about the `[C, CR5]` simplification, it may have been a remnant of earlier queries when I was trying to be more specific on which atoms I am after.

Regarding:
> OB matches the all-atom structure whereas the PDB file is often missing bonds and bond orders, so these must be inferred

I am not sure I fully understand what it means (?) but I may have come across this already, see if this is relevant:

Right after this ticket, I wrote my own matcher for the structure I am after, which is a simple recursive matcher starting on the N. If the N matches, it unrolls its bonds and tries to match the C, unrolls its bonds....and so on. In the end, if there is a match starting from an N, all the matching atoms are returned.

Again, 1GCN matches just fine, but 6QWY fails. But now, since I am in complete control of the matching process, I traced each match level and realised that the graph is taking a "detour". The main chain proceeds uninterrupted (that is, there are `OBBond` s describing the `NCC(=O)`, **EXCEPT** in some residues. Here is an example:

![image](https://user-images.githubusercontent.com/1336337/78659371-5cda7d00-78c3-11ea-943c-c08a2afaf570.png)

Notice residue 16, Nam->C3->C2, Residue 17, Nam->C3 and then the C3-C2 bond is only described from the C2 end.

After realising this, I decided to first create the implied graph and then run the matcher on the graph.

Is this what you mean by implied bonds further above?

Regarding the version being old, I understand, will try to compile from the latest, this is the version that Ubuntu has in its repositories by the way.

**Comment by aanastasiou** [comment]
@baoilleach Any ideas about this item?

**Comment by fredrikw** [comment]
I would say that it is an inherent problem with the PDB format. OpenBabel does as well as it can to try to guess the bonds but sometimes it fails. So the systematic way of inferring missing bonds is already tried in the above and you would have to resort to some other way. Either try to locate the original data in another file format or find the missing bonds yourself, manually or somehow by scripting.

**Comment by aanastasiou** [comment]
@fredrikw Thank you very much, I think that this is answering the point of this ticket. In terms of manually filling in the bonds, is there a systematic way of doing it? (I did try matching over the known residue templates but there are more than one ways that the fragments could be pieced together.)
