### ISSUE TITLE
Bug in argument parsing

### ISSUE THREAD

**Issue by fredrikw** [openbabel/openbabel#2159]
- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.0
Operating system and version: Windows 10

## Expected Behavior

Not create a file called --gen2D when calling the following command:
`obabel -ismi -:CCC -omol -Otf --gen2D`
but instead create a file called tf.
## Actual Behavior

When parsing the argument -O, to allow for both -Ofilename and -O filename, there is a check after parsing the first version to see if the filename is shorter than 3 characters long. If so, the next argument is used as filename. I think it can be fixed by changing the conditional on line 157 of obbabel.cpp (https://github.com/openbabel/openbabel/blob/d2fedbba582d9fc659052a9a8ef74f6387d25849/tools/obabel.cpp#L157) to be similar to the ones for -i and -o.

**Comment by baoilleach** [comment]
Good catch.

**Comment by fredrikw** [comment]
Might be better to await PR #2152 to simplify merge handling, or include this change there.
