### ISSUE TITLE
obtautomer

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#216]
The git head builds and installs a program "obtautomer", but the program doesn't work.

obtautomer -c foo.smi

obtautomer: symbol lookup error: obtautomer: undefined symbol: _ZN9OpenBabel17CanonicalTautomerEPNS_5OBMolE

Although the exact error seems to depend on the platform and whether I run it from the install directory or the build/bin directory.

I tried to do a git bisect, but I can't find that it ever worked.  In 2.3.2, it seems not to be get built or installed at all, although the code is present.

Is this program supposed to work, or is it some kind of experimental code that accidentally got included in the make file?

**Comment by ghutchis** [comment]
> The git head builds and installs a program "obtautomer", but the program doesn't work.
> 
> obtautomer -c foo.smi
> 
> obtautomer: symbol lookup error: obtautomer: undefined symbol: _ZN9OpenBabel17CanonicalTautomerEPNS_5OBMolE
> 


Works just fine for me - indeed there's test/tautomertest.cpp that exercises this code:
[ghutchis@Alumina] tools: obtautomer -c triazole.smi 
c1cnn[n]1	

[ghutchis@Alumina] openbabel: git grep CanonicalTautomer
doc/openbabel.tags:      <name>CanonicalTautomer</name>
doc/openbabel.tags:      <name>CanonicalTautomer</name>
doc/openbabel.tags:      <name>CanonicalTautomer</name>
include/openbabel/tautomer.h:  void OBAPI CanonicalTautomer(OBMol *mol);
src/tautomer.cpp:  void CanonicalTautomer(OBMol *mol)
test/tautomertest.cpp:void testCanonicalTautomers(const std::string &smiles)
test/tautomertest.cpp:    CanonicalTautomer(&mol2);
test/tautomertest.cpp:  testCanonicalTautomers("Nc1nc2ncnc2c([nH]1)O");
tools/obtautomer.cpp:        CanonicalTautomer(&mol);

**Comment by jeffjanes** [comment]
On Fri, Aug 7, 2015 at 12:17 PM, Geoff Hutchison <notifications@github.com>
wrote:

> > The git head builds and installs a program "obtautomer", but the program
> doesn't work.
> >
> > obtautomer -c foo.smi
> >
> > obtautomer: symbol lookup error: obtautomer: undefined symbol:
> _ZN9OpenBabel17CanonicalTautomerEPNS_5OBMolE
> >
>
>
> Works just fine for me - indeed there's test/tautomertest.cpp that
> exercises this code:
>


How does that test code get run?  Is it part of 'make test' from the build
directory or does it have to be run a different way?  I didn't see it
getting exercised by 'make test', and the test/README didn't explain how to
run it manually.

Thanks,

Jeff

**Comment by ghutchis** [comment]
Strange that it didn't get exercised before - I think it fell through the cracks in Noel's efforts to make the tests run faster.

**Comment by jeffjanes** [comment]
On a clean machine, I could get obtautomer to work after running make install.  I couldn't it to work when running out of the build directory, even after setting the library path.  When I checked out `ls -l /usr/local/lib/libopen*` on my real machine, I saw this:

    lrwxrwxrwx. 1 root root       17 Jul 20  2012 /usr/local/lib/libopenbabel.so -> libopenbabel.so.4
    -rwxr-xr-x. 1 root root 29479977 Sep 16  2012 /usr/local/lib/libopenbabel.so.4.0.1
    -rwxr-xr-x. 2 root root 30936231 May 22 09:38 /usr/local/lib/libopenbabel.so.4.0.2
    -rwxr-xr-x. 1 root root 33100304 Jul  7 12:40 /usr/local/lib/libopenbabel.so.4.0.0
    lrwxrwxrwx. 1 root root       21 Jul 19 15:41 /usr/local/lib/libopenbabel.so.4 -> libopenbabel.so.4.0.2

I have no idea what happened there, but manually pointing the symlink to the newest .so by timestamp, the so.4.0.0, fixed it.
