### ISSUE TITLE
improper use of OBconversion ?

### ISSUE THREAD

**Issue by michelsanner** [openbabel/openbabel#2178]
Hello,
I am trying to emulate the conversion of a PDB file to a mol2 file using the Python wrapper of OpenBabel.
I have a small molecule with 11 atoms. When I convert it using obabel (v2.3.2) 

obabel -ipdb bad.pdb -omol2 bad_babel.mol2

C and N in rings are aromatic. However, if I use the Python code below they are all C..2 and N.2
What am I missing ?

badsrc = [
'HETATM    1  F   A2F A  91     -11.661 -11.789  10.626  1.00 35.98          F',
'HETATM    2  C2  A2F A  91     -11.647 -11.140   9.446  1.00 36.07          C',
'HETATM    3  N3  A2F A  91     -11.218 -11.795   8.356  1.00 35.26          N',
'HETATM    4  N1  A2F A  91     -12.060  -9.865   9.375  1.00 34.52          N',
'HETATM    5  C6  A2F A  91     -12.054  -9.212   8.203  1.00 34.11          C',
'HETATM    6  N6  A2F A  91     -12.392  -7.927   8.148  1.00 31.63          N',
'HETATM    7  C5  A2F A  91     -11.626  -9.872   7.057  1.00 34.33          C',
'HETATM    8  C4  A2F A  91     -11.199 -11.188   7.163  1.00 34.93          C',
'HETATM    9  N7  A2F A  91     -11.502  -9.521   5.780  1.00 34.42          N',
'HETATM   10  C8  A2F A  91     -11.013 -10.561   5.109  1.00 34.57          C',
'HETATM   11  N9  A2F A  91     -10.826 -11.579   5.948  1.00 34.76          N',
]

import openbabel as ob

obmol = ob.OBMol()
obconv = ob.OBConversion()
obconv.SetInAndOutFormats('pdb', 'mol2')
notatend = obconv.ReadString(obmol, '\n'.join(badsrc))
mol2str = obconv.WriteString(obmol)

**Comment by ghutchis** [comment]
I don't see anything theoretically wrong with this process, although I suspect you're using different Open Babel versions. (For example, 2.3.2 is really ancient.)

I'd suggest installing OB-3.0, e.g.
`conda install -c conda-forge openbabel`

**Comment by baoilleach** [comment]
I'm going to mark as closed as we can't tell if the Python and command-line versions are the same. Feel free to reopen if this occurs with the latest release.
