### ISSUE TITLE
Failed to compile Openbabel 3.0.0 in Ubuntu 18.04.4: could not find wxwidgets and maestro formats will not be supported

### ISSUE THREAD

**Issue by Sukis123** [openbabel/openbabel#2179]
# Environment Information
Open Babel version: 3.0.0
Operating system and version: Ubuntu 18.04.4 64 bit 

I am trying to compile openbabel 3.0.0 in Ubuntu 18 following the instruction posted in https://open-babel.readthedocs.io/en/latest/Installation/install.html#compiling-open-babel. However, i got the following errors: 
CMake Deprecation Warning at CMakeLists.txt:12 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Using included inchi library.
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) 
-- Checking available shared pointer...
-- Use std::shared_ptr in memory
-- Found Boost: /usr/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0")  
-- Maestro formats will NOT be supported. Please install Boost to enable Maestro formats.
-- JSON formats will be supported. Using RapidJSON 1.1.0 at /home/sukis/openbabel-openbabel-3-0-0/external/rapidjson-1.1.0/include
-- Cairo found. PNG output will be supported.
-- Found Boost: /usr/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.45.0") found components: system 
-- Found Boost: /usr/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: program_options iostreams 
-- Attempting to build the GUI
--    wxWidgets not found => GUI will not be built
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sukis/build

I have installed wxwidgets and boost correctly according to the instructions. Moreover, I have added /usr/local/lib to the /etc/ld.so.conf file and run ldconfig as root. But i don't know why i still had this problem. 
PS: evidence of having wxwidgets installed correctly
sukis@sukis-virtual-machine:~$ wx-config --version
3.1.3

Please help!

**Comment by ghutchis** [comment]
This isn't an error - it says build files were written. My guess is that you do not have the `-dev` versions of the packages installed, but that seems like a better question on a Ubuntu forum. I would expect that you can compile with no issues.

**Comment by Sukis123** [comment]
Thanks for replying. I have compiled it successfully on LinuxMint now.
