### ISSUE TITLE
openbabel version on PyPI

### ISSUE THREAD

**Issue by aanastasiou** [openbabel/openbabel#2191]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1 - 3.0.0
Operating system and version: Linux 19.10

## Expected Behavior
``pip install openbabel`` should fetch and install 3.0.0

## Actual Behavior
``pip install openbabel`` fetches 2.4.1 no matter what.
``pip install openbabel==3.0.0`` returns "ERROR: Could not find a version that satisfies the requirement openbabel==3.0.0 (from versions: 1.8, 1.8.1, 1.8.2, 1.8.4, 2.4.0, 2.4.1)"

[pypi seems to have version 3.0.0 anyway (?)](https://pypi.org/project/openbabel/)

## Steps to Reproduce
N/A

**Comment by mcs07** [comment]
Currently only wheel files for windows are available for 3.0.0 on PyPI. We are waiting on a bug fix in 3.0.1 to be able to upload a cross-platform sdist.

**Comment by aanastasiou** [comment]
Thank you, looking forward to that then :)

**Comment by baoilleach** [comment]
Uploaded for 3.1.1.
