### ISSUE TITLE
*** Open Babel Error  in OpenAndSetFormat *** 

### ISSUE THREAD

**Issue by Rmadeye** [openbabel/openbabel#2192]
- [X ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.0.0
Operating system and version: Ubuntu 20.04 updated from 19.10

## Expected Behavior

<add r> $ obabel -ipdb file.pdb -opdb a.pdb -d

1 molecule converted

## Actual Behavior

*** Open Babel Error  in OpenAndSetFormat
  Cannot open a.pdb

It happens every time regardless the file format. I tried with small mol2 files, pdb files downloaded straight from PDB, files generated by AMBER.

I partly overcome it with ">" sign at the end of command:

<add r> $ obabel -ipdb file.pdb -opdb a.pdb -d > a.pdb

Then it gives proper albeit doubled result.

## Steps to Reproduce

Have a fresh install of openbabel on Ubuntu 20.04 any convert any file with obabel

**Comment by ghutchis** [comment]
The syntax of `obabel` is different from the old `babel` command. Try:

`obabel file.pdb -O a.pdb -d # obabel can detect file types by their extension`

The -O flag indicates the output filename.

**Comment by Rmadeye** [comment]
Looks like I was too accustomed to old syntax and that's what caused the problem..

Thank you very much sir
