### ISSUE TITLE
ValueError: inchikey is not a recognised Open Babel format

### ISSUE THREAD

**Issue by koyurion** [openbabel/openbabel#2194]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version:windows  anaconda python2.7.18

## Actual Behavior

`Error
Traceback (most recent call last):
  File "D:\anaconda\envs\my-python2.7\lib\unittest\case.py", line 329, in run
    testMethod()
  File "E:\plip-stable\plip\test\test_literature_validated.py", line 469, in test_1aku
    tmpmol.characterize_complex(ligand)
  File "E:\plip-stable\plip\modules\preparation.py", line 1409, in characterize_complex
    lig_obj = Ligand(self, ligand)
  File "E:\plip-stable\plip\modules\preparation.py", line 1003, in __init__
    self.inchikey = self.molecule.write(format='inchikey')
  File "D:\anaconda\envs\my-python2.7\lib\site-packages\pybel.py", line 527, in write
    format)

**ValueError: inchikey is not a recognised Open Babel format`**

environment info:
![image](https://user-images.githubusercontent.com/32454333/81146499-fec8b480-8faa-11ea-9433-65d6ea99796b.png)

**Comment by fredrikw** [comment]
OpenBabel 2.4.1 is rather old, but on the other hand there are no newer conda-forge package for python 2.7 on windows. I would upgrade both Python and OpenBabel if I was you.

That said, can you get an inchikey if you use the command line?
`echo c1ccccc1Br | babel -ismi -oinchi -xK` or `obabel -ismi -:"c1ccccc1Br" -oinchi -xK`

**Comment by koyurion** [comment]
it said: "babel: cannot write output format!"
> (my-python2.7) C:\Users\kk>echo c1ccccc1Br | babel -ismi -oinchi -xK or obabel -ismi -:"c1ccccc1Br" -oinchi -xK
> babel: cannot write output format!
> Open Babel 2.4.1 -- Jan 19 2019 -- 10:35:25
> Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>
> Try  -H option for more information.
> 
> WARNING: babel is deprecated and will be removed in a future release
>          of Open Babel. You should use obabel instead. For information
>          on the differences please see:
>              http://openbabel.org/docs/current/Command-line_tools/babel.html

**Comment by fredrikw** [comment]
I was a bit unclear, it was two different commands. So try again with only
`obabel -ismi -:"c1ccccc1Br" -oinchi -xK`

**Comment by koyurion** [comment]
![image](https://user-images.githubusercontent.com/32454333/81164432-ed8ba200-8fc2-11ea-869d-71ec407369e1.png)

**Comment by fredrikw** [comment]
I now remembered that there was an issue with the Windows conda builds regarding Inchi support. The actual bug was fixed in https://github.com/openbabel/conda-openbabel/pull/4 but the CI builds failed so there is no working Conda-build with Inchi support for Windows Python 2.7. If you really need to work with Python 2.7 you could try to clone https://github.com/openbabel/conda-openbabel/ and run `conda build` yourself.

**Comment by ghutchis** [comment]
I'd strongly suggest moving away from Python 2.7. I doubt any future versions of Open Babel will test against this.

**Comment by koyurion** [comment]
Thanks @fredrikw @ghutchis，I‘m now trying to use python3 instead. Thanks again~
