### ISSUE TITLE
OpenBabel3_LIBRARY cmake variable not populated

### ISSUE THREAD

**Issue by antonio-rojas** [openbabel/openbabel#2196]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.0
Operating system and version: Linux x86_64

## Expected Behavior
OpenBabel3_LIBRARY is correctly set in OpenBabel3Config.cmake

## Actual Behavior
OpenBabel3_LIBRARY is empty. I suppose it should be OpenBabel3_LIBRARIES instead.

**Comment by ghutchis** [comment]
Can you please submit a patch / pull request? Happy to make a 3.1.1 release to fix these packaging issues.

**Comment by baoilleach** [comment]
Pinging @dkoes - didn't you sort out something along these lines recently?

**Comment by dkoes** [comment]
Yes, is this bug report for master or a release version?  I would have though this commit would fix the issue: cd5f7fa6b00bce871a2a8109e030aae5dd35e990

**Comment by antonio-rojas** [comment]
In d387295788c4a7cfbafaca12ec5d555660245056 you renamed OpenBabel3_LIBRARY to OpenBabel3_LIBRARIES, but only in CMakeListst.txt, not in OpenBabel3Config.cmake.in

**Comment by dkoes** [comment]
Okay, someone make an executive decision - LIBRARY or LIBRARIES?

I obviously cannot be trusted.  LIBRARY makes more sense to me, but historically LIBRARIES has been used (https://github.com/nextmovesoftware/ecfp/blob/master/cmake/modules/FindOpenBabel.cmake)

**Comment by baoilleach** [comment]
The cmake convention is LIBRARIES.

**Comment by ghutchis** [comment]
@antonio-rojas - let me know if #2196 solves this for you.

**Comment by antonio-rojas** [comment]
Yes, it looks OK now

**Comment by ghutchis** [comment]
@antonio-rojas - do you think with the various cmake fixes, that we should spin a 3.1.1 release (i.e. to help packaging?)

**Comment by antonio-rojas** [comment]
Yes please - I'm trying to port kalzium downstream but it can't be done properly until these fixes are released

**Comment by ghutchis** [comment]
okay, i opened #2207 - hopefully it shouldn't take long to resolve the FreeBSD compile issues.
