### ISSUE TITLE
Missing Boost dependency in cmake config file

### ISSUE THREAD

**Issue by antonio-rojas** [openbabel/openbabel#2197]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.0
Operating system and version: Linux x86_64

## Expected Behavior
The openbabel cmake target depends on Boost::system, but that target is not defined unless the Boost cmake config is imported. There should be a find_dependency(Boost) in openbabel cmake config.

**Comment by ghutchis** [comment]
Can you submit a patch / diff? The main problem seems to be with the MAEPARSER bits, but cmake is not my strongest proficiency.

**Comment by antonio-rojas** [comment]
Wait, is boost::system actially used anywhere? This was introduced in 15601ca09353e1c1172cb0c809301a3ddd6908a4, but the only bits that remain from that commit are the cmake changes. Is it a leftover?

**Comment by baoilleach** [comment]
Maybe @dkoes can take a look?

**Comment by ghutchis** [comment]
@antonio-rojas - can you take a look at the fix in #2200

**Comment by antonio-rojas** [comment]
Doesn't work, now the cmake target depends on even more boost libraries
```
set_target_properties(openbabel PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/libmaeparser.so;/usr/lib/libcoordgen.so;/usr/lib/libm.so;dl;/usr/lib/libz.so;Boost::program_options;Boost::iostreams;Boost::unit_test_framework;-lpthread"
)
```
I think the `if(Boost_FOUND)` block starting at src/CMakeListst.txt:251 needs to be removed completely, since libopenbabel doesn't use any (dynamic) boost libraries.

**Comment by dkoes** [comment]
libcoordgen and libmaeparser are configured to require boost (although it looks like only maeparser links in a library - boost_iostream).  If I remember correctly, there was some discussion about this at the time and the consensus (but not unanimous opinion) was including boost dependencies for extra features that are not required is okay.

What is the goal? To build without boost?

**Comment by antonio-rojas** [comment]
No, the goal is that the openbabel cmake target doesn't depend on things it doesn't use. libopenbabel itself (not talking about libmaeparser) doesn't use boost, so it shouldn't link to it. And if it did, then the dependency must be declared in the cmake config file, otherwise the boost:: targets can't be resolved.

**Comment by antonio-rojas** [comment]
Just to illustrate what this issue is about, here's a test CMakeLists.txt
```
find_package(OpenBabel3)
add_library(lib lib.cpp)
target_link_libraries(lib openbabel)
```
If you run it (with 3.1.0), you will get an error
```
  Target "lib" links to target "Boost::system" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by dkoes** [comment]
Removing line 255 from src/CMakeLists.txt (`    target_link_libraries(openbabel ${Boost_LIBRARIES} )
`) should fix the issue, yes?

**Comment by antonio-rojas** [comment]
It should, yes

**Comment by dkoes** [comment]
Although I can build removing that whole if block, as you suggested, which I find surprising and worrisome - why do we no longer need the thread dependencies?

**Comment by antonio-rojas** [comment]
In my case I found -pthread was being added to CXXFLAGS by wxwidgets. Removing wxwidgets still builds fine, but the resulting libopenbabel has undefined symbols (from libpthread underlinking)
The same happens if I build without boost, so it seems pthread linking should be enabled regardless of whether boost is found or not.

**Comment by dkoes** [comment]
#2197 #2205

**Comment by ghutchis** [comment]
Closing this particular issue, thanks!
