### ISSUE TITLE
C++ compilation errors (clang-9)

### ISSUE THREAD

**Issue by yurivict** [openbabel/openbabel#2206]
```
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/spacegroup.cpp:360:39: error: reinterpret_cast from 'nullptr_t' to 'OpenBabel::transform3d *' is not allowed
    return (i == m_transforms.end())? reinterpret_cast<transform3d*>(NULL): *i++;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/spacegroup.cpp:367:39: error: reinterpret_cast from 'nullptr_t' to 'OpenBabel::transform3d *' is not allowed
    return (i == m_transforms.end())? reinterpret_cast<transform3d*>(NULL): *i++;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

```
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/align.cpp:448:14: error: C-style cast from 'nullptr_t' to 'double' is not allowed
      return (double) NULL;
             ^~~~~~~~~~~~~
```

```
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/spacegroup.cpp:360:39: error: reinterpret_cast from 'nullptr_t' to 'OpenBabel::transform3d *' is not allowed
    return (i == m_transforms.end())? reinterpret_cast<transform3d*>(NULL): *i++;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/openbabel/work/openbabel-openbabel-3-1-0/src/math/spacegroup.cpp:367:39: error: reinterpret_cast from 'nullptr_t' to 'OpenBabel::transform3d *' is not allowed
    return (i == m_transforms.end())? reinterpret_cast<transform3d*>(NULL): *i++;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

There are a lot of warnings too, some of which might indicate serious problems. for example:
```
            while(p1!=s1.end() && isdigit(*p1++)); --p1;
                                                 ^
```

Could you please rebuild with clang and fix all errors and warnings?

**Comment by ghutchis** [comment]
Can you tell me your flags? We have multiple clang builds, including my development on Mac. I don't get errors.

(Warnings.. that's a separate thing based on needing to run the codebase through some modernization.)

**Comment by ghutchis** [comment]
Mac clang 10 / 11
https://github.com/openbabel/openbabel/runs/654378735?check_suite_focus=true

Linux clang-7 on Travis
https://travis-ci.org/github/openbabel/openbabel/jobs/684435172

**Comment by yurivict** [comment]
My compiler is clang-9
NULL-related issues are due to NULL being defined as '0' on FreeBSD. In a C++ code you should use ```nullptr``` instead.

**Comment by yurivict** [comment]
The C++ standard https://en.cppreference.com/w/cpp/types/NULL says

> an integer literal with value zero, or a prvalue of type std::nullptr_t | (since C++11)

FreeBSD chose the former, while Linux chose the latter.

In case of the first choice many uses like in the error messages become invalid, therefore ```NULL``` can't be used in a valid C++ on all OSes.

**Comment by ghutchis** [comment]
Let me know if #2208 does it for you. If you know a way to test via GitHub actions, I'd be happy to add to the builds - I guess a Dockerfile build?

**Comment by ghutchis** [comment]
Looks like this is resolved, so I'm closing this.
