### ISSUE TITLE
Wrong canonical smiles from molfiles when NH3+ present.

### ISSUE THREAD

**Issue by cleblond** [openbabel/openbabel#2209]
When I convert the following molfile (anilinium ion) to smiles the smiles is wrong.  This is the smiles generated [NH2+]c1ccccc1.  Shouldn't it be [NH3+]c1ccccc1?

This is the command I use
obabel -imol -ocan --title

It seems to occur anytime there is an sp2 C connected to the N and the nitrogen has + charge and implied H's.

Molecule Name
  ChemDodl05082006282D 0   0.00000     0.00000     0
[Insert Comment Here]
  7  7  0  0  0  0  0  0  0  0  2 V2000
    0.0000    0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8660   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8660   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8660   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8660   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    1.5000    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  1  2  0  0  0  0
  1  7  1  0  0  0  0
M  CHG  1   7   1
M  END

**Comment by baoilleach** [comment]
The formatting is messed up of your mol file so I can't test it directly (you should attach it next time).

It seems to work fine for me with the current version of OB. My guess is that you are using an old version.

**Comment by cleblond** [comment]
Yes the issue is I was using old obabel (2.3.2).  2.4.1 seems to work.
Sorry to waste your time.
Thanks
