### ISSUE TITLE
Error in conversion of SMILES to Gaussian input with 3D coordinates 

### ISSUE THREAD

**Issue by cpfpengfei** [openbabel/openbabel#2210]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.0
Operating system and version: CentOS Linux 7 and Windows 10

## Expected Behavior
I am trying to use openbabel to convert molecules from their SMILES format to their gaussian input format (.gjf) with 3D coordinates (--gen3d enabled). Tried different versions of openbabel: 2.4.1, 3.0, and the recent 3.1.0 release but all of these versions fail to accurately convert a type of structures. I am using Python 3 and openbabel through the command line. 

## Steps to Reproduce
For example, this is the line used:
obabel -:"C(=Cc1c2scnc2cc2ncsc12)c1cncc2ccccc12" -O mol.gjf --gen3d

The expected structure: 
![image](https://user-images.githubusercontent.com/28598792/81405058-82c89b00-9169-11ea-9fd1-b2a49c3a7471.png)

## Actual Behavior
For the example above, after the gjf file is obtained, this is its structure when visualized on Chem3D:
![image](https://user-images.githubusercontent.com/28598792/81404718-be169a00-9168-11ea-8aa2-020ab861ccde.png)

This is the error log:
![image](https://user-images.githubusercontent.com/28598792/81405308-f7033e80-9169-11ea-9371-7a8df1fe6a40.png)

Rings containing nitrogen, particularly azoles, would lose its aromaticity after the gjf conversion. This is a repeated problem for similar structures as well.

Thank you for your help and for developing this tool and package. Cheers!

**Comment by ghutchis** [comment]
I don't know anything about viewing a Gaussian input with ChemDraw / Chem3D.

I'm not sure how you installed Open Babel, but it definitely is having problems finding data files, which can certainly be a problem (e.g., no coordinate cleanup).

What I can say is that using OB 3.1 with a full installation, your SMILES generates this (in Avogadro):
<img width="880" alt="Screen Shot 2020-05-08 at 10 04 17 AM" src="https://user-images.githubusercontent.com/41128/81413505-8d584580-9113-11ea-8b59-c8eb403be6a2.png">

I've attached a SDF file - you'll need to rename the extension from txt to .mol or .sdf for it to work:
[2210.txt](https://github.com/openbabel/openbabel/files/4599404/2210.txt)

**Comment by cpfpengfei** [comment]
Thanks for your help! How do I fix the problems of finding data files and no coordinate cleanup? I installed the 3.1 GUI and the conversion from SMILES to GJF with "Generate 3D Coordinates" does not work too. The coordinates are all set to 0.

**Comment by cpfpengfei** [comment]
Hi, I tried to convert from SMILES to mol with openbabel and it managed to convert successfully. But when converted from SMILES to gjf or from the generated mol to gjf, there is a loss of N=C double bond as per the example above. Do you know what could be the problem when the 3D coordinates are converted over from mol to gjf? 

Using Avagadro, I can view the mol file with no problem, but it can't seem to read gjf files?

Many thanks!

**Comment by ghutchis** [comment]
Avogadro uses Open Babel - which does not read Gaussian input files. I've seen far too many strange ones.

There's no "loss of N=C" bond. When you save to XYZ, etc. a program has to interpret the bonds from coordinates, while in the MOL file itself, the bond orders are stored.

I can promise that the atoms are not moving upon file conversion, and Gaussian calculations do not need bond orders to run correctly.

**Comment by cpfpengfei** [comment]
Okay, it makes sense now, thank you!
