### ISSUE TITLE
testdistgeom.py fails when run with Python 3

### ISSUE THREAD

**Issue by jcbollinger** [openbabel/openbabel#2217]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: CentOS 8.1

## Expected Behavior
After a successful build, all tests should pass.

## Actual Behavior

> 99% tests passed, 1 tests failed out of 229
> 
> Total Test time (real) = 137.16 sec
> 
> The following tests FAILED:
>         218 - pytest_distgeom (Failed)
> 

## Steps to Reproduce
 1. Perform an ordinary `cmake` / `make` build.
 2. in the build directory, run `make test`

## Additional Comments
On CentOS 8, the test runner apparently recognizes that the platform Python is Python 3.6, and uses that to run this test.  Running the failing test directly with Python 3 also fails, and this shows that the issue arises from incorrect (for Python 3) character escaping.  The same test passes in the same environment when run with Python 2.7.

**Comment by xtj87515** [comment]
Hello, I'm having the same exact issue although I thought this was already fixed?

**Comment by fredrikw** [comment]
As mentioned in my comment in #2578, this was fixed after the release of 3.1.1 so the question is if you use the trunk version?

**Comment by xtj87515** [comment]
I downloaded the source code from:
https://github.com/openbabel/openbabel/releases/tag/openbabel-3-1-1.

I tried both: openbabel-3.1.1-source.tar.bz2
<https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2>
 and Source code
<https://github.com/openbabel/openbabel/archive/refs/tags/openbabel-3-1-1.zip>
 (zip)
<https://github.com/openbabel/openbabel/archive/refs/tags/openbabel-3-1-1.zip>
.

Both of their openbabel3.1.1/test/testdistgeom.py files were still in their
"pre-fix" version according to the bug journal
<https://github.com/openbabel/openbabel/pull/2218/commits/7de27f309db5f7ec026ef5c5235e5b33bf7d1a85#diff-b0c1c91ef890aac128d98b666512172136a7b4d49ec74b5bf7f5f3922b0837d4L50>.
I manually changed line 45-51 according to the journal and that then fixed
my failed test "test_distgeom".

**Comment by fredrikw** [comment]
So, to conclude, the issue is still fixed.
