### ISSUE TITLE
Appveyor tests are failing because an environment issue

### ISSUE THREAD

**Issue by jcbollinger** [openbabel/openbabel#2222]
- [ ] I believe this to be a bug with Open Babel
- [X] I believe this to be a bug with Open Babel's CI framework
- [ ] This is a feature request

## Environment Information
GitHub

## Expected Behavior
Automated appveyor tests should evaluate the code under test.

## Actual Behavior
Automated appveyor tests of new PRs are failing over an issue with the test environment, independently of the code under test.  Example diagnostic message:

> LINK : fatal error LNK1104: cannot open file 'C:\msvc-dependencies-master\libs-common\i386\zlib1.lib' [C:\openbabel\build\src\openbabel.vcxproj]

## Steps to Reproduce
Submit a pull request.

**Comment by ghutchis** [comment]
We've been looking at discontinuing Appveyor vs. the GitHub action builds on Windows, which have much more generous time limits.

**Comment by baoilleach** [comment]
I believe this is now fixed.
