### ISSUE TITLE
Undefined behavior in OBForceFieldUFF::ParseParamFile()

### ISSUE THREAD

**Issue by jcbollinger** [openbabel/openbabel#2223]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: CentOS 8.1

## Expected Behavior
 1. OpenBabel should not attempt out-of-bounds array accesses.
 2. OpenBabel's tests should pass when compiled with GCC 8 and the `-Wp,-D__GLIBCXXX_ASSERTIONS` option

## Actual Behavior
While parsing "param" lines, `OBForceFieldUFF::ParseParamFile()` attempts to access a third byte of each atom type string, even when there are only two (including C string terminator).  The deuterium parameters in the default UFF.prm file provided by OpenBabel trigger this misbehavior in practice.  If symbol `__GLIBCXX_ASSERTIONS` is defined when building OpenBabel with GCC 8 then tests `test_regressions_1794` and `test_ffuff_1` fail.

## Steps to Reproduce
The access attempt is visible by inspection at [forcefields/forcefielduff.cpp:1650](https://github.com/openbabel/openbabel/blob/master/src/forcefields/forcefielduff.cpp#L1650) (it's even commented), and the single-character deuterium atom type can be seen at [data/UFF.prm:152](https://github.com/openbabel/openbabel/blob/master/data/UFF.prm#L152).

The test failures can be reproduced by building with g++ of GCC 8.3, and providing hardening options via the environment, then running the tests.  For example,

```
mkdir build
cd build
export CXXFLAGS="-O2 -Wp,-D_GLIBCXX_ASSERTIONS"
cmake ..
make
make test
```

## Additional Comments
I discovered this while packaging OpenBabel into an RPM.  By default, RedHat's rpm macros supply hardening options to software builds, including defining the `__GLIBCXX_ASSERTIONS` macro.

**Comment by ghutchis** [comment]
I'd be happy to have the GitHub actions test RPM builds so we can provide initial release binaries too. Can you give me the full set of flags?

I've been looking at, e.g. https://github.com/marketplace/actions/build-an-rpm

**Comment by jcbollinger** [comment]
Would you like an RPM .spec file, or would you prefer just the build flags?

**Comment by ghutchis** [comment]
A .spec would be great.

**Comment by jcbollinger** [comment]
I'm still working on the RPM, but I will provide a spec when I am satisfied with it, perhaps as soon as later today.  In the meantime, here are the relevant parts of the expansion of the `%cmake` rpm macro of CentOS 8.1 (Fortran flags are omitted, as are CMake options pertaining to specifying installation directories):

```
CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection}" ; export CFLAGS ;
CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection}" ; export CXXFLAGS ;
LDFLAGS="${LDFLAGS:--Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}" ; export LDFLAGS ;
  /usr/bin/cmake \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DBUILD_SHARED_LIBS:BOOL=ON
```

That was generated by trimming the output of the command `rpm --eval %cmake`.  The various flags do contain one or two things that probably need to be removed or changed for non-RedHat platforms (*i.e.* the ones with "redhat" in them).

**Comment by jcbollinger** [comment]
@ghutchis , as promised, I am attaching two RPM spec files.  `openbabel.spec` is the one I am using to build my RPMs, whereas `openbabel-ci.spec` is a modified version intended for use in a CI role.  The most significant difference between the two is that the latter does not designate any patches (which I haven't provided anyway), since I imagine that it would be used to test the actual contents of the repository at various points.

There is more that could be done to tune and trim the -ci spec for the role I imagine for it, but I think it would be better to base further changes on what you *actually* need instead of on what I guess you might need.

[openbabel.spec.txt](https://github.com/openbabel/openbabel/files/4650857/openbabel.spec.txt)
[openbabel-ci.spec.txt](https://github.com/openbabel/openbabel/files/4650858/openbabel-ci.spec.txt)

(".txt" was appended to the file names to persuade GitHub to accept them.)

If you would prefer to receive one or both of these in the form of a PR, then I would be happy to oblige -- just give me the details of what you want, where.

**Comment by jcbollinger** [comment]
I should also note that these specs do not provide for any of the language bindings other than Python.  Such could certainly be added, but I cannot presently justify devoting effort to that myself.
