### ISSUE TITLE
cmake question & make test error

### ISSUE THREAD

**Issue by koyurion** [openbabel/openbabel#2234]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:3.1.1
Operating system and version:  Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)

## Expected Behavior

After building OpenBabel I expected ctest to run all the tests and for them all to pass
## Actual Behavior

run this command twice:  **cmake ../../openbabel-2.4.1 -DPYTHON_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=~/softwares/openbabe**

-- Using included inchi library.
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
-- Checking available shared pointer...
-- Use std::shared_ptr in memory
-- Could NOT find Boost
-- Could NOT find Boost
-- Maestro formats will NOT be supported. Please install Boost to enable Maestro formats.
-- Coordinate generation with Coordgen will NOT be supported. Please install Boost to enable Maestro formats.
-- Could NOT find RapidJSON (missing: RAPIDJSON_INCLUDE_DIRS) (Required is at least version "1.1.0")
-- JSON formats will be supported. Using RapidJSON 1.1.0 at /home/kk/openbabel-openbabel-3-1-1/external/rapidjson-1.1.0/include
-- Cairo found. PNG output will be supported.
-- Could NOT find Boost
-- Could NOT find Boost
-- Attempting to build the GUI
--    wxWidgets not found => GUI will not be built
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "2.0")
-- SWIG 2.0 NOT found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kk/build

**make test**
97% tests passed, 6 tests failed out of 227

Total Test time (real) =  64.56 sec

The following tests FAILED:
        221 - pybindtest_bindings (Failed)
        222 - pybindtest__pybel (Failed)
        223 - pybindtest_example (Failed)
        224 - pybindtest_obconv_writers (Failed)
        225 - pybindtest_cdjsonformat (Failed)
        226 - pybindtest_pcjsonformat (Failed)
Errors while running CTest
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 8

## Steps to Reproduce

1. download  the sourse code(openbabel-openbabel-3-1-1.tar.gz)
2.  sudo apt install libboost-dev
3. sudo apt install gcc g++ make cmake
4.  sudo apt install libxml2-dev zlib1g-dev libcairo2-dev libeigen3-dev libopenbabel-dev
5. sudo apt install python3-dev
6. tar -xzvf openbabel-openbabel-3-1-1.tar.gz
7. mkdir build
8. cd build
9. cmake ../../openbabel-2.4.1 -DPYTHON_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=~/softwares/openbabel 
10. make
11. make test

**Comment by baoilleach** [comment]
Step 9 has 2.4.1. Reopen if still a problem with 3.1.1

**Comment by koyurion** [comment]
Hi, it was 3.1.1, I copied the wrong command by mistake.

**Comment by baoilleach** [comment]
Step 1 has openbabel-openbabel-3-1-1.tar.gz but the release has openbabel-3.1.1-source.tar.bz2.

**Comment by ghutchis** [comment]
If you don't have SWIG and you download the "default" GitHub packages, it won't have the Python bindings. That's why we provide the openbabel-3.1.1-source.tar.bz2 file. Without that, you need SWIG.
