### ISSUE TITLE
Atom chirality calculation

### ISSUE THREAD

**Issue by JinHuan95** [openbabel/openbabel#2237]
Does openbabel provide a functionality to calculate atom chirality given a molfile representation? I guess the obchiral can only detect whether an atom is chiral or not without classification of R/S.
Thanks so much!

- [ ] I believe this to be a bug with Open Babel
- [x] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by baoilleach** [comment]
For questions about OB, please use our mailing list.

If you specifically want the R/S symbols used in systematic IUPAC nomenclature, the answer is no. If you want to know the relative arrangement of atoms, then yes. That functionality is described in the documentation: https://open-babel.readthedocs.io/en/latest/Stereochemistry/stereo.html
