### ISSUE TITLE
mis-detection of aromaticity for quinones

### ISSUE THREAD

**Issue by i-lengyel** [openbabel/openbabel#2263]
Openbabel version 3.1, and perhaps former versions looking at ring-fragments.txt file, mis-identifies aromatics when O=C1C=COC=C1 ring fragments are present. Instead of the quinoidal structure, openbabel converts it to O=c1ccocc1, which is certainly wrong.  With version 3.1 there is no way even to convert it to Kekule form, which could fix this problem as it could not distribute the bonds correctly. With increasing version number it is a step back in functionality.   Wrong way to go honestly.  Anyone knows if it is possible to fix this with modifying the bondtyp.txt file or some other?
The problem may originate from Geoff Huchinson's years back statement and aromatic detection implementation, that out-of ring double bonds to an aromatic carbon does not break aromaticity of the ring. It certainly does. That C1 carbon now has too many electrons and bonds of course.  An xyz file is below that fails.  If you would look at the same molecule with Avogadro, it detects the bonds perfectly.  Perhaps they don't use openbabel for bond-detection, only for molecule conversion.  
----
17

C          2.55040       -0.73410        0.11530
C          1.24130       -0.01430       -0.01140
C          1.16330        1.30960       -0.24480
O         -0.00100        1.99450       -0.36510
C         -1.16460        1.30860       -0.24470
C         -1.24140       -0.01540       -0.01130
C          0.00030       -0.79380        0.12670
O          0.00090       -2.00280        0.34090
C         -2.54980       -0.73650        0.11560
H          3.39890       -0.05810       -0.00790
H          2.61890       -1.53020       -0.63070
H          2.62260       -1.22050        1.09180
H          2.01430        1.96810       -0.36130
H         -2.01620        1.96620       -0.36110
H         -2.61770       -1.53250       -0.63070
H         -2.62140       -1.22310        1.09190
H         -3.39900       -0.06120       -0.00740

**Comment by i-lengyel** [comment]
Found a temporary fix, just had to use opt={k:1} when writing the SMILES code.  Rather than  relying on the default smiles writer, use the kekule option whenever there are =c, c=, c(= patterns.

**Comment by ghutchis** [comment]
If you'd like to have a broader discussion of aromaticity in SMILES, please feel free to bring it up on the mailing list. I would certainly agree that quinoids like your example should be better represented with a Kekule form. The rule is a bit more complicated though because most people would want to see O=C(C1=C2C=CC=C1)NC2=O as aromatic: O=c(c1ccccc12)[nH]c2=O
