### ISSUE TITLE
Bug in obtautomer

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#227]
If I run vinyl ether through the obtautomer, it strips the double bonds, but only if I ask for the canonical tautomer.

obtautomer ~/foo.smi
C=COC=C

obtautomer -c ~/foo.smi
CCOCC

**Comment by jeffjanes** [comment]
I've tried to figure this out, but haven't made any progress.

If we can't fix it before 2.4.0, we should probably de-document the switch.

**Comment by baoilleach** [comment]
We document how things *should* work.      The bug tracker is for recording
differences in practice.

**Comment by baoilleach** [comment]
Still a problem even with #1576. Here I have...
[CH2][CH]O[CH][CH2]
...for the canonical tautomer

**Comment by serval2412** [comment]
I just noticed that if I apply this patch:
diff --git a/src/tautomer.cpp b/src/tautomer.cpp
index 8322110f..84726ebd 100644
--- a/src/tautomer.cpp
+++ b/src/tautomer.cpp
@@ -638,7 +638,7 @@ namespace OpenBabel {
       std::vector<Level> levels;
       EnumerateRecursive(mol, atomTypes, bondTypes, canonAtoms, numHydrogens, levels, functor);
 
-      if (!canonical) {
+      if (canonical) {
         // Restore original bond orders
         FOR_BONDS_OF_MOL (bond, mol)
           bond->SetBondOrder(bondOrders[bond->GetIdx()]);

I got "C=COC=C" in both situations, with and without -c flag.

**Comment by serval2412** [comment]
I know a little about C++ programming but almost nothing about chemistry (level high school only), would it be possible to have a simple example with corresponding 2 expected result depending on "-c" presence?

**Comment by jeffjanes** [comment]
In this highly simplified case, I would expect the output to be just one line, C=COC=C, both with and without the -c flag.

In the general case, the line returned with the -c option must be a member of the set of lines which are returned without the -c option.

**Comment by serval2412** [comment]
Indeed, I got this:
The following tests FAILED:
	 25 - test_canonstable_1 (Failed)
	113 - test_tautomer_2 (Failed)
Then I used test_runner and had this:
julien@debian:~/projects/openbabel/build/bin$ ./test_runner tautomertest 2
/home/julien/projects/openbabel/test/tautomertest.cpp:74: canonicalTautomers.size() == unsigned(1) [15 == 1] (FAIL)

**Comment by baoilleach** [comment]
Fixed by #2171.
