### ISSUE TITLE
Is Pybel deprecated and no longer available in openbabel conda distribution?

### ISSUE THREAD

**Issue by ffangliu** [openbabel/openbabel#2279]
Dear Developers,

I just found that if I install the new open babel version with conda from the conda-forge channel, I got errors in importing pybel.

However, if I install the deprecated version from the openbabel conda channel, I can import pybel without problem.

Is pybel deprecated? Or it may be caused by other issues of my computer? I am using Mac OS Catalina 10.15.6.

Thanks

- [x ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:  openbabel-3.1.1
Operating system and version: Mac OS Catalina 10.15.6.

## Expected Behavior
import pybel should work.

## Actual Behavior
ModuleNotFoundError: No module named 'pybel'

## Steps to Reproduce
On Mac OS Catlina, create a conda environment with python3.7, then install openbabel from the conda-forge channel: https://anaconda.org/conda-forge/openbabel

Once finished, enter python interpreter:
>>> import pybel

**Comment by ghutchis** [comment]
If you are using Open Babel > 3.0, you will need to update code. This has been mentioned in release docs, etc.

https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#python-module

**Comment by ffangliu** [comment]
> If you are using Open Babel > 3.0, you will need to update code. This has been mentioned in release docs, etc.
> 
> `from openbabel import pybel`
> 
> https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#python-module
> 
> Hope that helps!

Thanks! That really helps.

Best,
Fang

**Comment by ghutchis** [comment]
No worries - reach out to the mailing list as well if you have questions / problems: openbabel-discuss @ lists.sf.net
