### ISSUE TITLE
Unknown space group from cif get default to P1 in pdb conversion

### ISSUE THREAD

**Issue by kartlee** [openbabel/openbabel#228]
![screen shot 2015-09-11 at 2 50 00 pm](https://cloud.githubusercontent.com/assets/5375690/9823677/d3893660-5895-11e5-8c89-3fb3ee07f049.png)
Hi,

I attached a snapshot of the Si_crystal.cif where the space group mentioned is not a valid HM symbol. As a result openbabel default to lowest group symmetry P1 in .pdb conversion. This is the git history about the commit which default to P1 - https://github.com/openbabel/openbabel/commit/61294446d0a5781823029f6eda9b81d27b2bf9b4

Here are my questions - 

1) Does the pdb standard say that if a space group is not recognized, we should default to P1?
2) Can we just ignore the space group? or CRYST1 record in this case instead? Or Have babel additionally include in the warning report - "Unknown space group (HM:F d 3 m,Hall:) with incomplete or wrong definition."  that space group will default to P1 ?

Let me know your opinion on this.

-Karthik

**Comment by ghutchis** [comment]
Closed - merged previous pull request.
