### ISSUE TITLE
undefined symbol: _ZTVN9OpenBabel32OBMinimizingEnergyConformerScoreE

### ISSUE THREAD

**Issue by rbharath** [openbabel/openbabel#229]
Hi,

I'm trying to build openbabel from the github source on an Ubuntu 12.04 box with gcc 4.81. I followed the directions provided on the website and ran cmake with the following arguments:

```
rbharath@rbharath-XPS13-9333:~$ cmake ~/openbabel -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DOPTIMIZE_NATIVE=OFF -DEIGEN3_INCLUDE_DIR=/home/rbharath/eigen-eigen-bdd17ee3b1b3 -DCMAKE_INSTALL_PREFIX=~/Tools/
```

The install finished successfully, but when I try to import openbabel from python, I get the following error:

```
In [1]: import openbabel
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2335afcc2805> in <module>()
----> 1 import openbabel

/home/rbharath/Tools/lib/python2.7/site-packages/openbabel.py in <module>()
     35                 fp.close()
     36             return _mod
---> 37     _openbabel = swig_import_helper()
     38     del swig_import_helper
     39 else:

/home/rbharath/Tools/lib/python2.7/site-packages/openbabel.py in swig_import_helper()
     31         if fp is not None:
     32             try:
---> 33                 _mod = imp.load_module('_openbabel', fp, pathname, description)
     34             finally:
     35                 fp.close()

ImportError: /home/rbharath/Tools/lib/python2.7/site-packages/_openbabel.so: undefined symbol: _ZTVN9OpenBabel32OBMinimizingEnergyConformerScoreE
> /home/rbharath/Tools/lib/python2.7/site-packages/openbabel.py(35)swig_import_helper()
     34             finally:
---> 35                 fp.close()
     36             return _mod
```

I saw this forum post (http://forums.openbabel.org/openbabel-Bugs-3277614-undefined-symbol-in-python-when-compiling-without-EIGEN2-td3431130.html) which mentioned that the same problem resulted when building without Eigen, but I've explicitly set the -DEIGEN3_INCLUDE_DIR flag. Is it possible that Eigen is being ignored somehow?

I'd greatly appreciate any help here. I've been banging my head against this problem for a few hours now with no headway.

**Comment by ghutchis** [comment]
Was this resolved?

**Comment by ghutchis** [comment]
I'm closing this as "works for me" - if you still have problems, please post to the mailing list.
