### ISSUE TITLE
Option -e is not working with --gen3D

### ISSUE THREAD

**Issue by ivok2002** [openbabel/openbabel#2291]
I'am trying to convert some SMILES to 3D SDF. Here is the command line:
obabel -i smi IN.smi -o sdf -O OUT.sdf -e --gen3D --fastest

Some of the SMILES could pass but the option -e is bypassed and the result is empty SDF file.

The error is:
*** Open Babel Error  in OpenBabel::OBBuilder::GetFragmentCoord
  Rigid fragment CC#CC=O in rigid-fragments.txt has all zero coordinates.

Example data (the last one passes):

CC#CC(=O)NC1=NC=C2C(=C1)C(=NC=N2)NC3=CC(=C(C=C3)F)Cl 1
C=CC(=O)NC1=CC=CC(=C1)C2=C(OC3=NC=NC(=C23)NC(CO)C4=CC=CC=C4)C5=CC=CC=C5 2
C=CC(=O)N1CCCC(C1)N2C3=NC=NC(=C3C(=N2)C4=CC(=C(C=C4)OCC5=CC=CC=N5)Cl)N 3
CCC(C)(COC(=O)N)COC(=O)NC(C)C 4

**Comment by nbehrnd** [comment]
With Open Babel as currently provided in Linux Debian 10 (release 3.1.0), I copy-pasted you test data into `IN.smi` and run the instruction you mention, i.e., `obabel -i smi IN.smi -o sdf -O OUT.sdf -e --gen3D --fastest`.

Contrary to your report, I did not observe any error report at all.  I then read the `.sdf` in an old instance of  Jmol (14.6.4_2016.11.05), the viewer recognized the presence of four models.  It was possible to display them one by one (on Jmol's console, this requires an input in pattern of `load "OUT.sdf" 1`) and the geometries do not look terribly skewed either.  Equally, there was no problem to import the `.sdf`import into [DataWarrior](http://openmolecules.org/datawarrior/index.html) (version 5.2.1, 2020) to write a `.dwar` file either.

It looks like the problem does not occur (any more) in a (more) recent version of Open Babel.

[3D_generation.zip](https://github.com/openbabel/openbabel/files/5673497/3D_generation.zip)
