### ISSUE TITLE
"ACE" residue ID in SDF -> PDB Conversion

### ISSUE THREAD

**Issue by DanielJamesEvans** [openbabel/openbabel#2303]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.4.1
Operating system and version: Mac OS 10.14.6 (Mojave)

## Expected Behavior
I expected OpenBabel to produce a pdb file where each atom has the same residue and chain name.

## Actual Behavior
Most atoms of the output pdb file have residue name "UNL" and no chain name.  But a single carbon has residue name "ACE" and chain name "A".

## Steps to Reproduce
First, change the extension of any of the files I attached from txt to sdf.  (I changed it to txt so GitHub would let me upload.)
Then run the following command: `obabel -isdf <ligand_name>.sdf -opdb -O <ligand_name>.pdb`

In all cases, the affected carbon is in a similar place: single-bonded to a ring and a nitrogen, and double-bonded to an oxygen.

The sdf files were taken from a large sdf file downloaded at https://chemoinfo.ipmc.cnrs.fr/MOLDB/index.php.  Here are the files:
[PEMETREXED_1.txt](https://github.com/openbabel/openbabel/files/5526316/PEMETREXED_1.txt)
[NATEGLINIDE_1.txt](https://github.com/openbabel/openbabel/files/5526317/NATEGLINIDE_1.txt)
[METHOTREXATE_1.txt](https://github.com/openbabel/openbabel/files/5526318/METHOTREXATE_1.txt)

**Comment by nbehrnd** [comment]
I started to convert your `.sdf` test files into `.pdb` by `obabel -isdf <ligand_name>.sdf -opdb -O <ligand_name>.pdb` with Open Babel (version 3.1.0 in Linux Debian, I suggest you check if you equally may update to this) and displayed them pairwise in an elder installation of Jmol (14.6.4_2016.11.05).  Only the conversion about `PEMETREXED_1.sdb` yielded a  reasonable display of the `.pdb` with different atom colors for C, H, N, O.

You know that Open Babel may read and write `.sdf` and `.pdb` files.  I knew there are multiple ways an `.xyz` or a `.pdb` file may be written and occasionally -- just for the sake of consistency -- I use Open Babel to «correct» these prior to further processing.  Thanks to your test files, I learn that this apparently equally is the case for `.sdf` files and I thus issued conversions in pattern of `obabel -isdf NATEGLINIDE_1.sdf -osdf -O NATEGLINIDE_1_rewritten.sdf` for both `NATEGLINIDE` and `PEMETREXED`, and then converted these by e.g., `obabel -isdf NATEGLINIDE_1_rewritten.sdf -opdb NATEGLINIDE_1_rewritten.pdb`.  The visualizations by Jmol then look considerably better.  Could such an edit equally be helpful for you?

The obvious question is about the difference between the original and the modified `.sdf` files.  According to a difference view with `vimdiff` (an extension of the vim editor) or [meld](http://meldmerge.org/) (version 3.20.2) is that both the number of columns in the upper part of the connectivity table increase, as well as the connectivities are in part defined differently.   Archive `format_problem.zip` contains the files mentioned and some screen photos taken along to address the issue.

[format_problem.zip](https://github.com/openbabel/openbabel/files/5673926/format_problem.zip)

**Comment by DanielJamesEvans** [comment]
Thanks for the helpful information!  Sorry for taking so long to reply.  I agree that the described solutions fix my issue.  Thanks a lot!
