### ISSUE TITLE
Cmake fails to find imported targets maeparser and coordgen

### ISSUE THREAD

**Issue by kebp** [openbabel/openbabel#2305]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: CentOS 8.2.2004

## Expected Behavior
I expected to be able to build a small C++ application that uses cmake and has openbable as a dependency.  This has worked with previous versions of openbabel in the 2.x.x line.

## Actual Behavior
The packages CMakeLists.txt includes the command 
    find_package(OpenBabel3 REQUIRED)
which successfully locates openbablel's OpenBabel3Config.cmake file but that generates the following error:

  Found package configuration file:

    ~/software/openbabel/3.1.1/lib/cmake/openbabel3/OpenBabel3Config.cmake

  but it set OpenBabel3_FOUND to FALSE so package "OpenBabel3" is considered
  to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: maeparser
  coordgen

**Comment by CoryKornowicz** [comment]
It was not included in the "INSTALL" file instructions, but you need to install maeparser from Schrodinger's repo, https://github.com/schrodinger/maeparser 

MacOS 11.0.1, Python 3.6.11

This worked for building python bindings too if you have SWIG installed.

**Comment by kebp** [comment]
I'm sorry but I'm still struggling with this.  Where do I find the is the OpenBabel "INSTALL" file and how should it be modified?

I'm pretty confident that maeparser was installed as part of the build process and that that's not the issue.  libmaeparser.so and libcoordgen.so are in openbabel/3.1.1./lib and appear to be findable by the openbabel executables. For example the output of 'ldd obabel' includes:

libmaeparser.so.1 => /home/kevin2/software/openbabel/3.1.1/lib/libmaeparser.so.1 (0x00007f8fd4ef6000)
libcoordgen.so.1 => /home/kevin2/software/openbabel/3.1.1/lib/libcoordgen.so.1 (0x00007f8fd4763000)

**Comment by kebp** [comment]
I've now been able to work round this issue by setting the required variables manually in my program's CMakeLists.txt:

set(OPENBABEL3_INCLUDE_DIR "/home/kevin2/software/openbabel/3.1.1/include/openbabel3")
set(OPENBABEL3_LIBRARIES "/home/kevin2/software/openbabel/3.1.1/lib/libopenbabel.so")

Program now works fine although I unfortunately I loose portability.  However it solves the immediate problem.
