### ISSUE TITLE
API documentation does not default to latest

### ISSUE THREAD

**Issue by RMeli** [openbabel/openbabel#2327]
The link [http://openbabel.org/api/](http://openbabel.org/api/) links to the API documentation of version `2.3`. I think it should link to the API documentation for the latest version by default (which I was unable to locate).

**Comment by nbehrnd** [comment]
The apparently latest API's documentation [on-line](https://open-babel.readthedocs.io/en/latest/UseTheLibrary/CppAPI.html) of OpenBabel (OpenBabel's main index [here](https://open-babel.readthedocs.io/en/latest/index.html)) equally does so, as well as the hyperlinks in  chapter 11.1 of the then generated .pdf ahead of the description relevant to e.g., C++ and Python.  It is worth noting chapter 11.8 «Updating to Open Babel 3.0 from 2.x» starts by

> «Open Babel 3.0 breaks the API in a number of cases, and introduces some new behavior behind-the-scenes. These
changes were necessary to fix some long standing issues impacting chemical accuracy as well as performance.
Here we describe the main changes, and how to change existing code to adapt.»

At present, the .pdf was created on June 14, 2020, possibly to reflect about OpenBabel 3.0.1.

**Comment by rwest** [comment]
I finally tracked down more recent documentation at https://open-babel.readthedocs.io/en/latest/index.html but it's frustrating that most of my queries on Google and a lot of links from openbabel.org point me to 2.3.1, whether for documentation or downloads. 

Even 
https://openbabel.org/docs/dev/
Which claims "
The latest version of this documentation is available in several formats from http://openbabel.org/docs/dev/." Is 2.3.1

I think there are many corners of openbabel.org that could be updated.

**Comment by RMeli** [comment]
Interestingly, [https://open-babel.readthedocs.io/en/latest/index.html](https://open-babel.readthedocs.io/en/latest/index.html) seems to still point to 3.0.1 despite the current version being 3.1.1

**Comment by nbehrnd** [comment]
Speculation: some counters are out of sync.

Observation/why I think so:  For the .pdf manual just fetched
again,[0] `$pdfinfo open-babel-readthedocs-io-en-latest.pdf` yields a
`Fri Mar 26 16:53:11 2021 CET` as creation date.  Though the headers
of this document state `Release 3.0.1`, this date is considerably
/after/ the time stamp about release 3.1.1 (May 8, 2020) displayed on
GitHub.[1]

(The nuisance of openbabel.org still looking like release 2.3.1 would
represent the most recent version still is humming.)

[0] https://open-babel.readthedocs.io/en/latest/
[1] https://github.com/openbabel/openbabel/tags

**Comment by ghutchis** [comment]
@RMeli - it's planned. I just haven't had the time.

This repo contains a rework of the website, intended to also include the readthedocs bits and updated API:
https://github.com/openbabel/openbabel.github.io
