### ISSUE TITLE
TypeError when using "InternalToCartesian" from python interface

### ISSUE THREAD

**Issue by WardLT** [openbabel/openbabel#2329]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

I am looking to update a molecule with new internal coordinates, but am running into difficulty with the `InternalToCartesian` function when using the Python interface to OpenBabel. It gives me an error about Type mismatch:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-36-435f8694755f> in <module>
      6 ics = mol.OBMol.GetInternalCoord()
      7 mol.OBMol.SetInternalCoord(ics)
----> 8 InternalToCartesian(ics, mol)

TypeError: in method 'InternalToCartesian', argument 1 of type 'std::vector< OpenBabel::OBInternalCoord *,std::allocator< OpenBabel::OBInternalCoord * > > &'
```

Any thoughts on how to correct or get around this error?

## Environment Information
Open Babel version: 3.1.1
Operating system and version: Windows Subsystem for Linux (Ubuntu 20.04)

## Expected Behavior
Works the same way as from the C++ interface. Molecule's internal coordinates changed based on new input structure.

## Actual Behavior

`TypeError` shown above.

## Steps to Reproduce

```python
from openbabel import pybel, InternalToCartesian

mol = pybel.readstring("smi", "CCCC")
mol.make3D()

ics = mol.OBMol.GetInternalCoord()
mol.OBMol.SetInternalCoord(ics)
InternalToCartesian(ics, mol.OBMol)
```

**Comment by ghutchis** [comment]
That's going to be a tricky Python wrapper to work through. Since many of the modifications you might want (bond length change, angle change, torsion change) are available in other methods, can you describe a bit of your use case?

**Comment by WardLT** [comment]
Thanks, @ghutchis !

I am looking to use openbabel to manipulate the torsion angles as part of a conformer optimization program. 

My original thought was to manipulate the internal coordinates directly but, after looking at `OBMol.SetTorsion`, the routes you suggest would probably work better. It both provides a Python-friendly interface and avoids other issues around dealing with the internal coordinates directly (e.g., making sure to rotate neighboring atoms correctly).

**Comment by ghutchis** [comment]
@WardLT - not sure how you're planning on doing conformer optimization, but send me an e-mail. We've been working on an efficient Bayesian toolkit - and yes, it uses OBMol.SetTorsion().
