### ISSUE TITLE
How can I keep atom labels in the output PDB

### ISSUE THREAD

**Issue by shaoqx** [openbabel/openbabel#2330]
## Environment Information
Open Babel version:  Open Babel 3.1.0
Operating system and version: Ubuntu 16.04.4 LTS

## Expected Behavior
protonate a ligand from a PDB file and save a protonated PDB that keeps the atom label (e.g.: C2A) and residue name.

## Actual Behavior
The PDB openbabel exported just leaves element type (e.g.: C) but not the original atom label (e.g.: C2A). And the residue name was changed to 'UNL' but not the original '4CO'.

## Steps to Reproduce
I tried using both the command line:
`obabel ligand_1.pdb -o pdb -O ligand_1_aH.pdb --p 7.0`
and also python API:
```
mol = next(pybel.readfile('pdb', path))
mol.OBMol.AddHydrogens(False, True, ph)
mol.write('pdb', out_path, overwrite=True)
```
This is a original pdb line:
`ATOM      2  C2A 4CO   371      66.999  58.130  14.636  1.00  0.00`
This is one after openbabel:
`HETATM    2  C   UNL     1      66.999  58.130  14.636  1.00  0.00           C  `
I want to keep the atom label and the residue name.

**Comment by nbehrnd** [comment]
Suggestion: If the content of the .pdb is not confidential, copy-paste the file into a folder and attach the then generated .zip archive to your question.  This allows to replicate your operation, and to narrow down what's going on here.

**Comment by shaoqx** [comment]
Thank you for your reply! Here is the ligand PDB I'm working on. (also updated the command line file name in the previous comment.)
[ligand_1.zip](https://github.com/openbabel/openbabel/files/6046190/ligand_1.zip)

**Comment by nbehrnd** [comment]
With openbabel 3.1.0 as provided in Linux Debian 11 / bullseye (branch testing) and your .pdb I performed the default protonation, i.e. `obabel -ipdb ligand_1.pdb -h -opdb add_h.pdb`.  The newly written .pdb lists all atoms including the label `4CO`, too.  Contrasting to the original file submitted, the new .pdb has an additional trailing column about the atom type.

For most of the protonation suggested, chemically speaking (number of protons added, spatial arrangement vs. C, N, O), the results look plausible.  The protonation of the phosphates _may_ be different.  In the export of the protonated structure as .svg, the P=O in the terminal monophosphate is represented differently, than the P=O in the diphosphates.   Possibly this is influenced on the P-O bond lengths determined.  For a test, I reduced the information available in the .pdb about the protonated ligand to a SMILES string and let the structure recreate; the then displayed structure recreated from the SMILES does look plausible.

Maybe this result already is good enough for your work.  Maybe further evidence about the protonation at the terminal phosphate is important for you -- I don't know?  Attached below, a .zip archive about the processing of the data so far.

[ligand_1_revision.zip](https://github.com/openbabel/openbabel/files/6055089/ligand_1_revision.zip)

**Comment by shaoqx** [comment]
Thank you so much for looking into my problem!
I tried `obabel -ipdb ligand_1.pdb -h -opdb -O add_h.pdb` in my environment and it results as you described. It kept the original atom label and the residue name. While, there are still 2 problems about this:
1. The `--p ph` flag and the python usage `mol.OBMol.AddHydrogens(False, True, ph)` still do not keep atom label and residue name, which the ph will make big difference on the result. In my result with ph=7.0, the phosphates are all deprotonated and openbabel gives a good formal charge along with the connectivity. 
2. Even in the way that keeps atom label and residue name, there's no different name for newly added Hydrogens. I looked into the naming rule of tleap in Amber and it is just simply adding element count after the element name.  Like this:
```
HETATM   59  H   UNL     1      66.036  57.777  14.518  1.00  0.00          H  
HETATM   60  H1  UNL     1      69.447  60.888  17.041  1.00  0.00          H  
HETATM   61  H2  UNL     1      67.790  60.750  17.415  1.00  0.00          H  
HETATM   62  H3  UNL     1      72.206  58.616  13.563  1.00  0.00          H  
```

I actually fixed my problem by writing a function in my workflow to fix the openbabel generated file (just count the element and give them new amber readable names.) 
Also I found some potential problems of the protonation function:
1. The protonation will be plausible only when I start from a raw PDB without H and connectivity. Weird H will be added if you start from a protonated PDB (like ligand_1_aH.pdb), or remove H first with openbabel and then add H. 

Thanks again for the help!

**Comment by shaoqx** [comment]
```    
    @classmethod
    def _fix_ob_output(cls, pdb_path, out_path):
        '''
        fix atom label in pdb_pat write to out_path
        ---------
        according to tleap output, the name could be just *counting* the element start from ' ' to number
        '''
        with open(pdb_path) as f:
            with open(out_path, 'w') as of:
                # count element in a dict
                ele_count={}
                pdb_ls = PDB_line.fromlines(f.read())
                for pdb_l in pdb_ls:
                    if pdb_l.line_type == 'HETATM' or pdb_l.line_type == 'ATOM':
                        ele = pdb_l.get_element()
                        # determine the element count
                        try:
                            # rename if more than one (add count)
                            ele_count[ele] += 1
                            pdb_l.atom_name = ele+str(ele_count[ele])
                        except KeyError:
                            ele_count[ele] = 0
                        of.write(pdb_l.build())
```
Here are my fix and part of the code.

[ligand_1_aH.zip](https://github.com/openbabel/openbabel/files/6056723/ligand_1_aH.zip)

**Comment by nbehrnd** [comment]
I think I understand your concern: reading the listed atoms, you want to see at one glance which hydrogen atom is bond to which of the set (C,N,O,P,S).  As far as I know, OpenBabel is not capable to do this for you.

In small molecule crystallography -- and your ligand, if crystallized once, may fit into this category -- _typically_ the non-hydrogen atoms are identified first.  Completing the structure solution, hydrogens are taken into consideration, too.  Depending on the programs used (maybe [ShelX](https://shelx.uni-goettingen.de/) and [Olex2](https://www.olexsys.org/olex2/) are staples for you), and the quality of the experimental data available, this may be easy, because there are templates to start with.  E.g., for a methyl group around a (sp^3) carbon, the program knows that three hydrogens in this tetrahedral arrangement at a certain (temperature dependent) distance to C usually is a good _initial_ guess.  And hence labels these hydrogens bound to `C1` as `H1A`, `H1B`, `H1C`, too.  This automatism to add hydrogens _and_ to label them according to their rooting atom _apparently_ is not / yet (completely) included by OpenBabel; worth a feature request.

This suggest of the three hydrogens, as well as their labels is a mere _optional suggestion_ by the program to the user.  S/He may decide to attribute experimental data to the hydrogens without this help, s/he may decide to label these as `H1`, `H52`, `H365`, too; the model is not better, or worse because of this, only less accessible to the next user deposit in the .cif format.  As shown in the example attached below, even if these labels _initially_ were organized well, the direct conversion `obabel -icif example.cif -opdb -O example.pdb` may render this attribution invisible.  A light-weight alternative thus may be, as shown, to read the initial .cif by Jmol, to write by Jmol an intermediate .pdb and to convert this file by OpenBabel into an eventually complete .pdb with header and detailed label information.  (Here, there was no explicit ligand attribution, though).  Or to try CCDC's Mercury program instead (reads both .cif and .pdb, may export .pdb, too).

[test_case.zip](https://github.com/openbabel/openbabel/files/6057253/test_case.zip)

**Comment by shaoqx** [comment]
I see. Thank you! So I think I do not really need those additional labeling information. I will be good with just H1, H2, etc.

**Comment by shaoqx** [comment]
Sorry for reopening this issue. I just found some new problem related to protonation and I think it's good to post here.
Here I have a ligand called EFE and I tried to protonated it with Openbabel. The structure is simple but the result is wrong I guess. I wondered in which scenario this would happen since I also have many successful ligand cases with Openbabel.
The command I used were:
`obabel -ipdb 1.pdb -h -opdb -O 2.pdb` or `obabel -ipdb 1.pdb -opdb -O 2.pdb --p 7.0` or in python with Pybel.
Input and output files are attached.
[EFE.zip](https://github.com/openbabel/openbabel/files/6073586/EFE.zip)

**Comment by nbehrnd** [comment]
Babel follows two separate approaches to protonate a structure, either toggle `-h`, or `-p` (and extensions of `-p`).

The use of `-h` is suitable to protonate a molecular backbone to fill valences of C, N, O etc. to render e.g., a naked core of benzene of the six carbon atoms, C6, into the uncharged form of C6H6.  The result will be a neuter, uncharged molecule.  I speculate this is behind the switch `Add hydrogens (make explicit)` if engaging the GUI of OpenBabel.

The toggle `-p` adds protons to a structure deemed suitable for a certain pH value.  Note: If not specified further, by an explicit number, `p` corresponds to a pH of 7.4 ([reference](https://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html?highlight=protonate), search section «If you want to add hydrogens appropriate for pH7.4 when doing the conversion the command would be:»)

Assuming the basicity of the cyclic amine in your ligand to be somewhere in the range between triethylamine and morpholine, I would be fine if `-p` protonates the amine to yield an ammonium.

However, check your input structure about the terminal sulfonic acid.  It can't be a group attached to an alkyl chain _and simultaneously_ thrice protonated.  What is the origin of your .pdb?  With all three S-O distances equal to 1.47 Angstrom, the picture is _more likely_ you started with a deprotonated molecule in first place, than R-SO3H which formally distinguishes between two instances of S=O, and one of S-O-H.

**Comment by shaoqx** [comment]
My ligand was from the crystal structure of PDB id: [3WIW](https://www.rcsb.org/structure/3WIW).
The Dimorphit result was really cool, I will denefitly try it out. Thank you!

**Comment by BJWiley233** [comment]
This may be a little off topic but why does it matter where I `-h` parameter in the command line tool?  If I put it at the end before the input file it just hangs, but anywhere else it works.

Version: Open Babel 3.1.0 installed with Homebrew

This hangs:
```
obabel -ipdb -opdb -O test.pdb -h /path/to/imatinib.correct.CONECT.pdb
```

But these are all fine:
```
obabel -ipdb -opdb -h -O test.pdb /path/to/imatinib.correct.CONECT.pdb
obabel -ipdb -h -opdb -O test.pdb /path/to/imatinib.correct.CONECT.pdb
obabel -h -ipdb -opdb -h -O test.pdb /path/to/imatinib.correct.CONECT.pdb
```

Sounds like a `getopt` issue?

**Comment by fredrikw** [comment]
Citing the help for obabel `obabel -H`:

> Options, other than -i -o -O -m, must come after the input files.

**Comment by BJWiley233** [comment]
Right but `-h` can come **before** the input files and it works. As in the examples I gave above and below again:

But these are all fine:
```
obabel -ipdb -opdb -h -O test.pdb /path/to/imatinib.correct.CONECT.pdb
obabel -ipdb -h -opdb -O test.pdb /path/to/imatinib.correct.CONECT.pdb
obabel -h -ipdb -opdb -O test.pdb /path/to/imatinib.correct.CONECT.pdb
```

**Comment by fredrikw** [comment]
Yes, but since the instructions state that you should put it after it's not really a bug that you can't put it before.

**Comment by BJWiley233** [comment]
yes that argument could be made 😄.  logically sound!
