### ISSUE TITLE
Seeking guidance for GSoC 2021

### ISSUE THREAD

**Issue by ayushvpaliwal** [openbabel/openbabel#2334]
Hello everyone,

I am Ayush Paliwal, a 3rd-year student at the Indian Institute of Technology (BHU), Varanasi.

I am interested in working with OpenBabel for GSoC 2021. I want to work on the project Develop a validation and standardization filter. I have good experience in C++, python and JS. I also worked on a molecular simulation project using MAPS software.
I would be grateful if you guided me on how to get more involved, contribute.
Looking forward to contributing!

Sincerely,

Ayush Paliwal.

**Comment by ghutchis** [comment]
Thanks for your interest! This isn't so much of an issue - we have an e-mail list.

A successful project would propose a set of filters / transformations similar (or identical to) the MolVS project for RDKit.

 I'll post a few links / article that can help you get started (e.g., what is standardization):
* https://depth-first.com/articles/2020/07/27/a-guide-to-molecular-standardization/
* MolVS is an example for RDKit - https://molvs.readthedocs.io/en/latest/guide/intro.html
* PubChem standardization - https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0293-8
* ChemSpider standardization - https://jcheminf.biomedcentral.com/articles/10.1186/s13321-015-0072-8

The RDKit code is here:
* https://github.com/rdkit/rdkit/pull/2002
* https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/MolStandardize/standardize.py
* https://github.com/rdkit/UGM_2018/blob/master/Presentations/Leung_GSoC_RDKit-MolVS_Integration.pdf

There are a few more recent articles on tautomers:
* https://pubs.acs.org/doi/10.1021/acs.jcim.0c00232
* https://pubs.acs.org/doi/10.1021/acs.jcim.6b00338
* (InChI v2) https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b01080
  * https://cactus.nci.nih.gov/tautomerizer/

As a first step, I'd suggest looking at the code in `src/ops` and propose an OBOp that provides warnings for some simple things (e.g., carbon atoms beyond 4 bonds, total formal charge on a molecule isn't neutral, etc.)
