### ISSUE TITLE
PDB conversion overload 

### ISSUE THREAD

**Issue by MQSchleich** [openbabel/openbabel#2340]
- [x] I believe this to be a bug with Open Babel
- [x] This is a feature request

## Environment Information
Open Babel version: Open Babel 3.1.0 -- Oct 12 2020 -- 14:19:26
Operating system and version: macOS Big Sure 11.2.1

## Expected Behavior
```
obabel *.xyz -opdb -m
```
Converts over 60.000 thousand .xyz files to .pdb files without giving an error message. 

## Actual Behavior
```
** Open Babel Error  in OpenAndSetFormat
0 molecules converted
Argument list too long
```
Check why the argument list is too long. Are you operating on 64bit? Can you parallelize? It took for ever. 

## Steps to Reproduce
Create a directory with over 60.000 .xyz files and run
```
obabel *.xyz -opdb -m
```

**Comment by fredrikw** [comment]
I would say that this is mainly a shell problem. The globbing *.xyz is converted by the shell to a list with 60 000 filenames which will lead to a gigantic argument sent to openbabel. I don't know if openbabel can handle globbing by itself, but otherwise you could possibly try to use xargs to prepare several calls to openbabel with fewer files at a time.

**Comment by ghutchis** [comment]
This is 100% a shell problem. We deal with large directories of files all the time. `obabel` (or almost any other program) never see the glob - it's handled by the shell.

`find . -name "*.xyz" | xargs obabel -opdb -m` or use `-exec` with the `find` command.

**Comment by MQSchleich** [comment]
Thanks, I figured out it was a shell problem itself. I could circumvent it with a bash script, but did not try your solution yet. However, it may be nice to add such a feature to openbabel.

**Comment by sbembenek18** [comment]
I have something similar where I want to combine all my PDBQT in a single SDF --> 

find . -name '*.pdbqt' | xargs obabel -osdf -O mysdf.sdf

but obabel ends up taking ~2000 at a time and overwriting the mysdf.sdf each time -- how do I get it to do it all at once?

**Comment by fredrikw** [comment]
Again, it is not obabel that takes 2000 at a time, it is the shell and xargs that sets the limits (see options -n and -s to xargs but the shell will not let you just increase those indefinetly). So you need to find a way to do it in two steps, first prepare multipls sdfiles through some smart use of xargs and/or find and then cat the sdfiles together.

**Comment by ghutchis** [comment]
Also, you could do something like this to append to a file.

`find . -name '*.pdbqt' | xargs obabel -osdf >>mysdf.sdf`

**Comment by sbembenek18** [comment]
This helps - -thanks!

Scott Bembenek, Founder, CEO, CSO
Denovicon Therapeutics <https://www.denovicontx.com/>
1130 Wall St #558
La Jolla, CA 92037
<https://www.denovicontx.com/>

**Comment by sbembenek18** [comment]
This helps. Thanks!

**Comment by sbembenek18** [comment]
I'm cannot get a good conversion from pdbqt to sdf with version 3.1.0 -- oddly my older version 2.4 does better but still not perfect. 

obabel -ipdbqt my.pdbqt -osdf -O my.sdf

What am I missing here?
