### ISSUE TITLE
sdf convertion to pdbqt

### ISSUE THREAD

**Issue by PabloIriso** [openbabel/openbabel#2360]
- [ x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: Windows 10

## Expected Behavior

I want to convert several molecules from sdf format to pdbqt.

## Actual Behavior

I can't find pdbqt format neither in the output format options nor in the input.
I tried reinstalling MGLTools, as it has AutoDock, but the issue remains.

Edit: I tried finding babel.exe file but couldn´t. Maybe the installation isn´t complete?
I attach all the installed files:
![cap1](https://user-images.githubusercontent.com/79107558/115109300-4acef800-9f75-11eb-85cb-86531b2fb180.PNG)
![cap2](https://user-images.githubusercontent.com/79107558/115109302-4c002500-9f75-11eb-9748-f6c568ffa091.PNG)

**Comment by nbehrnd** [comment]
`pdbqt` (similar to, say `.pdb`, or `.xyz`) is one of the file formats OpenBabel may read _and_ write.  It is not an executable / library like `obgrep`, or the `obgui` are.  If working well, `pdbqt` should be visible as input / output in the GUI of OpenBabel, or -- from the CLI / cmd.exe --the command of `obabel -L pdbqt` should provide basically the same content as the current [documentation](https://open-babel.readthedocs.io/en/latest/) section 18.12.2 (or, in the .pdf version, page 201).

If not visible in your present installation, try a fresh reinstall with the current release of OpenBabel (note there are both `OpenBabel-3.1.1.exe` and `OpenBabel-3.1.1-x64.exe` though).  If not seen by the approaches mentioned above, check if an earlier release of OpenBabel, e.g. 3.1.0 solves the problem.
