### ISSUE TITLE
How to Translate this Aromatic Smiles Dialect?

### ISSUE THREAD

**Issue by craldaz** [openbabel/openbabel#2368]
I am using a package called [PySmiles](https://pypi.org/project/pysmiles/) and it is returning a different dialect of smiles for aromatic groups
e.g. 
`﻿NC:1:N:N:C:[N]1N`

Openbabel Version 2.3.2 successfully canonicalizes this to `Nc1nncn1N` but version 3.1.0 produces `NC1NNCN1N`.

What is happening? 

Any help is appreciated. Thanks!

**Comment by craldaz** [comment]
I've also posted the answer on Matter Modeling Stack exchange with a bounty if you want to gain some points there.

**Comment by baoilleach** [comment]
Atom aromaticity in SMILES is determined by the case of the characters, not
by the nature of the attached bonds.

Here is the SMILES for benzene:
c1ccccc1
The bond between two atoms marked as aromatic is implicitly an aromatic
bond. So, equivalently:
c:1:c:c:c:c:c:1

If this is benzene, then your question boils down to the following.
"What is the meaning of C:1:C:C:C:C:C:1?"

In short, the meaning is undefined. No toolkit should be writing values
like this if they care about other tools interpreting this 'correctly'.

I actually included this example in the SMILES benchmark (
https://github.com/nextmovesoftware/smilesreading/tree/master/3-results)
though I see that I didn't check in the results. I think I was wary of
distracting people from problems with defined behaviour.

Regards,
Noel
