### ISSUE TITLE
Openbabel fail to convert file downloaded from ccdc if transformation has unknown value

### ISSUE THREAD

**Issue by kartlee** [openbabel/openbabel#238]
For file downloaded from ccdc ( https://summary.ccdc.cam.ac.uk/structure-summary?id=doi:10.5517/cc8j3mh&sid=DataCite ), openbabel fail to convert from mmcif to pdb and give the following error - 

 Unknown space group error (H-M symbol:P21/c), cannot match the list of transforms, please file a bug report.
1 molecule converted
1 errors 21 warnings 14 audit log messages

In the attached cif file from ccdc, the short space group P21/c is recognized by openbabel. Openbabel by default remove the space and add it to dictionary. The thing went wrong was due to the following block -
 loop_
_symmetry_equiv_pos_as_xyz
???
Openbabel doesn't treat the transformation as unknown and try to match and fail in the library. I checked in a patch in my forked repo and created a pull request - 

https://github.com/openbabel/openbabel/commit/4d9b605f793cf932c8fd6e3fc3770d385a683d4b

Please evaluate and let me know.

**Comment by ghutchis** [comment]
I believe this issue is fixed now, correct?
