### ISSUE TITLE
SMILES rewrite by RDKit occasionally resolves "Open Babel Warning  in CorrectStereoAtoms"

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2393]
- [x] This is a feature request

## Environment Information
Open Babel version:  3.1.1 -- Jun 10 2021 -- 04:27:50
Operating system and version: Debian GNU/Linux 11 (bullseye)

## Expected Behavior

Jensen [lists here](https://molecularmodelingbasics.blogspot.com/2016/05/automating-calculations-pka-predictions.html) a few test structures encoded as SMILES which are to be converted by OpenBabel into `.xyz` with 3D information.   Cyclic structures should pass smoothly the conversion (yet occasionally they do not and issue warnings).

Is there an other way to "sanitize" SMILES than passing them to RDKit (*vide infra*), perhaps in OpenBabel itself?

## Actual Behavior

The conversion of
* `C[C@H]1CC[N@@]2CCC[C@@H]12`
* `C[C@H]1[C@@H]2[C@@H](C(N(C)C2=O)=O)C3[N@]1CCC3`
* `C[C@H]1[C@@H]2[C@@H](C(N(C)C2=O)=O)C3[N@H+]1CCC3`

in line of
```
obabel -:"C[C@H]1[C@@H]2[C@@H](C(N(C)C2=O)=O)C3[N@H+]1CCC3" --gen3D -h -oxyz
```
yield warnings like
```
*** Open Babel Warning  in CorrectStereoAtoms
  Could not correct 2 stereocenter(s) in this molecule ()
  with Atom Ids as follows: 2 3
Warning: Stereochemistry is wrong, using the distance geometry method instead
```
while e.g.,
```
obabel -:"C[C@H]1[C@@H]2[C@@H](C(N(C)C2=O)=O)C3[N@@H+]1CCC3" --gen3D -h -oxyz -O output.xyz
```
does not.

*However*

I noticed `C[C@H]1CC[N@@]2CCC[C@@H]12` is described with nitrogen as a stereocentre.  Thus, when submitted *as such* to either [PubChem Sketcher](https://pubchem.ncbi.nlm.nih.gov/edit3/index.html) or the [ChemDraw JS sample page](https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#) visualized with a wedge:

![initial_state](https://user-images.githubusercontent.com/19709084/123659339-1b185800-d822-11eb-9fc5-2cbd3506ad28.png)

Since the conversion SMILES to canonical SMILES 
```
obabel -:"C[C@H]1CC[N@@]2CCC[C@@H]12" -ocan
```
yields `C[C@H]1CC[N@]2[C@H]1CCC2` with the same issue in visualization and format conversion, I passed the canonical SMILES to RDKit (version 2020.09.4, as provided by Debian's repositories) :
```
>>> import rdkit
>>> from rdkit import Chem
>>> 
>>> # SMILES to mol:
>>> m = Chem.MolFromSmiles("C[C@H]1CC[N@]2[C@H]1CCC2")
>>> 
>>> # mol to SMILES:
>>> Chem.MolToSmiles(m)
'C[C@H]1CCN2CCC[C@@H]12'
>>> 
```
*This* newly generated SMILES string is visualized differently now, without the wedge on nitrogen

![later_state](https://user-images.githubusercontent.com/19709084/123661419-0b017800-d824-11eb-8b9a-e1a5a517ffb5.png)

and the attempt to convert this to a 3D `.xyz` by
```
obabel -:"C[C@H]1CCN2CCC[C@@H]12" -h --gen3d -oxyz -O output.xyz
```
does not yield any warning (even if it is not OpenBabel's canonical SMILES string, `C[C@H]1CCN2[C@H]1CCC2`).  Perhaps this is a bypass for a few instances when OpenBabel otherwise states "Open Babel Warning  in CorrectStereoAtoms", but is there a more efficient way to for this in OpenBabel itself?  Is there a "SMILES sanitizer", other than the options listed in section 18.1.7?

**Comment by fredrikw** [comment]
Hi,

A short question/remark. The round-tripped SMILES is missing stereochemistry on the nitrogens as you noted. It seems that Jan put some efforts into having the stereo on the nitrogens so it might be advisable to keep that if you are trying to use his protocol? Otherwise, you could loop through the atoms and remove stereo from any nitrogens in your python code.

I also think the warning says that the generation falls back on distance geometry, not that the 3D-generation fails...

**Comment by nbehrnd** [comment]
This issue will be closed, but not for failing to create a 3D structure *at all*.

I retract the issue because I don't possess enough insight how OpenBabel and RDKit's guess the spatial arrangement of the atoms if a SMILES string is the sole input at hand.  If the structures are read by Jmol, and if the later is requested to assign the absolute configuration (apparently, taking into account for the non-bonded electron pair on nitrogen then assigned priority `0`) then the two programs offer an output Jmol eventually assigns as either (*R*), or (*S*) about N.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19709084/124796016-35e47e00-df40-11eb-9b66-3ccc1aab40dc.gif)

For the interested, the archive below documents the steps and files leading to the animation shown.

[close_wegdes.zip](https://github.com/openbabel/openbabel/files/6778775/close_wegdes.zip)
