### ISSUE TITLE
`xyz` is missing from ----INPUT FORMAT--- in OpenBabel GUI

### ISSUE THREAD

**Issue by othmanalbahri1** [openbabel/openbabel#2394]
Hello,

Thank you for your great work with OpenBabel! 

- [x] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.1.1
Operating system and version: Windows 10 , 10.0.19043 Build 19043

## Expected Behavior
On OpenBabel GUI, I expected to find `xyz` format in the ----INPUT FORMAT---- list. 

## Actual Behavior
While dozens of formats are available in ----INPUT FORMAT---- list, `xyz` is not.

## Steps to Reproduce
I downloaded and installed the latest release `OpenBabel-3.1.1-x64.exe`. However, I can't see `xyz` in the ----INPUT FORMAT---- list. I am trying to convert multimolecule `xyz` files into multimolecule `sdf` files.

Running `obabel -L formats` in command prompt results in the following (`xyz` is missing):

`abinit -- ABINIT Output Format [Read-only]
acesin -- ACES input format [Write-only]
acesout -- ACES output format [Read-only]
adf -- ADF cartesian input format [Write-only]
adfband -- ADF Band output format [Read-only]
adfdftb -- ADF DFTB output format [Read-only]
adfout -- ADF output format [Read-only]
aoforce -- Turbomole AOFORCE output format [Read-only]
ascii -- ASCII format [Write-only]
axsf -- XCrySDen Structure Format [Read-only]
c09out -- Crystal 09 output format [Read-only]
can -- Canonical SMILES format
castep -- CASTEP format [Read-only]
cdjson -- ChemDoodle JSON
cdxml -- ChemDraw CDXML format
cml -- Chemical Markup Language
cmlr -- CML Reaction format
com -- Gaussian Input [Write-only]
confabreport -- Confab report format [Write-only]
CONTCAR -- VASP format
copy -- Copy raw text [Write-only]
cub -- Gaussian cube format
cube -- Gaussian cube format
dallog -- DALTON output format [Read-only]
dalmol -- DALTON input format
dmol -- DMol3 coordinates format
ent -- Protein Data Bank format
fch -- Gaussian formatted checkpoint file format [Read-only]
fchk -- Gaussian formatted checkpoint file format [Read-only]
fck -- Gaussian formatted checkpoint file format [Read-only]
fhiaims -- FHIaims XYZ format
fix -- SMILES FIX format [Write-only]
g03 -- Gaussian Output [Read-only]
g09 -- Gaussian Output [Read-only]
g16 -- Gaussian Output [Read-only]
g92 -- Gaussian Output [Read-only]
g94 -- Gaussian Output [Read-only]
g98 -- Gaussian Output [Read-only]
gal -- Gaussian Output [Read-only]
gam -- GAMESS Output [Read-only]
gamess -- GAMESS Output [Read-only]
gamin -- GAMESS Input
gamout -- GAMESS Output [Read-only]
gau -- Gaussian Input [Write-only]
gjc -- Gaussian Input [Write-only]
gjf -- Gaussian Input [Write-only]
got -- GULP format [Read-only]
gukin -- GAMESS-UK Input
gukout -- GAMESS-UK Output
gzmat -- Gaussian Z-Matrix Input
hin -- HyperChem HIN format
inchi -- InChI format
inchikey -- InChIKey [Write-only]
inp -- GAMESS Input
jin -- Jaguar input format
jout -- Jaguar output format [Read-only]
k -- Compare molecules using InChI [Write-only]
mdl -- MDL MOL format
ml2 -- Sybyl Mol2 format
mna -- Multilevel Neighborhoods of Atoms (MNA) [Write-only]
mol -- MDL MOL format
mol2 -- Sybyl Mol2 format
molreport -- Open Babel molecule report [Write-only]
moo -- MOPAC Output format [Read-only]
mop -- MOPAC Cartesian format
mopcrt -- MOPAC Cartesian format
mopin -- MOPAC Internal
mopout -- MOPAC Output format [Read-only]
mp -- Molpro input format [Write-only]
mpc -- MOPAC Cartesian format
mpo -- Molpro output format [Read-only]
mrv -- Chemical Markup Language
nul -- Outputs nothing [Write-only]
nw -- NWChem input format [Write-only]
nwo -- NWChem output format [Read-only]
orca -- ORCA output format [Read-only]
orcainp -- ORCA input format [Write-only]
outmol -- DMol3 coordinates format
paint -- Painter format [Write-only]
pc -- PubChem format [Read-only]
pcjson -- PubChem JSON
pdb -- Protein Data Bank format
png -- PNG 2D depiction
POSCAR -- VASP format
pov -- POV-Ray input format [Write-only]
pwscf -- PWscf format [Read-only]
qcin -- Q-Chem input format [Write-only]
qcout -- Q-Chem output format [Read-only]
report -- Open Babel report format [Write-only]
sd -- MDL MOL format
sdf -- MDL MOL format
siesta -- SIESTA format [Read-only]
smi -- SMILES format
smiles -- SMILES format
svg -- SVG 2D depiction [Write-only]
sy2 -- Sybyl Mol2 format
t41 -- ADF TAPE41 format [Read-only]
text -- Read and write raw text
tmol -- TurboMole Coordinate format
txt -- Title format
VASP -- VASP format
xml -- General XML format [Read-only]
xsf -- XCrySDen Structure Format [Read-only]
zin -- ZINDO input format [Write-only]`

In this [closed issue](https://github.com/openbabel/openbabel/issues/1722), @fredrikw suggests that this could have something to do with [BABEL_LIBDIR](https://open-babel.readthedocs.io/en/latest/Installation/install.html#environment-variables). However, it is not clear to me how I can use this information. I would appreciate your ideas.

Thanks,

Othman

**Comment by fredrikw** [comment]
It looks like you are missing all formats in `formats_misc` https://github.com/openbabel/openbabel/blob/08e23f39b0cc39b4eebd937a5a2ffc1a7bac3e1b/src/formats/formats.cmake#L84-L146
How that could happen, I don't know but it is probably not related to `BABEL_LIBDIR` since you have all the rest of them. I don't really know enough about the build process to say anything more.

**Comment by nbehrnd** [comment]
In version 3.1.1 packed for Linux Debian 11 / bullseye, `xyz` is the before last entry (or *penultimate*) of input formats in `obgui`.  Running `obabel -L formats` from the CLI of the same platform, `xyz` is the second to last entry (or *antepenultimate*) and in both cases, these work well as input formats.

**Comment by othmanalbahri1** [comment]
Thanks for your replies. I've managed to use openbabel on a Linux vm to convert from/to `xyz` but the issue presists on Windows (multiple machines). I don't have any further ideas at the moment so I'll close this issue.

**Comment by stevnBasbak** [comment]
i have the same issue
