### ISSUE TITLE
Distorted ring (hydrogen flipped inside out) in 3d conformer

### ISSUE THREAD

**Issue by ljmartin** [openbabel/openbabel#2398]
- I believe this to be a bug with Open Babel

version: Open Babel 3.1.0, installed via conda

Hi OB, thanks for all your great work.

This isomeric SMILES code leads to a bad ring conformation in 3d:
```
obabel -:"Cc1nnnn1[C@@H](Cc1cccc(F)c1)C(=O)Nc1cc2c(=O)[nH]cnc2cc1F" --gen3d -O out.sdf
```
The result has an 'inverted' atom - the hydrogen off nitrogen points inside the ring instead of outside. 

The SMILES came from EnumerateStereoisomers in RDKit, so it's possible there's some disparity in how the two libraries parse smiles, but at least it is parsed and embedded in 3d as you would expect by RDKit. Does anyone recognise what might be happening?

Thanks
Lewis

**Comment by nbehrnd** [comment]
Figuratively speaking, `--gen3d` attempts an energy optimization while varying the geometry described.  Out of the [multiple methods available](https://open-babel.readthedocs.io/en/latest/3DStructureGen/SingleConformer.html) (the default `--gen3d` *alone* is a place holder for the more verbose instruction `--gen3d med`), it is possible that the method selected identifies *one local*, but not necessarily *the global* optimum.

In the example presented, either one of the two following two instructions
```
obabel -:"Cc1nnnn1[C@@H](Cc1cccc(F)c1)C(=O)Nc1cc2c(=O)[nH]cnc2cc1F" --gen3d best -O out_best.sdf
obabel -:"Cc1nnnn1[C@@H](Cc1cccc(F)c1)C(=O)Nc1cc2c(=O)[nH]cnc2cc1F" --gen3d dg -O out_dg.sdf
```
yields a conformer more reasonable, i.e. with the proton in question oriented out to the periphery of the quinazolin-4(3*H*)-one if spending a little extra of computation.

![peripheral_hydrogen](https://user-images.githubusercontent.com/19709084/126817356-57c5865f-49a0-4cef-b24e-ddd25a28216a.png)

An open access publication (https://doi.org/10.1186/s13321-019-0372-5) illustrates the trade-offs for OpenBabel in further detail.

**Comment by ghutchis** [comment]
As mentioned by @nbehrnd we use a set of ring fragments first. I'd guess that `c1cc2c(=O)[nH]cnc2cc1F` isn't in the list, so it uses some heuristics. Not quite sure on why it generates that particular geometry, but as a workaround, the "best" option gives a bit more MMFF94 optimization. The `dg` option is something of an implementation of RDKit's distance geometry methods.

**Comment by ljmartin** [comment]
Great - thanks for that extra info! Makes sense.
