### ISSUE TITLE
Cannot open UFF.prm

### ISSUE THREAD

**Issue by baiqflab** [openbabel/openbabel#2401]
When I use the Open Babel 3.1.1 to covert SMILES to 3D mol2 format molecule,  the err happens as below:

==============================
*** Open Babel Error  in OpenBabel::OBBuilder::LoadFragments
  Cannot open ring-fragments-index.txt
==============================
*** Open Babel Error  in OpenBabel::OBForceFieldUFF::SetTypes
  Cannot open UFF.prm
1 molecule converted

What is the problem? Could somebody help me?

**Comment by ghutchis** [comment]
I'm closing this as a duplicate
