### ISSUE TITLE
Python API 'gen3d' option is not generating coordinates 

### ISSUE THREAD

**Issue by orioncohen** [openbabel/openbabel#2419]
- [ ] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.1.0
Operating system and version: macOS Catalina 10.15.7

## Expected Behavior
I expect my code to generate a pdb file with xyz coordinates included. When I try the same operation with the OpenBabel CLI, I have no issue. This is only a problem with the python interface.

## Actual Behavior
A PDB file is generated but there are no coordinates.

## Steps to Reproduce

I am running the following code. I have tried several different valid SMILES.

``` python
obConversion = openbabel.OBConversion()
obConversion.SetInAndOutFormats("smi", "pdb")

mol = openbabel.OBMol()
obConversion.ReadString(mol, 'C')
mol.AddHydrogens()
obConversion.AddOption('gen3d', obConversion.OUTOPTIONS)   # I have also tried INOPTIONS and GENOPTIONS
obConversion.WriteFile(mol, f"TEST.pdb")
```

**Comment by ghutchis** [comment]
`gen3d` is not an option. It's listed on the command line, but it's an `OBOp` so it's more like a format.

You want something like:
```
from openbabel import pybel

mol = pybel.readstring("smi", smiles)
mol.addh()
mol.make3D()
```
