### ISSUE TITLE
Problems with spg 230?

### ISSUE THREAD

**Issue by psavery** [openbabel/openbabel#242]
Hi there,

I've noticed some recent problems with spacegroup # 230 in OpenBabel. 

For a while, I haven't been able to use the 'set spacegroup' feature of Avogadro because it will crash with the following message:
   Cannot find an OpenBabel equivalent to Spglib's Hall symbol "-I 4bd 2c 3"

If I look inside the spacegroups.txt file in openbabel/data, I see that this is a symbol for spacegroup number 230, and for some reason it isn't loading properly.

I also noticed that if I do something as simple as OpenBabel::SpaceGroup::GetSpaceGroup(spg)->GetHMName(), it will crash if spg is 230 (but it will work fine if spg is any other number 1 to 229).

I'll try to look into the issue, but if any of you know how to fix it, that'd be great!

Thanks,
Patrick

**Comment by ghutchis** [comment]
No, I've noticed some similar problems with the space group code. It may take me a few weeks before I have time to find the bug though.

**Comment by psavery** [comment]
So I finally took the time to figure out which commit started causing the issue that I've been having. You're probably going to think it's strange, but believe it or not, it's this one:

ac2a135eb8560d5d8246eee2abdb5d266ad9ab17

https://github.com/openbabel/openbabel/commit/ac2a135eb8560d5d8246eee2abdb5d266ad9ab17

It's that line of white space that was deleted at the end of the file. I'm really not sure why this has been causing an issue for OpenBabel::SpaceGroup::GetSpaceGroup(), but it has. 

The function that is having the problem is "const SpaceGroup * SpaceGroup::GetSpaceGroup (const string &name_in)" src/math/spacegroup.cpp. The match isn't being found when "_SpaceGroups.sgbn.find(name)!=_SpaceGroups.sgbn.end()" is being called on line 381.

I looped through the map "sgbn" that the string is being compared to in the code, and the correct spacegroup "-I 4bd 2c 3"  is in there. I don't know why it isn't being found. It must be some kind of iterator issue or something. But that's the last one in data/space-groups.txt, so the extra line at the end of the file must have something to do with it.

Anyways, adding that extra line of whitespace at the end of data/space-groups.txt fixes the issue for me.

In addition, I had another issue come up with some recent commits. "SpaceGroup::GetSpaceGroup("-P 1")" fails because of the function "RemoveWhiteSpaceUnderscore(name_in)" added to line 351 of this recent commit: d5de951d606735b61d1686a0ea2321066956e085
https://github.com/openbabel/openbabel/commit/d5de951d606735b61d1686a0ea2321066956e085

It fails because it ends up trying to compare "-P 1" with "-P1" (removing the space in the middle), and that doesn't work. Unfortunately, he says that this fixes the issues for him with PDB, so he probably wants to keep it. Maybe if I move it after match line on the next line?

Anyways, do you want me to send a pull request? The reason I need this to work is because avogadro's 'setSpaceGroup()' function crashes every time it's called because of these issues. So I can't set a spacegroup and I can't get access to features like "fillUnitCell()" and "symmetrize()" (and of course, neither can other people, too).

Thanks,
Patrick

**Comment by ghutchis** [comment]
Yes, please submit a pull request.

**Comment by psavery** [comment]
Okay. I think the pull request I submitted should work fine for both of us.

As far as I can tell, the functions in Avogadro now work properly with these changes made.

**Comment by ghutchis** [comment]
This was fixed in master.
