### ISSUE TITLE
LICENSE for OptimizeNative.cmake and FindRapidJSON.cmake

### ISSUE THREAD

**Issue by oanastanca** [openbabel/openbabel#2425]
Hello,

Can you please specify which BSD(full text), mentioned in https://github.com/openbabel/openbabel/blob/openbabel-3-0-0/cmake/modules/OptimizeNative.cmake and 
https://github.com/openbabel/openbabel/blob/openbabel-3-0-0/cmake/modules/FindRapidJSON.cmake ?

There is no LICENSE file regarding the BSD that applies there.

Thank you.

**Comment by mcs07** [comment]
I wrote these files... and I *think* I was just trying to be consistent with the other CMake scripts. But looking at them now, they aren't very consistent anyway.

Here are all the others:

1. `FindInchi.cmake` added by @cryos (the referenced `COPYING-CMAKE-SCRIPTS` doesn't seem to exist) https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/cmake/modules/FindInchi.cmake#L8-L10

2. `FindCairo.cmake` added by @baoilleach https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/cmake/modules/FindCairo.cmake#L11

3. `FindEigen2.cmake` added by @ghutchis
https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/cmake/modules/FindEigen2.cmake#L13-L15

4. `FindEigen3.cmake` added by @ghutchis (specifically says "2-clause BSD license") https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/cmake/modules/FindEigen3.cmake#L13-L16

5. `UsePythonTest.cmake` added by @baoilleach (specifically says "New BSD license" i.e. 3-clause, and again the referenced `COPYING-CMAKE-SCRIPTS` doesn't seem to exist) https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/cmake/modules/UsePythonTest.cmake#L15-L19

I'm not sure what the best way to clear up the confusion is - it would be good to have a consistent specific BSD license for all these files but it might be tricky to establish the intentions of all the copyright holders. 

In the meantime, for the files that I am the copyright holder of (`OptimizeNative.cmake` and `FindRapidJSON.cmake`): By adding them to Open Babel, I consider them to be released under the GPLv2 that applies to the whole project, but I am also happy for them to be used/redistributed under the more permissive [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause).
