### ISSUE TITLE
Error in converting an .xyz file to .sdf

### ISSUE THREAD

**Issue by NicolaiRee** [openbabel/openbabel#2437]
- [x ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 3.1.0
Operating system and version:  CentOS Linux 7 (linux-64)
Downloaded using "conda install -c conda-forge openbabel"

## Expected Behavior
Info line in .sdf file is wrong, should have been:
```
energy: -143.561198201957 gnorm: 0.000327189782 xtb: 6.4.0 (d4b70c2)
 OpenBabel12142114443D

 94 100  0  0  1  0  0  0  0  0999 V2000
```

## Actual Behavior
A space between 94 and 100 is missing:
```
energy: -143.561198201957 gnorm: 0.000327189782 xtb: 6.4.0 (d4b70c2)
 OpenBabel12142114443D

 94100  0  0  1  0  0  0  0  0999 V2000
```

## Steps to Reproduce
Use the following command line:
`obabel -ixyz xtbopt.xyz -osdf`

.xyz format was not allowed for upload, so I have just changes the file format to .txt using "mv xtbopt.xyz xtbopt.txt"
[xtbopt.txt](https://github.com/openbabel/openbabel/files/7712072/xtbopt.txt)

**Comment by NicolaiRee** [comment]
However, when using the SDF/Mol V3000 file format everything works as expected.
`obabel -ixyz xtbopt.xyz -osdf -x3`

**Comment by fredrikw** [comment]
According to the specification, there should not be a space between 94 and 100. Both atom and bond counts should be specified with three positions. The count line is:
`aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv`
where aaa is atom count and bbb is bond count both with a maximum of 255.

**Comment by NicolaiRee** [comment]
@fredrikw thank you very much for the clarification! and sorry for opening this issue. 
Best wishes, Nicolai

**Comment by fredrikw** [comment]
No problem. I wish all issues would be this easy to close...
