### ISSUE TITLE
Obgui failed to understand wildchars in input filename box.

### ISSUE THREAD

**Issue by alchemistcai** [openbabel/openbabel#2445]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:3.1.1(self compiled version)
Operating system and version:Manjaro 5.15.12

## Expected Behavior

In the specified path,there are some SMI files:
```txt
zinc10.smi
*zinc10.smi
zinc10*.smi
?zinc10.smi
arg.smi
aspirin.smi
```
In obgui's input filename box,here are some inputs with wildchars I tested:

1. `*.smi`
2. `*zinc10.smi`
3. `?zinc10.smi`
4. `z*.smi`
5. `arg.smi;a*.smi;zinc10.smi`

Respiectively,expected conversed files are:

1. `zinc10.smi;*zinc10.smi;zinc10*.smi;?zinc10.smi;arg.smi;aspirin.smi`
2. `zinc10.smi;*zinc10.smi`
3. `*zinc10.smi;?zinc10.smi`
4. `zinc10.smi;zinc10*.smi`
5. `arg.smi;aspirin.smi;zinc10.smi`
## Actual Behavior

Actually,conversed files are:

1. None
2. None
3. None
4. None
5. `arg.smi;zinc10.smi`

In general,any wildchars in the input filename box will not be conversed.   
Any wildchars in the filename will not be conversed,even selected in the input dialoag.  
Other filenames without `*` or `?` splited by `;` will converse correctly.  
`*` in output filename box works correctly if input filename box has no `*`.
## Steps to Reproduce

![obguiWildcharBug](https://user-images.githubusercontent.com/60164864/150667555-1f458586-e8e1-4434-a4e9-8d9059fe9fb5.png)

**Comment by nbehrnd** [comment]
Already an input like
```bash
obabel -:"c1ccncc1" -O py*.smi
```
will not create `py*.smi`, but `py1.smi`.   In other cases, the file names will require an escape to access them (e.g., `py?.smi` as `py\?.smi` for e.g., `obabel py\?.smi -O test.png`).  You might be able to adjust the terminal emulator to do this for you *on the fly*, however chances are your colleagues' computers are not set up for this by default.

However, this may become an obstacle down the road (e.g., retrieve by regexes).  If you want to ease exchange, stick to to the 2x26 English characters of [a-zA-Z], decimals [0-9] plus dash, plus, and underscore.
