### ISSUE TITLE
'libopenbabel.so.5': No such file or directory

### ISSUE THREAD

**Issue by JosephPParker** [openbabel/openbabel#2446]
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: Linux CentOS 7
Conda version: 4.11.0
Python: 3.8.6 (have also tried 3.9.9, no help)

## Expected Behavior
Call obabel, with relevant flags/arguments, convert molecules.
The program worked this way for a long time with no issue, but ceased working around the time I set up a new virtual environment with conda and updated several modules.

## Actual Behavior
Using the command obabel in any capacity results in the following message:
obabel: error while loading shared libraries: libopenbabel.so.5: cannot open shared object file: No such file or directory
I have searched through the libraries in the conda virtual environments and in the base conda libraries but cannot find it (both lib and pkg directories).  Using the find command similarly does not find it.
I do, however, have 'libopenbabel.so.7' in the lib folders of conda, which I also find on when I use the ldcnfig command.  I have tried to add 'libopenbabel.so.5' temporarily to my library path (LD_LIBRARY_PATH) without success.  I also tried simply using conda remove and conda install again to try and reset it.

I have looked on previous GitHub issues and the forums on openbabel-discuss@lists.sourceforge.net.  I have not interfered with the deeper files of OpenBabel but fear either a library has been inadvertently deleted or I need to respecify which library OpenBabel should use (although I am not sure how to do that).

Can anyone advise me?

**Comment by fredrikw** [comment]
Did you have openbabel installed on the system before installing the conda version? If you run `which obabel`, what will it give as result? It sounds like you have multiple versions of openbabel and that there is a mismatch between system version and conda version.
Will it make a change whether you deactivate the conda environment?

**Comment by JosephPParker** [comment]
It seems you are right, thank you, although the new version is the non-conda version.  I installed MGLTools for doing some molecular docking work and that has the openbabel.so.5 in it.
It doesn't seem to make a difference in activating or deactivating the conda environment, although conda's OpenBabel 3.1.1 is installed in both base and my main virtual environment.
Is there any way of selecting which obabel files to use?

**Comment by fredrikw** [comment]
I don't really know about MGLTools so I don't know how they add openbabel (but it seems like it's an old version...). If `which obabel` points to the MGLTools version, you could try to use a command like `/home/{user}/miniconda3/bin/obabel` instead, that should force the use of the conda version from the main env or `/home/{user}/miniconda3/envs/{mainenv}/bin/obabel` to use the version in your main virtual environment.
Normally, the activation of the environment should handle this but I suspect that the MGLTools install is doing something to the path variables that makes this automatic path handling fail.

**Comment by JosephPParker** [comment]
That worked, thank you very much.  I didn't realise I had so many OpenBabel versions running on this thing.  I'm rather new to command line, so I'll suspect the 'which' command will be very helpful.
I've aliased it to simply 'openbabel' for now, but I'll try and tidy up my system in future and change the default to the OpenBabel version that I want.
