### ISSUE TITLE
pybel report of non-standard InChI (e.g., discern of tautomers)

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2450]
- [x] This is a feature request

## Environment Information
Open Babel version:  Open Babel 3.1.1 -- Jun 10 2021 -- 04:27:50 / libopenbabel7 3.1.1+dfsg-6
Operating system and version: Linux Debian 12/bookworm, branch testing.

## Expected Behavior

I would like to assign InChI with the optional fixed H-layer.  If used in conjunction with standard InChI, this information may be used to identify tautomers.  This was implemented recently in Jmol (version 14.32.12, 2022-01-18 00:28:54; [reference](https://sourceforge.net/p/jmol/mailman/message/37419194/)).

Thus -- lacking identification of an explicit example in the documentation -- an input like
```python
from openbabel import pybel

mol = pybel.readstring("smi", "Oc1ccccn1")  # i.e., 2-hydroxy pyridine
print(mol.write(["inchi", "xFixedH"]))
```
does not yield the anticipated (non standard) InChI
```bash
InChI=1/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)/f/h7H
```

## Actual Behavior
```python
from openbabel import pybel

lactim = pybel.readstring("smi", "Oc1ccccn1")  # i.e., 2-hydroxy pyridine
lactam = pybel.readstring("smi", "C1=CC=CNC(=O)1")  # i.e., 2-pyridone

print(lactim.write("inchi"))
print(lactam.write("inchi"))
```
yield the (necessarily identical) standard InChI
```
InChI=1S/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)
InChI=1S/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)
```
On the other hand, however, OpenBabel on the CLI assigns for 2-hydroxy pyridine
```bash
$ obabel -:"Oc1ccccn1" -oinchi -xFixedH
InChI=1/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)/f/h7H
```
and for 2-pyridone
```bash
$ obabel -:"C1=CC=CNC(=O)1" -oinchi -xFixedH
InChI=1/C5H5NO/c7-5-3-1-2-4-6-5/h1-4H,(H,6,7)/f/h6H
```

**Comment by baoilleach** [comment]
You're not setting the option correctly. The Python 'help' command can be used for showing the documentation on a function. From memory, it's something like mol.write("inchi", opt={"FixedH": True}).

**Comment by nbehrnd** [comment]
Affirmative, the syntax `mol.write("inchi", opt={"FixedH": True})` yields the wanted output.  Thank you.
