### ISSUE TITLE
delayed Open Babel Warning in CreateCisTrans

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2455]
- [X] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.1.1 (3.1.1+dfsg-6+b1)
Operating system and version:  Linux Debian 12/bookworm (branch testing)

## Expected Behavior
When submitting a list of SMILES for conversion, I prefer OpenBabel's warnings sent to the CLI to appear directly after the entry to be revised.  E.g. with `check01.smi`

```bash
$ awk '{print}' check01.smi
CO[C@@H]([C@@H](C[C@H]([C@@H]1OC)O)O)C1OC
COC(Cc(c(O)c(cc1OC)C(OC(c(cc(c(O)c2)OC)c2OC)=O)=O)c1O)=O
CC(OC(CCC(OC(c(ccc(O[C@@H](C(C(C=CC1)=C1O)=O)C(O)=O)c1)c1O)=O)=O)=O)=O
CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O
```

to yield a log like

```bash
$ awk '{print}' check01.smi | obabel -ismi -ocan --addinindex
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	1
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	2
O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	3
COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	4
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond
4 molecules converted
```
## Actual Behavior
Instead, above `check01.smi` is processed with a report as if the second entry would require a revision, i.e.

```bash
$ awk '{print}' check01.smi | obabel -ismi -ocan --addinindex
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	1
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	2
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	3
COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	4
4 molecules converted
```

## Steps to Reproduce
Processing `check01.smi` line by line, it actually is entry 4 (i.e., n + 2) OpenBabel's warning refers to:

```bash
$ awk 'NR == 4' check01.smi | obabel -ismi -ocan
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	
1 molecule converted
```
The same observations with the following different list of smiles (`check02.smi`):

```
CCOC(Cc(cc1)cc2c1c([C@H](C)OC)c[o]2)=O
CCc(cc1)cc2c1-c1c[o]cc1CC2
C/C=C(\c(c1c(c(CCC2)c3[C@H]2OC)O)c(O)[o]c1c3O)/O[C@@H](C1)CC=C[C@@H]1OC
C[C@H](C(C/C(\C1=O)=C/C([C@@H]([C@H]([C@@](C)(c2c(CC(C)(C)OC)cccc2)OC)OC)O)=O)=O)C1=O
```

**Comment by e-kwsm** [comment]
I cannot reproduce openbabel 3.1.1+dfsg-6 (apt) on Debian bullseye:
```shellsession
$ cat << EOF | obabel -ismi -ocan
CO[C@@H]([C@@H](C[C@H]([C@@H]1OC)O)O)C1OC
COC(Cc(c(O)c(cc1OC)C(OC(c(cc(c(O)c2)OC)c2OC)=O)=O)c1O)=O
CC(OC(CCC(OC(c(ccc(O[C@@H](C(C(C=CC1)=C1O)=O)C(O)=O)c1)c1O)=O)=O)=O)=O
CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O
EOF
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	
COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	
4 molecules converted
```

I didn't go into detail, but perhaps this is because `std::clog` is not flushed.

https://github.com/openbabel/openbabel/blob/f3ed2a9a5166dbd3b9ce386e636a176074a6c34c/src/oberror.cpp#L146

**Comment by nbehrnd** [comment]
@e-kwsm On the installation accessible to me, I'm able to replicate the processing, which yields the same output as reported.

Equally, the initially stated observations using only openbabel may be replicated.  For one, to identify the line yielding the warning

```bash
$ obabel -ismi check01.smi -ocan -f 4 -l 4
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	
1 molecule converted
``` 
while the other combinations of first line/last line to pick an other single line from the raw .smi file read don't yield a warning:

```bash
$ obabel -ismi check01.smi -ocan -f 1 -l 1
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	
1 molecule converted
$ obabel -ismi check01.smi -ocan -f 2 -l 2
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	
1 molecule converted
$ obabel -ismi check01.smi -ocan -f 3 -l 3
O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	
1 molecule converted
```

For the other, the report over all four entries processed in one batch, with the warning not next to the line it would belong to:

```bash
$ obabel -ismi check01.smi -ocan --addinindex
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	1
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	2
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	3
COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	4
4 molecules converted
```

**Comment by fredrikw** [comment]
The error/warning messages and the output is sent to different streams (STDERR and STDOUT respectively) to not pollute the output file with the warnings. So the difference in buffering between the streams is the reason why the messages are "out of order". You could try `stdbuf` or `unbuffer` (c.f. https://stackoverflow.com/questions/3465619/how-to-make-output-of-any-shell-command-unbuffered/25548995#25548995) but I haven't tried them myself.

**Comment by nbehrnd** [comment]
@fredrikw For quite some time, I couldn't translate the conceptual hints and tips the links in the documents you refer to into filters/scripts to work with reliably.  With better insight than I currently posses, I speculate there is a better (as in _more efficient_, thus _processing faster_) approach then the one identified in the following and welcome improvements.

----

The successful conversion of a SMILES string by OpenBabel into its canonical form yields an output worth two lines long:

```bash
$ obabel -:"c1ccncc1" -ocan
c1cccnc1	
1 molecule converted
```

However, the attempt to process an erroneous SMILES string extends over five lines:

```bash
$ obabel -:"c1ccncc5" -ocan
==============================
*** Open Babel Warning  in ParseSmiles
  Invalid SMILES string: 2 unmatched ring bonds.

0 molecules converted
```
Based on this observation, the AWK script below performs a conversion explicitly requesting both standard output as well as the error stream.  For unproblematic SMILES (i.e., entries reporting back with two lines [or line-feed separated records, in parlance of AWK]) the canonical SMILES string is provided.

Though written for Linux Debian 12/bookworm (branch testing), by use of AWK, this approach aims to be portable for other platforms (maybe others may check on this).  Reporting only the (processed) canonical SMILES passing the filter successfully equally should be helpful when running OpenBabel with the optional `--errorlevel <N>` (default 2 out of 5, cf. [section 3.2](https://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html)).

```awk
#!/usr/bin/awk -f

# name:    filter.awk
# author:  nbehrnd@yahoo.com
# license: GPL v2, 2022
# date:    <2022-03-23 Wed>
# edit:    <2022-03-28 Mon>

# Retain "reasonable" SMILES strings OpenBabel may process gently.
#
# For a successful application of this filter, this AWK script depends
# on a running installation of OpenBabel and AWK.  (Tests suggest you may
# use GNU AWK/gawk and nawk instead of AWK as well.)
#
# Write a list of SMILES into the same directory as this AWK script, e.g.,
# as file check01.smi.  Then deploy this filter e.g., by
#
# awk -f filter.awk check01.smi
#
# to process the content of the list of SMILES.  The output is a list of
# canonical SMILES which OpenBabel has no difficulty to process.  Entries
# which cause a warning by OpenBabel (i.e., a five-line output during the
# test conversion) are not reported back.

{test_convert = "obabel -:\"" $1 "\" -ocan > shuttle.txt 2>&1";
    system(test_convert);

    filter = "awk 'END{if (NR==2) {print $0;}}' shuttle.txt"
    system(filter);
}
```
Test input data (`check01.smi`):
```
CO[C@@H]([C@@H](C[C@H]([C@@H]1OC)O)O)C1OC
COC(Cc(c(O)c(cc1OC)C(OC(c(cc(c(O)c2)OC)c2OC)=O)=O)c1O)=O
CC(OC(CCC(OC(c(ccc(O[C@@H](C(C(C=CC1)=C1O)=O)C(O)=O)c1)c1O)=O)=O)=O)=O
CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O
c1ccncc1
C1CCCC5
CC
CCC
```
Reported SMILES passing the filter successfully:

```bash
$ awk -f filter.awk check01.smi 
COC1[C@@H](OC)[C@H](O)C[C@H]([C@@H]1OC)O	
COC(=O)Cc1c(O)c(cc(c1O)OC)C(=O)OC(=O)c1cc(OC)c(cc1OC)O	
O=C(OC(=O)c1ccc(cc1O)O[C@@H](C(=O)C1=C(O)CC=C1)C(=O)O)CCC(=O)OC(=O)C	
c1cccnc1	
CC	
CCC	
```

**Comment by fredrikw** [comment]
Was all that you wanted to do filter out the error messages? In that case, a simple `obabel check01.smi -ocan -e 2>/dev/null` would do. Or `obabel check01.smi -O result01.can -e` to get the output in a file. I thought you needed to know which input SMILESs that didn't convert properly.

**Comment by nbehrnd** [comment]
@fredrikw 
Your approach by `obabel check01.smi -O result01.can -e` is more compact, easier to memorize and returns unproblematic SMILES strings at a faster rate.  However, I notice it returns seven out of eight entries of `check01.smi` -- including the fourth one my approach did not let pass.  Do you think OpenBabel's report about this entry qualifies to skip the entry altogether?

For checks with partialsmiles'[1] `validate.py`, the entry passes well:

```bash
$ python3 validate.py "CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O"
Input: CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O

1. Parse as full SMILES:

OK

2. Parse as partial SMILES:

OK

3. Parse substrings as partial SMILES:

OK
```

OpenBabel however issues a warning/error _interpreted_ as serious enough to remove this entry for good:

```bash
$ obabel -:"CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O" -ocan
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO 1 molecule converted
```

The meaning of the formulae provided by CDKDepict[2] did not alter -- e.g., no change in the configuration of the stereogenic centers, and the double bond still can't be assigned to match either the pattern of (E), or (Z):

![2022-03-30_CDKDepict_entry04](https://user-images.githubusercontent.com/19709084/160856599-8123cc0e-39b3-44b7-a2be-019bf7d5294b.png)

Because I'm not aware if OpenBabel can resolve such ambiguities (here: to return one SMILES string with the explicit (E), and an other SMILES string with the explicit (Z) double bond) -- wouldn't be the more strict (pedantic?) remove of this entry an
advantage to address specific configurations?*


Last (but not least), the explicit return of problematic SMILES.  The in-silico generation of molecules as SMILES appeared to me as affordable (enough) to skip entries with SMILES OpenBabel/partialsmiles perceive as problematic.  Thus my change to focus on SMILES approved by partialsmiles/OpenBabel may process (the complementary set).  The above SMILES string yielding a warning because of extended stereochemistry (options for .and. and .or.) equally calls for an adjustment of the parameters how the molecules are generated (outside OpenBabel) to use only SMILES with unambiguous  stereochemistry.

---

*) On a tangent, this reminds me a bit to the extended stereochemistry options in .sdf (v3000 format) with logical .and. and .or. as seen e.g., in a presentation[3] by Andrey Yerin's about how to possibly improve InChI:

![2022-03-30_Yerin_InChI](https://user-images.githubusercontent.com/19709084/160856761-5908e26c-1f6d-4657-b6cb-0d55acbd2c53.png)


[1] https://github.com/baoilleach/partialsmiles
[2] https://github.com/cdk/depict
[3] slide 8 of the .pdf https://www.inchi-trust.org/wp/wp-content/uploads/2019/12/19.-InChI-Stereo-Yerin-2019-update.pdf

**Comment by fredrikw** [comment]
If it is serious enough for your application, you need to be the judge of that. But there is a problem in how the Cis/Trans is specified on the double bond. If you look at the depictions from CDK you will see that it is marked as unspecified both in `#1` and `#2`.
In your SMILES `CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O`, you specify that for the third C in the string, both substituents should be on the same side of the double bond which is not possible.
If you need the stereo on the double bond, the correct ones are:
`"CC(O/C(/CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O" (#3)` and `"CC(O\C(\CCC[C@H]([C@H]
(C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O" (#4)`
![image](https://user-images.githubusercontent.com/86855/160865007-706a7774-093d-4cf6-9e91-0e2213e72648.png)

So you need to think through what you are trying to do and then act accordingly. If you do indeed want to skip molecules with warnings, I don't think it is possible through the obabel interface.

**Comment by nbehrnd** [comment]
I knew `#1` and `#2` to be unspecific about the double bond both because of the wiggle bonds CDKDepict uses .and. because using the optional CIP labeling (second pull-down menu, last entry) thankfully assigns both (R)/(S) and (E)/(Z) if applicable.

What I still lack with SMILES is e.g., to recognize manually well enough if the substitutents around a double bond are in cis, or trans relationship.  As with but-2-ene, the four permutations are simpler to recognize (either `//`, or `\\` point to the same direction for the cis; and either opposing `/\`, or `\/` for the trans relationship):

![2022-03-30_cdkdepict_CIP](https://user-images.githubusercontent.com/19709084/160873791-cd5ca720-9dbf-4a4c-96b1-e504890a1204.png)

That's when tested programs may help.  Ok.  Thank you; case closed.
