### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ghost** [openbabel/openbabel#246]
Dear openbabel,
we at Gentoo are experiencing difficulties building openbabel 2.3.2 with the latest GCC-5 release. This is mostly due to std::shared_ptr issues and using it from TR1, all of which has been fixed in git. Instead of cherrypicking the fixing commits and backporting them, could you maybe make a 2.3.3 release instead so we can use this? Thanks.

**Comment by ghutchis** [comment]
We intend on releasing 2.4.0 by the end of January. I'm not really inclined to make a 2.3.3 release for the reasons you mentioned - we'd need to cherry-pick the commits and apply them to the 2-3 release branch.

**Comment by Reinis** [comment]
There is a live ebuild in science overlay, you can install latest development version using that. Though there is a bug currently which prevents installation of Python bindings for the live version because of the issue with sandbox, which I don't know how to resolve (have reported it on bugzilla).

**Comment by baoilleach** [comment]
Version 2.4.0 just released.
