### ISSUE TITLE
Is there any option so that using  openbabel command line we can redirect molecular optimzation and charge calculation method to NWChem? Please let me know. Thank you

### ISSUE THREAD

**Issue by sujit-sarkar** [openbabel/openbabel#2467]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:
Operating system and version:

**Comment by ghutchis** [comment]
Open Babel supports generating NWChem input files and reads NWChem output files. For example:
`obabel [file] -O file.nw`
`obabel -inwo file.out -O file.mol2`

https://open-babel.readthedocs.io/en/latest/FileFormats/NWChem_input_format.html?highlight=nwchem
https://open-babel.readthedocs.io/en/latest/FileFormats/NWChem_output_format.html?highlight=nwchem
