### ISSUE TITLE
Error calculating descriptor

### ISSUE THREAD

**Issue by jshan2020-33** [openbabel/openbabel#2482]
## Environment Information
Open Babel version: 3.1.1
Python version: 3.7
Operating system and version: Windows 10

## Expected Behavior
Calculate basic features and molecular fingerprints using Python's OpenBabel library.

## Actual Behavior
Basic descriptors have many missing items, and molecular fingerprints cannot be obtained.
![1653665232(1)](https://user-images.githubusercontent.com/81633044/170730581-ad860587-19f5-4398-a583-0b359204880b.png)
![1653665465(1)](https://user-images.githubusercontent.com/81633044/170731243-1f4172e6-fa49-42bf-8024-570912c04d5b.png)

## Steps to Reproduce

The running code is as follows:
from openbabel import openbabel,pybel 
for mymol in pybel.readfile("mol", "p0000078579.mol"):
    descr_dict = mymol.calcdesc()
    FP4_dict = mymol.calcfp(fptype="FP4")

The error message is as follows:
==============================
*** Open Babel Error  in OpenBabel::OBGroupContrib::ParseFile
   Could not find contribution data file.
==============================
*** Open Babel Error  in OpenBabel::OBGroupContrib::ParseFile
   Could not find contribution data file.
==============================
*** Open Babel Error  in OpenBabel::OBGroupContrib::ParseFile
   Could not find contribution data file.
==============================
*** Open Babel Error  in OpenBabel::PatternFP::ReadPatternFile
  Cannot open SMARTS_InteLigand.txt

[p0000078579.zip](https://github.com/openbabel/openbabel/files/8787754/p0000078579.zip)

**Comment by fredrikw** [comment]
Hello,

It looks like you have a problem with the BABEL_DATADIR variable. How did you install OpenBabel?

Kind regards,
Fredrik

**Comment by jshan2020-33** [comment]
> Hello,
> 
> It looks like you have a problem with the BABEL_DATADIR variable. How did you install OpenBabel? And how do you start the Python version?
> 
> Kind regards, Fredrik

Hello,

Thank you for your reply, my reply is as follows to your two questions:
1. Install code: conda install openbabel -c conda-forge
2. Run spyder installed in a virtual environment created with python3.7

Also, I found that I run my code in the anaconda prompt panel, and the calculation works fine, maybe I can't run it directly on spyder?
![DG4 DA DKRL4$DX8_{_@I](https://user-images.githubusercontent.com/81633044/171024705-15e53b90-bbe4-46c6-b8e7-17378de1761f.png)
![49_VELCKU6~HGH)LAH1NHIX](https://user-images.githubusercontent.com/81633044/171026327-b83579f6-a47d-45a2-b2fc-e876f69bc540.png)

**Comment by jshan2020-33** [comment]
Thank you very much, I solved this problem according to your method.
