### ISSUE TITLE
attribute error on pybel

### ISSUE THREAD

**Issue by ahmed4899** [openbabel/openbabel#2483]
I was trying to run a command for preparecovalent.py on python 3.10.4, and I get this error:

Traceback (most recent call last):
File "/home/ahmed/Downloads/adCovalentDockResidue/adcovalent/prepareCovalent.py", line 37, in
ob = pybel.ob
AttributeError: module 'pybel' has no attribute 'ob'

I can't find any ob attributes in my files.

**Comment by dkoes** [comment]
Is pybel actually openbabel pybel, or is it the PyBEL  package for parsing and handling biological networks encoded in the Biological Extension Language?  For example, does `pybel.readstring` exist, which is an openbabel pybel method, or does `pybel.from_bel_script_url` exist, which is a PyBEL method.

**Comment by dkoes** [comment]
Then you aren’t importing the right module. You probably need to change your script to import pybel from openbabel:
`from openbabel import pybel`
assuming openbabel is installed.

**Comment by dkoes** [comment]
You make sure you can import pybel from openbabel and you make sure the script is importing pybel correctly, as described above.

**Comment by ghutchis** [comment]
And you can make sure you've installed the right package:
https://pypi.org/project/openbabel/
https://anaconda.org/conda-forge/openbabel

For example:
`conda install -c conda-forge openbabel`

**Comment by ahmed4899** [comment]
I installed openbabel using conda with the command above. I tried to run the setup for pybel for openbabel, but I got this error:

Error: SWIG failed. Is Open Babel installed?
You may need to manually specify the location of Open Babel include and library directories. For example:
  python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
  python setup.py install



I tried to look for the local anf library files but I couldn't find any. Are those supposed to be there when openbabel is correctly installed, and if not, how can I overcome this error?

**Comment by nbehrnd** [comment]
@dkoes re pybel (about openbabel) which _is not_ PyBEL (about biological networks):  You were looking for the section [Updating to Open Babel 3.0 from 2.x](https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html), were sub section _Python module_ states:

>  "In OB 3.x, both openbabel.py and pybel.py live within the openbabel module [...] While more verbose, the new arrangement is in line with standard practice and helps avoid conflict with a different Python project, PyBEL."
