### ISSUE TITLE
Forcefield SystematicRotorSearch RAM demand

### ISSUE THREAD

**Issue by Aquaplant** [openbabel/openbabel#2498]
## Environment Information
Open Babel version: 2.4.1 with Python 3.7.9
Operating system and version: Ubuntu 20.04.4 LTS

## Expected Behavior
Peptide structure prediction

## Actual Behavior
SystematicRotorSearch briefly allocates more and more RAM until overflow (tested on a machine with 32 GB RAM).
RandomRotorSearch works fine alike the other methods, too. Maybe SystematicRotorSearch needs a lot of memory, but comparing to all other methods this looked odd for me.

## Steps to Reproduce
An arbitrary PDB file is needed. 
`ob_ff = openbabel.OBForceField.FindForceField("gaff")

ob_conv = openbabel.OBConversion()  # conversion object
ob_mol = openbabel.OBMol()  # molecule
ob_conv.ReadFile(ob_mol, pdb_path)

ob_ff.Setup(ob_mol)
ob_ff.SystematicRotorSearch(10)`

**Comment by fredrikw** [comment]
When you say "An arbitrary PDB file is needed"? Do you mean that you try to run the rotor search on a protein? There are "lots" of possible rotors to rotate in a protein and with SystematicRotorSearch you will get an exponential list of all possible combinations so a RAM overflow does not seem surprising...

**Comment by ghutchis** [comment]
I think we're pretty clear up-front that SystematicRotorSearch does exactly what it says - systematically generate all possible rotamers. Even for a small molecule, this is exponential, roughly 3^n for n rotatable bonds. I'm not sure I'd suggest it for anything beyond 8-10 rotatable bonds. (We've done it, but yes, it takes a lot of memory.)

**Comment by Aquaplant** [comment]
Thanks for the quick responses and your time.
I used an pdb file with up to 20 residues and was surprised about the RAM consumption in contrast to the other methods, but it is clear now.

**Comment by nbehrnd** [comment]
@Aquaplant You might consider updating openbabel.  The contemporary version 3.1.1 is among the [releases](https://github.com/openbabel/openbabel/releases), and there are more recent versions than 2.4.1 you mention repackaged for your OS (brief search on Ubuntu's [package index](https://packages.ubuntu.com/search?keywords=openbabel&searchon=names&suite=all&section=all)).
