### ISSUE TITLE
openbabel python import from conda environment fails due to undefined symbol

### ISSUE THREAD

**Issue by PanayotisManganaris** [openbabel/openbabel#2502]
## Environment Information
Open Babel version: 3.1.1 (compiled from source with cmake, gui off, eigen off, swig on, python bindings on)
install prefix set to .local/bin/openbabel-3.1.1
swig version 4.0.2
conda environment equipped with latest gcc and gxx compiler
Operating system and version: Archlinux Linux kernel 5.18.5

## Expected Behavior
from new conda environment with python 3.8.3, run
```
pip install
--install-option=build_ext
--install-option="-L/home/panos/.local/bin/openbabel-3.1.1/lib/"
--install-option="-I/home/panos/.local/bin/openbabel-3.1.1/include/openbabel3/" 
openbabel
```
to install python bindings successfully

## Actual Behavior
openbabel and _openbabel builds and installs successfully, however, upon importing openbabel, the following import error is raised:

```
ImportError: /opt/miniconda3/envs/pmg/lib/python3.8/site-packages/openbabel/_openbabel.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN9OpenBabel5OBMol12GetGTDVectorERSt6vectorIiSaIiEE
```

## Steps to Reproduce
git clone this repository and checkout tag v3.1.1
```
mkdir build && cd build
cmake .. -D CMAKE_INSTALL_PREFIX=~/.local/bin/openbabel-3.1.1/
                 -D CMAKE_BUILD_TYPE=DEBUG 
                 -D BUILD_GUI=OFF
                 -D RUN_SWIG=ON 
                 -D PYTHON_BINDINGS=ON
make && make install
```

```
conda create -n developing_something_else python=3.8.3 && conda activate developing_something_else
pip install -e /path/to/something/else
conda install -c conda-forge gxx_linux-64=12.1.0 gcc_linux-64-12.1.0 gcc=12.1.0 gxx=12.1.0 
```
  This just ensures that glibcxx_3.4.30 is available in the environment and lets the build system use g++, gcc didn't work.
```
pip install --install-option=build_ext --install-option="-L/home/panos/.local/bin/openbabel-3.1.1/lib/" --install-option="-I/home/panos/.local/bin/openbabel-3.1.1/include/openbabel3/" openbabel
```
then, finally
```
python
>>> import openbabel
ERROR
```

**Comment by ghutchis** [comment]
If you have conda installed, why not:
`conda install -c conda-forge openbabel`

https://anaconda.org/conda-forge/openbabel

**Comment by ghutchis** [comment]
It looks like `_openbabel.so` is linking to some other `libopenbabel`, which is a common challenge if you have multiple versions installed.

**Comment by PanayotisManganaris** [comment]
> If you have conda installed, why not: `conda install -c conda-forge openbabel`

Didn’t think to check. So far it is working.

I will spend some time when I get a chance to understand what I'm doing wrong here -- probably just me in retrospect. I will keep the issue until concluded.

**Comment by PanayotisManganaris** [comment]
I can confidently say this was all nonsense.
