### ISSUE TITLE
PDB writer is not obeying space group naming convention for rhombohedral groups

### ISSUE THREAD

**Issue by afonari** [openbabel/openbabel#251]
In particular (from http://deposit.rcsb.org/adit/docs/pdb_atom_format.html ):
**For a rhombohedral space group in the hexagonal setting, the lattice type symbol used is H.**

For example this:
`_symmetry_space_group_name_H-M   'R -3 m :H'`

Should be converted to:
`H-3m`

The code to fix is around: https://github.com/openbabel/openbabel/blob/master/src/formats/pdbformat.cpp#L557

Similar patch exists for the Computational Crystallography Toolbox: http://sourceforge.net/p/cctbx/mailman/message/19334798/

**Comment by ghutchis** [comment]
OK, what's your proposed fix - a special case for "R .. :H" space groups to rewrite to "H" instead?

**Comment by alexandr-fonari** [comment]
I think, it would be a good idea to follow the patch from CCT, mentioned in the original description. In particular, to define a set of rhombohedral groups:
```
standard_rhombohedral_space_group_symbols = [
"R 3 :H",
"R 3 :R",
"R -3 :H",
"R -3 :R",
"R 3 2 :H",
"R 3 2 :R",
"R 3 m :H",
"R 3 m :R",
"R 3 c :H",
"R 3 c :R",
"R -3 m :H",
"R -3 m :R",
"R -3 c :H",
"R -3 c :R"]
```

And if the space group is one of those, than to rewrite R .. :H with H, as you noted.
