### ISSUE TITLE
Catch (swig) error exception in python for system exit.

### ISSUE THREAD

**Issue by PatReis** [openbabel/openbabel#2522]
## Environment Information
Open Babel version: 3.1.1
Operating system and version: Win10

## Expected Behavior
```python
import openbabel
import openbabel.pybel as pybel
try:
    mol = pybel.readstring("smi", 'BrC/C=C/c1ccc(O[C@@H]2CCCNC2)cc1')
    mol.make3D()
except:
    print("Catched exception")
```

## Actual Behavior
System exit that is not caught:

Open Babel Error  in OpenBabel::OBBuilder::GetFragmentCoord
  Rigid fragment C1CCCNC1 in rigid-fragments.txt has all zero coordinates.

## Steps to Reproduce
Other example: "COC(=O)C1C23CC(=O)CC1(c1ccc4c(c1)OCO4)C2NC3=O",
also happens for:
```python
builder = openbabel.OBBuilder()
build_okay = builder.Build(mol)
```

**Comment by ghutchis** [comment]
Can you run `--gen3d` on the command-line? This seems to be a case in which there's an install problem and `rigid-fragments.txt` isn't found.

How did you install?

**Comment by PatReis** [comment]
Hallo, thanks for answering. You are right in command line and with GUI it works fine. I am suprised that the python try and except statement does not work but if this is a critical error that goes along with a faulty installation this should not be a problem for workflows. I installed with conda-forge. I am checking my setup now...

**Comment by PatReis** [comment]
The babel data dir is specified by conda at ``BABEL_DATADIR=C:\Users\...\anaconda3\envs\...\share\openbabel`` and there is also a `ring-fragments.txt`.

I have problems getting the binaries plus pip installed for 3.1.1. So I can not test this at the moment.

**Comment by fredrikw** [comment]
I don't seem to be able to reproduce on my machine running Windows 10 and installing openbabel fresh (`conda install openbabel -c conda-forge`) in a conda environment running Python 3.10.
Could you try to create a new conda environment to test? (And double check that you are running the correct python...)

It's a different error message than when `rigid-fragments.txt` is missing (and in that case, it seems like there is a fall-back mechanism that provides a structure).
```
>obabel -:"BrC/C=C/c1ccc(O[C@@H]2CCCNC2)cc1" -ismi -omol --gen3d
==============================
*** Open Babel Error  in OpenBabel::OBBuilder::LoadFragments
  Cannot open ring-fragments-index.txt

 OpenBabel08102211013D

 35 36  0  0  1  0  0  0  0  0999 V2000
   15.2854   -6.1963    0.6627 Br  0  0  0  0  0  0  0  0  0  0  0  0
   13.6538   -5.1799    0.3704 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.2738   -4.5221    1.6597 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.1549   -3.1889    1.7844 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.8632   -2.4283    3.0137 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.0643   -2.9261    4.3048 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.9515   -2.0818    5.4201 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6588   -0.7266    5.2613 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6605    0.0345    6.3986 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.1570    1.3845    6.2683 C   0  0  2  0  0  0  0  0  0  0  0  0
   14.2087    1.6314    7.3590 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.5728    1.5865    8.7459 C   0  0  0  0  0  0  0  0  0  0  0  0
...
`

**Comment by PatReis** [comment]
Hallo @fredrikw , thank you very much.
I think I got it now. You are right, in conda prompt everything is fine. But I do not get any error message about `fragments.txt` as you have anymore...
Also this seems to work:

```python
>> import openbabel
>> import openbabel.pybel as pybel
>> mol = pybel.readstring("smi", 'BrC/C=C/c1ccc(O[C@@H]2CCCNC2)cc1')
>> mol.make3D()
```

It seems that in my IDE Pycharm the BABEL_DATADIR variable gets lost somehow. I could run it with:

```python
import os
os.environ["BABEL_DATADIR"] = "C:\Users\...\anaconda3\envs\...\share\openbabel"
import openbabel
import openbabel.pybel as pybel
try:
    mol = pybel.readstring("smi", 'BrC/C=C/c1ccc(O[C@@H]2CCCNC2)cc1')
    mol.make3D()
    print("everything is fine.")
except:
    print("Catched exception")
```

Just for your information there is also another issue related to this: #2356 
which could be closed...

Last thing:

Did you check the Openbabel GUI, also? I do not know what the error might be here; could be conflict with conda?

**Comment by fredrikw** [comment]
I did not check the GUI, I haven't installed the binary package for Windows, only through Conda.

**Comment by PatReis** [comment]
Okay, I do not really care about the GUI anyhow. I close this issue now and write a comment to #2356 .
Thanks for your help @fredrikw and @ghutchis
