### ISSUE TITLE
QUESTION: What is the likelihood that the openbabel python api is broken due to the new patch update and how int/str conversions are changed?

### ISSUE THREAD

**Issue by EChung0111** [openbabel/openbabel#2535]
So recently there has been a patch update with python and it affects how int/str conversions work, putting a cap on those conversions to 4300 characters for non-base 2 ints. Is there a decent chance this could affect the python API for openbabel and pybel. I would really appreciate an answer as I heavily depend on the openbabel library in my code

**Comment by fredrikw** [comment]
Since OpenBabel is written in C++, I really doubt that there would be an impact. The parts that are written in python are wrappers and hence limited to the variable types in C++. I also have problem seeing where such large numbers would be of use in cheminformatics.
