### ISSUE TITLE
PDBQT to SDF

### ISSUE THREAD

**Issue by sbembenek18** [openbabel/openbabel#2547]
## Environment Information
Open Babel version: 3.1.0
Operating system and version: CENTOS 7

## Expected Behavior
PDBQT converted to SDF with nonpolar protons added. 

## Actual Behavior

I cannot get a good conversion from pdbqt to sdf with version 3.1.0 -- oddly my older version 2.4 does better but still not perfect.
What am I missing here?

## Steps to Reproduce
obabel -ipdbqt my.pdbqt -osdf -O my.sdf -h

**Comment by robertwerner67** [comment]
Inferring from other conversions between other formats than pdbqt, does `obabel -ipdbqt my.pdbqt -h -osdf -O my.sdf` trade better?  Though it is adjustable (addition of "polar protons" bound to O/N, or "nonpolar protons" to C, or according to a pH value you dial), the shorthand `-h` (if I remember correctly, for pH 7.4) often works well.

Side note:  Debian offers a openbabel package for version 3.1.1 (`obabel -v` reports a time stamp `Oct 20 2022 -- 17:31:22`).

**Comment by sbembenek18** [comment]
Thanks, unfortunately, it didn't improve things.

**Comment by fredrikw** [comment]
How do you define `a good conversion`? Are you missing some specific proton or all? Could you give a short example file with the expected output?

**Comment by robertwerner67** [comment]
Is there a .pdbqt file 1) you may share (you might get in touch with your PI for this), and 2) isn't to large that you can share it here?  For this, archive the file(s) in question as a .zip; this is one of the acceptable file formats for upload here (hoover with the mouse over the lower rim of the input mask).

3) The original post described the addition of non-polar protons as (so far) problematic.  But, there is no share of a file to replicate the processing.  If it is about a larger molecule greater than say 500 Da, an indication which amino acid needs special attention may accelerate the scrutiny.

**Comment by sbembenek18** [comment]
Thanks for the replies. Here's an example PDBQT. Using 3.1.0, none of the protons are added and valence is wrong on most/all atoms. With 2.4.1, this is not an issue. 
[small_mol_example.pdbqt.tar.gz](https://github.com/openbabel/openbabel/files/10117492/small_mol_example.pdbqt.tar.gz)

**Comment by robertwerner67** [comment]
There are two approaches identified to address the issue.  The first one will process the data with intermediate files you may check and use elsewhere.  The second one relays the result of one step into the next one as input via pipes; aside of the very input file, there will be only one permanent record of the output.

+ approach a, step by step:

``` shell
obabel small_mol_example.pdbqt -O without_hydrogens.pdb 
obabel without_hydrogens.pdb -h -O with_hydrogens.pdb
obabel with_hydrogens.pdb -xh -O with_hydrogens.pdbqt
```

Note, the addition of hydrogens (`-h`, second step) is *a parameter*.  The preservation of hydrogens (`-xh`, third step) is an *output option* to affect the format of the result already computed; this is similar to e.g., `-xc 8` for the generation of a .svg to display multiple molecules at once, but with an explicit, user defined constraint to write a table of 8 columns.

+ approach b, use of pipes

If your operating system allows to concatenate multiple instructions (e.g., Linux Debian), the result of one processing may be the input of the next.  E.g.,

``` bash
obabel small_mol_example.pdbqt -opdb | obabel -ipdb -h -opdb | obabel -ipdb -xh -O one_step_with_hydrogens.pdbqt
```

Either one of the two routes proceeds smoothly (obabel 3.1.1, Linux Debian 12).  In the display of e.g., Jmol, the addition of hydrogens appears plausible.  Out of caution, I recommend to check if the indazole is the correct one; perhaps you have additional evidence for this, or its isomer.

In the .zip attached below, I copy the results written by obabel, and visualizations by Jmol (14.32.79, 2022-10-26 15:52) reading the saturated .pdb and .pdbqt.  Last but not least: Thank you for pointing out by example `.tar.gz` equally is a file format suitable for upload in a discussion here on GitHub, too.

[obabel_pdbqt_conversion.zip](https://github.com/openbabel/openbabel/files/10121334/obabel_pdbqt_conversion.zip)

**Comment by fredrikw** [comment]
I think that the real problem lies in the reading of the pdbqt-file. Trying to transform to SMILES gives a lot of radical Carbons so it seems that the pdbqt reader doesn't handle implicit hydrogens. 
```(bash)
➜ obabel small_mol_example.pdbqt -osmi
C1([C][C]1)(NC(=O)c1[nH]nc2[C]=[C][C]=[C]c12)[C]NC(=O)C1=[C]C(=N[C]=[C]1)[C]O   small_mol_example.pdbqt
1 molecule converted
```
This is corrected with the round tripping through pdb-format
```(bash)
➜ obabel small_mol_example.pdbqt -opdb | obabel -ipdb -osmi
1 molecule converted
C1(CC1)(NC(=O)c1[nH]nc2ccccc12)CNC(=O)c1cc(ncc1)CO
1 molecule converted
```
Why that is, I haven't found out yet. I looked briefly at the code but I couldn't see anything obvious.

**Comment by fredrikw** [comment]
Long shot: It could maybe be due to the removal of `atom.ForceImplH();` in 6ed745f93b6dd130aebb25e4dbda0fe5092d4e4c
What do you think @baoilleach?

**Comment by fredrikw** [comment]
I think I found the problem by looking at the code for the pdb-format, see PR above.

**Comment by sbembenek18** [comment]
Yes, this the whole radical carbon atoms is the same problem I had with pdbqt-->sdf. This is not an issue for me when using 2.4.1 however. Thanks!

**Comment by robertwerner67** [comment]
This will streamline the pdbqt2pdb conversion.  And it brings the conversion (back) into a pattern similar to the other conversions, `obabel in.format -O out.format`, too.  Thank you.

**Comment by sbembenek18** [comment]
So this will be something that is fixed in the next version?

**Comment by robertwerner67** [comment]
@sbembenek18 Yes this will be different than now because commit [2b211d6](https://github.com/openbabel/openbabel/commit/2b211d6acfc0f9e1c6746a984da3483b729aa32b) by December 7, 2022 is in branch master.

**Comment by fredrikw** [comment]
And if you comfortable with compiling from master yourself, it is available to test right away.
