### ISSUE TITLE
OpenBabel cannot write output file

### ISSUE THREAD

**Issue by vidinjo** [openbabel/openbabel#2602]
Hello!
Everything worked just fine until this friday, but since then i keep getting a message that openbabel cannot open input file or write output file, eventhough i did it many times before and it worked just fine. I used a command for 2D similarity, and i get this error message.
babel: cannot write output format!
Open Babel 2.3.1 -- Oct  9 2011 -- 17:58:50
Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>
Try  -H option for more information.

## Environment Information
Open Babel version: 2.3.1
Operating system and version: Wingows 10 Pro for Workstations version 22H2

## Expected Behavior
The command should convert molecules with Tanimoto index above 0.5

## Actual Behavior
babel: cannot write output format!
Open Babel 2.3.1 -- Oct  9 2011 -- 17:58:50
Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>
Try  -H option for more information.

**Comment by flatstik** [comment]
Why are you using archaic version of openbabel? Please try and install the current one: 3.1.1

**Comment by vidinjo** [comment]
I am using it as i have an established workflow, but you are correct, it works on the current one.
the command i used is: babel ZBG_filtered_zinc20_database_pains.fs results_mbl11.sdf -sO=C(CS)Nc1cc(Cl)cc2c1Cc1ccccc1C2 at0.5
but then again as i used the 3.1.1, i got different hits in GUI and with the use of command line, which is a tad confusing.

**Comment by fredrikw** [comment]
Is that your exact command? If so, I think you miss a `-` before `at0.5`.

**Comment by vidinjo** [comment]
Thank you, it used to work without the - before at0.5, but anyways, this solves my issue. I appreciate the help a lot!
