### ISSUE TITLE
It can not convert elements such as Li, Mg from gro to pdb

### ISSUE THREAD

**Issue by y805939188** [openbabel/openbabel#2614]
## Environment Information
Open Babel version: Open Babel 3.1.0 -- Dec 12 2022 -- 05:03:20
Operating system and version: Mac M1

## Expected Behavior

Obabel can convert the format normally.

## Actual Behavior

Some elements can not be coverted from gro file to pdb file. I tried some elements like Li, Mg, Be.

## Steps to Reproduce

This is my `.gro` file content:
```
GAFF force field
   66
   15EC      Li    1   1.802   3.228   1.416 -0.5422 -0.0976 -0.1356
   41EC       C    2   1.943   2.749   1.644  0.6229 -0.0702 -0.7896
   41EC      C1    3   1.961   2.828   1.772  0.0766 -0.1379  0.1261
   41EC       O    4   1.932   2.968   1.738 -0.1870 -0.4902 -0.1177
   41EC      C2    5   1.897   2.970   1.604  0.4416 -0.4313  0.3827
   41EC      O1    6   1.866   3.069   1.542 -0.2911  0.2250  0.3756
   41EC      O2    7   1.885   2.848   1.556 -0.0665  0.1267 -0.4593
   41EC       H    8   1.887   2.655   1.652  0.9759 -0.2466 -0.3474
   41EC      H1    9   2.042   2.732   1.602 -0.0691  0.5175 -2.7663
   41EC      H2   10   2.066   2.813   1.797  0.6073 -0.2252 -1.9787
   41EC      H3   11   1.903   2.791   1.859 -2.1307 -0.4792 -1.3989
   44EC       C   12   2.035   2.297   2.100 -0.7722  0.0818  0.3746
   44EC      C1   13   2.098   2.224   1.975 -0.1648  0.0654  0.1066
   44EC       O   14   2.065   2.309   1.863  0.5016  0.5182 -0.4674
   44EC      C2   15   1.976   2.403   1.905  0.1617 -0.4948  0.4871
   44EC      O1   16   1.939   2.493   1.833 -0.2347  0.3852 -0.2123
   44EC      O2   17   1.964   2.403   2.040  0.5018  0.0404 -0.1403
   44EC       H   18   2.114   2.332   2.167  0.2077 -1.8570  0.3208
   44EC      H1   19   1.980   2.217   2.151 -0.2964  1.5837  3.4642
   44EC      H2   20   2.047   2.128   1.957 -2.0608  0.9698  0.5079
   44EC      H3   21   2.206   2.207   1.984  0.1159  0.1476 -2.3460
  182EMC      C   22   1.652   2.967   1.938 -0.5972  0.2232  0.6456
  182EMC     C1   23   1.521   2.897   1.888  0.2016  0.7386 -0.8290
  182EMC      O   24   1.545   2.794   1.793  0.0008  0.2908 -0.5534
  182EMC     C2   25   1.563   2.826   1.668 -0.0888  0.1790  0.5457
  182EMC     O1   26   1.588   2.936   1.623 -0.7181  0.0172 -0.9076
  182EMC     O2   27   1.553   2.713   1.587 -0.0828 -0.6685 -0.3943
  182EMC     C3   28   1.597   2.719   1.450  0.5024 -0.2811  0.2591
  182EMC      H   29   1.702   2.992   1.843 -2.2493 -0.1730 -0.3679
  182EMC     H1   30   1.708   2.893   1.996 -0.6685 -0.8339 -0.5901
  182EMC     H2   31   1.624   3.049   2.005  2.4448 -0.9075  3.5863
  182EMC     H3   32   1.466   2.977   1.837 -0.6818  1.4516  1.1547
  182EMC     H4   33   1.450   2.875   1.968 -0.2996  1.9128 -0.9261
  182EMC     H5   34   1.520   2.765   1.387  0.5735  1.9109  1.6654
  182EMC     H6   35   1.637   2.623   1.416  1.0196  0.2375 -0.6548
  182EMC     H7   36   1.693   2.772   1.445  0.0161  0.6645  0.5827
  192EMC      C   37   2.603   2.977   1.709  0.2419 -0.5229  0.3072
  192EMC     C1   38   2.601   2.890   1.577 -0.2015  0.2674  0.5924
  192EMC      O   39   2.555   2.761   1.604  0.3891 -0.2930  0.3360
  192EMC     C2   40   2.420   2.745   1.601 -0.1657  0.0491  0.3832
  192EMC     O1   41   2.335   2.835   1.592 -0.8101 -0.1854 -0.6991
  192EMC     O2   42   2.404   2.612   1.635 -0.1953  0.0212 -0.0009
  192EMC     C3   43   2.286   2.566   1.691  0.0342  0.1661 -0.2462
  192EMC      H   44   2.502   3.015   1.726 -0.2643 -1.7168  0.0653
  192EMC     H1   45   2.672   3.062   1.712 -0.5667  0.1074  2.4366
  192EMC     H2   46   2.635   2.914   1.793  0.5488 -1.0117 -0.1596
  192EMC     H3   47   2.706   2.879   1.545 -0.7230 -0.5184 -0.9714
  192EMC     H4   48   2.541   2.940   1.499  1.6073  0.2840 -0.8618
  192EMC     H5   49   2.305   2.474   1.749  0.2330 -0.3704 -1.1516
  192EMC     H6   50   2.208   2.551   1.616 -2.1097  0.9336  1.6878
  192EMC     H7   51   2.250   2.642   1.762 -0.7889  0.6878 -1.2049
  199EMC      C   52   1.633   2.515   1.956 -0.3302  0.6927  0.2476
  199EMC     C1   53   1.625   2.490   1.809  0.4996  0.0649 -0.0782
  199EMC      O   54   1.675   2.361   1.780  0.1035  0.1058  0.0193
  199EMC     C2   55   1.669   2.314   1.655 -0.4219 -0.4755 -0.2686
  199EMC     O1   56   1.591   2.356   1.572  0.8656 -0.0181 -0.0151
  199EMC     O2   57   1.762   2.213   1.627 -0.0487  0.0049 -0.5198
  199EMC     C3   58   1.784   2.158   1.493  0.0822  0.1957 -0.8029
  199EMC      H   59   1.539   2.493   2.009 -1.2197  1.4432 -0.9754
  199EMC     H1   60   1.654   2.622   1.974 -0.4898  0.9029 -0.7769
  199EMC     H2   61   1.710   2.454   2.005 -1.8533 -0.2063  1.6350
  199EMC     H3   62   1.685   2.569   1.763 -0.1682  0.2987 -0.5554
  199EMC     H4   63   1.522   2.499   1.772  0.3213 -1.1355  0.0788
  199EMC     H5   64   1.759   2.210   1.400  0.8308  1.1662 -0.4890
  199EMC     H6   65   1.730   2.063   1.495  0.4589 -0.0291  1.4094
  199EMC     H7   66   1.889   2.132   1.475 -0.2488 -1.7239 -0.1674
   3.00168   3.00168   3.00168
```
There is a `Li` element in the first line, I tried convert the file from `.gro` to `.pdb` but the `Li`(or other elements including but not limited to `Li`) element was not transformed properly:
`Li`
![mcxhVVqylT](https://github.com/openbabel/openbabel/assets/28889103/45d743bd-4509-472c-9998-070cf3fd0589)

`Be`
![KcKmDuwZ5O](https://github.com/openbabel/openbabel/assets/28889103/39d30ddd-503b-4673-8ac7-d9ab1105e689)

`Mg`
![l5NLIFpoVS](https://github.com/openbabel/openbabel/assets/28889103/b4981a23-42f0-442d-b092-a5e8b75c099a)

**All of this elements that failed I had tried switching capital and lower case**

But some elements was transformed like Na or K:

![yoJmxIuzoO](https://github.com/openbabel/openbabel/assets/28889103/d8818997-b499-4350-a8fb-963efe6ff8a7)
![yIxHhq7EVq](https://github.com/openbabel/openbabel/assets/28889103/6cb1e83b-378a-4a48-aaac-decd7614254a)

So I want to ask that it is a bug?

Thanks~

**Comment by y805939188** [comment]
> According to the documentation, not all elements are covered yet. To quote:
> 
> > Right now there is only limited support for element perception. It works for elements with one letter symbols if the atomtype starts with the same letter.
> 
> source: https://open-babel.readthedocs.io/en/latest/FileFormats/GRO_format.html
> 
> Let's say I generate a .gro about diethyl ether by
> 
> ```shell
> $ obabel -:"CCOCC" -h --gen3d -ogro
> 
> 15
>  1UNL      C    1   0.095  -0.007   0.005
>  1UNL      C    2   0.247  -0.010   0.002
>  1UNL      O    3   0.297   0.089   0.093
>  1UNL      C    4   0.439   0.091   0.094
>  1UNL      C    5   0.486   0.197   0.191
>  1UNL      H    6   0.054  -0.082  -0.063
>  1UNL      H    7   0.058   0.092  -0.024
>  1UNL      H    8   0.058  -0.027   0.106
>  1UNL      H    9   0.283   0.012  -0.099
>  1UNL      H   10   0.283  -0.109   0.033
>  1UNL      H   11   0.477   0.113  -0.006
>  1UNL      H   12   0.477  -0.007   0.126
>  1UNL      H   13   0.448   0.296   0.162
>  1UNL      H   14   0.595   0.201   0.195
>  1UNL      H   15   0.448   0.177   0.292
> 0.00000   0.00000   0.00000
> 1 molecule converted
> ```
> 
> As a permanent record (file `ether.gro.txt` attached below), this works fine for subsequent edits by obabel (e.g. conversion to .xyz). Substitution of the first atom entry to `C1` (see `ether_modified.gro.txt` attached) does not matter. Introduction of `Be` as second does not stop the conversion, however yields an .xyz with `B` instead of `Be`. An additional edit of atom 3 to either `Li`, `Mg`, `Na`, `Ca`, `Fe`, `Cl`, or `Br` currently yields
> 
> ```shell
> $ obabel ether_modified.gro -oxyz
> ==============================
> *** Open Babel Error  in Convert
>   Convert failed with an exception
> 0 molecules converted
> ```
> 
> equally in an instance of openbabel as provided by Linux Debian 13/trixie (branch testing, version 3.1.1 -- Jan 4 2023 -- 09:58:24).
> 
> [ether_modified.gro.txt](https://github.com/openbabel/openbabel/files/12237940/ether_modified.gro.txt) [ether.gro.txt](https://github.com/openbabel/openbabel/files/12237942/ether.gro.txt)

Thank you~ I understand. May I ask if it will be fixed in the future?

**Comment by robertwerner67** [comment]
> Thank you~ I understand. May I ask if it will be fixed in the future? 

Sorry, I do not know when this will be corrected.

Maybe one of the maintainers reads this thread and can easily identify the file(s) to adjust.

Meanwhile, maybe there is an other converter than openbabel known among the users of gromacs (maybe in a user list, perhaps on [mattermodelling.se](https://mattermodeling.stackexchange.com/), they use a dedicated tag `gromacs` to highlight questions specific to this program ([81 examples](https://mattermodeling.stackexchange.com/questions/tagged/gromacs), so far).  Else, [Jmol](https://jmol.sourceforge.net/) is a freely available structure viewer which can visualize your model structure and write both images as well as export into a couple of other formats from the program's console (File -> Console) by a command in pattern of 

```
write "structure.png";
write "structure.xyz";
```

![structure](https://github.com/openbabel/openbabel/assets/60490931/4ad8a53a-c31b-4899-9508-7b5480324152)

[structure.xyz.txt](https://github.com/openbabel/openbabel/files/12255050/structure.xyz.txt)

**Comment by y805939188** [comment]
> > Thank you~ I understand. May I ask if it will be fixed in the future?
> 
> Sorry, I do not know when this will be corrected.
> 
> Maybe one of the maintainers reads this thread and can easily identify the file(s) to adjust.
> 
> Meanwhile, maybe there is an other converter than openbabel known among the users of gromacs (maybe in a user list, perhaps on [mattermodelling.se](https://mattermodeling.stackexchange.com/), they use a dedicated tag `gromacs` to highlight questions specific to this program ([81 examples](https://mattermodeling.stackexchange.com/questions/tagged/gromacs), so far). Else, [Jmol](https://jmol.sourceforge.net/) is a freely available structure viewer which can visualize your model structure and write both images as well as export into a couple of other formats from the program's console (File -> Console) by a command in pattern of
> 
> ```
> write "structure.png";
> write "structure.xyz";
> ```
> 
> ![structure](https://user-images.githubusercontent.com/60490931/258236654-4ad8a53a-c31b-4899-9508-7b5480324152.png)
> 
> [structure.xyz.txt](https://github.com/openbabel/openbabel/files/12255050/structure.xyz.txt) [structure.pdb.txt](https://github.com/openbabel/openbabel/files/12255073/structure.pdb.txt)

Thank you for your reply and advice🙏🙏🙏. I will try another way to finish my scenario.
