### ISSUE TITLE
Issue with building Openbabel-3.1.1

### ISSUE THREAD

**Issue by tgupta2222** [openbabel/openbabel#2615]
I am getting following issue while building the openbabel version: :
```
/home/admin/software/openbabel-openbabel-3-1-1/include/openbabel/typer.h:70:1: error: ‘thread_local’ does not name a type
/home/admin/software/openbabel-openbabel-3-1-1/include/openbabel/typer.h:84:1: error: ‘thread_local’ does not name a type
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:107:10: error: ‘thread_local’ does not name a type
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:108:10: error: ‘thread_local’ does not name a type
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:109:10: error: ‘thread_local’ does not name a type
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘char* OpenBabel::OBAtom::GetType()’:
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:473:9: error: ‘atomtyper’ was not declared in this scope
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘unsigned int OpenBabel::OBAtom::GetHyb() const’:
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:500:7: error: ‘atomtyper’ was not declared in this scope
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘double OpenBabel::OBAtom::GetPartialCharge()’:
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:547:9: error: ‘phmodel’ was not declared in this scope
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘bool OpenBabel::OBAtom::IsAromatic() const’:
/home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:778:7: error: ‘aromtyper’ was not declared in this scope
make[2]: *** [src/CMakeFiles/openbabel.dir/atom.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/openbabel.dir/all] Error 2
make: *** [all] Error 2
```

Please advise

**Comment by ghutchis** [comment]
Can you provide more information? What OS are you using? What compiler are you using? (thread_local is defined in C++ so I suspect you are using an old compiler)

**Comment by tgupta2222** [comment]
My HPC :
```
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

**Comment by tgupta2222** [comment]
I am loading two modules : cmake/3.19.7 and gcc/7.2.0

**Comment by tgupta2222** [comment]
If I change the compiler from` gcc to intel/2015.6`, the error comes again as following : 
![image](https://github.com/openbabel/openbabel/assets/132712537/64c13d6f-2ba9-49da-89db-3143cd0fd236)
Suggest please

**Comment by tgupta2222** [comment]
However, I could find the missing library present/installed already in my HPC at :` /usr/lib/i386-linux-gnu/libstdc++.so.6`  
Do I need to export the library path?

**Comment by tgupta2222** [comment]
I am still unable to cross pa

> I am getting following issue while building the openbabel version: :
> 
> ```
> /home/admin/software/openbabel-openbabel-3-1-1/include/openbabel/typer.h:70:1: error: ‘thread_local’ does not name a type
> /home/admin/software/openbabel-openbabel-3-1-1/include/openbabel/typer.h:84:1: error: ‘thread_local’ does not name a type
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:107:10: error: ‘thread_local’ does not name a type
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:108:10: error: ‘thread_local’ does not name a type
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:109:10: error: ‘thread_local’ does not name a type
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘char* OpenBabel::OBAtom::GetType()’:
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:473:9: error: ‘atomtyper’ was not declared in this scope
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘unsigned int OpenBabel::OBAtom::GetHyb() const’:
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:500:7: error: ‘atomtyper’ was not declared in this scope
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘double OpenBabel::OBAtom::GetPartialCharge()’:
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:547:9: error: ‘phmodel’ was not declared in this scope
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp: In member function ‘bool OpenBabel::OBAtom::IsAromatic() const’:
> /home/admin/software/openbabel-openbabel-3-1-1/src/atom.cpp:778:7: error: ‘aromtyper’ was not declared in this scope
> make[2]: *** [src/CMakeFiles/openbabel.dir/atom.cpp.o] Error 1
> make[1]: *** [src/CMakeFiles/openbabel.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> Please advise

I am still stuck at this point. Please help me to resolve the issue

**Comment by tgupta2222** [comment]
[http://forums.openbabel.org/](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fforums.openbabel.org%2F&data=05%7C01%7Ct.gupta%40ucl.ac.uk%7C7117f26659874ced4d2308db982618c4%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638271061623334663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9QQCI1bZnGbXR4k7ASflVn4Iif0xZLPaXadhjLxkAc4%3D&reserved=0)

**Comment by tgupta2222** [comment]
![image](https://github.com/openbabel/openbabel/assets/132712537/6b8f279a-4788-40c8-bf22-7655243e565c)

**Comment by fredrikw** [comment]
I'm no expert in compiling, but you stated a different error when you used the intel compiler than when you used gcc. Is that so? Or do you see the CMake error also for gcc?

**Comment by tgupta2222** [comment]
Yes, I am getting the error even though I have loaded gcc module.  Any help would be really appreciated. 'Thread_local' related problem I looked through all possible resources but could not find any solution in regards to this openbabel install.

**Comment by fredrikw** [comment]
Then I would guess that that is the main problem. That CMake doesn't seem to be able to find a good version of libstc++. How you should fix it though, I don't know.

**Comment by tgupta2222** [comment]
The error does not state anything about libstc++. Following error :
![image](https://github.com/openbabel/openbabel/assets/132712537/dd9b7af1-c9e3-48e7-ad54-38b5987bd0c4)

**Comment by fredrikw** [comment]
If you have the error from CMake that says it doesn't find libstc++, and thread_local is a part of c++ I would guess that it's related yes.

**Comment by tgupta2222** [comment]
The error from CMake with libstc++ is gone now and only the thread_local error seems to retain. So, I need to mention the path of libstc++ desired versions then?

**Comment by fredrikw** [comment]
I asked above if you had the CMake error also with gcc (and you answered yes), if you didn't then you can ignore my following comments.
(But there still seems to be a problem with your compilation environment since thread_local is a c++ thing, not an OpenBabel thing.)

**Comment by tgupta2222** [comment]
I posted two error and sorry that might have caused confusion. libstc++ error is gone when I load gcc module and only `thread_local does not name not a type` error is still showing.

**Comment by tgupta2222** [comment]
Hi
I am loading gcc version 7.2.0 but still with CMake Openbabel selects  gcc version 4.7.2 (Debian 4.7.2-5). Can that be the cause of error and I need to ensure gcc 7.2.0 is being taken for compilation?
