### ISSUE TITLE
Assertion failure in rapidjson when using output of Avogadro2

### ISSUE THREAD

**Issue by jakiki6** [openbabel/openbabel#2619]
## Environment Information
Open Babel version: Open Babel 3.1.1
Operating system and version: Gentoo

## Expected Behavior

For it to not crash

## Actual Behavior

`obabel` crashes if you give it an exported cjson file from Avogadro2 or running Extensions>Open Babel>Optimize Geometry

The message is the following:
```obabel: /usr/include/rapidjson/document.h:1053: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
[1]    26929 IOT instruction  /home/laura/avo/openchemistry-build/prefix/bin/obabel -icjson -ocjson  --noh```

## Steps to Reproduce
- build https://github.com/openchemistry/openchemistry
- open Avogadro2
- create something
- press Ctrl+Alt+O

alternatively
- build https://github.com/openchemistry/openchemistry
- open Avogadro2
- create something
- save it as a cjson file like the one I attached
- run `$PREFIX/bin/obabel -icjson -ocjson --minimize --noh --log --ff UFF < e.cjson`

[e.cjson.txt](https://github.com/openbabel/openbabel/files/12336311/e.cjson.txt)
(btw ignore the .txt ending github doesn't let me upload it otherwise)

**Comment by ghutchis** [comment]
Yes - this is now fixed in `HEAD` - not sure how I missed that one. The next release for both OB and Avogadro will fix this.
