### ISSUE TITLE
Import Openbabel error from Python calling

### ISSUE THREAD

**Issue by tgupta2222** [openbabel/openbabel#2620]
**Environment Information**
Open Babel version: Open Babel 3.1.1

**Operating system and version:** 
 PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

**Behaviour procured** 
I have successfully installed Python bindings for Openbabel. But when I try to import openbabel from a new Python shell, it shows error as below: 
```
:```
~$ /usr/local/bin/python3.10
Python 3.10.9 (main, Aug 10 2023, 15:45:29) [GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openbabel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/openbabel/__init__.py", line 3, in <module>
    from . import openbabel
  File "/usr/local/lib/python3.10/site-packages/openbabel/openbabel.py", line 19, in <module>
    from . import _openbabel
ImportError: libopenbabel.so.7: cannot open shared object file: No such file or directory 
```

I could see the presence of libopenbabel.so.7 inside the lib folder of openbabel installed directory. But still, it is denying the presence. 

Please suggest

**Comment by tgupta2222** [comment]
Thanks, I just found https://github.com/openbabel/openbabel/issues/2413 useful to help solving my issue. So closing this issue

**Comment by robertwerner67** [comment]
By today's perspective, Debian 7/wheezy you report is elder than old stable.  If your workflow(s) permit, consider to install and use a newer release (stable branch Debian 12/bookworm, for example).
