### ISSUE TITLE
How to use OBGraphSym.GetSymmetry

### ISSUE THREAD

**Issue by 545487677** [openbabel/openbabel#2622]
Hello, this is the first time I use openbabel. Now I want to check whether a smile molecule is symmetric. When I used python API, It reports an error.

import openbabel

mol = openbabel.OBMol()
conv = openbabel.OBConversion()
conv.SetInFormat('smi')
conv.ReadString(mol, 'C1CC2(C1)CC(CC3C2CCC4=CC(=O)CCC34C)O')

sym = openbabel.OBSymmetry()

sym.Setup(mol)

     15     return getattr(openbabel, name)
     16 else:
---> 17     raise AttributeError

AttributeError: 

Can you help me fix this error?  
Thank you!

**Comment by baoilleach** [comment]
Is your question about OBSymmetry or OBGraphSym?

**Comment by fredrikw** [comment]
I believe @baoilleach's question was an either/or question, not a yes/no question. In the title you ask about OBGraphSym.GetSymmetry and in the code you use openbable.OBSymmetry so which of them do you ask about? Or put another way, what are you trying to do.
Your example code also seems to have been mangled by the formatting so if you could try to insert that again, while making sure that the formatting work by looking at the preview, it will be easier to help you.

**Comment by nbehrnd** [comment]
@545487677 A SMILES string is a reduced representation of the molecular structure.  It describes the atoms' connection and bond orders (on occasion, implicitly) and features of stereochemistry (keyword E/Z, or R/S in CIP rules).  It however does not report a specific conformer, i.e. *specific* (x,y,z) coordinates as in an .xyz or a .sdf file are absent.  For molecules with conformational flexibility (rings like cyclohexane, rotational free single bonds as in alkyl chains to mention two examples) like your molecule

![molecule](https://github.com/openbabel/openbabel/assets/19709084/5a161d9c-f9db-4607-a39f-33b6e5d010f9)

this is a crucial information missing.

**Comment by fredrikw** [comment]
This is how you use OBGraphSym.GetSymmetry:
```python
from openbabel import openbabel
mol = openbabel.OBMol()
conv = openbabel.OBConversion()
conv.ReadString(mol, 'C1CC2(C1)CC(CC3C2CCC4=CC(=O)CCC34C)O')
conv.SetInFormat('smi')
conv.ReadString(mol, 'C1CC2(C1)CC(CC3C2CCC4=CC(=O)CCC34C)O')
gsym = openbabel.OBGraphSym(mol)
symmetry = openbabel.vectorUnsignedInt()
print(gsym.GetSymmetry(symmetry))
print(list(symmetry))
```
The above will yield the following output:
```
19
[4, 10, 19, 10, 11, 14, 8, 17, 15, 9, 6, 16, 7, 13, 2, 5, 12, 18, 3, 1]
```
I do believe that since the number of atoms in the SMILES and the number of symmetry classes (19) is the same that the molecule doesn't have any symmetry. But note that this is graph symmetries on an atom level. It doesn't mean that the entire molecule is symmetric even if you have symmetries in the graph. So I would advise you to test on several examples to find how to do it best. For the symmetric molecule `CCc(c1)cccc1CC` I get the following:
```
>>> conv.ReadString(mol, 'CCc(c1)cccc1CC')
True
>>> gsym = openbabel.OBGraphSym(mol)
>>> gsym.GetSymmetry(symmetry)
6
>>> list(symmetry)
[1, 3, 6, 5, 4, 2, 4, 6, 3, 1]
```
While `FC(F)(F)c1cc(C)ccc1` will give:
```
>>> gsym.GetSymmetry(symmetry)
9
>>> mol.NumAtoms()
11
>>> list(symmetry)
[2, 9, 2, 2, 8, 6, 7, 1, 4, 3, 5]
```
i.e. the three F atoms are symmetric but not the molecule as a whole...

**Comment by ghutchis** [comment]
The point group is different from the graph symmetry, but yes there is a brute-force point group detection code. In C++

```
  OBMol mol;
  OBPointGroup pg;

  pg.Setup(&mol);
  std::cout << "Point Group: " << pg.IdentifyPointGroup() << std::endl;
  pg.Symmetrize(&mol);
```
