### ISSUE TITLE
Command obrms not found

### ISSUE THREAD

**Issue by 1980whisky** [openbabel/openbabel#2626]
Hello,

I installed the version 3.1.0 of Open Babel on Linux, but cannot find the command obrms for computing the RMSD of two conformations (all other commands such as obgen, obgrep, obrotate are available). Could you please verify this? Thank you in advance.

Regards,

**Comment by dkoes** [comment]
`obrms` will only be built if eigen3 is found (also, MINIMAL_BUILD needs to be off, but this is the default).  If cmake isn't finding eigen3 and it is installed, specify EIGEN3_INCLUDE_DIR directly.

**Comment by 1980whisky** [comment]
Thank you Pr.@dkoes for your response. Indeed I hadn't installed eigen3. After eigen3 had been installed, obrms was found.

**Comment by Dadiao-shuai** [comment]
How to set obrms to use Hungarian Algorithm to calculate RMSD?

**Comment by dkoes** [comment]
You don’t, it uses graph isomorphism to identify matching points.
