### ISSUE TITLE
problem openbabel installation

### ISSUE THREAD

**Issue by ivzzognam** [openbabel/openbabel#2627]
Guyss i tried to follow this on my linux system : 

https://github.com/seanharr11/phytebyte

i'm actually blocked on the 4th step! after pip install openbabel, this is outpout: 

 pip install openbabel
Defaulting to user installation because normal site-packages is not writeable
Collecting openbabel
  Using cached openbabel-3.1.1.1.tar.gz (82 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: openbabel
  Building wheel for openbabel (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Warning: invalid version number '3.1.1.1'.
      Guessing Open Babel location:
      - include_dirs: ['/usr/include/python3.10', '/usr/local/include/openbabel3']
      - library_dirs: ['/usr/local/lib']
      building 'openbabel._openbabel' extension
      swigging openbabel/openbabel-python.i to openbabel/openbabel-python_wrap.cpp
      swig -python -c++ -small -O -templatereduce -naturalvar -I/usr/include/python3.10 -I/usr/local/include/openbabel3 -o openbabel/openbabel-python_wrap.cpp openbabel/openbabel-python.i

      Error: SWIG failed. Is Open Babel installed?
      You may need to manually specify the location of Open Babel include and library directories. For example:
        python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
        python setup.py install
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openbabel
  Running setup.py clean for openbabel
Failed to build openbabel
Installing collected packages: openbabel
  Running setup.py install for openbabel ... error
  error: subprocess-exited-with-error

  × Running setup.py install for openbabel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build_ext
      Warning: invalid version number '3.1.1.1'.
      Guessing Open Babel location:
      - include_dirs: ['/usr/include/python3.10', '/usr/local/include/openbabel3']
      - library_dirs: ['/usr/local/lib']
      building 'openbabel._openbabel' extension
      swigging openbabel/openbabel-python.i to openbabel/openbabel-python_wrap.cpp
      swig -python -c++ -small -O -templatereduce -naturalvar -I/usr/include/python3.10 -I/usr/local/include/openbabel3 -o openbabel/openbabel-python_wrap.cpp openbabel/openbabel-python.i

      Error: SWIG failed. Is Open Babel installed?
      You may need to manually specify the location of Open Babel include and library directories. For example:
        python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
        python setup.py install
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> openbabel

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

can anyone help me ? A BIG BIG BIG THANKSSSS

**Comment by ghutchis** [comment]
If you want Python, we strongly recommend using `conda` and the `condo-forge` channel (e.g. `mambaforge`)

**Comment by ivzzognam** [comment]
> If you want Python, we strongly recommend using `conda` and the `condo-forge` channel (e.g. `mambaforge`)

so you mean, repeat the same command using condo-forge ?

**Comment by fredrikw** [comment]
No, he meant that you use the Mambaforge (or Anaconda/miniconda) python distribution (see https://mamba.readthedocs.io/en/latest/mamba-installation.html).
Then the openbabel installation is an easy command `mamba install openbabel` or `conda install -c conda-forge openbabel`

**Comment by nbehrnd** [comment]
@ivzzognam [openbabel-wheel](https://pypi.org/project/openbabel-wheel/) is one alternative to circumnavigate the currently present problem of openbabel 3.1.1.1 available from PyPI.

In the previous week, I faced a similar problem for an instance of Linux Xubuntu 22.04 LTS Jammy to use [my fork](https://github.com/nbehrnd/RegioSQM) of Jan Jensen's RegioSQM.  In this particular case, installation of openbabel via `apt` was not possible (for  user privileges), but the creation of a virtual environment for Python 3.10.2 and subsequent `pip3 install -r requirements.txt` with a `requirements.txt` file of

```
numpy>=1.24.2
openbabel-wheel==3.1.1.17
rdkit>=2022.09.3
```

allowed to use it.  Contrasting to your framework of phytebyte, RegioSQM however works locally without interaction with a database.  Here, openbabel's task is to convert geometries into input files for subsequent computations with MOPAC.

**Comment by ivzzognam** [comment]
ok thanks to everyone !! I resolved it using conda with commands signed here :
 https://github.com/conda-forge/openbabel-feedstock
