### ISSUE TITLE
curl: (60) SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by ivzzognam** [openbabel/openbabel#2628]
Hi guys, i'm trying to follow this papeline on git hub: 
https://github.com/seanharr11/phytebyte

When i arrive to point four this is the result : 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

How can i resolve it ? i don't want to use the site without protection.... 

Thanks

**Comment by ivzzognam** [comment]
Download the 'FooDB SQL file' from [http://foodb.ca/downloads](http://foodb.ca/downloads)  
This is the site i need to use

**Comment by fredrikw** [comment]
That site is not part of OpenBabel so you need to take that either with them or with the creator of phytebyte.
