### ISSUE TITLE
Ambiguous stereochemistry in -opng

### ISSUE THREAD

**Issue by Quaddroo** [openbabel/openbabel#2631]
## Environment Information
Open Babel version: 3.1.0
Operating system and version: Debian 10

## Expected Behavior
Unambiguous stereochemistry next to the ether in this molecule:
![image](https://github.com/openbabel/openbabel/assets/71138554/2c879175-e387-4e1d-8429-8e5a3ae1d7a2)

## Actual Behavior
As you can see, only one bond is displayed in 3D - however, this is insufficient to tell the stereochemical configuration. Either the phenyl, the chlorophenyl or the ether attachment could be behind plane. I believe the phenyl should be behind the plane. 

## Steps to Reproduce
If you have feh installed, one-liner:
`obabel -:"Clc1ccc(cc1)[C@](OCC[C@@H]2N(C)CCC2)(c3ccccc3)C" -opng | feh -`

If you don't, check the png output for this:
`obabel -:"Clc1ccc(cc1)[C@](OCC[C@@H]2N(C)CCC2)(c3ccccc3)C" -opng -O clemastine.png`

**Comment by robertwerner67** [comment]
I disagree that the depiction lacks an essential detail.

If one departs from the Newman projection / steering wheel like approach to assign *R* or *S* configuration within the CIP system (e.g. [here](https://www.organicchemistrytutor.com/topic/cip-rules-and-r-s-stereodescriptors/), the illustration indicates oxygen of the ether, carbon atom of the chiral centre and the two adjacent quaternary carbon atoms below the carbon atom of the methyl group.  The trained eye (training by building *physical* molecular models ([example](https://hgs.maruzen.info/products/1002alpha-organic-chemistry-introductory-set)), or/and with visualizing programs (e.g. [Avogadro](https://two.avogadro.cc/)) recalls that a conformation close to a tetrahedral geometry *similar* (not identical) to the one of [methane](https://en.wikipedia.org/wiki/Methane) is more likely, i.e. oxygen of ether and the two quaternary carbons next to the centre are in one level, while the carbon at the chiral centre is in one slightly above; however these four not as much close as the apex to the observer, the carbon of the methyl group:

![highlight_plane_in_common](https://github.com/openbabel/openbabel/assets/60490931/f72cf4bd-e7e8-4c3e-80fb-bd187034ea29)

ChemDraw (sample page [here](https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#)) equally reads the SMILES string `Clc1ccc(cc1)[C@](OCC[C@@H]2N(C)CCC2)(c3ccccc3)C` (structure -> load smiles) to depict the molecular structure as

![chemdraw_js](https://github.com/openbabel/openbabel/assets/60490931/540c81b6-40c5-4e84-b8be-8105a1f646da)

The presence of a bold wedge (or the dash) does not always require simultaneous presence of the other (carbon on stereogenic centre alpha to nitrogen).  Without doubt, however, it can assist the reader (example by [CDKDepict](https://www.simolecule.com/cdkdepict/depict.html)):

![cdkdepict](https://github.com/openbabel/openbabel/assets/60490931/5b3ee60d-fca8-432b-bafe-d47bbe332d93)

**Comment by Quaddroo** [comment]
It appears you are right and I've somehow completely misrepresented the stereocenter in my mind. I can't tell what I'm doing wrong, but I noticed that no matter how I draw the dashed bond, it still turns up R - which I, somehow, thought would not occur.

Sorry for the noise and thanks for the reply - I am closing this issue.
