### ISSUE TITLE
Wrong enegy values when converting Gaussian .log files to .xyz files

### ISSUE THREAD

**Issue by Astro-Aionia** [openbabel/openbabel#2636]
## Environment Information
Open Babel version: 3.1.1
Operating system and version: Ubuntu 22.04.3 (5.15.90.1-microsoft-standard-WSL2)

## Expected Behavior

After converting a Gaussian .log file to a .xyz file, the commit line should be written as input file name and Energy.  For example, I tried to convert a molclular with a calculated enegy value of -1871.263029 Hartree:

command: `obabel 1.log -ilog -oxyz -O 1.xyz`

output file content:
```
[atom number]
1.log	Energy: -1871.263029
[cartesian coordinate]
```

## Actual Behavior

The output format was right but the energy value was wrong:

```
[atom number]
1.out	Energy: -1174235.7067600
[cartesian coordinate]
```

In addition, the wrong value did not appear in the input .log file. I don't know how was it calculated out.

## Steps to Reproduce

Just use command `obabel filename.log -ilog -oxyz -O filename.xyz` to any .log file.

**Comment by ghutchis** [comment]
For comparison `cclib` generally converts to eV.
