### ISSUE TITLE
access record count by the compiled obabel executable

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2639]
**Is your feature request related to a problem? Please describe.**

The submission of a container file, i.e. a `.smi` or a `.sdf` with multiple records to prepare a stack of input files e.g.

```shell
obabel input.sdf -O run.mop -xk "pm3 charge=0 eps=4.8 cycles=200" -m
```

yields the input for the next program to use.  Openbabel reports back to the CLI in a pattern of

```shell
275 molecules converted
275 files output. The first is run1.mop
```

The pattern of the file name of the new files written however is varying within each of submission.  In the present case, for instance, there is `run1.mop`, `run3.mop` (one digit), `run36.mop` (two digits), `run123.mop` (three digits), etc. named in sequence of the entry in the original (container) file processed.

**Describe the solution you'd like**

I would like to see a name pattern which accounts for the number of records and -- where necessary -- pads the number assigned with leading zeroes.  In the present case, this would name the same files as above `run001.mop`, `run003.mop`, `run036.mop`, `run123.mop` with three digits each.  Second, it can be informative to just know the number of records the container file contains.

As an illustration of the first point, MOPAC issues a brief note to the CLI about a computation completed, for instance

```shell
MOPAC Job: "run239.mop" ended normally on Oct 27, 2023, at 13:14.
```

With the pattern scheme newly suggested, the submission of a batch of computations to MOPAC by

```shell
find *.mop | parallel -j 4 mopac {}
```

then would provide an easier to read (low level) monitor about the advance of the local computations in queue.  Though *completion* of the individual computation (by MOPAC) naturally will interfere a little bit and is outside of obabel's control, it is the pick of next job from the deck in question which follows a numeric sort.

**Describe alternatives you've considered**

So far, I renamed the files in file manager [vifm](https://vifm.info/). In the folder of question, the explicit commands are `:sort` and `e` for a sort of the files by file extension, their selection (by `V`), and rename e.g. by `:s/run/run00/` to rename files in range `run1.mop` up and including `run9.mop` as `run001.mop` ... `run009.mop`.

For the total record count, in Linux I either use a `wc -l data.smi` to count the number of lines in a list of SMILES.  Or, count keywords each record in the container file contains exactly once, e.g. `grep "V3000" ./Evolutionary_Library.sdf -c`.

**Comment by fredrikw** [comment]
An easy option in your case would be to change the last command to
```sh
find *.mop | sort -V | parallel -j 4 mopac {}
```
or
```sh
find *.mop | sort -k 1.4n | parallel -j 4 mopac {}
```
or something else using sort. Having OpenBabel adjust the name depending on the number of input molecules doesn't really work since the files are read streaming and hence the number of molecules is not known until the command is finished.

**Comment by nbehrnd** [comment]
Thank you; especially the use of `sort` with key of `1.4n` definitively was not on my radar.
