### ISSUE TITLE
openbabel.org with ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by j3mdamas** [openbabel/openbabel#2645]
Hi,

I don't know where else to do to, so I ask here. The openbabel.org page is not working, it is failing with `ERR_TOO_MANY_REDIRECTS`.

I didn't report it immediately, but it's been happening at least since last week.

Without it, there's no access to the documentation.

Thanks,
João

**Comment by nbehrnd** [comment]
It already is known (https://github.com/openbabel/openbabel/issues/2643) for about two days.

**Comment by j3mdamas** [comment]
Oh, I did not notice. Closing then as it is a duplicate
