### ISSUE TITLE
slurmstepd-falkor7: error: Step 1141810.0 exceeded memory limit (52917772 > 20971520), being killed srun: Exceeded job memory limit

### ISSUE THREAD

**Issue by ivzzognam** [openbabel/openbabel#2657]
Hello guys !!!! i'm trying to use the following script : 

#!/bin/bash
#
#SBATCH --job-name=index_human
#SBATCH --partition=all
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mail-user=ivanamango@gmail.com
#SBATCH --cpu-bind=rank
#SBATCH --mail-type=ALL
#SBATCH --hint=compute_bound

module load STAR/2.6.0c

srun /opt/STAR/bin/STAR --runMode genomeGenerate --runThreadN 10 --genomeDir Genomes_STAR --genomeFastaFiles Genomi/Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile GTF_files/Homo_sapiens.GRCh38.96.gtf --limitGenomeGenerateRAM 152003700778$

when i run it this is the error : 
Dec 13 08:56:22 ..... started STAR run
Dec 13 08:56:22 ... starting to generate Genome files
Dec 13 08:57:27 ... starting to sort Suffix Array. This may take a long time...
Dec 13 08:57:45 ... sorting Suffix Array chunks and saving them to disk...
slurmstepd-falkor7: error: Step 1141810.0 exceeded memory limit (52917772 > 20971520), being killed
srun: Exceeded job memory limit
slurmstepd-falkor7: error: *** STEP 1141810.0 ON falkor7 CANCELLED AT 2023-12-13T08:58:22 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: falkor7: task 0: Killed

How can i resolve it ? 

Thanks to everyone !!!!

**Comment by fredrikw** [comment]
I think you have reported this on the wrong project...

**Comment by nbehrnd** [comment]
@ivzzognam Because there is no line with an `obabel` instruction, is it related to obabel?  And if you want to report log from the shell in a GitHub issue, it is better to enclose it in a block starting / closing by a line of three back ticks as code block (see for example the 101 about markdown on [learnxinyminutes](https://learnxinyminutes.com/docs/markdown/)) to yield something in line of 

```shell
$ obabel -:"c1ccncc1" -h --gen3d -oxyz
11

C          1.43303        0.05159        0.00100
C          0.68800        1.22595        0.00151
C         -0.69424        1.12564        0.00218
N         -1.36237       -0.04853        0.00552
C         -0.61197       -1.17189        0.00692
C          0.77379       -1.17331        0.00332
H          2.51852        0.09036       -0.00113
H          1.17153        2.19630        0.00127
H         -1.31976        2.01344        0.00006
H         -1.17257       -2.10232        0.01145
H          1.32543       -2.10632        0.00270
1 molecule converted
```

**Comment by ivzzognam** [comment]
> Hello guys !!!! i'm trying to use the following script :
> 
> #!/bin/bash
> 
> #SBATCH --job-name=index_human #SBATCH --partition=all #SBATCH --ntasks=1 #SBATCH --cpus-per-task=10 #SBATCH --mail-user=[ivanamango@gmail.com](mailto:ivanamango@gmail.com) #SBATCH --cpu-bind=rank #SBATCH --mail-type=ALL #SBATCH --hint=compute_bound
> 
> module load STAR/2.6.0c
> 
> srun /opt/STAR/bin/STAR --runMode genomeGenerate --runThreadN 10 --genomeDir Genomes_STAR --genomeFastaFiles Genomi/Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile GTF_files/Homo_sapiens.GRCh38.96.gtf --limitGenomeGenerateRAM 152003700778$
> 
> when i run it this is the error : Dec 13 08:56:22 ..... started STAR run Dec 13 08:56:22 ... starting to generate Genome files Dec 13 08:57:27 ... starting to sort Suffix Array. This may take a long time... Dec 13 08:57:45 ... sorting Suffix Array chunks and saving them to disk... slurmstepd-falkor7: error: Step 1141810.0 exceeded memory limit (52917772 > 20971520), being killed srun: Exceeded job memory limit slurmstepd-falkor7: error: *** STEP 1141810.0 ON falkor7 CANCELLED AT 2023-12-13T08:58:22 *** srun: Job step aborted: Waiting up to 32 seconds for job step to finish. srun: error: falkor7: task 0: Killed
> 
> How can i resolve it ?
> 
> Thanks to everyone !!!!
