### ISSUE TITLE
regression tests fail on non-x86 architectures

### ISSUE THREAD

**Issue by rathann** [openbabel/openbabel#266]
This happens reproducibly at least on: armv7hl, aarch64, ppc64, ppc64le.

```
97% tests passed, 4 tests failed out of 157
Total Test time (real) = 4300.78 sec
The following tests FAILED:
     62 - test_regressions_1 (OTHER_FAULT)
     63 - test_regressions_221 (OTHER_FAULT)
    147 - inchiSteffen_PubChem.smi_Test (Timeout)
    149 - pytest_sym (Timeout)
Errors while running CTest
Makefile:130: recipe for target 'test' failed
```

The relevant log snippets are:

```
       Start  62: test_regressions_1
 62/157 Test  #62: test_regressions_1 ...............***Exception: Other601.71 sec
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
        Start  63: test_regressions_221
 63/157 Test  #63: test_regressions_221 .............***Exception: Other587.19 sec
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

```
147/157 Test #147: inchiSteffen_PubChem.smi_Test ....***Timeout 1500.01 sec
==============================
*** Open Babel Warning  in InChI code
  #8 :Salt was disconnected;
==============================
*** Open Babel Warning  in InChI code
  #30 :Salt was disconnected;
```

```
149/157 Test #149: pytest_sym .......................***Timeout 1500.01 sec
```

git commit used: 3a63a9849f8d9719c5989c43875d51be50c53019
environment: Fedora development branch (rawhide)

**Comment by ghutchis** [comment]
Can you try this with cmake -DOPTIMIZE_NATIVE=OFF

**Comment by ghutchis** [comment]
I'm wondering if the default should be OFF.

**Comment by baoilleach** [comment]
Please don't. There is a large speed boost with native popcount. It is intended that distros specify the off option.

**Comment by ghutchis** [comment]
@rathann I'm wondering if the -march=native call is the cause of your failures. (I'm guessing that some of the tests are done with cross-compilation.)

**Comment by baoilleach** [comment]
I should point out that even on Intel chips this will cause problems if off is not used by distros. E.g. compiled on machine with sse3 but run on machine without.

**Comment by rathann** [comment]
I do have -DOPTIMIZE_NATIVE=OFF.

**Comment by rathann** [comment]
Versions of dependencies used:
```
cmake-3.5.0-0.3.rc3.fc25
eigen3-devel-3.2.8-1.fc24
gcc-c++-6.0.0-0.15.fc25
inchi-devel-1.0.4-10.fc24
libxml2-devel-2.9.3-3.fc24
swig-3.0.8-5.fc25
wxGTK-devel-2.8.12-23.fc24
ImageMagick-6.9.3.0-2.fc24
perl-devel-5.22.1-358.fc25
python-devel-2.7.11-4.fc24
python3-devel-3.5.1-7.fc25
ruby-devel-2.3.0-54.fc24
```

**Comment by ghutchis** [comment]
Are there places I can access to debug this? AFAIK, Travis is only x86, so I don't have access to other arch personally.

**Comment by rathann** [comment]
@ghutchis : Red Hat provides interested developers with access to ppc64(le) VMs running Fedora: https://fit-rhlab.rhcloud.com/powerlinux-openpower-development-hosting/ . Just fill in the Request Form linked there. I've been using a couple of their VMs (ppc64 and ppc64le) for building and debugging my Fedora packages for quite some time now.

**Comment by rathann** [comment]
Still reproducible with 2.4.1.

**Comment by baoilleach** [comment]
I've requested time on the machines.

**Comment by baoilleach** [comment]
No response from RedHat.
