### ISSUE TITLE
Parsing error issue with obabel generated pdbqt files in vina 

### ISSUE THREAD

**Issue by AlexisGGk** [openbabel/openbabel#2665]
Ive been converting pdb structures for use in autodock vina using obabel. 

I get this error in autodock vina 
Parse error on line 2444 in file "receptor_4.pdbqt": Unknown or inappropriate tag

when I check this line it says ROOT. Out of curiosity I tried just deleting that line and it immediately flags up the following lines instead. The format of the file appears correct and when I used obabel to convert small molecules from the smiles the system has no issue with it

this is the 
line I used for the conversion 
obabel receptor_3.pdb -O receptor_4.pdbqt -h -gen3D 

I have tried lots of variations and using different structures etc. but always the same issue. Ive also tried using the online version of obabel and when I select add hydrogens and generate 3D co ordinates it simply gives a blank output. When I don't include this it works but because there aren't 3D co ordinates it can't be used 

attached here is the output. I am sure it's some silly mistake but I can't see it 

[receptor_5.txt](https://github.com/openbabel/openbabel/files/13950454/receptor_5.txt)

**Comment by dkoes** [comment]
When making a pdbqt for vina, the receptor needs to be rigid so you have to pass `-xr`
Or you can use smina/gnina and it will do all this for you.

**Comment by nbehrnd** [comment]
To check if an error occurs during obabel's format conversion and because you
state "attached is the output" prior to the file shared, can you equally share
the input .pdb file?  The addition of a `.txt` to upload the model as
`receptor_3.pdb.txt` (to keep the name you used when using openbabel), should
satisfy GitHub's requirements of an attachment.

Probably an accidental omission, the generation of a conformer requires two
leading dashes, `--gen3d`.

**Comment by AlexisGGk** [comment]
Oh wow thank you that finally worked! @dkoes (adding -xr that is) 

Now though the results from 
out="results.pdb" 
[receptor_3.pdb.txt](https://github.com/openbabel/openbabel/files/13951487/receptor_3.pdb.txt)

are only displaying the ligand not the ligand + protein? Not sure if the issue here is with open babel though or vina 
[results.pdb.txt](https://github.com/openbabel/openbabel/files/13951499/results.pdb.txt)

Attached here is the original pdb before conversion (receptor_3.pdb.txt) and the resulting structure (results.pdb.txt)

**Comment by dkoes** [comment]
I think you are running into vina issues, not openbabel.

**Comment by geeta-acog** [comment]
I am getting the following error when I use obabel converted pdbqt file of ligand for docking

`Structure parsing error: Unknown or inappropriate tag found in flex residue or ligand.
 > ROOT
`

Here is the data in the ligand pdbqt 
`REMARK  Name = hinge_enamine96
REMARK  5 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_3  and  O_4
REMARK    2  A    between atoms: O_4  and  C_5
REMARK    3  A    between atoms: C_5  and  C_6
REMARK    4  A    between atoms: C_8  and  O_9
REMARK    5  A    between atoms: C_16  and  N_17
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ROOT
ATOM      1 CL   UNL A   1       0.683   0.000   0.000  0.00  0.00    -0.145 Cl
ATOM      2  H   UNL A   1      -0.683   0.000   0.000  0.00  0.00    +0.145 HD
ENDROOT
TORSDOF 0
REMARK  Name = hinge_enamine96
REMARK  5 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_3  and  O_4
REMARK    2  A    between atoms: O_4  and  C_5
REMARK    3  A    between atoms: C_5  and  C_6
REMARK    4  A    between atoms: C_8  and  O_9
REMARK    5  A    between atoms: C_16  and  N_17
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ROOT
ATOM      1 CL   UNL A   2       0.688   0.000   0.000  0.00  0.00    -0.145 Cl
ATOM      2  H   UNL A   2      -0.688   0.000   0.000  0.00  0.00    +0.145 HD
ENDROOT
TORSDOF 0
REMARK  Name = hinge_enamine96
REMARK  5 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_3  and  O_4
REMARK    2  A    between atoms: O_4  and  C_5
REMARK    3  A    between atoms: C_5  and  C_6
REMARK    4  A    between atoms: C_8  and  O_9
REMARK    5  A    between atoms: C_16  and  N_17
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ROOT
ATOM      1  C   UNL A   3       2.172  -0.363  -0.184  0.00  0.00    +0.075 A 
ATOM      2  C   UNL A   3       2.289  -1.747  -0.253  0.00  0.00    +0.092 A 
ATOM      3  C   UNL A   3       1.174  -2.560  -0.236  0.00  0.00    +0.217 A 
ATOM      4  N   UNL A   3      -0.021  -1.952  -0.150  0.00  0.00    -0.179 NA
ATOM      5  C   UNL A   3      -0.184  -0.620  -0.082  0.00  0.00    +0.221 A 
ATOM      6  N   UNL A   3       0.944   0.136  -0.101  0.00  0.00    -0.217 NA
ATOM      7  N   UNL A   3      -1.459   0.001   0.009  0.00  0.00    -0.298 N 
ATOM      8  C   UNL A   3      -1.698   1.419   0.085  0.00  0.00    +0.109 C 
ATOM      9  C   UNL A   3      -3.190   1.591  -0.051  0.00  0.00    +0.039 C 
ATOM     10  C   UNL A   3      -3.813   0.230   0.152  0.00  0.00    +0.070 C 
ATOM     11  C   UNL A   3      -2.696  -0.745   0.035  0.00  0.00    +0.126 C 
ENDROOT
BRANCH  10  12
ATOM     12  N   UNL A   3      -4.424   0.090   1.459  0.00  0.00    -0.326 NA
ATOM     13  H   UNL A   3      -5.372  -0.350   1.398  0.00  0.00    +0.118 HD
ATOM     14  H   UNL A   3      -4.589   1.038   1.884  0.00  0.00    +0.118 HD
ENDBRANCH  10  12
BRANCH   3  15
ATOM     15  O   UNL A   3       1.319  -3.940  -0.307  0.00  0.00    -0.492 OA
ATOM     16  H   UNL A   3       0.881  -4.551   0.392  0.00  0.00    +0.294 HD
ENDBRANCH   3  15
BRANCH   1  17
ATOM     17  C   UNL A   3       3.409   0.460  -0.206  0.00  0.00    +0.214 C 
BRANCH  17  19
ATOM     18  C   UNL A   3       4.865   1.538  -1.616  0.00  0.00    +0.194 C 
ATOM     19  O   UNL A   3       3.713   0.766  -1.540  0.00  0.00    -0.377 OA
ENDBRANCH  17  19
ENDBRANCH   1  17
TORSDOF 4
`

Why am i getting this error and how to resolve it?

**Comment by fredrikw** [comment]
The answer seems to be five comments above yours (with an additional confirmation three comments above)!

**Comment by geeta-acog** [comment]
@AlexisGGk That was one of the molecules obtained from enamine library


@rwxayheee Thank you. Yes for all the compounds having salts, this error was shown

**Comment by Haleymouse** [comment]
> When making a pdbqt for vina, the receptor needs to be rigid so you have to pass `-xr` Or you can use smina/gnina and it will do all this for you.

Thanks, it works for me!
