### ISSUE TITLE
Creating a reduced version of openbabel for Python 3.11

### ISSUE THREAD

**Issue by sdr0598** [openbabel/openbabel#2672]
Hi all,
I have an application that runs on python 3.11 and it requires the conversion of a pdb file to a smiles code. OpenBabel has this feature but I cannot install it on python 3.11. Currently, I have installed OpenBabel on python 3.7 and I am trying to migrate the functions for reading PDB files and outputing smiles code to python 3.11. However, I am having difficulties with this approach because I am not able to identify what are the minimum files needed for this task.
So far, I've tried moving the following files: __init__, _openbabel.pyd, openbabel.py, pybel.py to my python 3.11 env in anaconda (Destination folder was: ./Lib/site-packages/openbabel). 
However, I am having the following error when importing openbabel:
`from . import _openbabel`
`ImportError: DLL load failed while importing _openbabel: The specified module could not be found`
I am not sure what other files to include. My goal is to clean up the .py files so as to include only the read pdb files and output smiles code functionalities.
Does anyone have any tips/suggestions on how I could approach this?
Also, I would like to keep downgrading the python version of my application as a last resort if nothing else works.

**Comment by ghutchis** [comment]
Open Babel is a binary package for Python because it's a C++ library. Make sure to install `openbabel` for your Python 3.11 install (e.g. through `conda-forge`)

**Comment by sdr0598** [comment]
I was having trouble install openbabel in my python 3.11 in myconda env using conda-forge. This issue was fixed by updating my conda.
