### ISSUE TITLE
Failed to compiling the python bindings.

### ISSUE THREAD

**Issue by hongyi-zhao** [openbabel/openbabel#2673]
I tried to compile the Python bindings according to [the guidance](https://open-babel.readthedocs.io/en/latest/Installation/install.html#compile-language-bindings). The compilation was completed, but no Python binding was generated:

```shell
sudo apt -y build-dep openbabel
git clone https://github.com/openbabel/openbabel.git openbabel.git && cd openbabel.git
mkdir build && cd $_
cmake .. -DBUILD_GUI=ON -DPYTHON_BINDINGS=ON
make -j 44
sudo make install
export PYTHONPATH=/usr/local/lib:$PYTHONPATH
```
Then I checked as follows:

```shell
werner@X10DAi:~$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbabel import openbabel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'openbabel' from 'openbabel' (unknown location)
>>> 

werner@X10DAi:~$ sudo find /usr/local -name "pybel*"
werner@X10DAi:~$ 
```
How to fix this problem?

Regards,
Zhao

**Comment by SharanRP** [comment]
Your issue is that after installing Open Babel and building the Python bindings, you’re unable to import the Openbabel module in Python. This could be due to ,The Open Babel Python bindings might not be in your Python path. You can add the Open Babel Python bindings to your Python path by adding the following line to your .bashrc or .bash_profile file (replace /path/to/openbabel/bindings with the actual path to the Open Babel Python bindings):
```
export PYTHONPATH=$PYTHONPATH:/path/to/openbabel/bindings
```
Then, source your .bashrc or .bash_profile file to apply the changes:
```
source ~/.bashrc
```
or
```
source ~/.bash_profile
```

correct me if I am wrong @ghutchis

**Comment by hongyi-zhao** [comment]
I don't know where the binding is.

**Comment by e-kwsm** [comment]
`make install` shows the destination, and I guess it is `/usr/local/lib/python3.10/site-packages`.

**Comment by hongyi-zhao** [comment]
See below in my case:
```shell
werner@X10DAi:~$ ls /usr/local/lib/python3.10/site-packages
ls: cannot access '/usr/local/lib/python3.10/site-packages': No such file or directory
```

**Comment by SharanRP** [comment]
while cmake ``` cmake ../openbabel-2.4.0 -DCMAKE_INSTALL_PREFIX : specify the installation prefix (default /usr/local)``` set this to your desired location

**Comment by hongyi-zhao** [comment]
I got it. I must generate the bindings first by `-DRUN_SWIG=ON`. The following does the trick:

```shell
werner@X10DAi:~/Public/repo/github.com/openbabel$ cmake .. -DCMAKE_INSTALL_PREFIX=~/Public/repo/github.com/openbabel/aaa -DBUILD_GUI=ON -DPYTHON_BINDINGS=ON -DRUN_SWIG=ON
werner@X10DAi:~/Public/repo/github.com/openbabel$ make -j44
werner@X10DAi:~/Public/repo/github.com/openbabel$ make install
werner@X10DAi:~/Public/repo/github.com/openbabel$ ls aaa/lib/python3.10/site-packages/openbabel/
__init__.py  openbabel.py  _openbabel.so  pybel.py
```

**Comment by hongyi-zhao** [comment]
But I still wonder why the following is enough:

`$ export PYTHONPATH=/usr/local/lib:$PYTHONPATH`

I mean, why shouldn't I use the following line to set the `PYTHONPATH`:

`$ export PYTHONPATH=/usr/local/lib/pythonX.Y/dist-packages:$PYTHONPATH`
