### ISSUE TITLE
ABI incompatibility can be introduced by obsharedptr

### ISSUE THREAD

**Issue by ktns** [openbabel/openbabel#268]
Hi.

Currently, ```openbabel/shared_ptr.h``` chooses
which implementation of a shared pointer should be used at compile time
and the header file is installed as is in the source tree.

Isn't it dangerous because different implementations can be chosen
at compile time of the library and of users' code?

I think it is better to hardcode a chosen implementation
at configure time into ```babelconfig.h```.

**Comment by ghutchis** [comment]
I think it's fairly unlikely to choose different implementations, but your point is valid. If you want to submit a patch that builds it into babelconfig.h and makes shared_ptr.h into a no-op (i.e., retaining header compatibility), that sounds like a pragmatic approach.
