### ISSUE TITLE
Openbabel not found in Jupyter Notebook

### ISSUE THREAD

**Issue by jennijones** [openbabel/openbabel#2683]
I have installed openbabel but when running the line `from openbabel import openbabel as ob` in a Jupyter notebook, the module is not found: `ModuleNotFoundError: No module named 'openbabel'`. 

The steps I followed for installation were:
1. Downloaded Source code (tar.gz) from [here](https://github.com/openbabel/openbabel/releases)
2. Followed the steps listed for Basic build procedure [here](https://open-babel.readthedocs.io/en/latest/Installation/install.html)
3. `pip install openbabel` which gave me a success message: `Successfully installed openbabel-3.1.1.1`

From my understanding, the pip install step should have given me the Python bindings required to use this module in Jupyter. Am I missing anything, or what could be the issue?

**Comment by nbehrnd** [comment]
Point 3) might be similar to problems installing openbabel in a virtual environment to run (Python) scripts from the plain CLI.  Either try

a) uninstall openbabel by `pip uninstall openbabel`.  Then install openbabel-wheel[1] by `pip install openbabel-wheel` instead.  This bypass usually fixes some of the problems, and works fine at least in Windows, and Linux.  The only edit necessary would be to update the `requirements.txt` file if you amend your virtual environment this way, but not the the Python scripts itself.

b) use `python3-openbabel` as packaged for your favorite Linux distribution (example [Debian](https://tracker.debian.org/pkg/openbabel)), Windows + WSL environment

c) try a different ecosystem around your Python interpreter, for instance [Miniconda](https://anaconda.org/conda-forge/openbabel).  It isn't necessary to give up standard [CPython](https://www.python.org/) for good -- there usually is no problem to have multiple interpreters on one computer.  But it might require some adjustments on the side of the Jupyter notebook to engage the one you want to use.


[1] https://pypi.org/project/openbabel-wheel/

**Comment by jennijones** [comment]
> Point 3) might be similar to problems installing openbabel in a virtual environment to run (Python) scripts from the plain CLI. Either try
> 
> a) uninstall openbabel by `pip uninstall openbabel`. Then install openbabel-wheel[1] by `pip install openbabel-wheel` instead. This bypass usually fixes some of the problems, and works fine at least in Windows, and Linux. The only edit necessary would be to update the `requirements.txt` file if you amend your virtual environment this way, but not the the Python scripts itself.
> 
> b) use `python3-openbabel` as packaged for your favorite Linux distribution (example [Debian](https://tracker.debian.org/pkg/openbabel)), Windows + WSL environment
> 
> c) try a different ecosystem around your Python interpreter, for instance [Miniconda](https://anaconda.org/conda-forge/openbabel). It isn't necessary to give up standard [CPython](https://www.python.org/) for good -- there usually is no problem to have multiple interpreters on one computer. But it might require some adjustments on the side of the Jupyter notebook to engage the one you want to use.
> 
> [1] https://pypi.org/project/openbabel-wheel/

Hi thank you for your suggestions! I did try the first one but unfortunately still had the same issue. I am using MacOS so don't think I can try the second one. 

But I figured out the issue is something to do with me having several versions of Python installed in my base environment and I couldn't figure out which one Jupyter notebook is using, so I have fixed the issue by creating a new conda environment and installed openbabel via conda in there, and running the notebook from that environment.
