### ISSUE TITLE
Fail to read molecule.pdb while covalent docking

### ISSUE THREAD

**Issue by Brett628** [openbabel/openbabel#2714]
## Environment Information
Open Babel version: 3.1.0
Operating system and version: Win11, Python 3.12.4, Autodock4

## Expected Behavior
I am trying to do Covalent Docking with Autodock4, I downloaded the script from the Scripps site and I'm testing the program with the examples provided by them. The output should be a file containing the protein with the covalent ligand docked.

## Actual Behavior
After initial difficulties in installing Openbabel and PythonBindings, the first errors appeared to be in the syntax of the files prepareCovalent.py, CopyMol.py and ResidueProfiler.py. After editing them I managed to make the script working (corrected files attached), but this messages appeared:

first:

> C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent> python prepareCovalent.py --ligand ligand1.mol2 --ligindices 24,25 --receptor 3upo_protein.pdb --residue B:SER222 --outputfile ligcovalent.pdb
> 
> --- Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
>   Unable to open data file 'space-groups.txt'
> 
> --- Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
>   Cannot initialize database 'space-groups.txt' which may cause further errors.
> Processing residue B:SER222
> [start] output filename is: ligcovalent.pdb
> Traceback (most recent call last):
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1319, in <module>
>     x = CovalentDockingMaster()
>         ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 871, in __init__
>     self.start()
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1262, in start
>     self.processResidues()
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1298, in processResidues
>     aligner = self.x = CovalentDockingMaker(**self.alignerArgs)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 230, in __init__
>     self.initResidue()
>     ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 273, in initResidue
>     self.residueProfile()
>   File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 288, in residueProfile
>     self.resType = self.receptorProfiler.residues[self.resName]
>                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
> KeyError: 'B:SER222'

Second message, after restarting the PC:

> C:\Users\brett>python C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py --ligand ligand1.mol2 --ligindices 24,25 --receptor 3upo_protein.cif --residue B:SER222 --outputfile ligcovalent.pdb
> 
> *** Open Babel Error  in OpenBabel::OBConversion::ReadFile
>   Cannot read from 3upo_protein.cif
> [ ERROR ] Fail to read molecule "3upo_protein.cif"
> 
> C:\Users\brett>python C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py --ligand ligand1.mol2 --ligindices 24,25 --receptor 3upo_protein.pdb --residue B:SER222 --outputfile ligcovalent.pdb
> 
> *** Open Babel Error  in OpenBabel::OBConversion::ReadFile
>   Cannot read from 3upo_protein.pdb
> [ ERROR ] Fail to read molecule "3upo_protein.pdb"

I tried to look online, but so far it was unsuccesful. I'm new to Python

Files:
[CopyMol.txt](https://github.com/user-attachments/files/16488935/CopyMol.txt)
[prepareCovalent.txt](https://github.com/user-attachments/files/16488936/prepareCovalent.txt)
[ResidueProfiler.txt](https://github.com/user-attachments/files/16488937/ResidueProfiler.txt)

**Comment by rwxayheee** [comment]
Hi @Brett628 
Are these files in the same folder where you execute the script? This looks like a file not found problem. 
You don't need to convert python2 to python3 manually. `$MGLROOT/bin/pythonsh` is a python2 interpreter with the required packages. Feel free to [contact us](https://autodocksuite.scripps.edu/support/) if you have any further questions ^^

**Comment by Brett628** [comment]
Yes, the files are present in the same folder of the scripts.
I have already Python3 installed, I don't know how to proceed

Il lun 5 ago 2024, 00:05 Amy He ***@***.***> ha scritto:

**Comment by rwxayheee** [comment]
Hi, 
Does it help if you use the full path of the files?

**Comment by nbehrnd** [comment]
@rwxayheee As a side note about

> You will need the $MGLROOT/bin/pythonsh python2 interpreter [...] won't have to manually edit the scripts for python2 to 3 conversion

[2to3](https://docs.python.org/3/library/2to3.html) *still* is in Python's standard library  with a scheduled removal for Python 3.13 (its release candidate 1 was published on August 1st, 2024).  While it might not fix every line in the source code during a transition of Python2 to Python3 (e.g., numpy later changed the syntax of arrays of floating numbers), could it equally assist you for a consistent modernization of the scripts you refer to?

**Comment by Brett628** [comment]
> Hi, Does it help if you use the full path of the files (just like how you call the scripts)? You will need the $MGLROOT/bin/pythonsh python2 interpreter in the following steps. If you use this in the first step, you won't have to manually edit the scripts for python2 to 3 conversion

Hello, yes i tried and this error appears:
```
C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent>python C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py --ligand C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\l
igand1.mol2 --ligindices 24,25 --receptor C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\3upo
_protein.pdb --residue B:SER222 --outputfile C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\l
igcovalent.pdb
==============================
*** Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Unable to open data file 'space-groups.txt'
==============================
*** Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot initialize database 'space-groups.txt' which may cause further errors.
Processing residue B:SER222
[start] output filename is: C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\ligcovalent.pdb
WARNING! Residue [B:SER222] was not recognized
SMILES[ [NH][C@H]([C]=O)C[O]    C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\3upo_protein.pdb [COPY]
 ]
Guess was [ser], Pattern |[$([NX3H2,NX4H3+]),$([NX3H](C)(C))][CX4H]([CH2X4][OX2H])[CX3](=[OX1])|
Traceback (most recent call last):
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1319, in <module>
    x = CovalentDockingMaster()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 871, in __init__
    self.start()
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1262, in start
    self.processResidues()
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 1298, in processResidues
    aligner = self.x = CovalentDockingMaker(**self.alignerArgs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 230, in __init__
    self.initResidue()
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 273, in initResidue
    self.residueProfile()
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 298, in residueProfile
    self.setResidueParms()
  File "C:\Users\brett\Desktop\adCovalentDockResidue\adcovalent\prepareCovalent.py", line 325, in setResidueParms
    resInfo = self._residueParms[self.resType]
              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

To make it simple, should I install Python2.7 and try to run the script with that Python version?

**Comment by rwxayheee** [comment]
Hi @Brett628 
If you want to follow the given procedure in this tutorial, please download the required `pythonsh` interpreter for the subsequent steps: 
https://ccsb.scripps.edu/mgltools/downloads/

Reasons we strongly recommend this `pythonsh`: 
(1) it's a ready-to-use python2.7. You do not have to install it by yourself (or replace your base Python3 with an older Python, which will cause many further inconvinience)
(2) it has a specific set of packages, including a specific version of Obabel and some other packages developed by the same authors. No installation of additional packages needed 

I'm not 100% sure if this works on Win11. But I have tested it on Linux, so I'm more confident that the same workflow works in WSL ^^

**Comment by rwxayheee** [comment]
Hi @nbehrnd 
Thanks so much for your kind reply. We have [a newer method for covalent docking](https://github.com/forlilab/Meeko/?tab=readme-ov-file#reactive-docking), supported by a set of new tools (and python3 packages). 

The inquired covalent docking is a relatively old method. But it should still work with the designated python2.7 interpreter, which is complemented by a set of Python2 packages, including a specific (older) version of obabel. 

The reported issues might be caused by a version change or by the fact that the Win11 platform wasn't tested when the tutorial was written.. We appreciate the report and all of your kind support. @Brett628 If you have any further questions, please do not hesitate to reach out.

**Comment by Brett628** [comment]
Thank so much for your patience and elucidations. I was not aware about the new method.
I'm going to try it, if I will have problems I will open a new issue :)
