### ISSUE TITLE
Is retaining an empty bond block in the sdf file necessary?

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2725]
This question branches off from a discussion on the GitHub page about InChI about structure models about single atoms like He, or C without provision of explicit hydrogen atoms about methane, see [here](https://github.com/IUPAC-InChI/InChI/issues/52).  It can be paraphrased as: if there is no other (second) explicit atom in the file, is it a requirement to define a bond block even if eventually empty, i.e.

```
M  V30 BEGIN BOND
M  V30 END BOND
```

1) One observation is on .sdf (v3000) written by openbabel -- though these can not be processed by the InChI reference executable (version 1.07.1, 64bit, Linux variant), openbabel itself is capable to assign an InChI.  For instance

```shell
$ obabel -:"[He]" -O obabel_Helium.sdf -x3
==============================
*** Open Babel Warning  in WriteMolecule
  No 2D or 3D coordinates exist. Stereochemical information will be stored using an Open Babel extension. To generate 2D or 3D coordinates instead use --gen2D or --gen3D.
1 molecule converted
$ cat obabel_Helium.sdf

 OpenBabel09192411482D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 1 0 0 0 0
M  V30 BEGIN ATOM
M  V30 1 He 0 0 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
$ 
$ ./inchi-1 ./obabel_Helium.sdf
InChI version 1, Software v. 1.07 (inchi-1 executable) 
Linux 64-bit Build (gcc 11.4.0) of Aug 10 2024 18:58:34

Opened log file './obabel_Helium.sdf.log'
Opened input file './obabel_Helium.sdf'
Opened output file './obabel_Helium.sdf.txt'
Opened problem file './obabel_Helium.sdf.prb'
The command line used:
"./inchi-1 ./obabel_Helium.sdf"
Generating standard InChI
Input format: MOLfile
Output format: Plain text
Full Aux. info
Timeout per structure: 60000 msec
Up to 1024 atoms per structure


Error 71 (no InChI; Error: No V3000 CTAB end marker) inp structure #1.
End of file detected after structure #1.   
Finished processing 1 structure: 1 error, processing time 0:00:00.00
$ cat obabel_Helium.sdf.txt 
* Input_File: "./obabel_Helium.sdf"
$ 
$ obabel obabel_Helium.sdf -oinchi
InChI=1S/He
1 molecule converted
$ 
```

2) On the other hand, [Marvin](https://marvinjs-demo.chemaxon.com/latest/) describes the same structure without the empty atom block:

```

  Mrv2311 09192409232D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 1 0 0 0 0
M  V30 BEGIN ATOM
M  V30 1 He -0.875 1.6667 0 0
M  V30 END ATOM
M  V30 END CTAB
M  END
```

Both InChI trust's reference executable, as well as OpenBabel can process and assign an InChI on this dataset:

```shell
$ ./inchi-1 ./marvinjs_He_v3000.mol
InChI version 1, Software v. 1.07 (inchi-1 executable) 
Linux 64-bit Build (gcc 11.4.0) of Aug 10 2024 18:58:34

Opened log file './marvinjs_He_v3000.mol.log'
Opened input file './marvinjs_He_v3000.mol'
Opened output file './marvinjs_He_v3000.mol.txt'
Opened problem file './marvinjs_He_v3000.mol.prb'
The command line used:
"./inchi-1 ./marvinjs_He_v3000.mol"
Generating standard InChI
Input format: MOLfile
Output format: Plain text
Full Aux. info
Timeout per structure: 60000 msec
Up to 1024 atoms per structure


End of file detected after structure #1.   
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
$ cat ./marvinjs_He_v3000.mol.txt 
* Input_File: "./marvinjs_He_v3000.mol"
Structure: 1
InChI=1S/He
AuxInfo=1/0/N:1/rA:1nHe/rB:/rC:.25,2.375,0;
$ 
$ obabel ./marvinjs_He_v3000.mol -oinchi
InChI=1S/He
1 molecule converted
```

The observations are collected with InChI version 1.07.1 published by August 21 ([source](https://github.com/IUPAC-InChI/InChI/releases)), and OpenBabel version 3.1.1/Sep 4 2024 as provided by Linux Debian 13/trixie.

**Comment by emadellaloggia** [comment]
install this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by nbehrnd** [comment]
@emadellaloggia I have no prior knowledge about the purpose of this archive, nor its content.  Thus I won't download, let alone unzip it.

**Comment by nbehrnd** [comment]
The same thread ([link](https://github.com/IUPAC-InChI/InChI/issues/52)) described OpenBabel's internal representation of molecules responsible to process molecules with either a) lacking explicit bound block, or b) an explicit bond block without an entry equally well.  It is convincing that this agnostic approach is better, than one opting for either one of the two patterns.
