### ISSUE TITLE
Invalid SMARTS pattern

### ISSUE THREAD

**Issue by Plancalkuele** [openbabel/openbabel#274]
Hi there,
I'm quite confused that I'm getting an error for the following SMART:
[CH2=CH]

OpenBabel complains about the equal sign which should actually define a double bond and is also documented like that in the SMARTS documentation (http://www.daylight.com/dayhtml/doc/theory/theory.smarts.html):
```
*** Open Babel Error  in SMARTSError
  SMARTS Error:
[CH2=CH]
    ^
```

So I tried the SMARTS Editor (http://www.biosolveit.de/SMARTStools/index.html) out because I was not sure about defining the molecular structure correctly and the editor gives me the following SMARTS for a CH2=CH group:
C([H])([H])=C[H]

But OpenBabel also complains about the parenthesis sign:

```
*** Open Babel Error  in SMARTSError
  SMARTS Error:
[C([H])([H])=C[H]]
  ^
```

What am I doing wrong?

**Comment by fredrikw** [comment]
If you indeed wrote the SMART as [CH2=CH] and [C([H])([H])=C[H]], that is that you used brackets around the full pattern, that is the problem. The brackets specify an atom so neither = nor ( should be in there. Just remove the brackets and you should be fine.

**Comment by Plancalkuele** [comment]
It worked! Thank you very much!
But statements like CH3 have to put in brackets, right? Because without brackets it doesn't work.
So I guess the rule is as following:
SMARTS which have no specific bond given in the statement are put in brackets. When defining explicitly the bonding between atoms in SMARTS then you neglect brackets around the SMARTS statement, examples:
CH3         ->	[CH3]
CH2         ->	[CH2]
CH           ->	[CH]
C              ->	[C]
CH2=CH  ->	C([H])([H])=C[H]
CH=CH    ->	C(=C[H])[H]

**Comment by cowsandmilk** [comment]
>  SMARTS which have no specific bond given in the statement are put in brackets. When defining explicitly the bonding between atoms in SMARTS then you neglect brackets around the SMARTS statement

CCC has no specific bonds, but has no brackets

[Cl]-[#6] has explicitly defined the bonding, but has brackets.

Brackets specify an atom, you may look at [CH2] and say that is three atoms, but I will quote from the smarts documentation:

> Note that atomic primitive H can have two meanings, implying a property or the element itself. [H] means hydrogen atom. [*H2] means any atom with exactly two hydrogens attached

So, [CH2] is expressing a carbon atom with the property of having two hydrogens attached, it is not specifying a carbon, a hydrogen, and a hydrogen. That would be C([H])([H]), which I feel I should also mention would match a carbon with 3 hydrogens attached, while [CH2] does not.

In your particular case, you've also specified the carbon should have a double bond to another carbon, so unless you have a [Texas Carbon](http://www.urbandictionary.com/define.php?term=Texas%20Carbon) floating around, your carbon with 2 hydrogens and a double bond is fully specified and won't also match a carbon with 3 hydrogens.

**Comment by Plancalkuele** [comment]
Haha...nice! Never heard about the term Texas Carbon. ;) Thanks for clearing things up for me!

**Comment by Plancalkuele** [comment]
Haha...nice! Never heard about the term Texas Carbon. ;) Thanks for clearing things up for me!
I guess this issue can be marked as question and closed now if nobody has any other questions about writing SMARTS correctly.
