### ISSUE TITLE
unclear origin of timestamp by `obabel --version`

### ISSUE THREAD

**Issue by nbehrnd** [openbabel/openbabel#2759]
## Environment Information
Open Babel version: 3.1.1
Operating system and version: Windows 10, 64bit

## Expected Behavior
Using the openbabel installer for Windows, running `obabel --version` should provide both version `3.1.1` as well as a time stamp close or identical to the ones of the [releases page](https://github.com/openbabel/openbabel/releases), i.e. May 17, 2020.

## Actual Behavior
The time stamp reads `Open Babel 3.1.1 -- Oct 15 2024 -- 18:31:13`.

## Steps to Reproduce
The executable was downloaded from the releases page (md5sum reports `60a05f3ab8ea2ff2041c9ae488246b09 *OpenBabel-3.1.1-x64.exe`) and installed the program by double click.  The check then executed was 

```
C:\Users\Norwid\Desktop>obabel --version
No input file or format spec or possibly a misplaced option.
Most options must come after the input files. (-i -o -O -m can be anywhwere.)

Open Babel 3.1.1 -- Oct 15 2024 -- 18:31:13
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.
```

I wonder about the difference between the time stamp here, vs the one on the releases page.  Is this delta intentional and if so, what is the reasoning?

Because of an additional installation of Python 3.12.4 on this Windows-only computer, I assumed this a could contribute to the shifted time stamp.  However neither a check by `python -m pip list` nor `python -m pipx list` yields a string like `babel`, `obabel`, or `openbabel` which were indicative of openbabel's Python bindings.  There is no secondary Python interpreter (e.g., conda) present.

**Comment by e-kwsm** [comment]
The timestamp must come from
https://github.com/openbabel/openbabel/blob/10da8d7b8916e5301298c7eba3a162ebba7d7de3/tools/obabel.cpp#L417-L421.

**Comment by fredrikw** [comment]
Start by checking that you are running the obabel version you think. On Windows, that is done with `where.exe obabel` or `Get-Command obabel`

**Comment by nbehrnd** [comment]
@fredrikw There are indeed two instances of OpenBabel

```
C:\Users\Norwid\Desktop>where.exe obabel
C:\Program Files\Avogadro2\bin\obabel.exe
C:\Program Files\OpenBabel-3.1.1\obabel.exe
```

A local call `obabel.exe -h` in their folders reports `May 16, 2020` for OpenBabel, the one by Avogadro `Oct 15 2024`.  By local call of `obabel -L formats`, both are aware about `pdbqt`.

For completion, I run a sequence of

- uninstallation of openbabel with Windows' control panel, retaining Avogadro2
- reboot of the OS. Now `where.exe obabel` only reports `obabel` by Avogadro2.
- re-installation of `obabel` by the installer of openbabel proper (`where.exe` still reports only the one by Avogadro2)
- reboot of the OS. Now `where.exe` again reports both executables.

After this, Windows10 continues to use the one Avogadro2 (by 2024) provides, i.e. date of installation is less important than an internal time stamp or indicator accessed during/after the installation.  Good to know when using the obabel executable; based on their md5sum, they are different (`b633ac...` for the one by Openbabel, `8e389e...` for the one by Avogadro2).

Thank you @fredrikw and @e-kwsm to answer my question; I close the ticket.

----

As about `get-command` in Windows' Powershell, it displays only (I speculate: by design) the executable eventually used.  One time typed, the other time typed with tab completion:

```shell

PS C:\Users\Norwid> get-command obabel

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     obabel.exe                                         0.0.0.0    C:\Program Files\Avogadro2\bin\obabel.exe


PS C:\Users\Norwid> Get-Command obabel.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     obabel.exe                                         0.0.0.0    C:\Program Files\Avogadro2\bin\obabel.exe


PS C:\Users\Norwid> where.exe obabel
C:\Program Files\Avogadro2\bin\obabel.exe
C:\Program Files\OpenBabel-3.1.1\obabel.exe
```

After intentional uninstallation of Avogadro2, the path to the remaining `obabel.exe` by OpenBabel is displayed (`Version` still populated with `0.0.0.0`, but ok).

**Comment by ghutchis** [comment]
Yes, the date is inserted at compile-time. Avogadro is using a newer snapshot for `cjson` support.
