### ISSUE TITLE
Default OPTIMIZE_NATIVE to OFF - unexpected behavior

### ISSUE THREAD

**Issue by cryos** [openbabel/openbabel#279]
I spent quite a bit of time debugging obabel on the Mac, and was seeing issues with an illegal instruction pretty early on as obabel started up. This was a pretty difficult one to debug as everything worked fine on the build machine, but I got a very generic error 14 on my laptop when trying to use the packaged obabel, in the end I found the answer through searching on Google and seeing a similar issue for Docker.

CMake and the upstream compilers don't enable this by default as the binaries can be quite specific for the GPU you are building on. In this case it was a pretty new Mac Pro, and trying to run them on an older Macbook Pro laptop. The comments seem incorrect too, as they have little to do with cross compiling and more to do with optimizations for the specific CPU on the build machine.

I think adding a section on optimization, and advising to turn this on there (with a big warning about the binaries being quite CPU dependent at that stage) would be great, but please consider turning this off by default to avoid having others spend time debugging strange run time errors.

**Comment by baoilleach** [comment]
Sounds like you might be right.
