### ISSUE TITLE
Compile failed: undefined reference

### ISSUE THREAD

**Issue by skodape** [openbabel/openbabel#282]
I tried to compile OpenBabel from source 76420f4d4c6bf786a5a0671f7c9b169718257121. Environment: Win7, CygWin, MinGW-w64 5.2.0, CMake 3.5.0. Used commands:
```
mkdir build
cd build
cmake.exe -G "Unix Makefiles" -DBUILD_SHARED=OFF -DBUILD_GUI=OFF ..
make
```
I got following errors:
```
[ 76%] Linking CXX executable ../bin/babel.exe
../src/libopenbabel.a(plugin.obj):plugin.cpp:(.rdata$.refptr._ZN9OpenBabel18theOrcaInputFormatE[.refptr._ZN9OpenBabel18theOrcaInputFormatE]+0x0): undefined reference to `OpenBabel::theOrcaInputFormat'
../src/libopenbabel.a(plugin.obj):plugin.cpp:(.rdata$.refptr._ZN9OpenBabel19theOrcaOutputFormatE[.refptr._ZN9OpenBabel19theOrcaOutputFormatE]+0x0): undefined reference to `OpenBabel::theOrcaOutputFormat'
../src/libopenbabel.a(plugin.obj):plugin.cpp:(.rdata$.refptr._ZN9OpenBabel13theEXYZFormatE[.refptr._ZN9OpenBabel13theEXYZFormatE]+0x0): undefined reference to `OpenBabel::theEXYZFormat'
```
After a brief inspection I find out that the undefined references points to files in src/fromats. Those files are listed in the CMakeLists.txt file but not in the formats.cmake file, which is probably used during the build process. So the files were not build and that caused the undefined reference.

It looks like this situation can be solved in at least two ways:
* Add exyzformat and orcaformat files to the formats.cmake .
* Remove reference to theOrcaOutputFormat, theOrcaInputFormat, theEXYZFormat from include/openabel/plugin.h and src/plugin.cpp .

I do not know if this is caused by my environment or not, but I though that it may be a good idea to let you know about this.

**Comment by ghutchis** [comment]
These should be fixed now, so please give master a test. I'm going to check if we can add an Appveyor MinGW build for testing.

**Comment by skodape** [comment]
Seems to be better, but in same cases (in my case for example), there may not be regex.h file presented in the path. So the line in https://github.com/openbabel/openbabel/commit/183879562e44e02f71ba4523f1aa327999d769b5#diff-490886b1d27f455347488b7d5e24b894L46 is evaluated to false (as MinGW and missing regex.h) so the orca format is not included and thus compilation give error about undefined reference to orca. 

Although it could probably be said that such setup may not be standard, the way in which openbabel handle this, at least for static compilation, is a little bit unbalanced. As it can handle the situation of missing regex.h file correctly, but then fail on static compilation in such case.
