### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/_openbabel.so: undefined symbol: _ZN9OpenBabel9OBBuilder5BuildERNS_5OBMolE

### ISSUE THREAD

**Issue by luolingqi** [openbabel/openbabel#286]
I followed the instruction page of openbabel installation, cmake with python binding like this,
"cmake ../openbabel -DEIGEN2_INCLUDE_DIR=/home/vagrant/Downloads/eigen-eigen-b23437e61a07 -DPYTHON_BINDINGS=ON" and finished subsequent steps of installation.

But "import pybel" generates the "ImportError" as shown in title. Has anybody got solution for this? Thanks

**Comment by ghutchis** [comment]
My guess is that it is not properly linked to libopenbabel. What OS are you using?

**Comment by luolingqi** [comment]
I have Ubuntu 14.04

**Comment by luolingqi** [comment]
And I set env as follow:
$LD_LIBRARY_PATH: /usr/local/lib
$BABEL_DATADIR: /usr/local/share/openbabel/
$BABEL_LIBDIR: /usr/local/lib/openbabel/

**Comment by baoilleach** [comment]
Look at the output of "ldd
/usr/local/lib/python2.7/dist-packages/_openbabel.so". Does it find the
correct versions of the required libraries?

**Comment by mwojcikowski** [comment]
Have you also tried to install Openbabel from system package? My guess would be that it's them. Make sure to remove openbabel related packages first: `apt-get remove openbabel python-openbabel libopenbabel*`

**Comment by ghutchis** [comment]
I'm closing this until there's more information. It works for most users and we can properly handle support on the mailing list.
