### ISSUE TITLE
SMILES doesn't round trip

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#298]
On the first trip through SMILES, it converts from kekule to aromatic:

obabel -ismi -ocan -:'C1=NS(=O)N=C1'
O=s1nccn1

On the second trip, it adds hydrogen across the ring:

obabel -ismi -ocan -:'C1=NS(=O)N=C1' | obabel -ismi -ocan
O=s1[nH]cc[nH]1

**Comment by baoilleach** [comment]
Fixed by #1576. "O=s1nccn1" obtained always.
