### ISSUE TITLE
the is no uninstall target

### ISSUE THREAD

**Issue by UnixJunkie** [openbabel/openbabel#300]
make uninstall doesn't work from the build directory after cmake ../.
Being able to install from sources is nice.
Being unable to uninstall is also very nice.

**Comment by cowsandmilk** [comment]
cmake intentionally does not provide this. Their response is that you should use the install_manifest.txt to remove the installed files.

i.e.
    $ xargs rm < install_manifest.txt

or 

    $ xargs sudo rm < install_manifest.txt

**Comment by UnixJunkie** [comment]
then they should provide an uninstall target that does just this.

**Comment by UnixJunkie** [comment]
Not everybody deals with cmake, and not everybody wants to learn about is peculiarities.
