### ISSUE TITLE
NWChem segfault

### ISSUE THREAD

**Issue by berquist** [openbabel/openbabel#301]
Here is the file causing the segfault: [pAz_2.txt](https://github.com/openbabel/openbabel/files/254034/pAz_2.txt)

I've confirmed that Hartree-Fock with analytic and numerical Hessians are read correctly, so it has something to do with MP2.

**Comment by ghutchis** [comment]
No, it was the vibration reading. The file is really confused, since there are empty lines in the vibrations. Is this definitely from NWChem? If so, there's something really weird about it.

**Comment by scbarton** [comment]
Here's a NWChem 6.8 output file for that molecule and a SCF energy calculation that segfaults in open babel 2.4.1. Should I make a new issue?

[pAz_2.txt](https://github.com/openbabel/openbabel/files/2819296/pAz_2.txt)
