### ISSUE TITLE
Regression: Differences in rotatable bond numbers in version 2.3.2 and master

### ISSUE THREAD

**Issue by llazzaro** [openbabel/openbabel#305]
Hello,
I just compiled the master and found some differences with version 2.3.2.
I attach a molecule where I found the differences.
with ob 2.3.2 I got RB = 9
with master branch I got RB = 4

[fail_ligand.sdf.zip](https://github.com/openbabel/openbabel/files/287018/fail_ligand.sdf.zip)

I'm looking in the git history to find the cause.

**Comment by baoilleach** [comment]
Working on this. Is due to a logic error introduced when distgeom was added. Just testing the patch now...
