### ISSUE TITLE
Problem with the negative charges when reading .cdx

### ISSUE THREAD

**Issue by genevievebo** [openbabel/openbabel#338]
When reading a .cdx with negative charges, the charges get an unsigned number.  
For example, converting a given .cdx containing two charged atoms into the mol format, atom no.8's charge is set to 255 instead of being -1. 
Hence, I see:  
M  CHG  2   4   1   8 255
instead of : 
M  CHG  2   4   1   8  -1

I have modified the file chemdrawcdx.cpp as below to fix this when the condition cdxr.GetLen()==1 is True. However, I was not able to test the code found in the else statement since I never meet this case. 

```
case kCDXProp_Atom_Charge:
          if(cdxr.GetLen()==1) 
            charge = (int)((char)cdxr.data().get());
          else
            READ_INT32(cdxr.data(), charge);
```

**Comment by serval2412** [comment]
would it be possible to have an example file + command line to reproduce this?

**Comment by aminophen** [comment]
I'm not sure the originator here had the same issue, but I have this:

```
Open Babel 3.1.1 -- Aug 31 2022 -- 22:56:54
```

```
$ obabel ATP.cdx -O ATP.png
```

The input file ATP.cdx here: [ATP.zip](https://github.com/openbabel/openbabel/files/9566958/ATP.zip)

![atp](https://user-images.githubusercontent.com/9957466/190173730-63ff966e-93c6-4cb5-855e-e34bdc2dc471.png)

with O^{255+}

**Comment by robertwerner67** [comment]
Running 

```shell
obabel ATP.cdx -O convert.cdxml
```

with obabel 3.1.1 and subsequent copy-paste into [ChemDraw JS sample page](https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#) via Structure -> Load .cdxml *somewhat* improves the situation: phosphates are now negatively charged. Good.  Except that the absolute values are not reasonable:

![ChemDraw_samplepage](https://user-images.githubusercontent.com/60490931/190347730-cdcc62d4-93d5-4438-a65a-9a5a15bff01a.png)

What version of ChemDraw do you use (release, Win or MacOS) to generate the .cdx?  Or, do you use an other program which exports in this format (e.g., [chemdoodle](https://www.chemdoodle.com/), or [Marvin Sketcher](https://marvinjs-demo.chemaxon.com/latest/examples/demo.html) to mention just two.

(For better portability across OSes and different programs, I prefer .cdxml over Chemdraw's binary .cdx format; the file size is a bit bigger but often this is no issue.)

**Comment by aminophen** [comment]
> What version of ChemDraw do you use (release, Win or MacOS) to generate the .cdx?

I'm not sure ... but I had that file [since 2014](https://github.com/aminophen/chemobabel/tree/71b8511ae44f981122747c22366a1c985d1a11c9/doc/chemobabel/draw) (when I was a student). At that time ...

* I had ChemBioDraw 12 on mac OS X 10.7.5 Lion,
* and I also had [ACD/ChemSketch Freeware 12.0](https://www.acdlabs.com/resources/free-chemistry-software-apps/chemsketch-freeware/) on Windows 7.

but I don't clearly remember which I actually used to *draw* ATP.cdx. OTOH, I clearly remember that I *opened* that file with both of those software/machine to see the same molecule.

FYI, OpenBabel 2.3.1 on the same machine generated with `$ obabel ATP.cdx -O ATP.svg` the following:

<img width="400" alt="atpcdx-obmac231" src="https://user-images.githubusercontent.com/9957466/190418125-c90d4611-f09c-4720-b032-5f84ed08b204.png">

(here no charge on oxygen!)

**Comment by robertwerner67** [comment]
There might be some more profound issue here, perhaps obabel does not access all information of a .cdxml file.

+ I let [ChemDrawJS](https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#) generate the structure formula of adenosine.  The structure exported (structure -> get cdxml) and processed with obabel 3.1.1 to yield a .png.  But hydrogen atoms (furanose alcohols and adenine) seem to be missing:

   ![CD_obabel](https://user-images.githubusercontent.com/60490931/190619165-2ef61861-d765-49cd-b3b1-bbd0afbdd5bb.png)

+ I redrew the phosphorylated adenosine in ChemDraw (for better compatibility with version 12) as a .cdxml file, which works reasonably well on ChemDrawJS (behind the "customize" button is a pulldown menu to toogle on/off the red warnings).  Still in ChemDrawPro12 for Windows, I exported the drawing as .svg with styles by ACS1996, Helvetica, Synthesis and one used e.g., in the Baran group at Scripps; compiled in the archive attached. (There too, .cdxml exported and processed by obabel 3.1.1 to .png loose hydrogens and add "dots".)

[adenosineP3.zip](https://github.com/openbabel/openbabel/files/9583249/adenosineP3.zip)

**Comment by robertwerner67** [comment]
An additional observation:  Reading above introduced `rewritten_adenosineP3.cdxml` in [GChemPaint](https://www.nongnu.org/gchemutils/gchempaint.html) (version 0.14.17, packaged as 0.14.17-6.1 in Debian) works just fine:

![gchempaint_import](https://user-images.githubusercontent.com/60490931/190631753-9e5b2827-921d-4b29-8b2c-dddd18afaf51.png)

and there are multiple formats to export this as structure, or illustration (.png, .svg).  However, newly drawn structures and saved as .cdxml by gchempaint again are not converted well into .png *by obabel 3.1.1* in Debian, while processing a .cml written by gchempaint by obabel passes better.

[tests_gchempaint.zip](https://github.com/openbabel/openbabel/files/9583710/tests_gchempaint.zip)
