### ISSUE TITLE
Total spins in -oreport are wrong in many systems

### ISSUE THREAD

**Issue by nakatamaho** [openbabel/openbabel#340]
- K do not output total spin and it should. It is a doublet system
  $ obabel -:"[K]" -oreport
  FILENAME:
  FORMULA: K
  MASS: 39.0983
  EXACT MASS: 38.9637067
  INTERATOMIC DISTANCES
- Following AlO should have TOTAL SPIN 2 (or maybe 4)
  $ obabel -:"O=[Al]" -oreport
  FILENAME:
  FORMULA: AlO
  MASS: 42.9809
  EXACT MASS: 42.9764532
  TOTAL SPIN: 3
- Following [PH2-] system should have TOTAL SPIN 1 or 3
  obabel -:"[PH2-]" -oreport
  FILENAME:
  FORMULA: H2P-
  MASS: 32.9896
  EXACT MASS: 32.9894117
  TOTAL CHARGE: -1
  TOTAL SPIN: 2
- Na atom should be doublet
  $ obabel -:"[Na]" -oreport
  FILENAME:
  FORMULA: Na
  MASS: 22.9898
  EXACT MASS: 22.9897693
- Li atom should be doublet
  obabel -:"[Li]" -oreport
- C2H5AlCl+ should be 
  $ obabel -:"CC[Al+]Cl" -oreport
  there are 22 electrons, but reports TOTAL SPIN: 2
  FILENAME:
  FORMULA: Li
  MASS: 6.9410
  EXACT MASS: 7.0160045
  INTERATOMIC DISTANCES
- LiH- should be doublet
  $ obabel -:"[H-].[Li]" -oreport
  FILENAME:
  FORMULA: HLi-
  MASS: 7.9489
  EXACT MASS: 8.0238296
  TOTAL CHARGE: -1

INTERATOMIC DISTANCES
INTERATOMIC DISTANCES

**Comment by baoilleach** [comment]
I want to add a reference here to https://github.com/openbabel/enhancement-proposals/pull/3. The code for atom-based spin multiplicity is undergoing some revisions at the moment.
