### ISSUE TITLE
loss of stereochemistry after protonization

### ISSUE THREAD

**Issue by samtn** [openbabel/openbabel#346]
Hello,

 I am trying to adjust the protonization based on the PH for a given molecule and I am using pybel and openbabel for python. I am using the following code:
<pre>
> > > mol = pybel.readstring('smi','C1=CC=C(C=C1)C[C@H](C(=O)[O-])[NH3+]')
> > > len(mol.atoms)
> > > 16
> > > mol.OBMol.AddHydrogens(True, True, 7.4)
> > > True
> > > len(mol.atoms)
> > > 15
> > > mol.write('smi').rstrip()
> > > 'c1ccc(cc1)C[C@H](C(=O)[O-])[NH3+]'
> > > # mol.write('inchi').rstrip()
> > > 
> > > **\* Open Babel Warning  in InChI code
> > >   #0 :Proton(s) added/removed
> > > 'InChI=1S/C9H11NO2/c10-8(9(11)12)6-7-4-2-1-3-5-7/h1-5,8H,6,10H2,(H,11,12)/t8-/m1/s1'
> > > # mol.write('inchikey').rstrip()
> > > 
> > > **\* Open Babel Warning  in InChI code
> > >   #0 :Proton(s) added/removed
> > > 'COLNVLDHVKWLRT-MRVPVSSYSA-N' 
</pre>

It seems that there are two issues after the conversion is successfully done.
1. When I output the SMILES, it is not affected, however the inchi and inchikey are changed
<pre>
> > > mol.write('smi').rstrip()
> > > 'c1ccc(cc1)C[C@H](C(=O)[O-])[NH3+]'
> > > # mol.write('inchikey').rstrip()
> > > 
> > > **\* Open Babel Warning  in InChI code
> > >   #0 :Wrong 0D stereo descriptor(s): #1; Proton(s) added/removed; Omitted undefined stereo
> > > 'COLNVLDHVKWLRT-UHFFFAOYSA-N'
> > > # mol.write('inchi').rstrip()
> > > 
> > > **\* Open Babel Warning  in InChI code
> > >   #0 :Wrong 0D stereo descriptor(s): #1; Proton(s) added/removed; Omitted undefined stereo
> > > 'InChI=1S/C9H11NO2/c10-8(9(11)12)6-7-4-2-1-3-5-7/h1-5,8H,6,10H2,(H,11,12)'
</pre>
1. The original stereochemistry information of the molecule is lost now.

Thanks,
Sam

**Comment by baoilleach** [comment]
The SMILES strings are messed up above so I'm a bit unsure how to reproduce. Try putting everything in three backticks, e.g. ```this```.

**Comment by samtn** [comment]
Sorry for the SMILES, it should be '''C1=CC=C(C=C1)C[C@H](C(=O)[O-])[NH3+]'''

**Comment by baoilleach** [comment]
I'm still confused: when you output the InChI first you get one result, but then later (?) you get another result.

Given the time delay I'm marking this as closed, but feel free to reopen and we can have another go.
