### ISSUE TITLE
python byte-code not cleaned up on 'make clean'

### ISSUE THREAD

**Issue by mbanck** [openbabel/openbabel#354]
After I run `make clean`, the following files which were generated during the build remain:

```
scripts/python/examples/testpybel.pyc 
scripts/python/openbabel.pyc 
scripts/python/pybel.pyc 
```

**Comment by mbanck** [comment]
Hrm, actually, they are included in the SourceForge tarball; however, I think that is not correct, as they will be generated and change during each build.

**Comment by serval2412** [comment]
I downloaded the package from https://sourceforge.net/projects/openbabel/?source=typ_redirect and had some pyc files:
./test/testbindings.pyc
./test/testbabel.pyc
./scripts/python/examples/testpybel.pyc
