### ISSUE TITLE
DeleteHydrogens(OBAtom) don't really remove the hydrogens.

### ISSUE THREAD

**Issue by klniu** [openbabel/openbabel#363]
I use the java binding from openbabel 2.4.1. The OBMol.DeleteHydrogens(OBAtom atom) acted well the first time but if I do it the second time, It did really remove the hydrogends bonded to atom. Following is the code: 
```java
import org.openbabel.*;

public class Main {

    public static void main(String[] args) {
        // Initialise
        System.loadLibrary("openbabel_java");

        // Read molecule from SMILES string
        OBConversion conv = new OBConversion();
        OBMol mol = new OBMol();
        conv.SetInFormat("smi");
        conv.ReadString(mol, "CCCCCC");
        mol.AddHydrogens();
        System.out.println(mol.NumAtoms()); // output: 20

        OBAtom atom = mol.GetAtom(1);
        System.out.println(atom.GetType()); // output: C3
        mol.DeleteHydrogens(atom);
        System.out.println(mol.NumAtoms()); // output: 17, it's right

        atom = mol.GetAtom(1);
        System.out.println(atom.GetType()); // output: C3
        mol.DeleteHydrogens(atom);
        System.out.println(mol.NumAtoms()); // output: 17, it should be 15

        mol.DeleteHydrogens(); // this one works;
        System.out.println(mol.NumAtoms()); // output: 6, It works as it should be.
    }
}
```
Thanks.

**Comment by baoilleach** [comment]
Is this issue resolved?

**Comment by klniu** [comment]
@baoilleach thanks for your concern, I have not figured out the problem yesterday.  Did DeleteHydrogens(atom) not really remove hydrogens? just hidden it.

**Comment by baoilleach** [comment]
In your test case, you attempt to delete the same atoms twice. The first time, the number of atoms goes from 20 to 17. The second time, it doesn't change. This is because they have already been suppressed.

It's true that DeleteHydrogens doesn't actually delete anything. It suppresses the explicit representation of hydrogen atoms in the molecular graph.

**Comment by klniu** [comment]
@baoilleach thanks.  Then what should I do to delete hydrogens implicitly? I tested that DeleteAtom can do the work.

**Comment by baoilleach** [comment]
Maybe you should describe the problem you are trying to solve. There may be a better way.

**Comment by klniu** [comment]
@baoilleach I want to remove the hydrogen atoms attach with SP3 C atom. Firstly I test if the C is SP3, find the neighbors, test if they are hydrogens, and then delete them.

**Comment by cstein** [comment]
Your second GetAtom is also:

```java
     atom = mol.GetAtom(1);
```

should it not be something like

```java
     atom = mol.GetAtom(2);
```

instead? Judging from your comments in your code you expect to remove only two hydrogen atoms which would imply you are expecting to be at the **second** carbon atom although you request the first (```GetAtom(1)```).
