### ISSUE TITLE
formats not being recognized?

### ISSUE THREAD

**Issue by arkose** [openbabel/openbabel#375]
Hello; I've run into a problem where openbabel doesn't recognize any file format:

`Laptops-MacBook-Pro:bin laptop$ ./obabel -ipdb 1DRF.pdb -oxyz -O 1DRF.xyz`
`obabel: cannot read input format!`
`Open Babel 2.4.1 -- Feb  4 2017 -- 11:01:17`
`Usage:`
`obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]`
`Try  -H option for more information.`

This seems to happen with all binaries and formats:

`Laptops-MacBook-Pro:bin laptop$ ./obminimize gaff.sdf`
`./obminimize: cannot read input/output format!`
`Laptops-MacBook-Pro:bin laptop$ ./obrotamer gaff.sdf`
`Error! Cannot read file format!`
`Laptops-MacBook-Pro:bin laptop$ ./roundtrip gaff.sdf out.sdf`
`./roundtrip: Cannot read file #1 format!`
`Laptops-MacBook-Pro:bin laptop$ ./roundtrip test3d.xyz out.xyz`
`./roundtrip: Cannot read file #1 format!`
`Laptops-MacBook-Pro:bin laptop$ ./roundtrip 1DRF.pdb out.pdb`
`./roundtrip: Cannot read file #1 format!`

I've compiled from source both on OSX and Linux and both had this problem; I tested both the 2.4.1 stable and the latest git version and both had this problem. Builds were done in the standard way with `mkdir build && cd build && cmake .. && make`. Am I doing something seriously wrong or does this issue occur for others?

Thank you.

**Comment by ghutchis** [comment]
Did you `make install` or not? You have to install to find the file formats.

**Comment by arkose** [comment]
That was the problem, thank you.
