### ISSUE TITLE
~/ in output filename crashes

### ISSUE THREAD

**Issue by UnixJunkie** [openbabel/openbabel#379]
This works:

    obabel ~/tmp/10_ligands.sdf -O10_ligands.smi

This doesn't:

     obabel ~/tmp/10_ligands.sdf -O~/tmp/10_ligands.smi
     ==============================
     *** Open Babel Error  in FullConvert
       Cannot write to ~/tmp/10_ligands.smi
     0 molecules converted

I am running Open Babel 2.3.2

**Comment by UnixJunkie** [comment]
also true for 2.4.0

**Comment by UnixJunkie** [comment]
This works:

    obabel ~/tmp/10_ligands.sdf -O ~/10_ligands.smi

with a space after -O

**Comment by cowsandmilk** [comment]
isn't tilde expansion generally considered to be the job of the shell?

**Comment by UnixJunkie** [comment]
yes, you are probably right. I should always add the space apparently.
