### ISSUE TITLE
Advanced SD encoding missing for Au conversion

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#628]
Reported by:
W. D. Ihlenfeldt
Xemistry GmbH
wdi@xemistry.com
 

Take the following completely legal SD file record:
 
----

  -ISIS-  03190722292D
$$$$
  1  0  0  0  0  0  0  0  0  0999 V2000
   -2.3167   -0.2167    0.0000 Au  0  0  0  1  0  0  1  0  0  0  0  0
M  END
> <PRICE>
$$$$
 
$$$$
------

While on superficial inspection the Babel output looks correct when run on the first records, a closer look shows that critical information has been lost. Babel needs to read records into its internal datastructure before output via conversion.However, its Molfile parser is rather simple and supports few of the more advanced Molfile encoding conventions. In this case, Babel silently drops the critical H0 designator flag (plus a second flag) which lets a Molfile reader distinguish between metal Au and AuH3 with implicit H. So after the pass through Babel, the compound has changed, without any notification, from metal Au to AuH3. That can be a problem.

Reported by: *anonymous

**Comment by baoilleach** [comment]
After #1576, we read this as [Au]. I believe this fixes the problem.
