### ISSUE TITLE
Canonical SMILES marks Se as aromatic

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#711]
OB version: 2.1.1

Converting the attached SDF file to SMILES produces the following output:

$ babel -isdf DB03043.sdf -osmi

NC(Cc1c[nH]c2[se]ccc12)C(O)=O   SDF file of DB03043
1 molecule converted
13 audit log messages

Which in a strict sense is wrong according to the openSMILES specification as non-aromatic atoms start with uppercase characters.

Reported by: *anonymous

**Comment by baoilleach** [comment]
This is not a bug.
