### ISSUE TITLE
kekulize runs "forever" for fullerenes

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#932]
The new kekulize algorithm uses a depth-first search that takes "forever" (> 6 hours) to finish for large aromatic systems such as fullerenes.

I will be redesigning this as a breadth-first search rather than depth-first, which should make it converge much more rapidly.  The problem with depth first is that it wanders all over the molecule trying to assign thousands and millions of combinations of single/double, when it might be that the very first bond it laid down was wrong.  By using breadth-first, the algorithm will ensure that all the bonds in a local region make sense before spreading out to the next layer of atoms.  For fullerenes, this should make it converge almost immediately on a solution.

Reported by: @cjames53

**Comment by baoilleach** [comment]
No test file provided. C60 works fine now, also with #1576. Marking as "works for me".
