### ISSUE TITLE
2 memory leaks

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#980]
version: SVN trunk
OS: Linux

1:
graphsym.cpp
Newly allocated memory for _frag_atoms in the OBGraphSym constructor gets not freed.
A simple `delete _frag_atoms;` in the destructor solved it for my test case, but this has to be reviewed esp. if frag_atoms are given as parameters.

2:
obconversion.cpp
The last pLineEndBuf created in OBConversion::InstallStreamFilter() gets never freed.
'delete pLineEndBuf;' in the destructor worked though.

Reported by: runz

**Comment by djhogan** [comment]
I couldn't find pLineEndBuf anywhere. Does this issue still exist?

**Comment by serval2412** [comment]
Indeed pLineEndBuf is nowhere to be seen in the file so there are perhaps other mem leaks but I think this tracker should be closed.

**Comment by ghutchis** [comment]
@serval2412 - thanks for all the help closing issues today!
